# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

"""Official-metadata regression for disposing a receiver inside invoke_detached.

Generate --namespace Microsoft.UI.Dispatching --class-name DispatcherQueue
--lang py from Microsoft.WindowsAppSDK.InteractiveExperiences 1.8.251104001,
metadata/10.0.18362.0/Microsoft.UI.winmd (SHA256
BA28DFC20E18630F3037AF2B91897082E41F1FA0E1DBB001D900505AB3577FE1),
with Windows SDK Windows.winmd as a reference. Pass the output to --generated.
The generated public IDispatcherQueue3 is used, not a handwritten replacement.
Select DispatcherQueue, not the ExclusiveTo interface directly: its required
interface dependencies expose this factory without widening visibility rules.

IDispatcherQueue3: 14a7a175-5c27-5a35-b079-21960cf764a8; IInspectable root;
no required interfaces. All eight contiguous HRESULT-returning ABI methods:
  6 EnqueueEventLoopExit()                       -> void
  7 EnsureSystemDispatcherQueue()                -> void
  8 RunEventLoop()                               -> void
  9 RunEventLoopWithOptions(in DispatcherRunOptions, in DispatcherExitDeferral)
                                                -> void
 10 add_FrameworkShutdownStarting(in TypedEventHandler<DispatcherQueue,
                                  DispatcherQueueShutdownStartingEventArgs>)
                                                -> out EventRegistrationToken
 11 remove_FrameworkShutdownStarting(in EventRegistrationToken) -> void
 12 add_FrameworkShutdownCompleted(in TypedEventHandler<DispatcherQueue, Object>)
                                                -> out EventRegistrationToken
 13 remove_FrameworkShutdownCompleted(in EventRegistrationToken) -> void
Slot 9 is metadata RunEventLoop with Overload("RunEventLoopWithOptions").
Options use the runtime's enumI32 representation for flags 0, 1, 2 (the raw
WinMD value__ field is UInt32); EventRegistrationToken is a single Int64.
The auxiliary deferral has IID 910b5aac-3310-563e-8418-f3005579729e, no
required interfaces, and exactly slot 6 Complete() -> void/HRESULT.

All receivers and the deferral are controlled standalone implementations.
Nothing activates a runtime class, bootstraps WinAppSDK, registers with the OS,
or runs a real event loop. No invocation monkeypatch, GC forcing, subprocess,
timeout adjustment, or forced process exit is used.
"""

from __future__ import annotations

import argparse
import ast
from contextlib import ExitStack
import hashlib
import importlib
import inspect
import json
from pathlib import Path
import platform
import sys
import threading
import traceback
from uuid import UUID


IID = "14a7a175-5c27-5a35-b079-21960cf764a8"
DEFERRAL_IID = "910b5aac-3310-563e-8418-f3005579729e"
RO_E_CLOSED = 0x80000013
PYTHON_CALLBACK_ERROR = 0xA0EE4005
ERROR_SENTINEL = "dispatcher fixture intentional callback failure"
METHODS = (
    (6, "EnqueueEventLoopExit"),
    (7, "EnsureSystemDispatcherQueue"),
    (8, "RunEventLoop"),
    (9, "RunEventLoopWithOptions"),
    (10, "add_FrameworkShutdownStarting"),
    (11, "remove_FrameworkShutdownStarting"),
    (12, "add_FrameworkShutdownCompleted"),
    (13, "remove_FrameworkShutdownCompleted"),
)
CASES = {
    "invoke_baseline": "enqueue_event_loop_exit",
    "invoke_detached": "run_event_loop",
    "invoke_detached_options": "run_event_loop_with_options",
    "callback_hresult": "run_event_loop",
}


def import_generated(directory):
    directory = directory.resolve()
    assert (directory / "__init__.py").is_file(), f"Not a generated package: {directory}"
    # Support the same long-path generated facades as the regular E2E runner.
    parent = str(directory.parent)
    if sys.platform == "win32" and not parent.startswith("\\\\?\\"):
        parent = (
            "\\\\?\\UNC\\" + parent[2:] if parent.startswith("\\\\")
            else "\\\\?\\" + parent
        )
    sys.path.insert(0, parent)
    return importlib.import_module(directory.name)


def registration(function, variable):
    """Inspect, never alter, the authoritative generated registration."""
    path = Path(inspect.getsourcefile(function))
    source = path.read_text(encoding="utf-8")
    assert source.startswith("# Generated by dynwinrt-codegen")
    assignment = next(
        node for node in ast.parse(source).body
        if isinstance(node, ast.Assign)
        and any(
            isinstance(target, ast.Name) and target.id == variable
            for target in node.targets
        )
    )
    call, methods = assignment.value, []
    while (
        isinstance(call, ast.Call) and isinstance(call.func, ast.Attribute)
        and call.func.attr == "add_method"
    ):
        methods.append((ast.literal_eval(call.args[0]), ast.unparse(call.args[1])))
        call = call.func.value
    return path, list(reversed(methods))


def check_projection(g):
    assert "IDispatcherQueue3" in g.__all__, "The real public generated interface is required"
    interface = g.IDispatcherQueue3
    descriptor = interface.implementation(DispatcherHandlers(g, "run_event_loop"))
    plan = descriptor.plan
    assert str(UUID(plan.interface_type.iid().to_string())) == IID
    assert plan.name == "Microsoft.UI.Dispatching.IDispatcherQueue3"
    assert tuple((m.vtable_index, m.name) for m in plan.methods) == METHODS
    assert list(plan.required_iids) == [], "Do not ignore metadata-required interfaces"
    path, methods = registration(interface.run_event_loop, "_IDispatcherQueue3")
    assert [name for name, _ in methods] == [name for _, name in METHODS]
    for name, slot, invoke in (
        ("enqueue_event_loop_exit", 6, "invoke"),
        ("_run_event_loop_8", 8, "invoke_detached"),
        ("_run_event_loop_9", 9, "invoke_detached"),
    ):
        assert f".method({slot}).{invoke}(" in inspect.getsource(getattr(interface, name))
    overload = inspect.getsource(interface.run_event_loop)
    assert "self._run_event_loop_8(" in overload and "self._run_event_loop_9(" in overload
    return {
        "iid": IID, "required_interfaces": [],
        "generated_source": str(path),
        "generated_source_sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        "methods": [
            {"slot": slot, "name": name, "generated_signature": signature}
            for (slot, name), (_, signature) in zip(METHODS, methods)
        ],
    }


def expect_hresult(action, expected):
    try:
        action()
    except OSError as error:
        actual = error.winerror & 0xFFFFFFFF
        assert actual == expected, f"Expected 0x{expected:08X}, got 0x{actual:08X}: {error}"
        return error
    raise AssertionError(f"Expected native HRESULT 0x{expected:08X}")


def expect_local_error(action, words):
    try:
        action()
    except RuntimeError as error:
        assert any(word in str(error).lower() for word in words), str(error)
        return
    raise AssertionError("Disposed primary must reject access before entering native code")


class DispatcherHandlers:
    """All eight actual handlers; unused event/system operations fail closed."""

    def __init__(self, g, expected, *, callback_error=False):
        self.g, self.expected, self.callback_error = g, expected, callback_error
        self.owner = None
        self.native_thread = threading.get_native_id()
        self.calls = []
        self.completed = 0
        self.deferral_identity = None

    def enter(self, name):
        self.calls.append((name, threading.get_native_id()))
        assert self.calls == [(self.expected, self.native_thread)], self.calls

    def finish(self, name, deferral=None):
        self.enter(name)
        if self.callback_error:
            raise ValueError(ERROR_SENTINEL)
        self.owner.dispose()  # The regression: release the active Python receiver.
        assert self.owner.is_closed
        if deferral is not None:
            deferral.complete()  # Still inside the already-entered dispatcher callback.
        self.completed += 1

    def enqueue_event_loop_exit(self):
        self.finish("enqueue_event_loop_exit")

    def ensure_system_dispatcher_queue(self):
        self.enter("ensure_system_dispatcher_queue")
        raise AssertionError("Unexpected standalone EnsureSystemDispatcherQueue")

    def run_event_loop(self):
        self.finish("run_event_loop")

    def run_event_loop_with_options(self, options, deferral):
        assert isinstance(options, self.g.DispatcherRunOptions)
        assert options == (
            self.g.DispatcherRunOptions.ContinueOnQuit
            | self.g.DispatcherRunOptions.QuitOnlyLocalLoop
        )
        assert isinstance(deferral, self.g.DispatcherExitDeferral)
        assert deferral._obj.identity_raw() == self.deferral_identity
        self.finish("run_event_loop_with_options", deferral)

    def add_framework_shutdown_starting(self, handler):
        self.enter("add_framework_shutdown_starting")
        raise AssertionError("Unexpected standalone FrameworkShutdownStarting subscription")

    def remove_framework_shutdown_starting(self, token):
        self.enter("remove_framework_shutdown_starting")
        raise AssertionError("Unexpected standalone FrameworkShutdownStarting removal")

    def add_framework_shutdown_completed(self, handler):
        self.enter("add_framework_shutdown_completed")
        raise AssertionError("Unexpected standalone FrameworkShutdownCompleted subscription")

    def remove_framework_shutdown_completed(self, token):
        self.enter("remove_framework_shutdown_completed")
        raise AssertionError("Unexpected standalone FrameworkShutdownCompleted removal")


def controlled_deferral(g, dw, cleanup, native_thread):
    # This ExclusiveTo default interface has no public generated .implement().
    # Verify its COMPLETE generated registration before describing its one
    # callback with the normal managed WinRT implementation API. Never alias an
    # unrelated IID, manufacture pointers, or call DispatcherExitDeferral.create().
    _, methods = registration(g.DispatcherExitDeferral.complete, "_IDispatcherExitDeferral")
    assert methods == [("Complete", "DynWinRTMethodSig()")]
    interface = g.DispatcherExitDeferral.complete.__globals__["_IDispatcherExitDeferral"]
    assert str(UUID(interface.iid().to_string())) == DEFERRAL_IID
    plan = dw.DynWinRTInterfacePlan.create(
        "Microsoft.UI.Dispatching.IDispatcherExitDeferral", interface,
        [dw.DynWinRTImplementationMethod("Complete", 6, dw.DynWinRTMethodSig())], [],
    )
    calls = []

    def complete(index, slot, args):
        calls.append(threading.get_native_id())
        assert (index, slot, args) == (0, 6, [])
        assert calls[-1] == native_thread
        return []

    owner = dw.DynWinRTImplementation.create([plan], complete)
    cleanup.callback(owner.dispose)
    value = owner.to_value()
    try:
        # This test-only runtime-class adapter QIs the controlled resource;
        # unlike the primary interface's .value path, the class has no public
        # constructor/from_value factory. It does not activate an OS object.
        projected = g.DispatcherExitDeferral._from_native(value)
    finally:
        value.release()
    cleanup.callback(dw.release_projected, projected)
    return owner, projected, calls


def exercise(g, dw, case, details):
    handlers = DispatcherHandlers(g, CASES[case], callback_error=case == "callback_hresult")
    deferral_calls = []
    with ExitStack() as cleanup:
        owner = g.IDispatcherQueue3.implement(handlers)
        handlers.owner = owner
        cleanup.callback(owner.dispose)
        primary = owner.value
        retained = g.IDispatcherQueue3.from_implementation(owner)
        cleanup.callback(dw.release_projected, retained)
        assert isinstance(primary, g.IDispatcherQueue3)
        assert owner.value is primary and owner.value is primary
        assert retained is not primary and retained._obj is not primary._obj
        assert retained._obj.identity_raw() == primary._obj.identity_raw()
        assert owner.take_error() is None
        try:
            if case == "callback_hresult":
                expect_hresult(owner.value.run_event_loop, PYTHON_CALLBACK_ERROR)
                saved = owner.take_error()
                assert saved is not None and ERROR_SENTINEL in saved, saved
                details["expected_callback_error"] = saved
                assert owner.take_error() is None
                assert not owner.is_closed and owner.value is primary
                assert handlers.completed == 0
                owner.dispose()
            elif case == "invoke_detached_options":
                deferral_owner, deferral, deferral_calls = controlled_deferral(
                    g, dw, cleanup, handlers.native_thread,
                )
                handlers.deferral_identity = deferral._obj.identity_raw()
                options = (
                    g.DispatcherRunOptions.ContinueOnQuit
                    | g.DispatcherRunOptions.QuitOnlyLocalLoop
                )
                assert owner.value.run_event_loop(options=options, deferral=deferral) is None
                assert deferral_calls == [handlers.native_thread]
                assert not deferral_owner.is_closed and deferral_owner.take_error() is None
                deferral.complete()  # Its independently owned resource survives dispatch.
                assert deferral_calls == [handlers.native_thread] * 2
                assert deferral_owner.take_error() is None
            elif case == "invoke_baseline":
                assert owner.value.enqueue_event_loop_exit() is None
            else:
                assert owner.value.run_event_loop() is None

            if case != "callback_hresult":
                assert handlers.completed == 1, "Already-entered callback did not complete"
            assert owner.is_closed
            expect_local_error(lambda: owner.value, ("closed", "released"))
            expect_local_error(primary.run_event_loop, ("object", "released"))
            pending = owner.take_error()
            assert pending is None, f"Unexpected callback error after disposal: {pending}"
            assert not retained._obj.is_null(), "Retained view must reach the native closed check"
            expect_hresult(retained.run_event_loop, RO_E_CLOSED)
            # The native closed gate may record its expected rejection even
            # though no Python handler entered. Preserve/drain that diagnostic,
            # rather than incorrectly treating it as a new callback failure.
            closed = owner.take_error()
            details["expected_closed_error"] = closed
            assert closed is None or (
                "IDispatcherQueue3::RunEventLoop (slot 8): 0x80000013:" in closed
            ), f"Unexpected error from retained closed view: {closed}"
            assert handlers.calls == [(CASES[case], handlers.native_thread)]
            assert threading.get_native_id() == handlers.native_thread
            assert owner.take_error() is None, "Unexpected residual callback error"
            owner.dispose()  # Idempotent cleanup must not reenter the handlers.
            assert handlers.calls == [(CASES[case], handlers.native_thread)]
        finally:
            details.update(
                calls=handlers.calls, completed=handlers.completed,
                native_thread=handlers.native_thread, deferral_calls=deferral_calls,
                callback_error=owner.take_error(), owner_closed=owner.is_closed,
            )
            handlers.owner = None  # Deterministic cycle breaking, not global GC.


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--generated", required=True, type=Path)
    parser.add_argument("--case", choices=CASES, help="Run just one focused scenario")
    args = parser.parse_args()
    import dynwinrt as dw

    g = import_generated(args.generated)
    projection = check_projection(g)
    print(json.dumps({
        "python": platform.python_version(), "compiler": platform.python_compiler(),
        "runtime": dw.dynwinrt.__file__, "projection": projection,
    }), flush=True)
    results = []
    # Only COM apartment initialization, never runtime-class activation.
    with dw.RoApartment(1):
        for case in ([args.case] if args.case else CASES):
            result = {"id": case, "pass": False}
            try:
                exercise(g, dw, case, result)
                assert result["callback_error"] is None, result["callback_error"]
                result["pass"] = True
            except Exception as error:
                result["error"] = traceback.format_exc()
                if isinstance(error, OSError) and error.winerror is not None:
                    result["hresult"] = f"0x{error.winerror & 0xFFFFFFFF:08X}"
            results.append(result)
            print("DYNWINRT_DISPATCHER_RESULT=" + json.dumps(result), flush=True)
    passed = sum(result["pass"] for result in results)
    print(f"Dispatcher implementation: {passed}/{len(results)} passed", flush=True)
    return 0 if passed == len(results) else 1


if __name__ == "__main__":
    sys.exit(main())
