// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Pure JavaScript and declaration rendering for validated Classic-COM IR.

use std::collections::BTreeMap;

#[cfg(test)]
use super::super::ir::ProjectedComEnumMember;
use super::super::ir::{
    ActivationPlan, ComEnumUnderlying, ComParamDirection, ComReturnConvention, ComType,
    DispatchShape, OverloadDispatch, PointerAliasKind, ProjectedComCoclass, ProjectedComEnum,
    ProjectedComInterface, ProjectedComMethod, ProjectedComMethodKind, ProjectedComParam,
    ProjectedEnumValue, ResultConversion, ResultSource, StringEncoding,
};
use super::naming::js_param_name;
use super::types::{
    abi_type_js, input_type_dts, result_type_dts, scalar_type_dts, unwrap_result_js, wrap_arg_js,
};
use crate::codegen::winrt::javascript::render::javascript::commonjs::convert_to_cjs_with_eager;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ComGeneratedOutput {
    pub js: String,
    pub dts: String,
    pub extra_files: Vec<(String, String)>,
}

pub(in crate::codegen::com) fn render_com_interface(
    meta: &ProjectedComInterface,
) -> ComGeneratedOutput {
    render_projected_interface(meta)
}

fn render_projected_interface(meta: &ProjectedComInterface) -> ComGeneratedOutput {
    let js = com_esm_to_cjs(&render_js(meta));
    let dts = render_dts(meta);
    let mut extra_files = BTreeMap::new();
    for en in &meta.referenced_enums {
        let (enum_js, enum_dts) = render_enum_files(en);
        extra_files.insert(format!("{}.js", en.name), enum_js);
        extra_files.insert(format!("{}.d.ts", en.name), enum_dts);
    }
    ComGeneratedOutput {
        js,
        dts,
        extra_files: extra_files.into_iter().collect(),
    }
}

pub(in crate::codegen::com) fn render_com_coclass(
    meta: &ProjectedComCoclass,
) -> ComGeneratedOutput {
    let (js, dts) = render_coclass_files(&meta.name, &meta.clsid, &meta.primary_interface);
    let mut extra_files = BTreeMap::new();
    for interface in &meta.associated_interfaces {
        let output = render_projected_interface(interface);
        extra_files.insert(format!("{}.js", interface.name), output.js);
        extra_files.insert(format!("{}.d.ts", interface.name), output.dts);
        for (name, content) in output.extra_files {
            extra_files.entry(name).or_insert(content);
        }
    }
    ComGeneratedOutput {
        js,
        dts,
        extra_files: extra_files.into_iter().collect(),
    }
}

fn render_coclass_files(
    name: &str,
    clsid: &str,
    primary_interface: &ProjectedComInterface,
) -> (String, String) {
    let mut js = String::new();
    js.push_str("// Generated by dynwinrt-codegen — do not edit\n");
    js.push_str(&format!(
        "import {{ DynCom }} from '{}';\n",
        com_runtime_import_name()
    ));
    js.push_str(&format!(
        "import {{ {}, IID_{} }} from './{}.js';\n\n",
        primary_interface.name, primary_interface.name, primary_interface.name
    ));
    js.push_str(&format!("export const CLSID_{name} = '{clsid}';\n\n"));
    js.push_str(&format!(
        "export class {name} extends {} {{\n",
        primary_interface.name
    ));
    js.push_str(&format!(
        "    constructor() {{\n        super(DynCom.coCreateInstance(CLSID_{name}, IID_{}));\n    }}\n",
        primary_interface.name
    ));
    js.push_str(&format!(
        "    static _fromNative(obj) {{\n        const cast = obj.cast(IID_{});\n        return Object.assign(Object.create({name}.prototype), {{ _obj: cast }});\n    }}\n",
        primary_interface.name
    ));
    js.push_str("    as(InterfaceClass) {\n        return InterfaceClass._fromNative(this._obj.cast(InterfaceClass.IID));\n    }\n");
    js.push_str("    tryAs(InterfaceClass) {\n        const obj = DynCom.tryCast(this._obj, InterfaceClass.IID);\n        return obj === null ? null : InterfaceClass._fromNative(obj);\n    }\n");
    js.push_str("    supports(InterfaceClass) {\n        const obj = DynCom.tryCast(this._obj, InterfaceClass.IID);\n        if (obj === null) return false;\n        obj.release();\n        return true;\n    }\n");
    js.push_str("}\n");

    let descriptor = "{ readonly IID: unknown; _fromNative(obj: unknown): T }";
    let mut dts = String::new();
    dts.push_str("// Generated by dynwinrt-codegen — do not edit\n");
    dts.push_str(&format!(
        "import {{ {} }} from './{}.js';\n\n",
        primary_interface.name, primary_interface.name
    ));
    dts.push_str(&format!("export declare const CLSID_{name}: string;\n\n"));
    dts.push_str(&format!(
        "export declare class {name} extends {} {{\n",
        primary_interface.name
    ));
    dts.push_str("    constructor();\n");
    dts.push_str(&format!("    static _fromNative(obj: unknown): {name};\n"));
    dts.push_str(&format!("    as<T>(InterfaceClass: {descriptor}): T;\n"));
    dts.push_str(&format!(
        "    tryAs<T>(InterfaceClass: {descriptor}): T | null;\n"
    ));
    dts.push_str(&format!(
        "    supports<T>(InterfaceClass: {descriptor}): boolean;\n"
    ));
    dts.push_str("}\n");
    (com_esm_to_cjs(&js), dts)
}

fn com_esm_to_cjs(esm: &str) -> String {
    let runtime_sources = std::collections::HashSet::from([com_runtime_import_name()]);
    convert_to_cjs_with_eager(esm, &runtime_sources)
}

fn render_js(meta: &ProjectedComInterface) -> String {
    let mut out = String::new();
    out.push_str("// Generated by dynwinrt-codegen — do not edit\n");
    let runtime_imports = if matches!(meta.activation, ActivationPlan::WinRtFactory { .. }) {
        "DynCom, DynComMethodSig, DynWinRtValue, WinGuid"
    } else {
        "DynCom, DynComMethodSig, WinGuid"
    };
    out.push_str(&format!(
        "import {{ {runtime_imports} }} from '{}';\n",
        com_runtime_import_name()
    ));
    for en in &meta.referenced_enums {
        out.push_str(&format!(
            "import {{ {} }} from './{}.js';\n",
            en.name, en.name
        ));
    }
    out.push('\n');
    if meta
        .methods
        .iter()
        .any(|method| method.string_buffer.is_some())
    {
        out.push_str("function _normalizeStringBufferCount(value, name) {\n");
        out.push_str("    if (!Number.isInteger(value) || value <= 0) throw new TypeError(`${name} must be a positive integer`);\n");
        out.push_str("    return value;\n}\n");
        out.push_str("function _decodeWideString(buffer) {\n    let end = 0;\n");
        out.push_str(
            "    while (end + 1 < buffer.length && buffer.readUInt16LE(end) !== 0) end += 2;\n",
        );
        out.push_str("    return buffer.subarray(0, end).toString('utf16le');\n}\n\n");
    }
    out.push_str(&format!(
        "export const IID_{} = WinGuid.parse('{}');\n",
        meta.name, meta.iid
    ));
    if let ActivationPlan::WinRtFactory {
        class_name,
        target_iid,
        ..
    } = &meta.activation
    {
        out.push_str(&format!(
            "const IID_{class_name}_default = WinGuid.parse('{target_iid}');\n"
        ));
    }
    out.push('\n');
    let register_fn = if meta.is_iunknown_rooted {
        "registerIUnknownInterface"
    } else {
        "registerIInspectableInterface"
    };
    let cache_var = format!("_{}Cache", meta.name);
    let iface_var = format!("_{}", meta.name);
    out.push_str(&format!("let {cache_var};\n"));
    out.push_str(&format!(
        "const {iface_var} = new Proxy({{}}, {{\n    get(_target, prop) {{\n        {cache_var} ??= DynCom.{register_fn}('{}.{}', IID_{})\n",
        meta.namespace, meta.name, meta.name
    ));
    for method in &meta.methods {
        out.push_str(&format!(
            "            .addMethodAt({}, '{}', {})\n",
            method.vtable_index,
            method.name,
            build_method_sig_js(method)
        ));
    }
    if out.ends_with('\n') {
        out.pop();
    }
    out.push_str(";\n");
    out.push_str(&format!("        const value = {cache_var}[prop];\n        return typeof value === 'function' ? value.bind({cache_var}) : value;\n    }},\n}});\n\n"));
    out.push_str(&format!("export class {} {{\n", meta.name));
    out.push_str(&format!("    static IID = IID_{};\n", meta.name));
    out.push_str("    _obj;\n    constructor(obj) { this._obj = obj; }\n");
    out.push_str(&format!(
        "    static _fromNative(obj) {{ return Object.assign(Object.create({}.prototype), {{ _obj: obj }}); }}\n",
        meta.name
    ));
    out.push_str("    /** Release the underlying native COM reference. Safe to call more than once. */\n    release() {\n        this._obj.release();\n    }\n");
    match &meta.activation {
        ActivationPlan::None => {}
        ActivationPlan::Coclass { .. } => {}
        ActivationPlan::WinRtFactory {
            class_name,
            class_namespace,
            ..
        } => {
            let full = format!("{class_namespace}.{class_name}");
            out.push_str(&format!("    /** Create a new `{}` by activating the `{full}` factory and QI'ing to the interop.\n     * `DynCom.initialize()` must be called once (e.g. at process startup) before this is used. */\n", meta.name));
            out.push_str(&format!("    static create() {{\n        const factory = DynWinRtValue.activationFactory('{full}');\n        const _obj = factory.cast(IID_{});\n        return new {}(_obj);\n    }}\n", meta.name, meta.name));
        }
    }
    let mut emitted_groups = std::collections::HashSet::new();
    for method in &meta.methods {
        if let Some(overload) = &method.overload {
            if !emitted_groups.insert(overload.public_name.clone()) {
                continue;
            }
            let group: Vec<&ProjectedComMethod> = meta
                .methods
                .iter()
                .filter(|candidate| {
                    candidate
                        .overload
                        .as_ref()
                        .is_some_and(|candidate_overload| {
                            candidate_overload.public_name == overload.public_name
                        })
                })
                .collect();
            emit_overload_group_js(&mut out, &group, &iface_var);
            continue;
        }
        match method.kind {
            ProjectedComMethodKind::Normal => emit_method_js(&mut out, method, &iface_var),
            ProjectedComMethodKind::CallerSuppliedDynamicIid {
                natural_param_count,
            } => emit_dynamic_iid_method_js(&mut out, method, natural_param_count, &iface_var),
            ProjectedComMethodKind::SynthesizedGetForWindow {
                natural_param_count,
                ref target_iid,
            } => emit_synthesized_interop_method_js(
                &mut out,
                method,
                natural_param_count,
                target_iid,
                &iface_var,
                meta,
            ),
        }
    }
    out.push_str("}\n");
    out
}

fn build_method_sig_js(method: &ProjectedComMethod) -> String {
    let mut parts = Vec::new();
    for (index, param) in method.params.iter().enumerate() {
        match param.direction {
            ComParamDirection::In => parts.push(format!(".addIn({})", abi_type_js(&param.typ))),
            ComParamDirection::InOut => {
                parts.push(format!(".addInOut({})", abi_type_js(&param.typ)))
            }
            ComParamDirection::OutStringBuffer => parts.push(".addIn(DynCom.pointerType())".into()),
            ComParamDirection::Out => {
                if method.string_buffer.as_ref().is_some_and(|plan| {
                    index > plan.count_param_index && plan.optional_param_indices.contains(&index)
                }) {
                    parts.push(".addIn(DynCom.pointerType())".into());
                } else {
                    parts.push(format!(
                        ".addOut({})",
                        out_abi_type_js(method, index, &param.typ)
                    ));
                }
            }
        }
    }
    match &method.return_convention {
        ComReturnConvention::HResult => {}
        ComReturnConvention::SemanticHResult => parts.push(".preserveHresult()".into()),
        ComReturnConvention::Void => parts.push(".returnsVoid()".into()),
        ComReturnConvention::Direct(typ) => parts.push(format!(".returns({})", abi_type_js(typ))),
    }
    if parts.is_empty() {
        "new DynComMethodSig()".into()
    } else {
        format!("new DynComMethodSig(){}", parts.join(""))
    }
}

/// Selects the ABI output type for an `Out` parameter, using the projected
/// result's ownership/conversion facts (not the parameter's raw type name) to
/// pick a semantically correct, provenance-tagged pointer type where the
/// runtime needs to know how to (or whether it may) reclaim the output value.
/// Any pointer output that isn't classified with a known ownership contract
/// falls back to the unclassified `pointerType()`, which the runtime does not
/// allow callers to adopt as an owned value.
fn out_abi_type_js(method: &ProjectedComMethod, param_index: usize, typ: &ComType) -> String {
    let conversion = method
        .results
        .iter()
        .find(|result| result.source == ResultSource::Param(param_index))
        .map(|result| &result.conversion);
    match conversion {
        Some(ResultConversion::DynamicIidAdoption) => "DynCom.ownedComPointerType()".into(),
        Some(ResultConversion::Bstr) => "DynCom.bstrPointerType()".into(),
        Some(ResultConversion::CoTaskMemString(_) | ResultConversion::CoTaskMemData) => {
            "DynCom.coTaskMemPointerType()".into()
        }
        Some(
            ResultConversion::ManagedCom | ResultConversion::HString | ResultConversion::Value,
        )
        | None => abi_type_js(typ),
    }
}

fn input_params(method: &ProjectedComMethod) -> Vec<(usize, &ProjectedComParam)> {
    method
        .params
        .iter()
        .enumerate()
        .filter(|(_, param)| param.direction.is_input())
        .collect()
}

fn emit_method_js(out: &mut String, method: &ProjectedComMethod, iface_var: &str) {
    emit_method_doc_js(out, &method.doc);
    emit_method_js_named(out, method, iface_var, &method.camel_name);
}

/// Emits a one-line `@see` JSDoc comment above a method when metadata
/// supplied a doc reference (win32metadata's `DocumentationAttribute`, a
/// `learn.microsoft.com` URL — see `com_metadata::parse_methods`). Renders
/// nothing when `doc` is `None`; the renderer never invents documentation.
fn emit_method_doc_js(out: &mut String, doc: &Option<String>) {
    if let Some(url) = doc {
        out.push_str(&format!("    /** @see {{@link {url}}} */\n"));
    }
}

/// Renders a single method body under `js_name`. Used both for standalone
/// methods (`js_name == method.camel_name`) and for each private per-overload
/// implementation of a grouped overload set (`js_name ==
/// overload.impl_name`), so the JS body-emission logic is shared regardless
/// of whether the method is dispatched to directly or via the public
/// overload dispatcher.
fn emit_method_js_named(
    out: &mut String,
    method: &ProjectedComMethod,
    iface_var: &str,
    js_name: &str,
) {
    let inputs = input_params(method);
    let params = inputs
        .iter()
        .enumerate()
        .map(|(surface, (index, param))| {
            let name = js_param_name(&param.name, surface);
            if let Some(plan) = &method.string_buffer {
                if plan.optional_param_indices.contains(index) {
                    return if *index == plan.count_param_index {
                        format!("{name} = 260")
                    } else {
                        format!("{name} = 0")
                    };
                }
            }
            name
        })
        .collect::<Vec<_>>();
    out.push_str(&format!("    {js_name}({}) {{\n", params.join(", ")));
    if let Some(plan) = &method.string_buffer {
        emit_string_buffer_method_body(out, method, plan, &inputs, iface_var);
        out.push_str("    }\n");
        return;
    }
    let args = inputs
        .iter()
        .enumerate()
        .map(|(surface, (_, param))| wrap_arg_js(&param.typ, &js_param_name(&param.name, surface)))
        .collect::<Vec<_>>();
    emit_invocation_and_results(out, method, iface_var, &args);
    out.push_str("    }\n");
}

/// Renders one same-name overload group: every branch's private
/// implementation (named per `OverloadInfo::impl_name`, e.g.
/// `_setOpacity_7`), followed by a single public dispatcher method that picks
/// a branch using only the validated, distinguishable dispatch decision
/// computed during projection (`OverloadInfo::dispatch`) — never a
/// renderer-invented heuristic.
fn emit_overload_group_js(out: &mut String, group: &[&ProjectedComMethod], iface_var: &str) {
    for method in group {
        let overload = method
            .overload
            .as_ref()
            .expect("group members are always overloaded");
        emit_method_js_named(out, method, iface_var, &overload.impl_name);
    }
    let public_name = &group[0]
        .overload
        .as_ref()
        .expect("group members are always overloaded")
        .public_name;
    // Attach the first branch's doc reference (if any) to the public
    // dispatcher, since that's the method callers actually see and call.
    emit_method_doc_js(out, &group.iter().find_map(|method| method.doc.clone()));
    out.push_str(&format!("    {public_name}(...args) {{\n"));
    for method in group {
        let overload = method
            .overload
            .as_ref()
            .expect("group members are always overloaded");
        let arity = input_params(method).len();
        let condition = match overload.dispatch {
            OverloadDispatch::Arity => format!("args.length === {arity}"),
            OverloadDispatch::ArityAndShape {
                key_param_index,
                shape,
            } => format!(
                "args.length === {arity} && {}",
                dispatch_shape_check_js(shape, key_param_index)
            ),
        };
        out.push_str(&format!(
            "        if ({condition}) return this.{}(...args);\n",
            overload.impl_name
        ));
    }
    out.push_str(&format!(
        "        throw new TypeError(`No overload of {public_name} matches the given arguments`);\n"
    ));
    out.push_str("    }\n");
}

fn dispatch_shape_check_js(shape: DispatchShape, index: usize) -> String {
    match shape {
        DispatchShape::Boolean => format!("typeof args[{index}] === 'boolean'"),
        DispatchShape::Number => format!("typeof args[{index}] === 'number'"),
        DispatchShape::BigInt => format!("typeof args[{index}] === 'bigint'"),
        DispatchShape::String => format!("typeof args[{index}] === 'string'"),
        DispatchShape::Object => {
            format!("(args[{index}] !== null && typeof args[{index}] === 'object')")
        }
    }
}

fn emit_string_buffer_method_body(
    out: &mut String,
    method: &ProjectedComMethod,
    plan: &super::super::ir::StringBufferPlan,
    inputs: &[(usize, &ProjectedComParam)],
    iface_var: &str,
) {
    let count_surface = inputs
        .iter()
        .position(|(index, _)| *index == plan.count_param_index)
        .expect("validated count input");
    let count_name = js_param_name(&method.params[plan.count_param_index].name, count_surface);
    if plan.encoding == StringEncoding::Ansi {
        out.push_str("        throw new Error('PSTR out buffers are not yet decoded safely');\n");
        return;
    }
    let args = method
        .params
        .iter()
        .enumerate()
        .filter_map(|(index, param)| {
            if index == plan.buffer_param_index {
                Some("DynCom.pointer(_buffer)".into())
            } else if param.direction.is_input() {
                let surface = inputs
                    .iter()
                    .position(|(input_index, _)| *input_index == index)
                    .expect("validated input");
                Some(wrap_arg_js(
                    &param.typ,
                    &js_param_name(&param.name, surface),
                ))
            } else if index > plan.count_param_index && plan.optional_param_indices.contains(&index)
            {
                Some("DynCom.pointer(0n)".into())
            } else {
                None
            }
        })
        .collect::<Vec<_>>();
    out.push_str(&format!(
        "        {count_name} = _normalizeStringBufferCount({count_name}, '{count_name}');\n"
    ));
    out.push_str(&format!(
        "        const _buffer = Buffer.alloc({count_name} * 2);\n"
    ));
    match method.results.len() {
        0 => out.push_str(&format!(
            "        {iface_var}.method({}).invoke(this._obj, [{}]);\n",
            method.vtable_index,
            args.join(", ")
        )),
        1 => out.push_str(&format!(
            "        const _out = {iface_var}.method({}).invoke(this._obj, [{}]);\n",
            method.vtable_index,
            args.join(", ")
        )),
        _ => out.push_str(&format!(
            "        const _out = {iface_var}.method({}).invokeAll(this._obj, [{}]);\n",
            method.vtable_index,
            args.join(", ")
        )),
    }
    out.push_str("        const _text = _decodeWideString(_buffer);\n");
    match method.results.len() {
        0 => out.push_str("        return _text;\n"),
        1 => out.push_str(&format!(
            "        return [_text, {}];\n",
            unwrap_result_js(&method.results[0], "_out")
        )),
        _ => {
            let values = method
                .results
                .iter()
                .enumerate()
                .map(|(index, result)| unwrap_result_js(result, &format!("_out[{index}]")))
                .collect::<Vec<_>>();
            out.push_str(&format!("        return [_text, {}];\n", values.join(", ")));
        }
    }
}

fn emit_invocation_and_results(
    out: &mut String,
    method: &ProjectedComMethod,
    iface_var: &str,
    args: &[String],
) {
    match method.results.len() {
        0 => out.push_str(&format!(
            "        {iface_var}.method({}).invoke(this._obj, [{}]);\n",
            method.vtable_index,
            args.join(", ")
        )),
        1 => {
            out.push_str(&format!(
                "        const _out = {iface_var}.method({}).invoke(this._obj, [{}]);\n",
                method.vtable_index,
                args.join(", ")
            ));
            out.push_str(&format!(
                "        return {};\n",
                unwrap_result_js(&method.results[0], "_out")
            ));
        }
        _ => {
            out.push_str(&format!(
                "        const _r = {iface_var}.method({}).invokeAll(this._obj, [{}]);\n",
                method.vtable_index,
                args.join(", ")
            ));
            let values = method
                .results
                .iter()
                .enumerate()
                .map(|(index, result)| unwrap_result_js(result, &format!("_r[{index}]")))
                .collect::<Vec<_>>();
            out.push_str(&format!("        return [{}];\n", values.join(", ")));
        }
    }
}

fn emit_dynamic_iid_method_js(
    out: &mut String,
    method: &ProjectedComMethod,
    natural_count: usize,
    iface_var: &str,
) {
    let natural = &method.params[..natural_count];
    let mut surface = natural
        .iter()
        .enumerate()
        .map(|(index, param)| js_param_name(&param.name, index))
        .collect::<Vec<_>>();
    surface.push("iid".into());
    let mut args = natural
        .iter()
        .enumerate()
        .map(|(index, param)| wrap_arg_js(&param.typ, &js_param_name(&param.name, index)))
        .collect::<Vec<_>>();
    args.push("DynCom.iidPointer(_iid)".into());
    out.push_str(&format!(
        "    {}({}) {{\n        const _iid = WinGuid.parse(iid);\n",
        method.camel_name,
        surface.join(", ")
    ));
    out.push_str(&format!(
        "        const _raw = {iface_var}.method({}).invoke(this._obj, [{}]);\n",
        method.vtable_index,
        args.join(", ")
    ));
    out.push_str("        return DynCom.adoptComPointer(_raw, _iid);\n    }\n");
}

fn emit_synthesized_interop_method_js(
    out: &mut String,
    method: &ProjectedComMethod,
    natural_count: usize,
    _target_iid: &str,
    iface_var: &str,
    meta: &ProjectedComInterface,
) {
    let natural = &method.params[..natural_count];
    let params = natural
        .iter()
        .enumerate()
        .map(|(index, param)| js_param_name(&param.name, index))
        .collect::<Vec<_>>();
    let mut args = natural
        .iter()
        .enumerate()
        .map(|(index, param)| wrap_arg_js(&param.typ, &js_param_name(&param.name, index)))
        .collect::<Vec<_>>();
    let class_name = match &meta.activation {
        ActivationPlan::WinRtFactory { class_name, .. } => class_name,
        _ => unreachable!("validated interop activation"),
    };
    args.push(format!("DynCom.iidPointer(IID_{class_name}_default)"));
    out.push_str(&format!(
        "    {}({}) {{\n",
        method.camel_name,
        params.join(", ")
    ));
    out.push_str(&format!(
        "        const _raw = {iface_var}.method({}).invoke(this._obj, [{}]);\n",
        method.vtable_index,
        args.join(", ")
    ));
    out.push_str(&format!("        const _out = DynCom.adoptComPointer(_raw, IID_{class_name}_default);\n        return _out;\n    }}\n"));
}

fn render_dts(meta: &ProjectedComInterface) -> String {
    let mut out = String::new();
    out.push_str("// Generated by dynwinrt-codegen — do not edit\n");
    for en in &meta.referenced_enums {
        out.push_str(&format!(
            "import {{ {} }} from './{}.js';\n",
            en.name, en.name
        ));
    }
    if needs_bridge_import(meta) {
        out.push_str(&format!(
            "import type {{ DynWinRtValue }} from '{}';\n",
            com_runtime_import_name()
        ));
    }
    out.push('\n');
    for (name, underlying) in collect_scalar_aliases(meta) {
        out.push_str(&format!(
            "/** Transparent Win32 scalar typedef. */\nexport type {name} = {};\n",
            scalar_type_dts(underlying)
        ));
    }
    if !collect_scalar_aliases(meta).is_empty() {
        out.push('\n');
    }
    for (name, kind) in collect_pointer_aliases(meta) {
        match kind {
            PointerAliasKind::HandleValue => out.push_str(&format!("/** Opaque Win32 handle value. Pass a raw pointer value as a `bigint` (full pointer width) or `number` (safe integer). */\nexport type {name} = bigint | number;\n")),
            PointerAliasKind::DataPointer => out.push_str(&format!("/** Opaque native data address. Inputs may also use a `Buffer`/`Uint8Array`, whose backing-store address is passed and retained for the call. */\nexport type {name} = bigint | number;\n")),
            PointerAliasKind::StringPointer(encoding) => {
                let description = match encoding {
                    StringEncoding::Wide => "Pass a JS `string` (encoded automatically via DynCom.wideStringPointer), a `Buffer`/`Uint8Array` holding UTF-16LE bytes (including the NUL terminator), or a raw pointer as `bigint`.",
                    StringEncoding::Ansi => "Pass an ASCII JS `string` (encoded automatically via DynCom.ansiStringPointer), a `Buffer`/`Uint8Array` holding explicitly ANSI-encoded bytes (including the NUL terminator), or a raw pointer as `bigint`. Non-ASCII text must use pre-encoded bytes.",
                };
                out.push_str(&format!(
                    "/** Win32 NUL-terminated string pointer. {description} */\nexport type {name} = string | Buffer | Uint8Array | bigint;\n"
                ));
            }
        }
    }
    if !collect_pointer_aliases(meta).is_empty() {
        out.push('\n');
    }
    out.push_str(&format!(
        "export declare const IID_{}: unknown;\n\nexport declare class {} {{\n",
        meta.name, meta.name
    ));
    out.push_str(&format!(
        "    static readonly IID: typeof IID_{};\n",
        meta.name
    ));
    out.push_str("    protected constructor(obj: unknown);\n");
    match &meta.activation {
        ActivationPlan::None => {}
        ActivationPlan::Coclass { .. } => {}
        ActivationPlan::WinRtFactory { .. } => out.push_str(&format!(
            "    /** Activate the projected WinRT class and QI to the interop.\n     * `DynCom.initialize()` must be called once (e.g. at process startup) before this is used. */\n    static create(): {};\n",
            meta.name
        )),
    }
    out.push_str(&format!("    /** Wrap an existing native COM pointer (for QueryInterface bridging). */\n    static _fromNative(obj: unknown): {};\n", meta.name));
    out.push_str("    /** Release the underlying native COM reference. Safe to call more than once. */\n    release(): void;\n");
    let mut emitted_groups = std::collections::HashSet::new();
    for method in &meta.methods {
        if let Some(overload) = &method.overload {
            if !emitted_groups.insert(overload.public_name.clone()) {
                continue;
            }
            let group_methods: Vec<_> = meta
                .methods
                .iter()
                .filter(|candidate| {
                    candidate
                        .overload
                        .as_ref()
                        .is_some_and(|candidate_overload| {
                            candidate_overload.public_name == overload.public_name
                        })
                })
                .collect();
            emit_method_doc_dts(&mut out, &group_methods.iter().find_map(|m| m.doc.clone()));
            for group_method in &group_methods {
                out.push_str(&format!(
                    "    {}({}): {};\n",
                    overload.public_name,
                    dts_params(group_method).join(", "),
                    dts_return_type(group_method)
                ));
            }
            continue;
        }
        let (params, ret) = match method.kind {
            ProjectedComMethodKind::Normal => (dts_params(method), dts_return_type(method)),
            ProjectedComMethodKind::CallerSuppliedDynamicIid {
                natural_param_count,
            } => {
                let mut params = dts_natural_params(method, natural_param_count);
                params.push("iid: string".into());
                (params, "DynWinRtValue".into())
            }
            ProjectedComMethodKind::SynthesizedGetForWindow {
                natural_param_count,
                ..
            } => (
                dts_natural_params(method, natural_param_count),
                "DynWinRtValue".into(),
            ),
        };
        emit_method_doc_dts(&mut out, &method.doc);
        out.push_str(&format!(
            "    {}({}): {};\n",
            method.camel_name,
            params.join(", "),
            ret
        ));
    }
    out.push_str("}\n");
    out
}

/// Emits a one-line `@see` TSDoc comment above a `.d.ts` method signature
/// when metadata supplied a doc reference. Mirrors `emit_method_doc_js`;
/// renders nothing when `doc` is `None`.
fn emit_method_doc_dts(out: &mut String, doc: &Option<String>) {
    if let Some(url) = doc {
        out.push_str(&format!("    /** @see {{@link {url}}} */\n"));
    }
}

fn dts_natural_params(method: &ProjectedComMethod, count: usize) -> Vec<String> {
    method.params[..count]
        .iter()
        .enumerate()
        .map(|(index, param)| {
            format!(
                "{}: {}",
                js_param_name(&param.name, index),
                input_type_dts(&param.typ)
            )
        })
        .collect()
}

fn dts_params(method: &ProjectedComMethod) -> Vec<String> {
    method
        .params
        .iter()
        .enumerate()
        .filter(|(_, param)| param.direction.is_input())
        .enumerate()
        .map(|(surface, (index, param))| {
            let mut name = js_param_name(&param.name, surface);
            if method
                .string_buffer
                .as_ref()
                .is_some_and(|plan| plan.optional_param_indices.contains(&index))
            {
                name.push('?');
            }
            format!("{name}: {}", input_type_dts(&param.typ))
        })
        .collect()
}

fn dts_return_type(method: &ProjectedComMethod) -> String {
    if method.string_buffer.is_some() {
        return if method.results.is_empty() {
            "string".into()
        } else {
            format!(
                "[string, {}]",
                method
                    .results
                    .iter()
                    .map(result_type_dts)
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        };
    }
    match method.results.len() {
        0 => "void".into(),
        1 => result_type_dts(&method.results[0]),
        _ => format!(
            "[{}]",
            method
                .results
                .iter()
                .map(result_type_dts)
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

fn collect_pointer_aliases(meta: &ProjectedComInterface) -> Vec<(String, PointerAliasKind)> {
    let mut aliases = BTreeMap::new();
    for method in &meta.methods {
        for typ in
            method
                .params
                .iter()
                .map(|param| &param.typ)
                .chain(match &method.return_convention {
                    ComReturnConvention::Direct(typ) => Some(typ),
                    _ => None,
                })
        {
            match typ {
                ComType::PointerAlias { name, kind } => {
                    aliases.insert(name.clone(), *kind);
                }
                ComType::Bstr => {
                    aliases.insert("BSTR".into(), PointerAliasKind::HandleValue);
                }
                ComType::Primitive(_)
                | ComType::NativeIsize
                | ComType::NativeUsize
                | ComType::Win32Bool
                | ComType::HResult
                | ComType::Guid
                | ComType::HString
                | ComType::Enum { .. }
                | ComType::ScalarAlias { .. }
                | ComType::RawPointer
                | ComType::ManagedInterface { .. } => {}
            }
        }
    }
    aliases.into_iter().collect()
}

fn collect_scalar_aliases(
    meta: &ProjectedComInterface,
) -> Vec<(String, super::super::ir::ComScalarRepr)> {
    let mut aliases = BTreeMap::new();
    for method in &meta.methods {
        for typ in
            method
                .params
                .iter()
                .map(|param| &param.typ)
                .chain(match &method.return_convention {
                    ComReturnConvention::Direct(typ) => Some(typ),
                    _ => None,
                })
        {
            if let ComType::ScalarAlias { name, underlying } = typ {
                aliases.insert(name.clone(), *underlying);
            }
        }
    }
    aliases.into_iter().collect()
}

fn needs_bridge_import(meta: &ProjectedComInterface) -> bool {
    matches!(meta.activation, ActivationPlan::WinRtFactory { .. })
        || meta.methods.iter().any(|method| {
            !matches!(method.kind, ProjectedComMethodKind::Normal)
                || method
                    .params
                    .iter()
                    .any(|param| matches!(param.typ, ComType::ManagedInterface { .. }))
                || method.results.iter().any(|result| {
                    matches!(
                        result.conversion,
                        ResultConversion::ManagedCom
                            | ResultConversion::CoTaskMemData
                            | ResultConversion::DynamicIidAdoption
                    )
                })
        })
}

fn com_runtime_import_name() -> String {
    let import_name = crate::codegen::project::get_import_name();
    if import_name == "@microsoft/dynwinrt" {
        format!("{import_name}/com")
    } else {
        import_name
    }
}

fn render_enum_files(en: &ProjectedComEnum) -> (String, String) {
    let mut js = String::from("// Generated by dynwinrt-codegen — do not edit\n");
    js.push_str(&format!("export const {} = Object.freeze({{\n", en.name));
    for member in &en.members {
        js.push_str(&format!(
            "    {}: {},\n",
            member.name,
            render_enum_value(&member.value, en.underlying)
        ));
    }
    js.push_str("});\n");
    let mut dts = String::from("// Generated by dynwinrt-codegen — do not edit\n");
    dts.push_str(&format!(
        "export type {} = (typeof {})[keyof typeof {}];\n",
        en.name, en.name, en.name
    ));
    dts.push_str(&format!("export declare const {}: {{\n", en.name));
    for member in &en.members {
        dts.push_str(&format!(
            "    readonly {}: {};\n",
            member.name,
            render_enum_value(&member.value, en.underlying)
        ));
    }
    dts.push_str("};\n");
    (com_esm_to_cjs(&js), dts)
}

fn render_enum_value(value: &ProjectedEnumValue, underlying: ComEnumUnderlying) -> String {
    let suffix = if matches!(underlying, ComEnumUnderlying::I64 | ComEnumUnderlying::U64) {
        "n"
    } else {
        ""
    };
    match value {
        ProjectedEnumValue::Signed(value) => format!("{value}{suffix}"),
        ProjectedEnumValue::Unsigned(value) => format!("{value}{suffix}"),
    }
}

#[cfg(test)]
#[path = "render_tests.rs"]
mod tests;
