# Generated by winrt-meta — do not edit
from __future__ import annotations
from dynwinrt_py import (
    DynWinRTValue, DynWinRTArray, DynWinRTStruct, DynWinRtDelegate, WinGUID,
)


IID_IStringable: WinGUID


class IStringable:
    def __init__(self, obj: DynWinRTValue) -> None: ...

    @staticmethod
    def from_value(obj: DynWinRTValue) -> 'IStringable': ...

    def to_string(self) -> str: ...
