# Generated by winrt-meta — do not edit
from __future__ import annotations
from dynwinrt_py import (
    DynWinRTType, DynWinRTValue, DynWinRTArray, DynWinRTStruct, DynWinRtDelegate, WinGUID,
)


IID_IUriRuntimeClassWithAbsoluteCanonicalUri: WinGUID


class IUriRuntimeClassWithAbsoluteCanonicalUri:
    def __init__(self, obj: DynWinRTValue) -> None: ...

    @staticmethod
    def from_value(obj: DynWinRTValue) -> 'IUriRuntimeClassWithAbsoluteCanonicalUri': ...

    @property
    def absolute_canonical_uri(self) -> str: ...

    @property
    def display_iri(self) -> str: ...
