// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Classic-COM (option A) code generation.
//!
//! This module generates natural TypeScript/JS wrappers for IUnknown-rooted
//! Win32 COM interfaces described in Windows.Win32.winmd. It intentionally
//! keeps a **separate pipeline** from the WinRT projection: classic COM has
//! meaningfully different semantics (IUnknown base offset of 3 vs 6, HRESULT
//! throw-on-failure, `CoCreateInstance` activation, no IReference/async
//! projection) so mixing them into the existing IR would obscure both paths.
//!
//! What we emit today (phase 1):
//! - `<InterfaceName>.js`: registration via `DynCom.registerIUnknownInterface`
//!   + a natural class with camelCase methods and static `create()` /
//!   `_fromNative()`.
//! - `<InterfaceName>.d.ts`: PascalCase class, camelCase methods, handle-value
//!   typedefs (HWND etc.) as `bigint | number`, string-pointer typedefs (PWSTR
//!   etc.) as `bigint | Buffer`, HRESULT returns projected to `void` (throwing
//!   on failure via the runtime).
//! - Per-enum sibling files for each enum referenced by any method parameter.

use crate::com_metadata::{
    ComEnumMeta, ComEnumValue, ComInterfaceMeta, MethodMeta, ParamDirection, ParamMeta,
};
use crate::types::TypeMeta;

#[cfg(test)]
use super::naming::strip_hungarian;
use super::naming::{camel_case, js_param_name};
use super::projection::method_is_interop_shape;
use super::projection::{InteropInfo, InteropMethod, detect_interop};
use super::type_mapping::{
    HandleAliasKind, MethodResult, StringEncoding, collect_handle_aliases, dts_params_for_method,
    dts_return_type, enum_import_names, has_string_buffer_method, is_bstr, is_cotaskmem_owned,
    is_hresult, is_optional_find_data_out_after_string_count, is_sys_free_string_owned,
    method_results, string_buffer_param_is_optional, string_buffer_pattern, ts_input_type_expr_dts,
    ts_type_expr_js, unwrap_return_js, uses_winrt_bridge_value, validate_com_abi, wrap_arg_js,
};
#[cfg(test)]
use super::type_mapping::{handle_alias_kind, handle_type_name, ts_type_expr_dts};

/// A rendered classic-COM output: primary `.js` + `.d.ts` for the interface,
/// plus zero or more sibling files (one `.js` + `.d.ts` per referenced enum).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ComGeneratedOutput {
    pub js: String,
    pub dts: String,
    /// Additional files (filename → content). Includes each enum's `.js` and
    /// `.d.ts`. Stable-sorted by filename for deterministic output.
    pub extra_files: Vec<(String, String)>,
}

// ---------------------------------------------------------------------------
// Public entry
// ---------------------------------------------------------------------------

/// Generate the `.js` + `.d.ts` for a classic-COM interface.
///
/// `winmd_paths` is the semicolon-separated list of `.winmd` files loaded by
/// the generator. Interop `*Interop` interfaces consult these winmds FIRST
/// to resolve the projected WinRT runtime class's default IID; if that fails
/// (e.g. the caller only passed Win32 metadata), the generator falls back to
/// the NEWEST installed `UnionMetadata\<version>\Windows.winmd`. If the target
/// IID still cannot be resolved for a confirmed interop shape, generation
/// **fails loudly** with `Err(...)` — the generator must never emit a NULL
/// riid that would silently break the wrapper at runtime.
pub fn generate_com_interface_files(
    meta: &ComInterfaceMeta,
    winmd_paths: &str,
) -> Result<ComGeneratedOutput, String> {
    validate_com_abi(meta)?;
    validate_untyped_outputs(meta)?;

    // Detect whether this is a `*Interop` interface whose every method has the
    // `(HWND, [HSTRING…,] REFIID, out void**)` GetForWindow shape. Natural
    // signatures hide the REFIID + void** and return an explicit bridge value.
    let interop = detect_interop(meta, winmd_paths)?;

    let js = render_js(meta, interop.as_ref());
    let dts = render_dts(meta, interop.as_ref());

    // Per-enum sibling files (referenced by parameter types).
    let mut extra_files: Vec<(String, String)> = Vec::new();
    for en in &meta.referenced_enums {
        let (enum_js, enum_dts) = render_enum_files(en);
        extra_files.push((format!("{}.js", en.name), enum_js));
        extra_files.push((format!("{}.d.ts", en.name), enum_dts));
    }

    extra_files.sort_by(|a, b| a.0.cmp(&b.0));

    Ok(ComGeneratedOutput {
        js,
        dts,
        extra_files,
    })
}

// ---------------------------------------------------------------------------
// .js rendering
// ---------------------------------------------------------------------------

fn render_js(meta: &ComInterfaceMeta, interop: Option<&InteropInfo>) -> String {
    let iface = &meta.interface;
    let iid = &iface.iid;
    let name = &iface.name;

    let mut out = String::new();
    out.push_str("// Generated by dynwinrt-codegen — do not edit\n");

    // Imports (runtime + any referenced enums)
    let runtime_imports = if interop.is_some() {
        "DynCom, DynComMethodSig, DynWinRtValue, WinGuid"
    } else {
        "DynCom, DynComMethodSig, WinGuid"
    };
    out.push_str(&format!(
        "import {{ {runtime_imports} }} from '{}';\n",
        com_runtime_import_name()
    ));
    for en in enum_import_names(meta) {
        out.push_str(&format!("import {{ {} }} from './{}.js';\n", en, en));
    }
    out.push('\n');

    if has_string_buffer_method(meta) {
        out.push_str("function _normalizeStringBufferCount(value, name) {\n");
        out.push_str("    if (!Number.isInteger(value) || value <= 0) throw new TypeError(`${name} must be a positive integer`);\n");
        out.push_str("    return value;\n");
        out.push_str("}\n");
        out.push_str("function _decodeWideString(buffer) {\n");
        out.push_str("    let end = 0;\n");
        out.push_str(
            "    while (end + 1 < buffer.length && buffer.readUInt16LE(end) !== 0) end += 2;\n",
        );
        out.push_str("    return buffer.subarray(0, end).toString('utf16le');\n");
        out.push_str("}\n\n");
    }

    out.push_str(&format!(
        "export const IID_{name} = WinGuid.parse('{iid}');\n",
        name = name,
        iid = iid
    ));
    // For interop wrappers with a resolved target IID, also emit the target
    // interface IID as a private constant used by the getForWindow call.
    if let Some(info) = interop {
        if !info.target_iid.is_empty() {
            out.push_str(&format!(
                "const IID_{cls}_default = WinGuid.parse('{iid}');\n",
                cls = info.class_name,
                iid = info.target_iid,
            ));
        }
    }
    out.push('\n');

    // Interface registration is base-aware.
    let register_fn = if meta.is_iunknown_rooted {
        "registerIUnknownInterface"
    } else {
        "registerIInspectableInterface"
    };
    let registration_name = format!("{}.{}", iface.namespace, name);
    let cache_var = format!("_{name}Cache", name = name);
    let iface_var = format!("_{name}", name = name);
    out.push_str(&format!("let {cache_var};\n", cache_var = cache_var));
    out.push_str(&format!(
        "const {iface_var} = new Proxy({{}}, {{\n    get(_target, prop) {{\n        {cache_var} ??= DynCom.{register_fn}('{registration_name}', IID_{name})\n",
        iface_var = iface_var,
        cache_var = cache_var,
        name = name,
        registration_name = registration_name,
        register_fn = register_fn,
    ));
    for m in &iface.methods {
        out.push_str(&format!(
            "            .addMethod('{}', {})\n",
            m.name,
            build_method_sig_js(m)
        ));
    }
    // Trim trailing newline before closing the block, then close.
    if out.ends_with('\n') {
        out.truncate(out.len() - 1);
    }
    out.push_str(";\n");
    out.push_str(&format!(
        "        const value = {cache_var}[prop];\n        return typeof value === 'function' ? value.bind({cache_var}) : value;\n    }},\n}});\n",
        cache_var = cache_var,
    ));
    out.push('\n');

    // Class body
    out.push_str(&format!("export class {name} {{\n", name = name));
    out.push_str("    _obj;\n");
    out.push_str("    constructor(obj) { this._obj = obj; }\n");
    out.push_str(&format!(
        "    static _fromNative(obj) {{ return new {name}(obj); }}\n",
        name = name
    ));

    if let Some(ref clsid) = meta.coclass_clsid {
        // static create() — classic COM CLSID-based activation.
        out.push_str(&format!(
            "    /** Create a new `{name}` via `CoCreateInstance` on `CLSID_{cc}`. */\n",
            name = name,
            cc = meta.coclass_name.as_deref().unwrap_or("Coclass")
        ));
        out.push_str(&format!(
            "    static create() {{\n        const _obj = DynCom.coCreateInstance('{clsid}', IID_{name});\n        return new {name}(_obj);\n    }}\n",
            clsid = clsid,
            name = name,
        ));
    } else if let Some(info) = interop {
        if !info.class_namespace.is_empty() {
            // static create() — interop activation: activate the projected
            // WinRT runtime class's factory, then QI to the interop IID.
            let full_class_name = format!("{}.{}", info.class_namespace, info.class_name);
            out.push_str(&format!(
                "    /** Create a new `{name}` by activating the `{full_class_name}` factory and QI'ing to the interop. */\n",
                name = name,
                full_class_name = full_class_name,
            ));
            out.push_str(&format!(
                "    static create() {{\n        const factory = DynWinRtValue.activationFactory('{full_class_name}');\n        const _obj = factory.cast(IID_{name});\n        return new {name}(_obj);\n    }}\n",
                full_class_name = full_class_name,
                name = name,
            ));
        }
    }

    // Emit methods: natural interop shape when available, otherwise pass-through.
    if let Some(info) = interop {
        for im in &info.methods {
            emit_interop_method_js(&mut out, im, &iface_var, info);
        }
    } else {
        for m in &iface.methods {
            if let Some(natural_params) = method_is_interop_shape(m) {
                emit_dynamic_iid_method_js(&mut out, m, &natural_params, &iface_var);
            } else {
                emit_method_js(&mut out, m, &iface_var);
            }
        }
    }
    out.push_str("}\n");
    out
}

fn unwrap_method_result_js(
    method: &MethodMeta,
    result: MethodResult<'_>,
    expression: &str,
) -> String {
    if is_sys_free_string_owned(method, result) {
        format!("DynCom.takeBstr({expression})")
    } else if is_cotaskmem_owned(method, result)
        && !matches!(
            result.typ,
            TypeMeta::Struct { namespace, name, .. }
                if namespace == "Windows.Win32.Foundation"
                    && (name == "PWSTR" || name == "PSTR")
        )
    {
        format!("DynCom.adoptCoTaskMemPointer({expression})")
    } else {
        unwrap_return_js(result.typ, expression)
    }
}

fn validate_untyped_outputs(meta: &ComInterfaceMeta) -> Result<(), String> {
    for method in &meta.interface.methods {
        for (param_index, param) in method.params.iter().enumerate() {
            let is_untyped =
                param.direction == ParamDirection::Out && param.typ == TypeMeta::Object;
            let is_owned = method.owned_outputs.iter().any(|owned| {
                owned.param_index == param_index
                    && (owned.free_with.contains("CoTaskMemFree")
                        || (owned.free_with.contains("SysFreeString") && is_bstr(&param.typ)))
            });
            if is_untyped && !is_owned && method_is_interop_shape(method).is_none() {
                return Err(format!(
                    "{}.{}: untyped pointer output has no ownership projection",
                    meta.interface.name, method.name
                ));
            }
        }
    }
    Ok(())
}

fn emit_dynamic_iid_method_js(
    out: &mut String,
    method: &MethodMeta,
    natural_params: &[ParamMeta],
    interface_var: &str,
) {
    let mut surface_params = natural_params
        .iter()
        .enumerate()
        .map(|(index, param)| js_param_name(&param.name, index))
        .collect::<Vec<_>>();
    surface_params.push("iid".into());
    let mut args = natural_params
        .iter()
        .enumerate()
        .map(|(index, param)| wrap_arg_js(&param.typ, &js_param_name(&param.name, index)))
        .collect::<Vec<_>>();
    args.push("DynCom.iidPointer(_iid)".into());
    out.push_str(&format!(
        "    {name}({params}) {{\n",
        name = camel_case(&method.name),
        params = surface_params.join(", ")
    ));
    out.push_str("        const _iid = WinGuid.parse(iid);\n");
    out.push_str(&format!(
        "        const _raw = {interface_var}.method({slot}).invoke(this._obj, [{args}]);\n",
        slot = method.vtable_index,
        args = args.join(", ")
    ));
    out.push_str("        return DynCom.adoptComPointer(_raw, _iid);\n");
    out.push_str("    }\n");
}

fn build_method_sig_js(m: &MethodMeta) -> String {
    let mut parts = Vec::new();
    let string_buffer = string_buffer_pattern(m);
    for (idx, p) in m.params.iter().enumerate() {
        if p.direction == ParamDirection::In {
            parts.push(format!(".addIn({})", ts_type_expr_js(&p.typ)));
        } else if p.direction == ParamDirection::InOut {
            parts.push(format!(".addInOut({})", ts_type_expr_js(&p.typ)));
        } else if matches!(p.direction, ParamDirection::OutStringBuffer { .. }) {
            parts.push(".addIn(DynCom.pointerType())".to_string());
        } else if p.direction == ParamDirection::Out {
            if string_buffer.is_some_and(|(_, count_idx, _)| {
                idx > count_idx && is_optional_find_data_out_after_string_count(p)
            }) {
                parts.push(".addIn(DynCom.pointerType())".to_string());
            } else {
                parts.push(format!(".addOut({})", ts_type_expr_js(&p.typ)));
            }
        } else if p.direction == ParamDirection::OutFill {
            parts.push(format!(".addOutFill({})", ts_type_expr_js(&p.typ)));
        }
    }
    match &m.return_type {
        None => parts.push(".returnsVoid()".to_string()),
        Some(rt) if !is_hresult(rt) => {
            parts.push(format!(".returns({})", ts_type_expr_js(rt)));
        }
        _ => {}
    }
    if parts.is_empty() {
        "new DynComMethodSig()".to_string()
    } else {
        format!("new DynComMethodSig(){}", parts.join(""))
    }
}

fn emit_method_js(out: &mut String, m: &MethodMeta, iface_var: &str) {
    let camel = camel_case(&m.name);
    let in_params: Vec<(usize, &ParamMeta)> = m
        .params
        .iter()
        .enumerate()
        .filter(|(_, p)| p.direction.is_input())
        .collect();
    let results = method_results(m);
    let has_outfill = m
        .params
        .iter()
        .any(|p| p.direction == ParamDirection::OutFill);

    let param_list: Vec<String> = in_params
        .iter()
        .enumerate()
        .map(|(surface_i, (idx, p))| {
            let name = js_param_name(&p.name, surface_i);
            if let Some((_, count_idx, _)) = string_buffer_pattern(m) {
                if *idx == count_idx && string_buffer_param_is_optional(m, *idx) {
                    return format!("{name} = 260");
                }
                if *idx > count_idx && string_buffer_param_is_optional(m, *idx) {
                    return format!("{name} = 0");
                }
            }
            name
        })
        .collect();

    let args_exprs: Vec<String> = in_params
        .iter()
        .enumerate()
        .map(|(i, (_, p))| wrap_arg_js(&p.typ, &js_param_name(&p.name, i)))
        .collect();

    out.push_str(&format!(
        "    {camel}({params}) {{\n",
        camel = camel,
        params = param_list.join(", ")
    ));
    if let Some((buffer_idx, count_idx, encoding)) = string_buffer_pattern(m) {
        let count_surface_idx = in_params
            .iter()
            .position(|(idx, _)| *idx == count_idx)
            .expect("count param must be an input");
        let count_name = js_param_name(&m.params[count_idx].name, count_surface_idx);
        if encoding == StringEncoding::Ansi {
            out.push_str(
                "        throw new Error('PSTR out buffers are not yet decoded safely');\n",
            );
            out.push_str("    }\n");
            return;
        }
        let args: Vec<String> = m
            .params
            .iter()
            .enumerate()
            .filter_map(|(idx, p)| {
                if idx == buffer_idx {
                    Some("DynCom.pointer(_buffer)".to_string())
                } else if p.direction.is_input() {
                    let surface_idx = in_params
                        .iter()
                        .position(|(param_idx, _)| *param_idx == idx)
                        .expect("input param must have a surface index");
                    Some(wrap_arg_js(&p.typ, &js_param_name(&p.name, surface_idx)))
                } else if idx > count_idx && is_optional_find_data_out_after_string_count(p) {
                    Some("DynCom.pointer(0n)".to_string())
                } else {
                    None
                }
            })
            .collect();
        out.push_str(&format!(
            "        {count_name} = _normalizeStringBufferCount({count_name}, '{count_name}');\n"
        ));
        out.push_str(&format!(
            "        const _buffer = Buffer.alloc({count_name} * 2);\n"
        ));
        match results.len() {
            0 => out.push_str(&format!(
                "        {iface_var}.method({slot}).invoke(this._obj, [{args}]);\n",
                iface_var = iface_var,
                slot = m.vtable_index,
                args = args.join(", ")
            )),
            1 => out.push_str(&format!(
                "        const _out = {iface_var}.method({slot}).invoke(this._obj, [{args}]);\n",
                iface_var = iface_var,
                slot = m.vtable_index,
                args = args.join(", ")
            )),
            _ => out.push_str(&format!(
                "        const _out = {iface_var}.method({slot}).invokeAll(this._obj, [{args}]);\n",
                iface_var = iface_var,
                slot = m.vtable_index,
                args = args.join(", ")
            )),
        }
        out.push_str("        const _text = _decodeWideString(_buffer);\n");
        match results.len() {
            0 => out.push_str("        return _text;\n"),
            1 => out.push_str(&format!(
                "        return [_text, {}];\n",
                unwrap_method_result_js(m, results[0], "_out")
            )),
            _ => {
                let values = results
                    .iter()
                    .enumerate()
                    .map(|(index, result)| {
                        unwrap_method_result_js(m, *result, &format!("_out[{index}]"))
                    })
                    .collect::<Vec<_>>();
                out.push_str(&format!("        return [_text, {}];\n", values.join(", ")));
            }
        }
        out.push_str("    }\n");
        return;
    }
    // Project trailing `[out]` params as JS return values, mirroring how the
    // WinRT codegen already handles out-params (see
    // `codegen/javascript/project/methods.rs` — `is_multi_output` / `invokeAll`).
    // OutFill (caller-allocated buffers, e.g. GetPath(LPWSTR, cchMax)) are
    // NOT projected — see the TODO note below.
    if has_outfill {
        out.push_str("        // TODO: caller-allocated [out, sizeis] buffers are not yet projected as returns.\n");
    }
    match results.len() {
        0 => {
            out.push_str(&format!(
                "        {iface_var}.method({slot}).invoke(this._obj, [{args}]);\n",
                iface_var = iface_var,
                slot = m.vtable_index,
                args = args_exprs.join(", ")
            ));
        }
        1 => {
            out.push_str(&format!(
                "        const _out = {iface_var}.method({slot}).invoke(this._obj, [{args}]);\n",
                iface_var = iface_var,
                slot = m.vtable_index,
                args = args_exprs.join(", ")
            ));
            out.push_str(&format!(
                "        return {};\n",
                unwrap_method_result_js(m, results[0], "_out")
            ));
        }
        _ => {
            out.push_str(&format!(
                "        const _r = {iface_var}.method({slot}).invokeAll(this._obj, [{args}]);\n",
                iface_var = iface_var,
                slot = m.vtable_index,
                args = args_exprs.join(", ")
            ));
            let items: Vec<String> = results
                .iter()
                .enumerate()
                .map(|(i, result)| unwrap_method_result_js(m, *result, &format!("_r[{i}]")))
                .collect();
            out.push_str(&format!("        return [{}];\n", items.join(", ")));
        }
    }
    out.push_str("    }\n");
}

/// Emit an interop method: either natural (hide trailing REFIID + void**) or
/// plain (fall back to the normal classic-COM emission).
fn emit_interop_method_js(
    out: &mut String,
    im: &InteropMethod,
    iface_var: &str,
    info: &InteropInfo,
) {
    let Some(natural_params) = &im.natural_params else {
        if let Some(m) = &im.plain {
            if let Some(natural) = method_is_interop_shape(m) {
                emit_dynamic_iid_method_js(out, m, &natural, iface_var);
            } else {
                emit_method_js(out, m, iface_var);
            }
        }
        return;
    };
    let param_list: Vec<String> = natural_params
        .iter()
        .enumerate()
        .map(|(i, p)| js_param_name(&p.name, i))
        .collect();

    let mut arg_exprs: Vec<String> = natural_params
        .iter()
        .enumerate()
        .map(|(i, p)| wrap_arg_js(&p.typ, &js_param_name(&p.name, i)))
        .collect();

    // The synthesised REFIID pointer. When we have a resolved target IID we
    // pass the cached pointer; otherwise the method is unusable (still emitted
    // for completeness so `.d.ts` doesn't lie about the surface).
    let riid_arg = if !info.target_iid.is_empty() {
        format!("DynCom.iidPointer(IID_{}_default)", info.class_name)
    } else {
        "DynCom.pointer(0n)".to_string()
    };
    arg_exprs.push(riid_arg);

    out.push_str(&format!(
        "    {camel}({params}) {{\n",
        camel = im.camel,
        params = param_list.join(", "),
    ));
    if !info.target_iid.is_empty() {
        out.push_str(&format!(
            "        const _raw = {iface_var}.method({slot}).invoke(this._obj, [{args}]);\n",
            iface_var = iface_var,
            slot = im.vtable_index,
            args = arg_exprs.join(", "),
        ));
        out.push_str(&format!(
            "        const _out = DynCom.adoptComPointer(_raw, IID_{cls}_default);\n",
            cls = info.class_name,
        ));
        out.push_str("        return _out;\n");
    } else {
        // Fallback: no projection available. Return the raw object.
        out.push_str(&format!(
            "        return {iface_var}.method({slot}).invoke(this._obj, [{args}]);\n",
            iface_var = iface_var,
            slot = im.vtable_index,
            args = arg_exprs.join(", "),
        ));
    }
    out.push_str("    }\n");
}

// ---------------------------------------------------------------------------
// .d.ts rendering
// ---------------------------------------------------------------------------

fn render_dts(meta: &ComInterfaceMeta, interop: Option<&InteropInfo>) -> String {
    let iface = &meta.interface;
    let name = &iface.name;

    let mut out = String::new();
    out.push_str("// Generated by dynwinrt-codegen — do not edit\n");
    // Import Buffer type hint via `import type` from Node ambient — HWND uses `Buffer`.
    // Node.js `Buffer` is a global type; no import needed. We DO import enum types.
    for en in enum_import_names(meta) {
        out.push_str(&format!("import {{ {} }} from './{}.js';\n", en, en));
    }
    if interop.is_some()
        || uses_winrt_bridge_value(meta)
        || has_dynamic_iid_method(meta)
        || has_owned_pointer_output(meta)
    {
        out.push_str(&format!(
            "import type {{ DynWinRtValue }} from '{}';\n",
            com_runtime_import_name()
        ));
    }
    out.push('\n');

    // Emit typedef aliases for handles seen in method parameters.
    let handle_aliases = collect_handle_aliases(meta);
    for (h, kind) in &handle_aliases {
        match kind {
            HandleAliasKind::HandleValue => out.push_str(&format!(
                "/** Opaque Win32 handle value. Pass a raw pointer value as a `bigint` (full pointer width) or `number` (safe integer). */\nexport type {h} = bigint | number;\n"
            )),
            HandleAliasKind::DataPointer => out.push_str(&format!(
                "/** Opaque native data address. Inputs may also use a `Buffer`/`Uint8Array`, whose backing-store address is passed and retained for the call. */\nexport type {h} = bigint | number;\n"
            )),
            HandleAliasKind::StringPointer => out.push_str(&format!(
                "/** Win32 NUL-terminated string pointer. Pass a `Buffer` holding the string bytes (including the NUL terminator), or pass a raw pointer as `bigint`. */\nexport type {h} = bigint | Buffer;\n"
            )),
        }
    }
    if !handle_aliases.is_empty() {
        out.push('\n');
    }

    out.push_str(&format!(
        "export declare const IID_{name}: unknown;\n\n",
        name = name
    ));

    out.push_str(&format!("export declare class {name} {{\n", name = name));
    if meta.coclass_clsid.is_some() {
        out.push_str("    /** Create a new instance via the coclass activation path. */\n");
        out.push_str(&format!("    static create(): {name};\n", name = name));
    } else if let Some(info) = interop {
        if !info.class_namespace.is_empty() {
            out.push_str(&format!(
                "    /** Activate the projected WinRT class and QI to the interop. */\n    static create(): {name};\n",
                name = name
            ));
        }
    }
    out.push_str(&format!(
        "    /** Wrap an existing native COM pointer (for QueryInterface bridging). */\n    static _fromNative(obj: unknown): {name};\n",
        name = name
    ));

    if let Some(info) = interop {
        // Interop methods: NATURAL signatures for interop-shape methods (no
        // riid, no void**). Plain methods fall through to the normal
        // classic-COM emission.
        for im in &info.methods {
            match (&im.natural_params, &im.plain) {
                (Some(natural), _) => {
                    let ts_params: Vec<String> = natural
                        .iter()
                        .enumerate()
                        .map(|(i, p)| {
                            format!(
                                "{}: {}",
                                js_param_name(&p.name, i),
                                ts_input_type_expr_dts(&p.typ)
                            )
                        })
                        .collect();
                    let ret = "DynWinRtValue";
                    out.push_str(&format!(
                        "    {camel}({params}): {ret};\n",
                        camel = im.camel,
                        params = ts_params.join(", "),
                        ret = ret,
                    ));
                }
                (None, Some(m)) => {
                    let camel = camel_case(&m.name);
                    let (ts_params, ret) = if let Some(natural) = method_is_interop_shape(m) {
                        let mut params = natural
                            .iter()
                            .enumerate()
                            .map(|(index, param)| {
                                format!(
                                    "{}: {}",
                                    js_param_name(&param.name, index),
                                    ts_input_type_expr_dts(&param.typ)
                                )
                            })
                            .collect::<Vec<_>>();
                        params.push("iid: string".into());
                        (params, "DynWinRtValue".to_string())
                    } else {
                        (dts_params_for_method(m), dts_return_type(m))
                    };
                    out.push_str(&format!(
                        "    {camel}({params}): {ret};\n",
                        camel = camel,
                        params = ts_params.join(", "),
                        ret = ret,
                    ));
                }
                _ => {}
            }
        }
    } else {
        for m in &iface.methods {
            let camel = camel_case(&m.name);
            let (ts_params, ret) = if let Some(natural) = method_is_interop_shape(m) {
                let mut params = natural
                    .iter()
                    .enumerate()
                    .map(|(index, param)| {
                        format!(
                            "{}: {}",
                            js_param_name(&param.name, index),
                            ts_input_type_expr_dts(&param.typ)
                        )
                    })
                    .collect::<Vec<_>>();
                params.push("iid: string".into());
                (params, "DynWinRtValue".to_string())
            } else {
                (dts_params_for_method(m), dts_return_type(m))
            };
            out.push_str(&format!(
                "    {camel}({params}): {ret};\n",
                camel = camel,
                params = ts_params.join(", "),
                ret = ret,
            ));
        }
    }
    out.push_str("}\n");
    out
}

fn has_dynamic_iid_method(meta: &ComInterfaceMeta) -> bool {
    meta.interface
        .methods
        .iter()
        .any(|method| method_is_interop_shape(method).is_some())
}

fn has_owned_pointer_output(meta: &ComInterfaceMeta) -> bool {
    meta.interface.methods.iter().any(|method| {
        method.owned_outputs.iter().any(|owned| {
            owned.free_with.contains("CoTaskMemFree") || owned.free_with.contains("SysFreeString")
        })
    })
}

fn com_runtime_import_name() -> String {
    let import_name = crate::codegen::project::get_import_name();
    if import_name == "@microsoft/dynwinrt" {
        format!("{import_name}/com")
    } else {
        import_name
    }
}

// ---------------------------------------------------------------------------
// Enum sibling files
// ---------------------------------------------------------------------------

fn render_enum_files(en: &ComEnumMeta) -> (String, String) {
    let name = en.name.as_str();
    // .js: a frozen object.
    let mut js = String::new();
    js.push_str("// Generated by dynwinrt-codegen — do not edit\n");
    js.push_str(&format!(
        "export const {name} = Object.freeze({{\n",
        name = name
    ));
    for member in &en.members {
        js.push_str(&format!(
            "    {}: {},\n",
            member.name,
            render_enum_value(&member.value, &en.underlying)
        ));
    }
    js.push_str("});\n");

    // .d.ts: emit a const object + companion type — matches the JS `Object.freeze({...})`
    // runtime shape and mirrors the WinRT enum generator (see
    // `codegen::javascript::render::declarations::render_enum_dts`). Using `const enum`
    // breaks under TS `isolatedModules`, so we intentionally avoid it.
    let mut dts = String::new();
    dts.push_str("// Generated by dynwinrt-codegen — do not edit\n");
    dts.push_str(&format!(
        "export type {name} = (typeof {name})[keyof typeof {name}];\n",
        name = name
    ));
    dts.push_str(&format!("export declare const {name}: {{\n", name = name));
    for member in &en.members {
        dts.push_str(&format!(
            "    readonly {}: {};\n",
            member.name,
            render_enum_value(&member.value, &en.underlying)
        ));
    }
    dts.push_str("};\n");

    (js, dts)
}

fn render_enum_value(value: &ComEnumValue, underlying: &TypeMeta) -> String {
    let suffix = if matches!(underlying, TypeMeta::I64 | TypeMeta::U64) {
        "n"
    } else {
        ""
    };
    match value {
        ComEnumValue::Signed(value) => format!("{value}{suffix}"),
        ComEnumValue::Unsigned(value) => format!("{value}{suffix}"),
    }
}

// ---------------------------------------------------------------------------
// Unit tests (fast, no winmd — pure logic)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn camel_case_basic() {
        assert_eq!(camel_case("HrInit"), "hrInit");
        assert_eq!(camel_case("SetProgressValue"), "setProgressValue");
        assert_eq!(camel_case("AddTab"), "addTab");
        assert_eq!(camel_case("URL"), "url");
        assert_eq!(camel_case("IOHandle"), "ioHandle");
    }

    #[test]
    fn default_runtime_import_uses_com_subpath() {
        let previous = crate::codegen::project::get_import_name();
        crate::codegen::project::set_import_name("@microsoft/dynwinrt");
        assert_eq!(com_runtime_import_name(), "@microsoft/dynwinrt/com");
        crate::codegen::project::set_import_name(&previous);
    }

    #[test]
    fn strip_hungarian_only_at_word_boundary() {
        assert_eq!(strip_hungarian("dwReserved"), "Reserved");
        assert_eq!(strip_hungarian("hwndTab"), "Tab");
        // "hwnd" alone must NOT be stripped (no uppercase follow-up).
        assert_eq!(strip_hungarian("hwnd"), "hwnd");
    }

    #[test]
    fn handle_type_name_recognizes_hwnd_shape() {
        let hwnd = TypeMeta::Struct {
            namespace: "Windows.Win32.Foundation".into(),
            name: "HWND".into(),
            fields: vec![crate::types::FieldMeta {
                name: "Value".into(),
                typ: TypeMeta::Object,
            }],
        };
        assert_eq!(handle_type_name(&hwnd).as_deref(), Some("HWND"));
    }

    #[test]
    fn handle_alias_kind_distinguishes_handle_values_from_string_pointers() {
        let hwnd = TypeMeta::Struct {
            namespace: "Windows.Win32.Foundation".into(),
            name: "HWND".into(),
            fields: vec![crate::types::FieldMeta {
                name: "Value".into(),
                typ: TypeMeta::Object,
            }],
        };
        assert_eq!(handle_alias_kind(&hwnd), Some(HandleAliasKind::HandleValue));
        assert_eq!(
            handle_alias_kind(&pwstr_struct()),
            Some(HandleAliasKind::StringPointer)
        );
        let psid = TypeMeta::Struct {
            namespace: "Windows.Win32.Security".into(),
            name: "PSID".into(),
            fields: vec![crate::types::FieldMeta {
                name: "Value".into(),
                typ: TypeMeta::Object,
            }],
        };
        assert_eq!(handle_alias_kind(&psid), Some(HandleAliasKind::DataPointer));
    }

    #[test]
    fn hresult_is_not_a_handle() {
        let hr = TypeMeta::Struct {
            namespace: "Windows.Win32.Foundation".into(),
            name: "HRESULT".into(),
            fields: vec![crate::types::FieldMeta {
                name: "Value".into(),
                typ: TypeMeta::I32,
            }],
        };
        assert!(handle_type_name(&hr).is_none());
        assert!(is_hresult(&hr));
    }

    #[test]
    fn non_win32_struct_is_not_a_handle() {
        let rect = TypeMeta::Struct {
            namespace: "Windows.Foundation".into(),
            name: "Rect".into(),
            fields: vec![
                crate::types::FieldMeta {
                    name: "X".into(),
                    typ: TypeMeta::F32,
                },
                crate::types::FieldMeta {
                    name: "Y".into(),
                    typ: TypeMeta::F32,
                },
                crate::types::FieldMeta {
                    name: "Width".into(),
                    typ: TypeMeta::F32,
                },
                crate::types::FieldMeta {
                    name: "Height".into(),
                    typ: TypeMeta::F32,
                },
            ],
        };
        assert!(handle_type_name(&rect).is_none());
    }

    // ---- Fix 2 (BOOL → boolean/i32) ----

    fn win32_bool_struct() -> TypeMeta {
        TypeMeta::Struct {
            namespace: "Windows.Win32.Foundation".into(),
            name: "BOOL".into(),
            fields: vec![crate::types::FieldMeta {
                name: "Value".into(),
                typ: TypeMeta::I32,
            }],
        }
    }

    #[test]
    fn win32_bool_is_not_a_handle() {
        let b = win32_bool_struct();
        // Sanity: it's the exact shape of a handle (single Value: I32) — the
        // special-case must WIN over the generic handle heuristic.
        assert!(
            handle_type_name(&b).is_none(),
            "BOOL must not be emitted as an opaque handle typedef"
        );
    }

    #[test]
    fn win32_bool_projects_as_boolean_and_i32() {
        let b = win32_bool_struct();
        // .d.ts surface: boolean (not `BOOL` or `bigint | Buffer`)
        assert_eq!(ts_type_expr_dts(&b), "boolean");
        // .js registration: i32 type (not pointer)
        assert_eq!(ts_type_expr_js(&b), "DynCom.i32Type()");
        // .js argument marshalling: truthy→1, falsy→0 as an i32 (not pointer)
        assert_eq!(
            wrap_arg_js(&b, "fFullscreen"),
            "DynCom.i32(fFullscreen ? 1 : 0)"
        );
    }

    #[test]
    fn hresult_input_projects_as_number_and_i32_value() {
        let hr = make_hresult();
        assert_eq!(ts_type_expr_dts(&hr), "number");
        assert_eq!(ts_type_expr_js(&hr), "DynCom.i32Type()");
        assert_eq!(wrap_arg_js(&hr, "hr"), "DynCom.i32(hr)");

        let m = MethodMeta {
            name: "Close".into(),
            vtable_index: 4,
            params: vec![ParamMeta {
                name: "hr".into(),
                typ: hr,
                direction: ParamDirection::In,
            }],
            return_type: Some(make_hresult()),
            ..Default::default()
        };
        let com = plain_iface_with_method(m);
        let js = render_js(&com, None);
        let dts = render_dts(&com, None);
        assert!(
            js.contains(".addMethod('Close', new DynComMethodSig().addIn(DynCom.i32Type()))"),
            ".js must register HRESULT in-param as i32:\n{}",
            js
        );
        assert!(
            js.contains("DynCom.i32(hr)"),
            ".js must pass HRESULT by value as i32:\n{}",
            js
        );
        assert!(
            !js.contains("DynCom.pointer(hr)"),
            ".js must not pass HRESULT as a pointer:\n{}",
            js
        );
        assert!(
            dts.contains("close(hr: number): void;"),
            ".d.ts must type HRESULT in-param as number:\n{}",
            dts
        );
        assert!(
            !dts.contains("HRESULT"),
            ".d.ts must not expose an undefined HRESULT alias:\n{}",
            dts
        );
    }

    // ---- Fix 3 (REFIID-guarded interop heuristic) ----

    /// Helper: construct a MethodMeta with HRESULT return type.
    fn make_hresult() -> TypeMeta {
        TypeMeta::Struct {
            namespace: "Windows.Win32.Foundation".into(),
            name: "HRESULT".into(),
            fields: vec![crate::types::FieldMeta {
                name: "Value".into(),
                typ: TypeMeta::I32,
            }],
        }
    }

    #[test]
    fn interop_shape_accepts_riid_named_object_trailing_in() {
        // Real Windows.Win32 shape: `HRESULT GetForWindow(HWND appWindow, REFIID riid, out void** ppv)`.
        // REFIID typically projects to TypeMeta::Object with name "riid".
        let m = MethodMeta {
            name: "GetForWindow".into(),
            vtable_index: 3,
            params: vec![
                ParamMeta {
                    name: "appWindow".into(),
                    typ: TypeMeta::Object,
                    direction: ParamDirection::In,
                },
                ParamMeta {
                    name: "riid".into(),
                    typ: TypeMeta::Object,
                    direction: ParamDirection::In,
                },
                ParamMeta {
                    name: "ppv".into(),
                    typ: TypeMeta::Object,
                    direction: ParamDirection::Out,
                },
            ],
            return_type: Some(make_hresult()),
            ..Default::default()
        };
        let natural = method_is_interop_shape(&m)
            .expect("REFIID-shaped trailing in-param named `riid` must be recognised as interop");
        // Natural in-params = every in EXCEPT the trailing REFIID.
        assert_eq!(natural.len(), 1);
        assert_eq!(natural[0].name, "appWindow");
    }

    #[test]
    fn interop_shape_accepts_guid_typed_trailing_in() {
        // Some winmds project REFIID as TypeMeta::Guid rather than Object.
        let m = MethodMeta {
            name: "GetSomething".into(),
            vtable_index: 3,
            params: vec![
                ParamMeta {
                    name: "target".into(),
                    typ: TypeMeta::Object,
                    direction: ParamDirection::In,
                },
                ParamMeta {
                    // Deliberately NOT named "riid" — the type alone is sufficient.
                    name: "interfaceId".into(),
                    typ: TypeMeta::Guid,
                    direction: ParamDirection::In,
                },
                ParamMeta {
                    name: "out".into(),
                    typ: TypeMeta::Object,
                    direction: ParamDirection::Out,
                },
            ],
            return_type: Some(make_hresult()),
            ..Default::default()
        };
        let natural = method_is_interop_shape(&m)
            .expect("System.Guid-typed trailing in-param must be recognised as interop");
        assert_eq!(natural.len(), 1);
        assert_eq!(natural[0].name, "target");
    }

    /// FIX 3 REGRESSION: a method returning HRESULT with an [out] Object and a
    /// trailing In-Object whose name is NOT `riid`/`iid` (e.g. a real application
    /// COM interface pointer like `original`) must NOT be mis-classified as
    /// interop-shape. Otherwise the codegen would silently drop the caller's
    /// meaningful argument.
    #[test]
    fn interop_shape_rejects_non_refiid_trailing_object() {
        let m = MethodMeta {
            name: "CloneWithOriginal".into(),
            vtable_index: 3,
            params: vec![
                ParamMeta {
                    name: "context".into(),
                    typ: TypeMeta::Object,
                    direction: ParamDirection::In,
                },
                ParamMeta {
                    // NOT `riid`/`iid`, NOT Guid — a real COM pointer in-param.
                    name: "original".into(),
                    typ: TypeMeta::Object,
                    direction: ParamDirection::In,
                },
                ParamMeta {
                    name: "cloned".into(),
                    typ: TypeMeta::Object,
                    direction: ParamDirection::Out,
                },
            ],
            return_type: Some(make_hresult()),
            ..Default::default()
        };
        assert!(
            method_is_interop_shape(&m).is_none(),
            "trailing in-param `original` is a real Object argument, NOT a REFIID — \
             it must not be dropped by the interop heuristic"
        );
    }

    #[test]
    fn interop_shape_rejects_iid_named_non_object_param() {
        // A parameter named `riid` but typed as a plain I32 is not a REFIID —
        // reject rather than silently drop.
        let m = MethodMeta {
            name: "Weird".into(),
            vtable_index: 3,
            params: vec![
                ParamMeta {
                    name: "hwnd".into(),
                    typ: TypeMeta::Object,
                    direction: ParamDirection::In,
                },
                ParamMeta {
                    name: "riid".into(),
                    typ: TypeMeta::I32,
                    direction: ParamDirection::In,
                },
                ParamMeta {
                    name: "out".into(),
                    typ: TypeMeta::Object,
                    direction: ParamDirection::Out,
                },
            ],
            return_type: Some(make_hresult()),
            ..Default::default()
        };
        assert!(
            method_is_interop_shape(&m).is_none(),
            "an I32 named `riid` is not a REFIID — must be rejected"
        );
    }

    // ---- Fix 1 (winmd-derived interop IID, fail-loud on unresolved) ----

    /// Build a fully synthetic ComInterfaceMeta for an `IFooInterop`-style
    /// interface whose derived projected class name (`Foo`) does NOT exist
    /// anywhere reachable. The generator must FAIL LOUDLY rather than emit
    /// a NULL riid.
    #[test]
    fn interop_generation_fails_when_target_iid_unresolvable() {
        use crate::com_metadata::{ComInterfaceMeta, InterfaceMeta};

        let iface = InterfaceMeta {
            name: "IThisRuntimeClassDoesNotExist_DynWinrtInterop".into(),
            namespace: "Windows.Win32.System.WinRT".into(),
            iid: "00000000-0000-0000-0000-000000000000".into(),
            methods: vec![MethodMeta {
                name: "GetForWindow".into(),
                vtable_index: 3,
                params: vec![
                    ParamMeta {
                        name: "appWindow".into(),
                        typ: TypeMeta::Object,
                        direction: ParamDirection::In,
                    },
                    ParamMeta {
                        name: "riid".into(),
                        typ: TypeMeta::Object,
                        direction: ParamDirection::In,
                    },
                    ParamMeta {
                        name: "ppv".into(),
                        typ: TypeMeta::Object,
                        direction: ParamDirection::Out,
                    },
                ],
                return_type: Some(make_hresult()),
                ..Default::default()
            }],
            generic_piid: None,
            generic_args: Vec::new(),
            doc: None,
            deprecated: None,
        };
        let com = ComInterfaceMeta {
            interface: iface,
            base_offset: 3,
            is_iunknown_rooted: true,
            base_chain: vec!["IUnknown".into()],
            coclass_clsid: None,
            coclass_name: None,
            own_methods_start: 3,
            referenced_enums: Vec::new(),
        };
        // Pass empty winmd_paths — even with the newest-SDK fallback, the
        // synthetic class name won't be found anywhere.
        let result = generate_com_interface_files(&com, "");
        assert!(
            result.is_err(),
            "generator must fail loudly when the projected runtime-class IID \
             cannot be resolved; got Ok(_)"
        );
        let err = result.unwrap_err();
        assert!(
            err.contains("ThisRuntimeClassDoesNotExist_Dynwinrt")
                || err.contains("ThisRuntimeClassDoesNotExist_DynWinrt"),
            "error must name the class it failed to resolve: {}",
            err
        );
        assert!(
            !err.is_empty(),
            "error message must be non-empty (fail-loud contract)"
        );
    }

    #[test]
    fn non_interop_iunknown_interface_still_generates_without_winmd_lookup() {
        // A vanilla IUnknown-rooted interface with no coclass and no
        // interop shape must succeed even when we pass empty winmd paths.
        use crate::com_metadata::{ComInterfaceMeta, InterfaceMeta};
        let iface = InterfaceMeta {
            name: "IMyPlainClassicCom".into(),
            namespace: "Windows.Win32.System.Com".into(),
            iid: "11111111-2222-3333-4444-555555555555".into(),
            methods: vec![MethodMeta {
                name: "DoStuff".into(),
                vtable_index: 3,
                params: vec![],
                return_type: Some(make_hresult()),
                ..Default::default()
            }],
            generic_piid: None,
            generic_args: Vec::new(),
            doc: None,
            deprecated: None,
        };
        let com = ComInterfaceMeta {
            interface: iface,
            base_offset: 3,
            is_iunknown_rooted: true,
            base_chain: vec!["IUnknown".into()],
            coclass_clsid: None,
            coclass_name: None,
            own_methods_start: 3,
            referenced_enums: Vec::new(),
        };
        let out = generate_com_interface_files(&com, "")
            .expect("plain classic-COM codegen must succeed with no winmds");
        assert!(out.js.contains("DynCom.registerIUnknownInterface"));
        assert!(out.js.contains("method(3)"));
    }

    // ---- Fix 4 (classic-COM plain `[out]` param → return-value projection) ----

    fn plain_iface_with_method(m: MethodMeta) -> crate::com_metadata::ComInterfaceMeta {
        use crate::com_metadata::{ComInterfaceMeta, InterfaceMeta};
        let iface = InterfaceMeta {
            name: "IHasOut".into(),
            namespace: "Windows.Win32.System.Com".into(),
            iid: "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee".into(),
            methods: vec![m],
            generic_piid: None,
            generic_args: Vec::new(),
            doc: None,
            deprecated: None,
        };
        ComInterfaceMeta {
            interface: iface,
            base_offset: 3,
            is_iunknown_rooted: true,
            base_chain: vec!["IUnknown".into()],
            coclass_clsid: None,
            coclass_name: None,
            own_methods_start: 3,
            referenced_enums: Vec::new(),
        }
    }

    #[test]
    fn unsupported_struct_in_out_fails_closed() {
        let method = MethodMeta {
            name: "Read".into(),
            params: vec![ParamMeta {
                name: "value".into(),
                typ: TypeMeta::Struct {
                    namespace: "Windows.Win32.System.Com".into(),
                    name: "VARIANT".into(),
                    fields: vec![
                        crate::types::FieldMeta {
                            name: "vt".into(),
                            typ: TypeMeta::U16,
                        },
                        crate::types::FieldMeta {
                            name: "data".into(),
                            typ: TypeMeta::U64,
                        },
                    ],
                },
                direction: ParamDirection::InOut,
            }],
            return_type: Some(make_hresult()),
            ..Default::default()
        };

        let error = generate_com_interface_files(&plain_iface_with_method(method), "")
            .expect_err("unsupported struct in/out must not emit a wrong T** ABI");
        assert!(error.contains("requires native layout projection"));
    }

    #[test]
    fn unsupported_by_value_struct_fails_closed() {
        let method = MethodMeta {
            name: "DragEnter".into(),
            params: vec![ParamMeta {
                name: "point".into(),
                typ: TypeMeta::Struct {
                    namespace: "Windows.Win32.Foundation".into(),
                    name: "POINTL".into(),
                    fields: vec![
                        crate::types::FieldMeta {
                            name: "x".into(),
                            typ: TypeMeta::I32,
                        },
                        crate::types::FieldMeta {
                            name: "y".into(),
                            typ: TypeMeta::I32,
                        },
                    ],
                },
                direction: ParamDirection::In,
            }],
            return_type: Some(make_hresult()),
            ..Default::default()
        };
        let error = generate_com_interface_files(&plain_iface_with_method(method), "")
            .expect_err("struct layout must fail closed");
        assert!(error.contains("requires native layout projection"));
    }

    #[test]
    fn unsupported_struct_direct_return_fails_closed() {
        let method = MethodMeta {
            name: "GetPoint".into(),
            return_type: Some(TypeMeta::Struct {
                namespace: "Windows.Win32.Foundation".into(),
                name: "POINT".into(),
                fields: vec![
                    crate::types::FieldMeta {
                        name: "x".into(),
                        typ: TypeMeta::I32,
                    },
                    crate::types::FieldMeta {
                        name: "y".into(),
                        typ: TypeMeta::I32,
                    },
                ],
            }),
            ..Default::default()
        };

        let error = generate_com_interface_files(&plain_iface_with_method(method), "")
            .expect_err("unsupported struct return must not panic at invocation time");
        assert!(error.contains("unsupported direct native return"));
    }

    #[test]
    fn plain_method_single_out_scalar_projects_as_return() {
        // Model: `HRESULT GetShowCmd([out] int* pcmd)` — the classic single-out
        // int shape. The out-int must become the method's return value.
        let m = MethodMeta {
            name: "GetShowCmd".into(),
            vtable_index: 8,
            params: vec![ParamMeta {
                name: "pcmd".into(),
                typ: TypeMeta::I32,
                direction: ParamDirection::Out,
            }],
            return_type: Some(make_hresult()),
            ..Default::default()
        };
        let com = plain_iface_with_method(m);
        let js = render_js(&com, None);
        let dts = render_dts(&com, None);
        // .js: must capture `_out` and return it as a JS number.
        assert!(
            js.contains("const _out = _IHasOut.method(8).invoke(this._obj, [])"),
            ".js must capture invoke() result into _out:\n{}",
            js
        );
        assert!(
            js.contains("return DynCom.toNumber(_out);"),
            ".js must unwrap the I32 out:\n{}",
            js
        );
        // .d.ts: return type must be `number`, not `void`.
        assert!(
            dts.contains("getShowCmd(): number;"),
            ".d.ts must project single-out I32 as `number`:\n{}",
            dts
        );
    }

    #[test]
    fn plain_method_single_out_guid_projects_as_string() {
        // Model: `HRESULT GetClassID([out] GUID* pClassID)` (IPersist shape).
        let m = MethodMeta {
            name: "GetClassID".into(),
            vtable_index: 3,
            params: vec![ParamMeta {
                name: "pClassID".into(),
                typ: TypeMeta::Guid,
                direction: ParamDirection::Out,
            }],
            return_type: Some(make_hresult()),
            ..Default::default()
        };
        let com = plain_iface_with_method(m);
        let js = render_js(&com, None);
        let dts = render_dts(&com, None);
        assert!(
            js.contains("const _out = _IHasOut.method(3).invoke(this._obj, [])"),
            ".js must capture invoke() result into _out:\n{}",
            js
        );
        assert!(
            js.contains("return DynCom.toGuidString(_out);"),
            ".js must unwrap GUID out:\n{}",
            js
        );
        assert!(
            dts.contains("getClassID(): string;"),
            ".d.ts must project single-out GUID as `string`:\n{}",
            dts
        );
    }

    #[test]
    fn plain_method_single_out_enum_projects_as_underlying() {
        // Model: `HRESULT GetKind([out] MyKind* pk)` where MyKind is an I32
        // enum. Underlying-scalar unwrap → `.toNumber()`; .d.ts uses the enum
        // type name.
        let m = MethodMeta {
            name: "GetKind".into(),
            vtable_index: 5,
            params: vec![ParamMeta {
                name: "pk".into(),
                typ: TypeMeta::Enum {
                    namespace: "Windows.Win32.System.Com".into(),
                    name: "MyKind".into(),
                    underlying: Box::new(TypeMeta::I32),
                    members: Vec::new(),
                    is_flags: false,
                    doc: None,
                    deprecated: None,
                },
                direction: ParamDirection::Out,
            }],
            return_type: Some(make_hresult()),
            ..Default::default()
        };
        let com = plain_iface_with_method(m);
        let js = render_js(&com, None);
        let dts = render_dts(&com, None);
        assert!(
            js.contains("return DynCom.toNumber(_out);"),
            ".js must unwrap enum out via its underlying scalar:\n{}",
            js
        );
        assert!(
            dts.contains("getKind(): MyKind;"),
            ".d.ts must project enum out under the enum's declared name:\n{}",
            dts
        );
    }

    #[test]
    fn plain_method_multi_out_uses_invoke_all_and_tuple_return() {
        // Model: `HRESULT Q([out] uint32_t* a, [out] BOOL* found)` — two
        // trailing out params must flip to `.invokeAll()` and a tuple return.
        let m = MethodMeta {
            name: "Q".into(),
            vtable_index: 6,
            params: vec![
                ParamMeta {
                    name: "a".into(),
                    typ: TypeMeta::U32,
                    direction: ParamDirection::Out,
                },
                ParamMeta {
                    name: "found".into(),
                    typ: TypeMeta::Bool,
                    direction: ParamDirection::Out,
                },
            ],
            return_type: Some(make_hresult()),
            ..Default::default()
        };
        let com = plain_iface_with_method(m);
        let js = render_js(&com, None);
        let dts = render_dts(&com, None);
        assert!(
            js.contains("const _r = _IHasOut.method(6).invokeAll(this._obj, [])"),
            ".js multi-out must use .invokeAll():\n{}",
            js
        );
        assert!(
            js.contains("return [DynCom.toU32(_r[0]), DynCom.toBool(_r[1])];"),
            ".js multi-out must return a tuple with each out unwrapped:\n{}",
            js
        );
        assert!(
            dts.contains("q(): [number, boolean];"),
            ".d.ts multi-out must project a tuple type:\n{}",
            dts
        );
    }

    #[test]
    fn plain_method_zero_out_still_discards_result() {
        // No out params: existing behavior — invoke and discard.
        let m = MethodMeta {
            name: "DoIt".into(),
            vtable_index: 4,
            params: vec![ParamMeta {
                name: "arg".into(),
                typ: TypeMeta::I32,
                direction: ParamDirection::In,
            }],
            return_type: Some(make_hresult()),
            ..Default::default()
        };
        let com = plain_iface_with_method(m);
        let js = render_js(&com, None);
        let dts = render_dts(&com, None);
        assert!(
            !js.contains("const _out ="),
            ".js zero-out must not capture invoke() result:\n{}",
            js
        );
        assert!(
            !js.contains("invokeAll"),
            ".js zero-out must not use .invokeAll():\n{}",
            js
        );
        assert!(
            js.contains("_IHasOut.method(4).invoke(this._obj,"),
            ".js zero-out must call plain .invoke():\n{}",
            js
        );
        assert!(
            dts.contains("doIt(arg: number): void;"),
            ".d.ts zero-out must still be `void`:\n{}",
            dts
        );
    }

    #[test]
    fn direct_native_return_uses_return_abi_instead_of_synthetic_out_param() {
        let method = MethodMeta {
            name: "RetryRejectedCall".into(),
            vtable_index: 5,
            return_type: Some(TypeMeta::U32),
            ..Default::default()
        };
        let signature = build_method_sig_js(&method);
        assert_eq!(signature, "new DynComMethodSig().returns(DynCom.u32Type())");

        let com = plain_iface_with_method(method);
        let js = render_js(&com, None);
        let dts = render_dts(&com, None);
        assert!(js.contains("const _out = _IHasOut.method(5).invoke(this._obj, [])"));
        assert!(js.contains("return DynCom.toU32(_out);"));
        assert!(dts.contains("retryRejectedCall(): number;"));
    }

    #[test]
    fn native_void_return_is_declared_explicitly() {
        let method = MethodMeta {
            name: "OnClose".into(),
            vtable_index: 8,
            return_type: None,
            ..Default::default()
        };
        assert_eq!(
            build_method_sig_js(&method),
            "new DynComMethodSig().returnsVoid()"
        );

        let com = plain_iface_with_method(method);
        let js = render_js(&com, None);
        assert!(js.contains("_IHasOut.method(8).invoke(this._obj, [])"));
        assert!(!js.contains("const _out ="));
    }

    #[test]
    fn direct_64_bit_returns_use_bigint_accessors() {
        let i64_method = MethodMeta {
            name: "GetSigned".into(),
            return_type: Some(TypeMeta::I64),
            ..Default::default()
        };
        let u64_method = MethodMeta {
            name: "GetUnsigned".into(),
            return_type: Some(TypeMeta::U64),
            ..Default::default()
        };

        let i64_js = render_js(&plain_iface_with_method(i64_method), None);
        let u64_js = render_js(&plain_iface_with_method(u64_method), None);
        assert!(i64_js.contains("return DynCom.toI64Bigint(_out);"));
        assert!(u64_js.contains("return DynCom.toU64Bigint(_out);"));
    }

    #[test]
    fn return_only_handle_declares_its_alias() {
        let hwnd = TypeMeta::Struct {
            namespace: "Windows.Win32.Foundation".into(),
            name: "HWND".into(),
            fields: vec![crate::types::FieldMeta {
                name: "Value".into(),
                typ: TypeMeta::Object,
            }],
        };
        let method = MethodMeta {
            name: "GetWindow".into(),
            return_type: Some(hwnd),
            ..Default::default()
        };
        let com = plain_iface_with_method(method);
        let dts = render_dts(&com, None);
        assert!(dts.contains("export type HWND = bigint | number;"));
        assert!(dts.contains("getWindow(): HWND;"));
    }

    #[test]
    fn handle_value_arg_accepts_buffer_and_string_pointer_keeps_buffer() {
        let hwnd = TypeMeta::Struct {
            namespace: "Windows.Win32.Foundation".into(),
            name: "HWND".into(),
            fields: vec![crate::types::FieldMeta {
                name: "Value".into(),
                typ: TypeMeta::Object,
            }],
        };
        let method = MethodMeta {
            name: "SetOverlayIcon".into(),
            params: vec![
                ParamMeta {
                    name: "hwnd".into(),
                    typ: hwnd,
                    direction: ParamDirection::In,
                },
                ParamMeta {
                    name: "description".into(),
                    typ: pwstr_struct(),
                    direction: ParamDirection::In,
                },
            ],
            return_type: Some(make_hresult()),
            ..Default::default()
        };
        let iface = plain_iface_with_method(method);
        let dts = render_dts(&iface, None);
        let js = render_js(&iface, None);

        // HWND inputs accept Electron's pointer-width Buffer, but the HWND
        // output alias remains a numeric handle value.
        assert!(dts.contains("export type HWND = bigint | number;"));
        assert!(dts.contains("export type PWSTR = bigint | Buffer;"));
        assert!(dts.contains("Pass a `Buffer` holding the string bytes"));
        assert!(dts.contains(
            "setOverlayIcon(hwnd: HWND | Buffer | Uint8Array, description: PWSTR): void;"
        ));

        // Handle-value conversion is centralized in the runtime; string
        // pointers continue to pass their backing-store address.
        assert!(
            js.contains("DynCom.pointer(DynCom.handleValue(hwnd))"),
            "HWND arg must use DynCom.handleValue:\n{js}"
        );
        assert!(!js.contains("function _handleArg("));
        assert!(!js.contains("handleValue(description)"));
    }

    #[test]
    fn data_pointer_alias_does_not_read_buffer_contents_as_a_handle() {
        let psid = TypeMeta::Struct {
            namespace: "Windows.Win32.Security".into(),
            name: "PSID".into(),
            fields: vec![crate::types::FieldMeta {
                name: "Value".into(),
                typ: TypeMeta::Object,
            }],
        };
        let method = MethodMeta {
            name: "AddUserSid".into(),
            params: vec![ParamMeta {
                name: "userSid".into(),
                typ: psid,
                direction: ParamDirection::In,
            }],
            return_type: Some(make_hresult()),
            ..Default::default()
        };
        let iface = plain_iface_with_method(method);
        let js = render_js(&iface, None);
        let dts = render_dts(&iface, None);

        assert!(dts.contains("export type PSID = bigint | number;"));
        assert!(dts.contains("addUserSid(userSid: PSID | Buffer | Uint8Array): void;"));
        assert!(js.contains("DynCom.pointer(userSid)"));
        assert!(!js.contains("handleValue(userSid)"));
    }

    #[test]
    fn hwnd_in_out_uses_runtime_handle_conversion_without_inline_helper() {
        let hwnd = TypeMeta::Struct {
            namespace: "Windows.Win32.Foundation".into(),
            name: "HWND".into(),
            fields: vec![crate::types::FieldMeta {
                name: "Value".into(),
                typ: TypeMeta::Object,
            }],
        };
        let method = MethodMeta {
            name: "Create".into(),
            params: vec![ParamMeta {
                name: "window".into(),
                typ: hwnd,
                direction: ParamDirection::InOut,
            }],
            return_type: Some(make_hresult()),
            ..Default::default()
        };
        let iface = plain_iface_with_method(method);
        let js = render_js(&iface, None);

        assert!(js.contains("DynCom.pointer(DynCom.handleValue(window))"));
        assert!(!js.contains("function _handleArg("));
    }

    #[test]
    fn return_only_enum_emits_import_and_sibling_files() {
        let kind = TypeMeta::Enum {
            namespace: "Windows.Win32.Example".into(),
            name: "THING_KIND".into(),
            underlying: Box::new(TypeMeta::I32),
            members: Vec::new(),
            is_flags: false,
            doc: None,
            deprecated: None,
        };
        let method = MethodMeta {
            name: "GetKind".into(),
            return_type: Some(kind.clone()),
            ..Default::default()
        };
        let mut com = plain_iface_with_method(method);
        com.referenced_enums.push(ComEnumMeta {
            namespace: "Windows.Win32.Example".into(),
            name: "THING_KIND".into(),
            underlying: TypeMeta::I32,
            members: Vec::new(),
            is_flags: false,
        });

        let output = generate_com_interface_files(&com, "").unwrap();
        assert!(
            output
                .dts
                .contains("import { THING_KIND } from './THING_KIND.js';")
        );
        assert!(
            output
                .extra_files
                .iter()
                .any(|(name, _)| name == "THING_KIND.d.ts")
        );
    }

    #[test]
    fn unsigned_enum_literals_preserve_u32_and_u64_values() {
        let u32_enum = ComEnumMeta {
            namespace: "Windows.Win32.Example".into(),
            name: "U32_FLAGS".into(),
            underlying: TypeMeta::U32,
            members: vec![crate::com_metadata::ComEnumMember {
                name: "HIGH_BIT".into(),
                value: ComEnumValue::Unsigned(2_147_483_648),
            }],
            is_flags: true,
        };
        let u64_enum = ComEnumMeta {
            namespace: "Windows.Win32.Example".into(),
            name: "U64_FLAGS".into(),
            underlying: TypeMeta::U64,
            members: vec![crate::com_metadata::ComEnumMember {
                name: "HIGH_BIT".into(),
                value: ComEnumValue::Unsigned(9_223_372_036_854_775_808),
            }],
            is_flags: true,
        };

        let (u32_js, u32_dts) = render_enum_files(&u32_enum);
        assert!(u32_js.contains("HIGH_BIT: 2147483648"));
        assert!(u32_dts.contains("readonly HIGH_BIT: 2147483648;"));
        let (u64_js, u64_dts) = render_enum_files(&u64_enum);
        assert!(u64_js.contains("HIGH_BIT: 9223372036854775808n"));
        assert!(u64_dts.contains("readonly HIGH_BIT: 9223372036854775808n;"));
    }

    #[test]
    fn in_out_parameter_is_both_argument_and_result() {
        let method = MethodMeta {
            name: "Adjust".into(),
            vtable_index: 4,
            params: vec![ParamMeta {
                name: "value".into(),
                typ: TypeMeta::I32,
                direction: ParamDirection::InOut,
            }],
            return_type: Some(make_hresult()),
            ..Default::default()
        };
        assert_eq!(
            build_method_sig_js(&method),
            "new DynComMethodSig().addInOut(DynCom.i32Type())"
        );

        let com = plain_iface_with_method(method);
        let js = render_js(&com, None);
        let dts = render_dts(&com, None);
        assert!(js.contains("adjust(value)"));
        assert!(
            js.contains("const _out = _IHasOut.method(4).invoke(this._obj, [DynCom.i32(value)])")
        );
        assert!(js.contains("return DynCom.toNumber(_out);"));
        assert!(dts.contains("adjust(value: number): number;"));
    }

    #[test]
    fn unsupported_outfill_fails_closed() {
        let m = MethodMeta {
            name: "GetPath".into(),
            vtable_index: 2,
            params: vec![
                ParamMeta {
                    name: "pszFile".into(),
                    typ: TypeMeta::String, // PWSTR buffer, caller-allocated
                    direction: ParamDirection::OutFill,
                },
                ParamMeta {
                    name: "cch".into(),
                    typ: TypeMeta::I32,
                    direction: ParamDirection::In,
                },
            ],
            return_type: Some(make_hresult()),
            ..Default::default()
        };
        let com = plain_iface_with_method(m);
        let error = generate_com_interface_files(&com, "")
            .expect_err("unsupported caller-allocated arrays must fail closed");
        assert!(error.contains("caller-allocated array outputs are not supported"));
    }

    fn pwstr_struct() -> TypeMeta {
        TypeMeta::Struct {
            namespace: "Windows.Win32.Foundation".into(),
            name: "PWSTR".into(),
            fields: vec![crate::types::FieldMeta {
                name: "Value".into(),
                typ: TypeMeta::Object,
            }],
        }
    }

    #[test]
    fn out_string_buffer_allocates_decodes_and_returns_string() {
        let m = MethodMeta {
            name: "GetDescription".into(),
            vtable_index: 6,
            params: vec![
                ParamMeta {
                    name: "pszName".into(),
                    typ: pwstr_struct(),
                    direction: ParamDirection::OutStringBuffer {
                        count_param_index: 1,
                    },
                },
                ParamMeta {
                    name: "cch".into(),
                    typ: TypeMeta::I32,
                    direction: ParamDirection::In,
                },
            ],
            return_type: Some(make_hresult()),
            ..Default::default()
        };
        let com = plain_iface_with_method(m);
        let js = render_js(&com, None);
        let dts = render_dts(&com, None);
        assert!(
            js.contains("function _normalizeStringBufferCount"),
            ".js must emit string buffer validation helper:\n{}",
            js
        );
        assert!(
            js.contains(".addMethod('GetDescription', new DynComMethodSig().addIn(DynCom.pointerType()).addIn(DynCom.i32Type()))"),
            ".js must register string buffer as an input pointer:\n{}",
            js
        );
        assert!(
            js.contains("getDescription(cch = 260)") && js.contains("Buffer.alloc(cch * 2)"),
            ".js must default cch and allocate a UTF-16 buffer:\n{}",
            js
        );
        assert!(
            js.contains("const _text = _decodeWideString(_buffer);")
                && js.contains("return _text;"),
            ".js must return the decoded wide string:\n{}",
            js
        );
        assert!(
            dts.contains("getDescription(cch?: number): string;"),
            ".d.ts must expose optional count and string return:\n{}",
            dts
        );
    }

    #[test]
    fn callee_allocated_pwstr_is_decoded_and_freed() {
        let method = MethodMeta {
            name: "GetDisplayName".into(),
            vtable_index: 5,
            params: vec![ParamMeta {
                name: "name".into(),
                typ: pwstr_struct(),
                direction: ParamDirection::Out,
            }],
            return_type: Some(make_hresult()),
            ..Default::default()
        };
        let com = plain_iface_with_method(method);
        let js = render_js(&com, None);
        let dts = render_dts(&com, None);

        assert!(js.contains("return DynCom.takeCoTaskMemWideString(_out);"));
        assert!(dts.contains("getDisplayName(): string;"));
    }

    #[test]
    fn untyped_sysfree_output_fails_closed() {
        let method = MethodMeta {
            name: "GetAllFileTypes".into(),
            vtable_index: 4,
            params: vec![ParamMeta {
                name: "types".into(),
                typ: TypeMeta::Object,
                direction: ParamDirection::Out,
            }],
            return_type: Some(make_hresult()),
            owned_outputs: vec![crate::com_metadata::OwnedOutput {
                param_index: 0,
                free_with: "SysFreeString".into(),
            }],
            ..Default::default()
        };
        let error = generate_com_interface_files(&plain_iface_with_method(method), "")
            .expect_err("BSTR**-style untyped outputs must fail closed");
        assert!(error.contains("untyped pointer output has no ownership projection"));
    }

    #[test]
    fn string_buffer_preserves_additional_outputs() {
        let method = MethodMeta {
            name: "GetIconLocation".into(),
            vtable_index: 16,
            params: vec![
                ParamMeta {
                    name: "path".into(),
                    typ: pwstr_struct(),
                    direction: ParamDirection::OutStringBuffer {
                        count_param_index: 1,
                    },
                },
                ParamMeta {
                    name: "cch".into(),
                    typ: TypeMeta::I32,
                    direction: ParamDirection::In,
                },
                ParamMeta {
                    name: "icon".into(),
                    typ: TypeMeta::I32,
                    direction: ParamDirection::Out,
                },
            ],
            return_type: Some(make_hresult()),
            ..Default::default()
        };
        let com = plain_iface_with_method(method);
        let js = render_js(&com, None);
        let dts = render_dts(&com, None);

        assert!(js.contains("const _out = _IHasOut.method(16).invoke"));
        assert!(js.contains("return [_text, DynCom.toNumber(_out)];"));
        assert!(dts.contains("getIconLocation(cch?: number): [string, number];"));
    }

    #[test]
    fn interface_out_param_projects_as_explicit_bridge_value() {
        let m = MethodMeta {
            name: "GetThing".into(),
            vtable_index: 7,
            params: vec![ParamMeta {
                name: "thing".into(),
                typ: TypeMeta::Interface {
                    namespace: "Windows.Win32.System.Com".into(),
                    name: "IThing".into(),
                    iid: "11111111-2222-3333-4444-555555555555".into(),
                },
                direction: ParamDirection::Out,
            }],
            return_type: Some(make_hresult()),
            ..Default::default()
        };
        let com = plain_iface_with_method(m);
        let js = render_js(&com, None);
        let dts = render_dts(&com, None);
        assert!(
            !js.contains("from './IThing.js'"),
            ".js must not depend on an ungenerated wrapper:\n{}",
            js
        );
        assert!(js.contains(
            ".addOut(DynCom.interfaceType(WinGuid.parse('11111111-2222-3333-4444-555555555555')))"
        ));
        assert!(
            js.contains("return _out;"),
            ".js must return the managed bridge value:\n{}",
            js
        );
        assert!(
            dts.contains("import type { DynWinRtValue }"),
            ".d.ts must import the bridge type:\n{}",
            dts
        );
        assert!(
            dts.contains("getThing(): DynWinRtValue;"),
            ".d.ts must return the explicit bridge value:\n{}",
            dts
        );
    }

    #[test]
    fn caller_supplied_riid_output_is_adopted() {
        let method = MethodMeta {
            name: "BindToHandler".into(),
            vtable_index: 4,
            params: vec![
                ParamMeta {
                    name: "pbc".into(),
                    typ: TypeMeta::Object,
                    direction: ParamDirection::In,
                },
                ParamMeta {
                    name: "riid".into(),
                    typ: TypeMeta::Object,
                    direction: ParamDirection::In,
                },
                ParamMeta {
                    name: "ppv".into(),
                    typ: TypeMeta::Object,
                    direction: ParamDirection::Out,
                },
            ],
            return_type: Some(make_hresult()),
            ..Default::default()
        };
        let com = plain_iface_with_method(method);
        let output = generate_com_interface_files(&com, "").unwrap();

        assert!(output.js.contains("bindToHandler(pbc, iid)"));
        assert!(output.js.contains("DynCom.adoptComPointer(_raw, _iid)"));
        assert!(
            output
                .dts
                .contains("bindToHandler(pbc: bigint | Buffer, iid: string): DynWinRtValue;")
        );
    }
}
