// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Generate Python `.pyi` stub files for IDE / type-checker support.
//! Stubs contain only type signatures; method bodies are `...`.
//! Implementation details (interface registration, struct helpers, IID
//! constants tied to runtime, factory activation) are not emitted.

use std::collections::HashSet;

use crate::meta::{ClassMeta, InterfaceMeta, MethodMeta, ParamDirection};
use crate::types::{TypeKind, TypeMeta};

use super::common::{
    collect_iface_type_imports, collect_type_imports,
    collect_used_generics_from_class, collect_used_generics_from_methods,
    collect_used_structs_from_class, collect_used_structs_from_iface,
    get_in_params, is_py_reserved, py_dynwinrt_type, to_snake_case, to_snake_case_filename,
};
use super::py_method::{
    py_array_element_type, py_param_list, py_param_type_safe, py_return_type_safe,
};
use super::py_shared::reorder_getters_before_setters;

const HEADER: &str = "# Generated by winrt-meta — do not edit\n";
const FUTURE_ANNOTATIONS: &str = "from __future__ import annotations\n";
const IMPORT_LINE: &str = "\
from dynwinrt_py import (
    DynWinRTValue, DynWinRTArray, DynWinRTStruct, DynWinRtDelegate, WinGUID,
)\n";

fn format_py_type_import(name: &str, kind: TypeKind) -> String {
    let module = to_snake_case_filename(name);
    if kind == TypeKind::Interface {
        format!("from .{module} import IID_{name}, {name}  # noqa: F401\n")
    } else {
        format!("from .{module} import {name}  # noqa: F401\n")
    }
}

fn py_struct_export_names(s: &TypeMeta) -> Vec<String> {
    match s {
        TypeMeta::Struct { name, .. } => {
            let snake = to_snake_case(name);
            vec![
                format!("{}_TYPE", name),
                format!("pack_{}", snake),
                format!("unpack_{}", snake),
            ]
        }
        _ => vec![],
    }
}

fn emit_struct_stub(s: &TypeMeta) -> String {
    let (_namespace, name, fields) = match s {
        TypeMeta::Struct { namespace, name, fields } => (namespace, name, fields),
        _ => return String::new(),
    };
    let mut out = String::new();
    let snake_name = to_snake_case(name);

    out.push_str(&format!("\nclass {}:\n", name));
    if fields.is_empty() {
        out.push_str("    pass\n");
    } else {
        let init_params: Vec<String> = fields.iter()
            .map(|f| format!("{}: {} = ...", to_snake_case(&f.name), py_struct_field_stub_type(&f.typ)))
            .collect();
        out.push_str(&format!("    def __init__(self, {}) -> None: ...\n", init_params.join(", ")));
        for f in fields {
            out.push_str(&format!(
                "    {}: {}\n",
                to_snake_case(&f.name),
                py_struct_field_stub_type(&f.typ)
            ));
        }
    }
    out.push('\n');

    out.push_str(&format!("def unpack_{}(v: DynWinRTValue) -> {}: ...\n", snake_name, name));
    out.push_str(&format!("{}_TYPE: 'DynWinRTValue'\n", name));
    out.push_str(&format!("def pack_{}(v: {}) -> DynWinRTStruct: ...\n", snake_name, name));
    out
}

fn py_struct_field_stub_type(typ: &TypeMeta) -> String {
    match typ {
        TypeMeta::Bool => "bool".to_string(),
        TypeMeta::I8 | TypeMeta::U8 | TypeMeta::I16 | TypeMeta::U16 | TypeMeta::Char16
        | TypeMeta::I32 | TypeMeta::U32 | TypeMeta::I64 | TypeMeta::U64
        | TypeMeta::Enum { .. } => "int".to_string(),
        TypeMeta::F32 | TypeMeta::F64 => "float".to_string(),
        TypeMeta::String | TypeMeta::Guid => "str".to_string(),
        TypeMeta::Struct { name, .. } if name == "HResult" => "int".to_string(),
        TypeMeta::Struct { name, .. } => format!("'{}'", name),
        _ => "object".to_string(),
    }
}

fn emit_method_stub(
    method: &MethodMeta,
    known_types: &HashSet<String>,
    delegate_type_names: &HashSet<String>,
    indent_spaces: usize,
) -> String {
    let indent = " ".repeat(indent_spaces);
    let in_params = get_in_params(method);
    let return_type = method.return_type.as_ref();
    let has_array_out = method.params.iter().any(|p| {
        (p.direction == ParamDirection::Out || p.direction == ParamDirection::OutFill)
            && matches!(p.typ, TypeMeta::Array(_))
    });

    let is_delegate_type = |typ: Option<&TypeMeta>| -> bool {
        match typ {
            Some(TypeMeta::Delegate { .. }) => true,
            Some(TypeMeta::Interface { name, .. }) => delegate_type_names.contains(name),
            _ => false,
        }
    };

    let mut out = String::new();

    // Events
    if method.is_event_add {
        let event_name = to_snake_case(method.name.strip_prefix("add_").unwrap_or(&method.name));
        out.push_str(&format!(
            "{indent}def on_{}(self, callback) -> 'DynWinRTValue': ...\n",
            event_name
        ));
        return out;
    }
    if method.is_event_remove {
        let event_name = to_snake_case(method.name.strip_prefix("remove_").unwrap_or(&method.name));
        out.push_str(&format!(
            "{indent}def off_{}(self, token: 'DynWinRTValue') -> None: ...\n",
            event_name
        ));
        return out;
    }

    if method.is_property_getter && in_params.is_empty() {
        let prop_name = to_snake_case(method.name.strip_prefix("get_").unwrap_or(&method.name));
        let py_return = if is_delegate_type(return_type) {
            "'DynWinRTValue'".to_string()
        } else {
            py_return_type_safe(return_type, known_types)
        };
        out.push_str(&format!("{indent}@property\n"));
        out.push_str(&format!("{indent}def {}(self) -> {}: ...\n", prop_name, py_return));
    } else if method.is_property_setter {
        let prop_name = to_snake_case(method.name.strip_prefix("put_").unwrap_or(&method.name));
        let param_type = if in_params.first().is_some_and(|p| is_delegate_type(Some(&p.typ))) {
            "'DynWinRTValue'".to_string()
        } else {
            in_params.first()
                .map(|p| py_param_type_safe(&p.typ, known_types))
                .unwrap_or_else(|| "object".to_string())
        };
        out.push_str(&format!("{indent}@{}.setter\n", prop_name));
        out.push_str(&format!(
            "{indent}def {}(self, value: {}) -> None: ...\n",
            prop_name, param_type
        ));
    } else {
        let py_params = py_param_list(&in_params, known_types);
        let array_out_elem = if has_array_out && return_type.is_none() {
            method.params.iter().find_map(|p| {
                if p.direction == ParamDirection::Out || p.direction == ParamDirection::OutFill {
                    if let TypeMeta::Array(inner) = &p.typ {
                        Some(inner.as_ref())
                    } else {
                        None
                    }
                } else {
                    None
                }
            })
        } else {
            None
        };
        let py_return = if let Some(elem) = array_out_elem {
            py_array_element_type(elem, known_types)
        } else {
            py_return_type_safe(return_type, known_types)
        };
        let method_name = to_snake_case(&method.name);
        let self_and_params = if py_params.is_empty() {
            "self".to_string()
        } else {
            format!("self, {}", py_params)
        };
        out.push_str(&format!(
            "{indent}def {}({}) -> {}: ...\n",
            method_name, self_and_params, py_return
        ));
    }

    out
}

fn emit_static_method_stub(
    class_name: &str,
    method: &MethodMeta,
    known_types: &HashSet<String>,
    is_factory: bool,
) -> String {
    let in_params = get_in_params(method);
    let py_params = py_param_list(&in_params, known_types);

    let return_type = method.return_type.as_ref();
    let py_return = if is_factory {
        format!("'{}'", class_name)
    } else {
        py_return_type_safe(return_type, known_types)
    };

    let mut out = String::new();

    if !is_factory && method.is_property_getter && in_params.is_empty() {
        let prop_name = to_snake_case(method.name.strip_prefix("get_").unwrap_or(&method.name));
        out.push_str("    @classmethod\n");
        out.push_str(&format!(
            "    def get_{}(cls) -> {}: ...\n",
            prop_name, py_return
        ));
    } else {
        let method_name = to_snake_case(&method.name);
        out.push_str("    @staticmethod\n");
        if py_params.is_empty() {
            out.push_str(&format!(
                "    def {}() -> {}: ...\n",
                method_name, py_return
            ));
        } else {
            out.push_str(&format!(
                "    def {}({}) -> {}: ...\n",
                method_name, py_params, py_return
            ));
        }
    }
    out
}

/// Generate a `.pyi` stub for an enum. Returns `None` for non-enum TypeMeta.
pub fn generate_enum_stub(en: &TypeMeta) -> Option<String> {
    let (name, members) = match en {
        TypeMeta::Enum { name, members, .. } => (name, members),
        _ => return None,
    };
    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str("from enum import IntEnum\n\n\n");
    out.push_str(&format!("class {}(IntEnum):\n", name));
    if members.is_empty() {
        out.push_str("    pass\n");
    } else {
        for m in members {
            let member_name = if is_py_reserved(&m.name) {
                format!("{}_", m.name)
            } else {
                m.name.clone()
            };
            out.push_str(&format!("    {} = {}\n", member_name, m.value));
        }
    }
    Some(out)
}

/// Generate a `.pyi` stub for an interface (or a delegate).
pub fn generate_interface_stub(
    iface: &InterfaceMeta,
    known_types: &HashSet<String>,
    delegate_type_names: &HashSet<String>,
) -> String {
    let is_delegate = iface.methods.iter().any(|m| m.name == ".ctor")
        && iface.methods.iter().any(|m| m.name == "Invoke");
    if is_delegate {
        // Delegate stub: only IID + PARAM_TYPES declarations
        let mut out = String::new();
        out.push_str(HEADER);
        out.push_str(FUTURE_ANNOTATIONS);
        out.push_str("from dynwinrt_py import WinGUID\n\n");
        out.push_str(&format!("IID_{}: WinGUID\n", iface.name));
        out.push_str(&format!("{}_PARAM_TYPES: list\n", iface.name));
        return out;
    }

    let used_structs = collect_used_structs_from_iface(iface);

    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str(FUTURE_ANNOTATIONS);
    out.push_str(IMPORT_LINE);
    out.push('\n');

    let mut delegate_names: HashSet<String> = delegate_type_names.clone();
    for method in &iface.methods {
        for p in &method.params {
            if let TypeMeta::Delegate { name, .. } = &p.typ {
                delegate_names.insert(name.clone());
            }
            if method.is_event_add || method.is_event_remove {
                if let TypeMeta::Parameterized { name, args, .. } = &p.typ {
                    delegate_names.insert(crate::meta::make_parameterized_name(name, args));
                }
            }
        }
    }

    let collection_names = collect_used_generics_from_methods(&iface.methods);
    for cname in &collection_names {
        if cname != &iface.name && !delegate_names.contains(cname) {
            let module = to_snake_case_filename(cname);
            out.push_str(&format!("from .{} import {}  # noqa: F401\n", module, cname));
        }
    }

    let mut sorted_delegates: Vec<_> = delegate_names.iter().collect();
    sorted_delegates.sort();
    for dname in &sorted_delegates {
        let module = to_snake_case_filename(dname);
        out.push_str(&format!(
            "from .{module} import IID_{dname}, {dname}_PARAM_TYPES  # noqa: F401\n",
        ));
    }

    let type_imports = collect_iface_type_imports(iface);
    let mut sorted_type_imports: Vec<_> = type_imports.iter().collect();
    sorted_type_imports.sort_by(|a, b| (&a.namespace, &a.name, &a.kind).cmp(&(&b.namespace, &b.name, &b.kind)));
    for r in &sorted_type_imports {
        if known_types.contains(&r.name) && !delegate_names.contains(&r.name) {
            out.push_str(&format_py_type_import(&r.name, r.kind));
        }
    }
    out.push('\n');

    if iface.generic_piid.is_some() || !iface.iid.is_empty() {
        out.push_str(&format!("IID_{}: WinGUID\n", iface.name));
    }
    out.push('\n');

    for s in &used_structs {
        out.push_str(&emit_struct_stub(s));
        out.push('\n');
    }

    out.push_str(&format!("\nclass {}:\n", iface.name));
    out.push_str("    def __init__(self, obj: DynWinRTValue) -> None: ...\n");
    if !iface.iid.is_empty() || iface.generic_piid.is_some() {
        out.push('\n');
        out.push_str("    @staticmethod\n");
        out.push_str(&format!(
            "    def from_value(obj: DynWinRTValue) -> '{}': ...\n",
            iface.name
        ));
    }

    // IVector<T> / IMap<K,V> create()
    if let Some(ref piid) = iface.generic_piid {
        if piid == "913337e9-11a1-4345-a3a2-4e7f956e222d" && iface.generic_args.len() == 1 {
            out.push('\n');
            out.push_str("    @staticmethod\n");
            out.push_str(&format!(
                "    def create(items: list[DynWinRTValue]) -> '{}': ...\n",
                iface.name
            ));
        } else if piid == "3c2925fe-8519-45c1-aa79-197b6718c1c1" && iface.generic_args.len() == 2 {
            out.push('\n');
            out.push_str("    @staticmethod\n");
            out.push_str(&format!(
                "    def create(keys: list[DynWinRTValue], values: list[DynWinRTValue]) -> '{}': ...\n",
                iface.name
            ));
        }
    }

    for method in reorder_getters_before_setters(&iface.methods) {
        out.push('\n');
        out.push_str(&emit_method_stub(method, known_types, &delegate_names, 4));
    }

    out
}

/// Generate a `.pyi` stub for a runtime class.
pub fn generate_class_stub(
    class: &ClassMeta,
    known_types: &HashSet<String>,
    delegate_type_names: &HashSet<String>,
    shared_iids: &HashSet<String>,
) -> String {
    let used_structs = collect_used_structs_from_class(class);

    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str(FUTURE_ANNOTATIONS);
    out.push_str(IMPORT_LINE);
    out.push('\n');

    let mut delegate_names: HashSet<String> = delegate_type_names.clone();
    for iface in class.all_interfaces() {
        for method in &iface.methods {
            for p in &method.params {
                if let TypeMeta::Delegate { name, .. } = &p.typ {
                    delegate_names.insert(name.clone());
                }
                if method.is_event_add || method.is_event_remove {
                    if let TypeMeta::Parameterized { name, args, .. } = &p.typ {
                        delegate_names.insert(crate::meta::make_parameterized_name(name, args));
                    }
                }
            }
        }
    }

    let collection_names = collect_used_generics_from_class(class);
    for cname in &collection_names {
        if !delegate_names.contains(cname) {
            let module = to_snake_case_filename(cname);
            out.push_str(&format!("from .{} import {}  # noqa: F401\n", module, cname));
        }
    }

    let mut sorted_delegates: Vec<_> = delegate_names.iter().collect();
    sorted_delegates.sort();
    for dname in &sorted_delegates {
        let module = to_snake_case_filename(dname);
        out.push_str(&format!(
            "from .{module} import IID_{dname}, {dname}_PARAM_TYPES  # noqa: F401\n",
        ));
    }

    let mut imported_names: HashSet<String> = HashSet::new();
    let imports = collect_type_imports(class);
    let mut sorted_imports: Vec<_> = imports.iter().collect();
    sorted_imports.sort_by(|a, b| (&a.namespace, &a.name, &a.kind).cmp(&(&b.namespace, &b.name, &b.kind)));
    for r in &sorted_imports {
        if known_types.contains(&r.name) && !delegate_names.contains(&r.name) {
            out.push_str(&format_py_type_import(&r.name, r.kind));
            imported_names.insert(r.name.clone());
            if r.kind == TypeKind::Interface {
                imported_names.insert(format!("IID_{}", r.name));
            }
        }
    }
    for req_iface in &class.required_interfaces {
        if !req_iface.iid.is_empty()
            && shared_iids.contains(&req_iface.iid)
            && !imported_names.contains(&req_iface.name)
        {
            out.push_str(&format_py_type_import(&req_iface.name, TypeKind::Interface));
            imported_names.insert(req_iface.name.clone());
            imported_names.insert(format!("IID_{}", req_iface.name));
        }
    }
    out.push('\n');

    // IID constants (declarations only)
    for iface in class.all_interfaces() {
        let iid_name = format!("IID_{}", iface.name);
        if !iface.iid.is_empty() && !imported_names.contains(&iid_name) {
            out.push_str(&format!("{}: WinGUID\n", iid_name));
        }
    }
    out.push('\n');

    for s in &used_structs {
        out.push_str(&emit_struct_stub(s));
        out.push('\n');
    }

    out.push_str(&format!("\nclass {}:\n", class.name));
    out.push_str("    def __init__(self, obj: DynWinRTValue) -> None: ...\n");

    // Default constructor
    if class.has_default_constructor {
        let has_create_factory = class.factory_interfaces.iter().any(|iface| {
            iface.methods.iter().any(|m| {
                let snake = to_snake_case(&m.name);
                snake == "create" || snake.starts_with("create")
            })
        });
        let ctor_name = if has_create_factory { "create_default" } else { "create" };
        out.push('\n');
        out.push_str("    @staticmethod\n");
        out.push_str(&format!(
            "    def {}() -> '{}': ...\n",
            ctor_name, class.name
        ));
    }

    // Factory methods
    for iface in &class.factory_interfaces {
        for method in &iface.methods {
            out.push('\n');
            out.push_str(&emit_static_method_stub(&class.name, method, known_types, true));
        }
    }
    // Static methods
    for iface in &class.static_interfaces {
        for method in &iface.methods {
            out.push('\n');
            out.push_str(&emit_static_method_stub(&class.name, method, known_types, false));
        }
    }
    // Instance methods (default interface)
    if let Some(ref default_iface) = class.default_interface {
        for method in reorder_getters_before_setters(&default_iface.methods) {
            out.push('\n');
            out.push_str(&emit_method_stub(method, known_types, &delegate_names, 4));
        }
    }

    // IClosable -> close()
    const ICLOSABLE_IID: &str = "30d5a829-7fa4-4026-83bb-d75bae4ea99e";
    if class.required_interfaces.iter().any(|ri| ri.iid == ICLOSABLE_IID) {
        out.push('\n');
        out.push_str("    def close(self) -> None: ...\n");
    }

    if !class.required_interfaces.is_empty() {
        out.push('\n');
        out.push_str("    def as_interface(self, interface_class): ...\n");
    }

    // Inline wrapper classes for required interfaces
    for req_iface in &class.required_interfaces {
        if req_iface.iid.is_empty() {
            continue;
        }
        if imported_names.contains(&req_iface.name) {
            continue;
        }
        out.push('\n');
        out.push_str(&format!("\nclass {}:\n", req_iface.name));
        out.push_str("    def __init__(self, obj: DynWinRTValue) -> None: ...\n");
        out.push('\n');
        out.push_str("    @staticmethod\n");
        out.push_str(&format!(
            "    def from_value(obj: DynWinRTValue) -> '{}': ...\n",
            req_iface.name
        ));
        for method in reorder_getters_before_setters(&req_iface.methods) {
            out.push('\n');
            out.push_str(&emit_method_stub(method, known_types, &delegate_names, 4));
        }
    }

    let _ = py_dynwinrt_type; // keep import referenced
    out
}

/// Generate an `__init__.pyi` index stub.
pub fn generate_index_stub(
    classes: &[ClassMeta],
    interfaces: &[InterfaceMeta],
    enums: &[TypeMeta],
) -> String {
    let mut out = String::new();
    let mut seen: HashSet<String> = HashSet::new();
    out.push_str(HEADER);

    let mut sorted_classes: Vec<_> = classes.iter().collect();
    sorted_classes.sort_by(|a, b| a.name.cmp(&b.name));
    for class in sorted_classes {
        if seen.insert(class.name.clone()) {
            let struct_names: Vec<_> = collect_used_structs_from_class(class).iter()
                .flat_map(|s| py_struct_export_names(s))
                .filter(|n| seen.insert(n.clone()))
                .collect();
            let module = to_snake_case_filename(&class.name);
            if struct_names.is_empty() {
                out.push_str(&format!("from .{} import {} as {}\n", module, class.name, class.name));
            } else {
                out.push_str(&format!(
                    "from .{} import {} as {}, {}\n",
                    module, class.name, class.name, struct_names.join(", ")
                ));
            }
        }
    }

    let mut sorted_ifaces: Vec<_> = interfaces.iter().collect();
    sorted_ifaces.sort_by(|a, b| a.name.cmp(&b.name));
    for iface in sorted_ifaces {
        if !seen.insert(iface.name.clone()) {
            continue;
        }
        let is_delegate = iface.methods.iter().any(|m| m.name == ".ctor")
            && iface.methods.iter().any(|m| m.name == "Invoke");
        let module = to_snake_case_filename(&iface.name);
        if is_delegate {
            out.push_str(&format!(
                "from .{module} import IID_{iname}, {iname}_PARAM_TYPES\n",
                module = module, iname = iface.name
            ));
        } else {
            out.push_str(&format!(
                "from .{module} import IID_{iname}, {iname} as {iname}\n",
                module = module, iname = iface.name
            ));
        }
    }

    let mut sorted_enums: Vec<_> = enums.iter().collect();
    sorted_enums.sort_by(|a, b| {
        let na = match a { TypeMeta::Enum { name, .. } => name.as_str(), _ => "" };
        let nb = match b { TypeMeta::Enum { name, .. } => name.as_str(), _ => "" };
        na.cmp(nb)
    });
    for en in sorted_enums {
        if let TypeMeta::Enum { name, .. } = en {
            if seen.insert(name.clone()) {
                let module = to_snake_case_filename(name);
                out.push_str(&format!("from .{} import {} as {}\n", module, name, name));
            }
        }
    }
    out
}
