// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

use std::collections::HashSet;

use crate::meta::{ClassMeta, InterfaceMeta, ParamDirection};
use crate::types::{TypeKind, TypeMeta};

use super::common::{
    collect_used_structs_from_class, collect_used_structs_from_iface,
    py_struct_field_type, py_struct_field_getter, py_struct_field_setter,
    py_dynwinrt_type, py_generate_interface_registration,
    collect_used_generics_from_methods, collect_used_generics_from_class,
    collect_iface_type_imports, collect_type_imports,
    to_snake_case, to_snake_case_filename, is_py_reserved,
};
use super::py_method::{
    generate_factory_method_invoke, generate_static_method_invoke,
    generate_iface_instance_method,
};

use super::py_shared::reorder_getters_before_setters;

const HEADER: &str = "# Generated by winrt-meta — do not edit\n";
const FUTURE_ANNOTATIONS: &str = "from __future__ import annotations\n";
const IMPORT_LINE: &str = "\
from dynwinrt_py import (
    DynWinRTType, DynWinRTMethodSig, DynWinRTValue, DynWinRTArray,
    DynWinRTStruct, DynWinRtDelegate, WinGUID,
)\n";

/// Generate a Python `__init__.py` that re-exports all generated types.
pub fn generate_index(classes: &[ClassMeta], interfaces: &[InterfaceMeta], enums: &[TypeMeta]) -> String {
    let mut out = String::new();
    let mut seen: HashSet<String> = HashSet::new();
    out.push_str(HEADER);
    let mut sorted_classes: Vec<_> = classes.iter().collect();
    sorted_classes.sort_by(|a, b| a.name.cmp(&b.name));
    for class in sorted_classes {
        if seen.insert(class.name.clone()) {
            let struct_names: Vec<_> = collect_used_structs_from_class(class).iter()
                .flat_map(|s| py_struct_export_names(s))
                .filter(|n| seen.insert(n.clone()))
                .collect();
            let module = to_snake_case_filename(&class.name);
            if struct_names.is_empty() {
                out.push_str(&format!("from .{} import {}  # noqa: F401\n", module, class.name));
            } else {
                out.push_str(&format!(
                    "from .{} import {}, {}  # noqa: F401\n",
                    module, class.name, struct_names.join(", ")
                ));
            }
        }
    }
    let mut sorted_ifaces: Vec<_> = interfaces.iter().collect();
    sorted_ifaces.sort_by(|a, b| a.name.cmp(&b.name));
    for iface in sorted_ifaces {
        if !seen.insert(iface.name.clone()) {
            continue;
        }
        let is_delegate = iface.methods.iter().any(|m| m.name == ".ctor")
            && iface.methods.iter().any(|m| m.name == "Invoke");
        let module = to_snake_case_filename(&iface.name);
        let struct_names: Vec<_> = collect_used_structs_from_iface(iface).iter()
            .flat_map(|s| py_struct_export_names(s))
            .filter(|n| seen.insert(n.clone()))
            .collect();
        if is_delegate {
            out.push_str(&format!(
                "from .{module} import IID_{iname}, {iname}_PARAM_TYPES  # noqa: F401\n",
                module = module, iname = iface.name
            ));
        } else {
            if struct_names.is_empty() {
                out.push_str(&format!(
                    "from .{module} import IID_{iname}, {iname}  # noqa: F401\n",
                    module = module, iname = iface.name
                ));
            } else {
                out.push_str(&format!(
                    "from .{module} import IID_{iname}, {iname}, {structs}  # noqa: F401\n",
                    module = module, iname = iface.name, structs = struct_names.join(", ")
                ));
            }
        }
    }
    let mut sorted_enums: Vec<_> = enums.iter().collect();
    sorted_enums.sort_by(|a, b| {
        let name_a = match a { TypeMeta::Enum { name, .. } => name.as_str(), _ => "" };
        let name_b = match b { TypeMeta::Enum { name, .. } => name.as_str(), _ => "" };
        name_a.cmp(name_b)
    });
    for en in sorted_enums {
        if let TypeMeta::Enum { name, .. } = en {
            if seen.insert(name.clone()) {
                let module = to_snake_case_filename(name);
                out.push_str(&format!("from .{} import {}  # noqa: F401\n", module, name));
            }
        }
    }
    out
}

/// Append new types to an existing `__init__.py`.
pub fn append_to_index(
    existing: &str,
    classes: &[ClassMeta],
    interfaces: &[InterfaceMeta],
    enums: &[TypeMeta],
) -> String {
    let mut seen: HashSet<String> = HashSet::new();
    let mut exported_modules: HashSet<String> = HashSet::new();
    for line in existing.lines() {
        // Parse: from .module import Name1, Name2  # noqa: F401
        if line.starts_with("from .") {
            if let Some(import_start) = line.find("import ") {
                let after_import = &line[import_start + 7..];
                // Strip trailing comment
                let names_part = if let Some(comment_pos) = after_import.find('#') {
                    &after_import[..comment_pos]
                } else {
                    after_import
                };
                for name in names_part.split(',') {
                    let name = name.trim();
                    if !name.is_empty() {
                        seen.insert(name.to_string());
                    }
                }
            }
            // Track module name from `from .module`
            if let Some(rest) = line.strip_prefix("from .") {
                if let Some(space_pos) = rest.find(' ') {
                    let module = &rest[..space_pos];
                    exported_modules.insert(module.to_string());
                }
            }
        }
    }

    let mut out = existing.to_string();
    if !out.ends_with('\n') {
        out.push('\n');
    }

    let mut sorted_classes: Vec<_> = classes.iter().collect();
    sorted_classes.sort_by(|a, b| a.name.cmp(&b.name));
    for class in sorted_classes {
        let module = to_snake_case_filename(&class.name);
        if !exported_modules.contains(&module) && seen.insert(class.name.clone()) {
            let struct_names: Vec<_> = collect_used_structs_from_class(class).iter()
                .flat_map(|s| py_struct_export_names(s))
                .filter(|n| seen.insert(n.clone()))
                .collect();
            if struct_names.is_empty() {
                out.push_str(&format!("from .{} import {}  # noqa: F401\n", module, class.name));
            } else {
                out.push_str(&format!(
                    "from .{} import {}, {}  # noqa: F401\n",
                    module, class.name, struct_names.join(", ")
                ));
            }
        }
    }

    let mut sorted_ifaces: Vec<_> = interfaces.iter().collect();
    sorted_ifaces.sort_by(|a, b| a.name.cmp(&b.name));
    for iface in sorted_ifaces {
        let module = to_snake_case_filename(&iface.name);
        if exported_modules.contains(&module) || !seen.insert(iface.name.clone()) { continue; }
        let is_delegate = iface.methods.iter().any(|m| m.name == ".ctor")
            && iface.methods.iter().any(|m| m.name == "Invoke");
        let struct_names: Vec<_> = collect_used_structs_from_iface(iface).iter()
            .flat_map(|s| py_struct_export_names(s))
            .filter(|n| seen.insert(n.clone()))
            .collect();
        if is_delegate {
            out.push_str(&format!(
                "from .{module} import IID_{iname}, {iname}_PARAM_TYPES  # noqa: F401\n",
                module = module, iname = iface.name
            ));
        } else {
            if struct_names.is_empty() {
                out.push_str(&format!(
                    "from .{module} import IID_{iname}, {iname}  # noqa: F401\n",
                    module = module, iname = iface.name
                ));
            } else {
                out.push_str(&format!(
                    "from .{module} import IID_{iname}, {iname}, {structs}  # noqa: F401\n",
                    module = module, iname = iface.name, structs = struct_names.join(", ")
                ));
            }
        }
    }

    let mut sorted_enums: Vec<_> = enums.iter().collect();
    sorted_enums.sort_by(|a, b| {
        let name_a = match a { TypeMeta::Enum { name, .. } => name.as_str(), _ => "" };
        let name_b = match b { TypeMeta::Enum { name, .. } => name.as_str(), _ => "" };
        name_a.cmp(name_b)
    });
    for en in sorted_enums {
        if let TypeMeta::Enum { name, .. } = en {
            let module = to_snake_case_filename(name);
            if !exported_modules.contains(&module) && seen.insert(name.clone()) {
                out.push_str(&format!("from .{} import {}  # noqa: F401\n", module, name));
            }
        }
    }

    out
}

/// Generate a Python file for a single enum.
pub fn generate_enum(en: &TypeMeta) -> Option<String> {
    let (name, members, enum_doc, enum_dep) = match en {
        TypeMeta::Enum { name, members, doc, deprecated, .. } =>
            (name, members, doc.as_deref(), deprecated.as_deref()),
        _ => return None,
    };

    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str("from enum import IntEnum\n\n\n");
    out.push_str(&format!("class {}(IntEnum):\n", name));
    let type_doc = super::xml_text::DocText {
        summary: enum_doc,
        deprecated: enum_dep,
        returns: None,
        params: Vec::new(),
    };
    let type_ds = super::xml_text::format_pydoc(&type_doc, "    ");
    if !type_ds.is_empty() {
        out.push_str(&type_ds);
        out.push('\n');
    }
    if members.is_empty() && type_ds.is_empty() {
        out.push_str("    pass\n");
    } else {
        for member in members {
            let member_name = if is_py_reserved(&member.name) {
                format!("{}_", member.name)
            } else {
                member.name.clone()
            };
            out.push_str(&format!("    {} = {}\n", member_name, member.value));
            if let Some(d) = member.doc.as_deref() {
                let mdoc = super::xml_text::DocText {
                    summary: Some(d),
                    deprecated: None,
                    returns: None,
                    params: Vec::new(),
                };
                let mds = super::xml_text::format_pydoc(&mdoc, "    ");
                if !mds.is_empty() {
                    out.push_str(&mds);
                }
            }
        }
    }
    Some(out)
}

/// Generate a Python file for a WinRT interface (non-exclusive).
pub fn generate_interface(iface: &InterfaceMeta, known_types: &HashSet<String>, delegate_type_names: &HashSet<String>) -> String {
    let is_delegate = iface.methods.iter().any(|m| m.name == ".ctor")
        && iface.methods.iter().any(|m| m.name == "Invoke");
    if is_delegate {
        return generate_delegate(iface);
    }

    let used_structs = collect_used_structs_from_iface(iface);

    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str(FUTURE_ANNOTATIONS);
    out.push_str(IMPORT_LINE);
    out.push('\n');

    // Collect delegate names
    let mut delegate_names: HashSet<String> = delegate_type_names.clone();
    for method in &iface.methods {
        for p in &method.params {
            if let TypeMeta::Delegate { name, .. } = &p.typ {
                delegate_names.insert(name.clone());
            }
            if method.is_event_add || method.is_event_remove {
                if let TypeMeta::Parameterized { name, args, .. } = &p.typ {
                    delegate_names.insert(crate::meta::make_parameterized_name(name, args));
                }
            }
        }
    }

    // Import parameterized collection types (skip delegates)
    let collection_names = collect_used_generics_from_methods(&iface.methods);
    for cname in &collection_names {
        if cname != &iface.name && !delegate_names.contains(cname) {
            let module = to_snake_case_filename(cname);
            out.push_str(&format!("from .{} import {}  # noqa: F401\n", module, cname));
        }
    }

    // Import delegate IID + PARAM_TYPES
    let mut sorted_delegates: Vec<_> = delegate_names.iter().collect();
    sorted_delegates.sort();
    for dname in &sorted_delegates {
        let module = to_snake_case_filename(dname);
        out.push_str(&format!(
            "from .{module} import IID_{dname}, {dname}_PARAM_TYPES  # noqa: F401\n",
        ));
    }

    // Type imports for referenced types
    let type_imports = collect_iface_type_imports(iface);
    let mut sorted_type_imports: Vec<_> = type_imports.iter().collect();
    sorted_type_imports.sort_by(|a, b| (&a.namespace, &a.name, &a.kind).cmp(&(&b.namespace, &b.name, &b.kind)));
    for r in &sorted_type_imports {
        if known_types.contains(&r.name) && !delegate_names.contains(&r.name) {
            out.push_str(&format_py_type_import(&r.name, r.kind));
        }
    }
    out.push('\n');

    // IID constant
    if let Some(ref piid) = iface.generic_piid {
        let args_py: Vec<String> = iface.generic_args.iter().map(|a| py_dynwinrt_type(a)).collect();
        out.push_str(&format!(
            "IID_{} = DynWinRTType.parameterized(WinGUID.parse('{}'), [{}]).iid()\n\n",
            iface.name, piid, args_py.join(", ")
        ));
    } else if !iface.iid.is_empty() {
        out.push_str(&format!(
            "IID_{} = WinGUID.parse('{}')\n\n",
            iface.name, iface.iid
        ));
    }

    // Interface registration
    out.push_str(&py_generate_interface_registration(iface, &format!("_{}", iface.name)));
    out.push('\n');

    // Struct helpers
    for s in &used_structs {
        out.push_str(&generate_struct_helpers(s));
        out.push('\n');
    }

    // Wrapper class
    out.push_str(&format!("\nclass {}:\n", iface.name));
    {
        let doc = super::xml_text::DocText {
            summary: iface.doc.as_deref(),
            deprecated: iface.deprecated.as_deref(),
            ..Default::default()
        };
        out.push_str(&super::xml_text::format_pydoc(&doc, "    "));
    }
    out.push_str("    def __init__(self, obj: DynWinRTValue):\n");
    if iface.generic_piid.is_some() {
        out.push_str(&format!("        self._obj = obj.cast(IID_{})\n", iface.name));
    } else {
        out.push_str("        self._obj = obj\n");
    }
    out.push('\n');

    // static from() — QI cast
    if !iface.iid.is_empty() || iface.generic_piid.is_some() {
        out.push_str("    @staticmethod\n");
        out.push_str(&format!(
            "    def from_value(obj: DynWinRTValue) -> '{}':\n",
            iface.name
        ));
        out.push_str(&format!(
            "        return {}(obj.cast(IID_{}))\n",
            iface.name, iface.name
        ));
        out.push('\n');
    }

    // static create() for IVector<T> and IMap<K,V>
    if let Some(ref piid) = iface.generic_piid {
        if piid == "913337e9-11a1-4345-a3a2-4e7f956e222d" && iface.generic_args.len() == 1 {
            let elem_type = py_dynwinrt_type(&iface.generic_args[0]);
            out.push_str("    @staticmethod\n");
            out.push_str(&format!(
                "    def create(items: list[DynWinRTValue]) -> '{}':\n",
                iface.name
            ));
            out.push_str(&format!(
                "        return {}(DynWinRTValue.create_vector([getattr(i, '_obj', i) for i in items], {}))\n",
                iface.name, elem_type
            ));
            out.push('\n');
        } else if piid == "3c2925fe-8519-45c1-aa79-197b6718c1c1" && iface.generic_args.len() == 2 {
            let key_type = py_dynwinrt_type(&iface.generic_args[0]);
            let val_type = py_dynwinrt_type(&iface.generic_args[1]);
            out.push_str("    @staticmethod\n");
            out.push_str(&format!(
                "    def create(keys: list[DynWinRTValue], values: list[DynWinRTValue]) -> '{}':\n",
                iface.name
            ));
            out.push_str(&format!(
                "        return {}(DynWinRTValue.create_map([getattr(k, '_obj', k) for k in keys], [getattr(v, '_obj', v) for v in values], {}, {}))\n",
                iface.name, key_type, val_type
            ));
            out.push('\n');
        }
    }

    // Instance methods (reorder so @property comes before @x.setter)
    let iface_var = format!("_{}", iface.name);
    for method in reorder_getters_before_setters(&iface.methods) {
        out.push('\n');
        out.push_str(&generate_iface_instance_method(iface, &iface_var, method, known_types, &delegate_names));
    }

    out
}

/// Generate a Python file for a delegate type.
fn generate_delegate(iface: &InterfaceMeta) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str(FUTURE_ANNOTATIONS);
    out.push_str("from dynwinrt_py import DynWinRTType, WinGUID\n\n");

    let invoke = iface.methods.iter().find(|m| m.name == "Invoke");
    let param_exprs: Vec<String> = invoke.map(|inv| {
        inv.params.iter()
            .filter(|p| p.direction == ParamDirection::In)
            .map(|p| py_dynwinrt_type(&p.typ))
            .collect()
    }).unwrap_or_default();

    if !iface.iid.is_empty() {
        out.push_str(&format!(
            "IID_{} = DynWinRTType.parameterized(WinGUID.parse('{}'), [{}]).iid()\n",
            iface.name, iface.iid, param_exprs.join(", ")
        ));
    } else {
        out.push_str(&format!(
            "IID_{} = None\n",
            iface.name
        ));
    }

    if let Some(invoke) = invoke {
        let param_exprs: Vec<String> = invoke.params.iter()
            .filter(|p| p.direction == ParamDirection::In)
            .map(|p| py_dynwinrt_type(&p.typ))
            .collect();
        out.push_str(&format!(
            "{}_PARAM_TYPES = [{}]\n",
            iface.name,
            param_exprs.join(", ")
        ));
    }

    out
}

// ======================================================================
// Struct helpers: Python dataclass-style + _unpack/_pack functions
// ======================================================================

fn generate_struct_helpers(s: &TypeMeta) -> String {
    let (namespace, name, fields) = match s {
        TypeMeta::Struct { namespace, name, fields } => (namespace, name, fields),
        _ => return String::new(),
    };
    let mut out = String::new();
    let snake_name = to_snake_case(name);

    // Python class with typed fields
    out.push_str(&format!("\nclass {}:\n", name));
    if fields.is_empty() {
        out.push_str("    pass\n");
    } else {
        // __init__ with typed fields
        let init_params: Vec<String> = fields.iter()
            .map(|f| format!("{}: {} = {}", to_snake_case(&f.name), py_struct_field_type(&f.typ), py_default_value(&f.typ)))
            .collect();
        out.push_str(&format!("    def __init__(self, {}):\n", init_params.join(", ")));
        for f in fields {
            let snake = to_snake_case(&f.name);
            out.push_str(&format!("        self.{} = {}\n", snake, snake));
        }
    }
    out.push('\n');

    // unpack function
    out.push_str(&format!("\ndef unpack_{}(v: DynWinRTValue) -> {}:\n", snake_name, name));
    out.push_str("    s = v.as_struct()\n");
    let field_args: Vec<String> = fields.iter().enumerate().map(|(i, f)| {
        format!("{}={}", to_snake_case(&f.name), py_struct_field_getter(&f.typ, i))
    }).collect();
    out.push_str(&format!("    return {}({})\n", name, field_args.join(", ")));
    // Internal alias
    out.push_str(&format!("_unpack_{0} = unpack_{0}\n", snake_name));

    // Type constant
    let full_name = format!("{}.{}", namespace, name);
    let field_types: Vec<String> = fields.iter().map(|f| py_dynwinrt_type(&f.typ)).collect();
    out.push_str(&format!("{}_TYPE = DynWinRTType.struct_type('{}', [{}])\n",
        name, full_name, field_types.join(", ")));
    out.push_str(&format!("_{0}_TYPE = {0}_TYPE\n", name));

    // pack function
    out.push_str(&format!("\ndef pack_{}(v: {}) -> DynWinRTStruct:\n", snake_name, name));
    out.push_str(&format!("    s = DynWinRTStruct.create({}_TYPE)\n", name));
    for (i, f) in fields.iter().enumerate() {
        out.push_str(&format!("    {}\n", py_struct_field_setter(&f.typ, i, &format!("v.{}", to_snake_case(&f.name)))));
    }
    out.push_str("    return s\n");
    out.push_str(&format!("_pack_{0} = pack_{0}\n", snake_name));

    out
}

/// Python default value for struct field initialization.
fn py_default_value(typ: &TypeMeta) -> String {
    match typ {
        TypeMeta::Bool => "False".to_string(),
        TypeMeta::I8 | TypeMeta::U8 | TypeMeta::I16 | TypeMeta::U16 | TypeMeta::Char16
        | TypeMeta::I32 | TypeMeta::U32 | TypeMeta::I64 | TypeMeta::U64
        | TypeMeta::Enum { .. } => "0".to_string(),
        TypeMeta::F32 | TypeMeta::F64 => "0.0".to_string(),
        TypeMeta::String => "''".to_string(),
        TypeMeta::Guid => "''".to_string(),
        _ => "None".to_string(),
    }
}

/// Returns the exported names for struct helpers (for Python index).
fn py_struct_export_names(s: &TypeMeta) -> Vec<String> {
    match s {
        TypeMeta::Struct { name, .. } => {
            let snake = to_snake_case(name);
            vec![
                format!("{}_TYPE", name),
                format!("pack_{}", snake),
                format!("unpack_{}", snake),
            ]
        }
        _ => vec![],
    }
}

/// Generate a Python file for a single RuntimeClass.
pub fn generate_class(class: &ClassMeta, known_types: &HashSet<String>, delegate_type_names: &HashSet<String>, shared_iids: &HashSet<String>) -> String {
    let used_structs = collect_used_structs_from_class(class);

    let mut out = String::new();

    // Header
    out.push_str(HEADER);
    out.push_str(FUTURE_ANNOTATIONS);
    out.push_str(IMPORT_LINE);
    out.push('\n');

    // Collect delegate names from all interfaces of this class
    let mut delegate_names: HashSet<String> = delegate_type_names.clone();
    let all_ifaces: Vec<&InterfaceMeta> = class.default_interface.iter()
        .chain(class.factory_interfaces.iter())
        .chain(class.static_interfaces.iter())
        .chain(class.required_interfaces.iter())
        .collect();
    for iface in &all_ifaces {
        for method in &iface.methods {
            for p in &method.params {
                if let TypeMeta::Delegate { name, .. } = &p.typ {
                    delegate_names.insert(name.clone());
                }
                if method.is_event_add || method.is_event_remove {
                    if let TypeMeta::Parameterized { name, args, .. } = &p.typ {
                        delegate_names.insert(crate::meta::make_parameterized_name(name, args));
                    }
                }
            }
        }
    }

    // Collection generics import (skip delegates)
    let collection_names = collect_used_generics_from_class(class);
    for cname in &collection_names {
        if !delegate_names.contains(cname) {
            let module = to_snake_case_filename(cname);
            out.push_str(&format!("from .{} import {}  # noqa: F401\n", module, cname));
        }
    }

    // Import delegate IID + PARAM_TYPES
    let mut sorted_delegates: Vec<_> = delegate_names.iter().collect();
    sorted_delegates.sort();
    for dname in &sorted_delegates {
        let module = to_snake_case_filename(dname);
        out.push_str(&format!(
            "from .{module} import IID_{dname}, {dname}_PARAM_TYPES  # noqa: F401\n",
        ));
    }

    // Type imports
    let mut imported_names: HashSet<String> = HashSet::new();
    let imports = collect_type_imports(class);
    let mut sorted_imports: Vec<_> = imports.iter().collect();
    sorted_imports.sort_by(|a, b| (&a.namespace, &a.name, &a.kind).cmp(&(&b.namespace, &b.name, &b.kind)));
    for r in &sorted_imports {
        if known_types.contains(&r.name) && !delegate_names.contains(&r.name) {
            out.push_str(&format_py_type_import(&r.name, r.kind));
            imported_names.insert(r.name.clone());
            if r.kind == TypeKind::Interface {
                imported_names.insert(format!("IID_{}", r.name));
            }
        }
    }

    // Import shared required interfaces
    for req_iface in &class.required_interfaces {
        if !req_iface.iid.is_empty() && shared_iids.contains(&req_iface.iid) && !imported_names.contains(&req_iface.name) {
            out.push_str(&format_py_type_import(&req_iface.name, TypeKind::Interface));
            imported_names.insert(req_iface.name.clone());
            imported_names.insert(format!("IID_{}", req_iface.name));
        }
    }
    out.push('\n');

    // IID constants for all interfaces used by this class (skip if already imported)
    let all_class_ifaces: Vec<&InterfaceMeta> = class.default_interface.iter()
        .chain(class.factory_interfaces.iter())
        .chain(class.static_interfaces.iter())
        .chain(class.required_interfaces.iter())
        .collect();
    for iface in &all_class_ifaces {
        let iid_name = format!("IID_{}", iface.name);
        if !iface.iid.is_empty() && !imported_names.contains(&iid_name) {
            out.push_str(&format!(
                "{} = WinGUID.parse('{}')\n",
                iid_name, iface.iid
            ));
        }
    }
    out.push('\n');

    // Interface registrations
    if let Some(ref iface) = class.default_interface {
        out.push_str(&py_generate_interface_registration(iface, &format!("_{}", iface.name)));
        out.push('\n');
    }
    for iface in &class.factory_interfaces {
        out.push_str(&py_generate_interface_registration(iface, &format!("_{}", iface.name)));
        out.push('\n');
    }
    for iface in &class.static_interfaces {
        out.push_str(&py_generate_interface_registration(iface, &format!("_{}", iface.name)));
        out.push('\n');
    }
    for iface in &class.required_interfaces {
        if !iface.iid.is_empty() && shared_iids.contains(&iface.iid) && imported_names.contains(&iface.name) {
            continue;
        }
        out.push_str(&py_generate_interface_registration(iface, &format!("_{}", iface.name)));
        out.push('\n');
    }

    // IActivationFactory for default constructor
    if class.has_default_constructor {
        out.push_str("_IActivationFactory = DynWinRTType.register_interface(\n");
        out.push_str("    'IActivationFactory', WinGUID.parse('00000035-0000-0000-c000-000000000046')) \\\n");
        out.push_str("    .add_method('ActivateInstance', DynWinRTMethodSig().add_out(DynWinRTType.object()))\n");
        out.push('\n');
    }

    // Struct helpers
    for s in &used_structs {
        out.push_str(&generate_struct_helpers(s));
        out.push('\n');
    }

    // Class declaration
    out.push_str(&format!("\nclass {}:\n", class.name));
    {
        let doc = super::xml_text::DocText {
            summary: class.doc.as_deref(),
            deprecated: class.deprecated.as_deref(),
            ..Default::default()
        };
        out.push_str(&super::xml_text::format_pydoc(&doc, "    "));
    }

    // Constructor
    out.push_str("    def __init__(self, obj: DynWinRTValue):\n");
    if let Some(ref iface) = class.default_interface {
        if !iface.iid.is_empty() {
            out.push_str(&format!("        self._obj = obj.cast(IID_{})\n", iface.name));
        } else {
            out.push_str("        self._obj = obj\n");
        }
    } else {
        out.push_str("        self._obj = obj\n");
    }
    out.push('\n');

    // Lazy-cached factory/static interface accessors
    let mut declared: HashSet<String> = HashSet::new();
    for iface in &class.factory_interfaces {
        let key = format!("f_{}", iface.name);
        if !iface.iid.is_empty() && declared.insert(key.clone()) {
            out.push_str(&format!("    _{} = None\n", key));
            out.push('\n');
            out.push_str("    @classmethod\n");
            out.push_str(&format!(
                "    def _get_{}(cls):\n",
                key
            ));
            out.push_str(&format!(
                "        if cls._{k} is None:\n\
                 \x20           cls._{k} = DynWinRTValue.activation_factory('{full}').cast(IID_{iface})\n\
                 \x20       return cls._{k}\n",
                k = key, iface = iface.name, full = class.full_name
            ));
            out.push('\n');
        }
    }
    for iface in &class.static_interfaces {
        let key = format!("s_{}", iface.name);
        if !iface.iid.is_empty() && declared.insert(key.clone()) {
            out.push_str(&format!("    _{} = None\n", key));
            out.push('\n');
            out.push_str("    @classmethod\n");
            out.push_str(&format!(
                "    def _get_{}(cls):\n",
                key
            ));
            out.push_str(&format!(
                "        if cls._{k} is None:\n\
                 \x20           cls._{k} = DynWinRTValue.activation_factory('{full}').cast(IID_{iface})\n\
                 \x20       return cls._{k}\n",
                k = key, iface = iface.name, full = class.full_name
            ));
            out.push('\n');
        }
    }

    // Default constructor
    if class.has_default_constructor {
        let has_create_factory = class.factory_interfaces.iter()
            .any(|iface| iface.methods.iter().any(|m| {
                let snake = to_snake_case(&m.name);
                snake == "create" || snake.starts_with("create")
            }));
        let ctor_name = if has_create_factory { "create_default" } else { "create" };
        out.push_str("    @staticmethod\n");
        out.push_str(&format!(
            "    def {}() -> '{}':\n",
            ctor_name, class.name
        ));
        out.push_str(&format!(
            "        return {}(_IActivationFactory.method(6).invoke(DynWinRTValue.activation_factory('{}'), []))\n",
            class.name, class.full_name
        ));
        out.push('\n');
    }

    // Factory methods
    for iface in &class.factory_interfaces {
        for method in &iface.methods {
            out.push('\n');
            out.push_str(&generate_factory_method_invoke(class, iface, method, known_types));
        }
    }

    // Static methods
    for iface in &class.static_interfaces {
        for method in &iface.methods {
            out.push('\n');
            out.push_str(&generate_static_method_invoke(class, iface, method, known_types));
        }
    }

    // Instance methods: default interface (reorder for Python @property before @setter)
    if let Some(ref default_iface) = class.default_interface {
        let iface_var = format!("_{}", default_iface.name);
        for method in reorder_getters_before_setters(&default_iface.methods) {
            out.push('\n');
            out.push_str(&generate_iface_instance_method(default_iface, &iface_var, method, known_types, &delegate_names));
        }
    }

    // Auto-generate close() if class implements IClosable
    const ICLOSABLE_IID: &str = "30d5a829-7fa4-4026-83bb-d75bae4ea99e";
    if class.required_interfaces.iter().any(|ri| ri.iid == ICLOSABLE_IID) {
        out.push('\n');
        out.push_str("    def close(self):\n");
        out.push_str("        IClosable.from_value(self._obj).close()\n");
    }

    // .as_interface() method for accessing non-default interfaces
    if !class.required_interfaces.is_empty() {
        out.push('\n');
        out.push_str("    def as_interface(self, interface_class):\n");
        out.push_str("        return interface_class.from_value(self._obj)\n");
    }

    // Generate inline wrapper classes for required interfaces (non-default)
    for req_iface in &class.required_interfaces {
        if req_iface.iid.is_empty() { continue; }
        if imported_names.contains(&req_iface.name) {
            continue;
        }
        let reg_var = format!("_{}", req_iface.name);
        out.push('\n');
        out.push_str(&format!("\nclass {}:\n", req_iface.name));
        out.push_str("    def __init__(self, obj: DynWinRTValue):\n");
        out.push_str("        self._obj = obj\n");
        out.push('\n');
        out.push_str("    @staticmethod\n");
        out.push_str(&format!(
            "    def from_value(obj: DynWinRTValue) -> '{}':\n",
            req_iface.name
        ));
        out.push_str(&format!(
            "        return {}(obj.cast(IID_{}))\n",
            req_iface.name, req_iface.name
        ));
        for method in reorder_getters_before_setters(&req_iface.methods) {
            out.push('\n');
            out.push_str(&generate_iface_instance_method(req_iface, &reg_var, method, known_types, &delegate_names));
        }
    }
    out
}

/// Format a Python import line based on type kind.
fn format_py_type_import(name: &str, kind: TypeKind) -> String {
    let module = to_snake_case_filename(name);
    if kind == TypeKind::Interface {
        format!("from .{module} import IID_{name}, {name}  # noqa: F401\n")
    } else {
        format!("from .{module} import {name}  # noqa: F401\n")
    }
}
