// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

use std::collections::HashSet;

use crate::meta::{ClassMeta, InterfaceMeta};
use crate::types::TypeMeta;

use super::common::{collect_used_structs_from_class, collect_used_structs_from_iface};

/// Generate an index.ts that re-exports all generated types.
pub fn generate_index(
    classes: &[ClassMeta],
    interfaces: &[InterfaceMeta],
    enums: &[TypeMeta],
) -> String {
    let mut out = String::new();
    let mut seen: HashSet<String> = HashSet::new();
    out.push_str("// Generated by dynwinrt-codegen \u{2014} do not edit\n");
    // Export classes + their pack/unpack struct helpers.
    // IID_*, *_Type, *_PARAM_TYPES remain importable from individual module files.
    let mut sorted_classes: Vec<_> = classes.iter().collect();
    sorted_classes.sort_by(|a, b| a.name.cmp(&b.name));
    for class in sorted_classes {
        if seen.insert(class.name.clone()) {
            let struct_names: Vec<_> = collect_used_structs_from_class(class)
                .iter()
                .flat_map(|s| ts_pack_export_names(s))
                .filter(|n| seen.insert(n.clone()))
                .collect();
            if struct_names.is_empty() {
                out.push_str(&format!(
                    "export {{ {} }} from './{}.js';\n",
                    class.name, class.name
                ));
            } else {
                out.push_str(&format!(
                    "export {{ {}, {} }} from './{}.js';\n",
                    class.name,
                    struct_names.join(", "),
                    class.name
                ));
            }
        }
    }
    let mut sorted_ifaces: Vec<_> = interfaces.iter().collect();
    sorted_ifaces.sort_by(|a, b| a.name.cmp(&b.name));
    for iface in sorted_ifaces {
        if !seen.insert(iface.name.clone()) {
            continue;
        }
        // Skip delegates (IID + PARAM_TYPES only — internal plumbing)
        let is_delegate = iface.methods.iter().any(|m| m.name == ".ctor")
            && iface.methods.iter().any(|m| m.name == "Invoke");
        if is_delegate {
            continue;
        }
        let struct_names: Vec<_> = collect_used_structs_from_iface(iface)
            .iter()
            .flat_map(|s| ts_pack_export_names(s))
            .filter(|n| seen.insert(n.clone()))
            .collect();
        if struct_names.is_empty() {
            out.push_str(&format!(
                "export {{ {iname} }} from './{iname}.js';\n",
                iname = iface.name
            ));
        } else {
            out.push_str(&format!(
                "export {{ {iname}, {structs} }} from './{iname}.js';\n",
                iname = iface.name,
                structs = struct_names.join(", ")
            ));
        }
    }
    let mut sorted_enums: Vec<_> = enums.iter().collect();
    sorted_enums.sort_by(|a, b| {
        let name_a = match a {
            TypeMeta::Enum { name, .. } => name.as_str(),
            _ => "",
        };
        let name_b = match b {
            TypeMeta::Enum { name, .. } => name.as_str(),
            _ => "",
        };
        name_a.cmp(name_b)
    });
    for en in sorted_enums {
        if let TypeMeta::Enum { name, .. } = en {
            if seen.insert(name.clone()) {
                out.push_str(&format!("export {{ {} }} from './{}.js';\n", name, name));
            }
        }
    }
    out
}

// ======================================================================
// Public: append_to_index — merge new types into an existing ESM index
// ======================================================================

pub fn append_to_index(
    existing: &str,
    classes: &[ClassMeta],
    interfaces: &[InterfaceMeta],
    enums: &[TypeMeta],
) -> String {
    // Parse existing export lines to find already-exported names and modules
    let mut seen: HashSet<String> = HashSet::new();
    let mut exported_modules: HashSet<String> = HashSet::new();
    for line in existing.lines() {
        // Match: export { Foo } from './Foo.js';
        // Match: export { IID_IBar, IBar } from './IBar.js';
        if line.starts_with("export {") {
            if let Some(start) = line.find('{') {
                if let Some(end) = line.find('}') {
                    for name in line[start + 1..end].split(',') {
                        let name = name.trim();
                        if !name.is_empty() {
                            seen.insert(name.to_string());
                        }
                    }
                }
            }
            // Track module name from `from './Foo.js'`
            if let Some(start) = line.find("from './") {
                if let Some(end) = line[start + 8..].find("'") {
                    let module = &line[start + 8..start + 8 + end];
                    let module = module.strip_suffix(".js").unwrap_or(module);
                    exported_modules.insert(module.to_string());
                }
            }
        }
    }

    let mut out = existing.to_string();
    if !out.ends_with('\n') {
        out.push('\n');
    }

    // Add new classes with pack/unpack struct helpers
    let mut sorted_classes: Vec<_> = classes.iter().collect();
    sorted_classes.sort_by(|a, b| a.name.cmp(&b.name));
    for class in sorted_classes {
        if !exported_modules.contains(&class.name) && seen.insert(class.name.clone()) {
            let struct_names: Vec<_> = collect_used_structs_from_class(class)
                .iter()
                .flat_map(|s| ts_pack_export_names(s))
                .filter(|n| seen.insert(n.clone()))
                .collect();
            if struct_names.is_empty() {
                out.push_str(&format!(
                    "export {{ {} }} from './{}.js';\n",
                    class.name, class.name
                ));
            } else {
                out.push_str(&format!(
                    "export {{ {}, {} }} from './{}.js';\n",
                    class.name,
                    struct_names.join(", "),
                    class.name
                ));
            }
        }
    }

    // Add new interfaces with pack/unpack struct helpers (no IID_*)
    let mut sorted_ifaces: Vec<_> = interfaces.iter().collect();
    sorted_ifaces.sort_by(|a, b| a.name.cmp(&b.name));
    for iface in sorted_ifaces {
        if exported_modules.contains(&iface.name) || !seen.insert(iface.name.clone()) {
            continue;
        }
        // Skip delegates (IID + PARAM_TYPES only — internal plumbing)
        let is_delegate = iface.methods.iter().any(|m| m.name == ".ctor")
            && iface.methods.iter().any(|m| m.name == "Invoke");
        if is_delegate {
            continue;
        }
        let struct_names: Vec<_> = collect_used_structs_from_iface(iface)
            .iter()
            .flat_map(|s| ts_pack_export_names(s))
            .filter(|n| seen.insert(n.clone()))
            .collect();
        if struct_names.is_empty() {
            out.push_str(&format!("export {{ {0} }} from './{0}.js';\n", iface.name));
        } else {
            out.push_str(&format!(
                "export {{ {0}, {1} }} from './{0}.js';\n",
                iface.name,
                struct_names.join(", ")
            ));
        }
    }

    // Add new enums
    let mut sorted_enums: Vec<_> = enums.iter().collect();
    sorted_enums.sort_by(|a, b| {
        let name_a = match a {
            TypeMeta::Enum { name, .. } => name.as_str(),
            _ => "",
        };
        let name_b = match b {
            TypeMeta::Enum { name, .. } => name.as_str(),
            _ => "",
        };
        name_a.cmp(name_b)
    });
    for en in sorted_enums {
        if let TypeMeta::Enum { name, .. } = en {
            if !exported_modules.contains(name) && seen.insert(name.clone()) {
                out.push_str(&format!("export {{ {} }} from './{}.js';\n", name, name));
            }
        }
    }

    out
}

/// Returns only user-facing struct helpers (pack/unpack) for index re-export.
/// Excludes *_Type which is internal plumbing.
fn ts_pack_export_names(s: &TypeMeta) -> Vec<String> {
    match s {
        TypeMeta::Struct { name, .. } => vec![format!("pack{}", name), format!("unpack{}", name)],
        _ => vec![],
    }
}
