# Generated by dynwinrt-codegen — do not edit
from __future__ import annotations
from dynwinrt_py import (
    DynWinRTType, DynWinRTValue, DynWinRTArray, DynWinRTStruct, DynWinRtDelegate, WinGUID,
)

from .i_www_form_url_decoder_entry import IID_IWwwFormUrlDecoderEntry, IWwwFormUrlDecoderEntry  # noqa: F401

IID_IIterator_IWwwFormUrlDecoderEntry: WinGUID


class IIterator_IWwwFormUrlDecoderEntry:
    def __init__(self, obj: DynWinRTValue) -> None: ...

    @staticmethod
    def from_value(obj: DynWinRTValue) -> 'IIterator_IWwwFormUrlDecoderEntry': ...

    @property
    def current(self) -> 'IWwwFormUrlDecoderEntry': ...

    @property
    def has_current(self) -> bool: ...

    def move_next(self) -> bool: ...

    def get_many(self, items: 'DynWinRTArray') -> list['IWwwFormUrlDecoderEntry']: ...
