# Generated by dynwinrt-codegen — do not edit
from __future__ import annotations
import builtins
from ._typing import (
    Callable, Iterable, Iterator, Mapping, MutableMapping, MutableSequence, Sequence,
    UUID, WinGUID, datetime, overload, timedelta,
    DynWinRTType, DynWinRTValue, DynWinRTArray, DynWinRTStruct, DynWinRtDelegate,
    _DynWinRTObject, _DynWinRTProjector,
)
from typing import Protocol, Self, TypeVar

_InterfaceT = TypeVar('_InterfaceT')

from .windows__foundation__i_www_form_url_decoder_entry import IID_IWwwFormUrlDecoderEntry, IWwwFormUrlDecoderEntry  # noqa: F401

IID_IIterator_IWwwFormUrlDecoderEntry: WinGUID


class _IIterator_IWwwFormUrlDecoderEntryIdentity(Protocol):
    def _dynwinrt_iid_g2bb0b33cef11eb455ace3197fce2b56f216f6802e23b208c88ebad8f950f8628(self) -> None: ...

class IIterator_IWwwFormUrlDecoderEntry(_IIterator_IWwwFormUrlDecoderEntryIdentity, Iterator[IWwwFormUrlDecoderEntry | None]):
    @builtins.property
    def _obj(self) -> DynWinRTValue: ...
    # Windows.Foundation.Collections.IIterator_IWwwFormUrlDecoderEntry cannot be implemented: generic interface implementations are not supported
    def __init__(self, obj: DynWinRTValue) -> None: ...

    def __iter__(self) -> Iterator[IWwwFormUrlDecoderEntry | None]: ...
    def __next__(self) -> IWwwFormUrlDecoderEntry | None: ...

    @classmethod
    def from_value(cls, obj: DynWinRTValue) -> Self: ...
    def as_interface(self, interface_class: _DynWinRTProjector[_InterfaceT]) -> _InterfaceT: ...

    @builtins.property
    def current(self) -> IWwwFormUrlDecoderEntry | None: ...

    @builtins.property
    def has_current(self) -> bool: ...

    def move_next(self) -> bool: ...

    def get_many(self, items: DynWinRTArray | Sequence['IWwwFormUrlDecoderEntry']) -> list[IWwwFormUrlDecoderEntry | None]: ...
