# Generated by dynwinrt-codegen — do not edit
from __future__ import annotations
import builtins
from ._typing import (
    Callable, Iterable, Iterator, Mapping, MutableMapping, MutableSequence, Sequence,
    UUID, WinGUID, datetime, overload, timedelta,
    DynWinRTType, DynWinRTValue, DynWinRTArray, DynWinRTStruct, DynWinRtDelegate,
    _DynWinRTObject, _DynWinRTProjector,
)
from abc import ABCMeta
from typing import Protocol, TypedDict
from dynwinrt import (
    DynWinRTInterfacePlan, DynWinRTImplementationMethod,
    DynWinRTImplementation, DynWinRTImplementationDescriptor,
    DynWinRTImplementationHandle,
)
from typing import TypeVar
from dynwinrt import _DynWinRTImplementationFactory
_ImplementationHandlers = TypeVar('_ImplementationHandlers')
from typing import Protocol, Self, TypeVar

_InterfaceT = TypeVar('_InterfaceT')


IID_IStringable: WinGUID


class IStringableHandlers(Protocol):
    """Synchronous handlers; multi-output results are named dicts and FillArray inputs are capacities."""
    def to_string(self) -> str: ...

class _IStringableImplementationFactory(ABCMeta):
    def from_value(cls: type[_InterfaceT], obj: DynWinRTValue) -> _InterfaceT: ...
    def implementation(cls, handlers: IStringableHandlers) -> DynWinRTImplementationDescriptor: ...
    def implement(cls, handlers: IStringableHandlers, *additional: DynWinRTImplementationDescriptor, interfaces: Sequence[tuple[_DynWinRTImplementationFactory[_ImplementationHandlers], _ImplementationHandlers]] = ...) -> DynWinRTImplementationHandle[IStringable]: ...
    def from_implementation(cls, owner: DynWinRTImplementation | DynWinRTImplementationHandle[object]) -> IStringable: ...


class _IStringableIdentity(Protocol):
    def _dynwinrt_iid_windows_foundation_istringable(self) -> None: ...

class IStringable(_IStringableIdentity, Protocol, metaclass=_IStringableImplementationFactory):
    @builtins.property
    def _obj(self) -> DynWinRTValue: ...

    def as_interface(self, interface_class: _DynWinRTProjector[_InterfaceT]) -> _InterfaceT: ...

    def to_string(self) -> str: ...
