# Generated by dynwinrt-codegen — do not edit
from __future__ import annotations
import builtins
from ._typing import (
    Callable, Iterable, Iterator, Mapping, MutableMapping, MutableSequence, Sequence,
    UUID, WinGUID, datetime, overload, timedelta,
    DynWinRTType, DynWinRTValue, DynWinRTArray, DynWinRTStruct, DynWinRtDelegate,
    _DynWinRTProjector,
)
from typing import Protocol, Self


IID_IWwwFormUrlDecoderEntry: WinGUID


class IWwwFormUrlDecoderEntry(Protocol):

    @classmethod
    def from_value(cls, obj: DynWinRTValue) -> Self: ...

    @builtins.property
    def name(self) -> str: ...

    @builtins.property
    def value(self) -> str: ...
