# Generated by dynwinrt-codegen — do not edit
from __future__ import annotations
from collections.abc import (
    Callable, Iterable, Iterator, Mapping, MutableMapping, MutableSequence, Sequence,
)
from datetime import datetime, timedelta
from uuid import UUID
from typing import overload
from dynwinrt_py import (
    DynWinRTType, DynWinRTValue, DynWinRTArray, DynWinRTStruct, DynWinRtDelegate, WinGUID,
)


IID_IWwwFormUrlDecoderEntry: WinGUID


class IWwwFormUrlDecoderEntry:
    def __init__(self, obj: DynWinRTValue) -> None: ...

    @staticmethod
    def from_value(obj: DynWinRTValue) -> 'IWwwFormUrlDecoderEntry': ...

    @property
    def name(self) -> str: ...

    @property
    def value(self) -> str: ...
