# Generated by dynwinrt-codegen — do not edit
from __future__ import annotations
import builtins
from ._typing import (
    Callable, Iterable, Iterator, Mapping, MutableMapping, MutableSequence, Sequence,
    UUID, WinGUID, datetime, overload, timedelta,
    DynWinRTType, DynWinRTValue, DynWinRTArray, DynWinRTStruct, DynWinRtDelegate,
    _DynWinRTProjector,
)
from typing import Protocol, TypedDict
from dynwinrt import (
    DynWinRTInterfacePlan, DynWinRTImplementationMethod,
    DynWinRTImplementation, DynWinRTImplementationDescriptor,
    DynWinRTImplementationHandle,
)
from abc import ABCMeta
from typing import TypeVar
from dynwinrt import _DynWinRTImplementationFactory
_ImplementationHandlers = TypeVar('_ImplementationHandlers')
from typing import Protocol, Self, TypeVar

_InterfaceT = TypeVar('_InterfaceT')


IID_IWwwFormUrlDecoderEntry: WinGUID


class IWwwFormUrlDecoderEntryHandlers(Protocol):
    """Synchronous handlers; multi-output results are named dicts and FillArray inputs are capacities."""
    def get_name(self) -> str: ...
    def get_value(self) -> str: ...

class _IWwwFormUrlDecoderEntryImplementationFactory(ABCMeta):
    def implementation(cls, handlers: IWwwFormUrlDecoderEntryHandlers) -> DynWinRTImplementationDescriptor: ...
    def implement(cls, handlers: IWwwFormUrlDecoderEntryHandlers, *additional: DynWinRTImplementationDescriptor, interfaces: Sequence[tuple[_DynWinRTImplementationFactory[_ImplementationHandlers], _ImplementationHandlers]] = ...) -> DynWinRTImplementationHandle[IWwwFormUrlDecoderEntry]: ...
    def from_implementation(cls, owner: DynWinRTImplementation | DynWinRTImplementationHandle[object]) -> IWwwFormUrlDecoderEntry: ...


class _IWwwFormUrlDecoderEntryIdentity(Protocol):
    def _dynwinrt_iid_windows_foundation_iwwwformurldecoderentry(self) -> None: ...

class IWwwFormUrlDecoderEntry(_IWwwFormUrlDecoderEntryIdentity, Protocol, metaclass=_IWwwFormUrlDecoderEntryImplementationFactory):

    @classmethod
    def from_value(cls, obj: DynWinRTValue) -> Self: ...
    def as_interface(self, interface_class: _DynWinRTProjector[_InterfaceT]) -> _InterfaceT: ...

    @builtins.property
    def name(self) -> str: ...

    @builtins.property
    def value(self) -> str: ...
