// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

mod class;
mod imports;
mod index;
mod structs;
mod types;

use std::collections::HashSet;

use crate::meta::{ClassMeta, InterfaceMeta, ParamDirection};
use crate::types::{TypeKind, TypeMeta};

use crate::codegen::shared::imports::{
    collect_iface_type_imports, collect_type_imports, collect_used_generics_from_class,
    collect_used_generics_from_methods,
};
use crate::codegen::shared::structs::{
    collect_used_structs_from_class, collect_used_structs_from_iface,
};

use super::method::{
    generate_factory_method_invoke, generate_iface_instance_method, generate_static_method_invoke,
};
use super::naming::{is_py_reserved, to_snake_case, to_snake_case_filename};
use super::shared::reorder_getters_before_setters;
use super::signature::{py_dynwinrt_type, py_generate_interface_registration, py_runtime_symbol};
use super::structs::{py_struct_field_getter, py_struct_field_setter, py_struct_field_type};

const HEADER: &str = "# Generated by dynwinrt-codegen — do not edit\n";
const FUTURE_ANNOTATIONS: &str = "from __future__ import annotations\n";
const IMPORT_LINE: &str = "\
from functools import lru_cache
from importlib import import_module
from typing import TYPE_CHECKING
from dynwinrt_py import (
    DynWinRTType, DynWinRTMethodSig, DynWinRTValue, DynWinRTArray,
    DynWinRTStruct, DynWinRtDelegate, WinGUID,
)


@lru_cache(maxsize=None)
def _dynwinrt_symbol(module, name):
    return getattr(import_module(f'.{module}', __package__), name)


def _dynwinrt_wrap_values(module, name, values):
    wrapper = _dynwinrt_symbol(module, name)
    return [wrapper(value) for value in values]


def _dynwinrt_enum(module, name, value):
    enum_type = _dynwinrt_symbol(module, name)
    try:
        return enum_type(value)
    except ValueError:
        return value


def _dynwinrt_wait_action(value):
    value.wait()
    return None
\n";

pub use class::generate_class;
pub use index::{append_to_index, generate_index};
pub use types::{generate_enum, generate_interface};
