// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

mod class;
mod imports;
mod index;
mod structs;
mod types;

use std::collections::HashSet;

use crate::meta::{ClassMeta, InterfaceMeta, MethodMeta, ParamDirection};
use crate::types::{TypeKind, TypeMeta};

use crate::codegen::winrt::shared::imports::{
    collect_iface_type_imports_by_identity, collect_struct_field_type_imports,
    collect_used_generic_identities_from_class, collect_used_generic_identities_from_methods,
    collect_used_generic_identities_from_type, ireference_inner_type,
};
use crate::codegen::winrt::shared::structs::{
    collect_used_structs_from_class, collect_used_structs_from_iface,
    collect_used_structs_from_struct,
};

use super::method::{
    InstanceOverload, StaticOverload, StaticOverloadKind, generate_instance_method_group,
    generate_static_method_group, py_method_type_guard,
};
use super::naming::{PythonProjectionContext, PythonSupportSymbol, is_py_reserved, to_snake_case};
use super::shared::reorder_getters_before_setters;
use super::signature::{
    py_collect_runtime_class_iid_consts, py_dynwinrt_type, py_generate_interface_registration,
    py_interface_iid_expr, py_runtime_named_symbol, py_runtime_symbol, py_wrap_collection_item,
};
use super::structs::{
    py_struct_field_getter, py_struct_field_read_type, py_struct_field_setter, py_struct_field_type,
};
use super::type_helpers::methods_have_async_output;

const HEADER: &str = "# Generated by dynwinrt-codegen — do not edit\n";
const FUTURE_ANNOTATIONS: &str = "from __future__ import annotations\n";
fn import_line(context: &PythonProjectionContext) -> String {
    let object_input = context.support_symbol_import(PythonSupportSymbol::ObjectInput);
    format!(
        "\
from ._runtime import (
    Callable, Iterable, Iterator, Mapping, MutableMapping, MutableSequence, Sequence,
    TYPE_CHECKING, UUID, WinGUID, datetime, timedelta,
    DynWinRTType, DynWinRTMethodSig, DynWinRTValue, DynWinRTArray,
    DynWinRTStruct, DynWinRtDelegate, DynWinRTOverrideInterface,
    {object_input}, _property, _weakref_ref,
    _dynwinrt_array, _dynwinrt_bind_overload, _dynwinrt_can_cast, _dynwinrt_create_delegate,
    _dynwinrt_datetime_to_ticks, _dynwinrt_delegate, _dynwinrt_enum, _dynwinrt_guid,
    _dynwinrt_map, _dynwinrt_new_vector, _dynwinrt_ticks_to_datetime,
    _dynwinrt_ticks_to_timedelta, _dynwinrt_timedelta_to_ticks,
    _dynwinrt_cache_projected, _dynwinrt_projected_from_native,
    _dynwinrt_symbol, _dynwinrt_track_projected, _dynwinrt_uuid,
    _dynwinrt_vector, _dynwinrt_wrap_values,
)
"
    )
}

fn collection_item_import<'a>(
    methods: impl IntoIterator<Item = &'a MethodMeta>,
    collection_interface: bool,
) -> &'static str {
    let method_uses_helper = methods.into_iter().any(|method| {
        !method.collection_inputs.is_empty()
            || method.params.iter().any(|parameter| {
                parameter.direction == ParamDirection::In
                    && super::collections::type_kind(&parameter.typ).is_some()
            })
    });
    if collection_interface || method_uses_helper {
        "from ._runtime import _dynwinrt_collection_item\n"
    } else {
        ""
    }
}

const RUNTIME_SUPPORT_BODY: &str = "\
from builtins import property as _property
from functools import lru_cache
from importlib import import_module
from collections.abc import (
    Callable, Iterable, Iterator, Mapping, MutableMapping, MutableSequence, Sequence,
)
from datetime import datetime, timedelta
from typing import TYPE_CHECKING, Protocol
from uuid import UUID
from weakref import ref as _weakref_ref
from dynwinrt import (
    DynWinRTType, DynWinRTMethodSig, DynWinRTValue, DynWinRTArray,
    DynWinRTStruct, DynWinRtDelegate, DynWinRTOverrideInterface, WinGUID,
)
from dynwinrt.dynwinrt import (
    _dynwinrt_array, _dynwinrt_bind_overload, _dynwinrt_datetime_to_ticks, _dynwinrt_guid,
    _dynwinrt_map, _dynwinrt_new_vector, _dynwinrt_ticks_to_datetime, _dynwinrt_ticks_to_timedelta,
    _dynwinrt_timedelta_to_ticks, _dynwinrt_cache_projected, _dynwinrt_projected_from_native,
    _dynwinrt_track_projected, _dynwinrt_uuid, _dynwinrt_vector,
    _dynwinrt_wrap_delegate_callback,
)


@lru_cache(maxsize=None)
def _dynwinrt_symbol(module, name):
    return getattr(import_module(f'.{module}', __package__), name)


def _dynwinrt_wrap_values(module, name, values):
    wrapper = _dynwinrt_symbol(module, name)
    wrap = getattr(wrapper, '_from_native', wrapper)
    return [None if value.is_null() else wrap(value) for value in values]


def _dynwinrt_collection_item(value, wrap, allow_none, role):
    if value is None:
        if allow_none:
            return DynWinRTValue.null_value()
        raise TypeError(f'{role} cannot be None')
    return wrap(value)


def _dynwinrt_enum(module, name, value):
    enum_type = _dynwinrt_symbol(module, name)
    try:
        return enum_type(value)
    except ValueError:
        return value


def _dynwinrt_create_delegate(iid, parameter_types, callback):
    return DynWinRtDelegate.create(
        iid,
        parameter_types,
        _dynwinrt_wrap_delegate_callback(callback),
    )

def _dynwinrt_delegate(value, iid, parameter_types):
    raw = getattr(value, '_obj', value)
    if isinstance(raw, DynWinRTValue):
        return raw
    if not callable(value):
        raise TypeError('delegate value must be callable or a DynWinRTValue')
    return _dynwinrt_create_delegate(iid, parameter_types, value).to_value()
def _dynwinrt_can_cast(value, iid):
    raw = getattr(value, '_obj', value)
    if not isinstance(raw, DynWinRTValue):
        return False
    try:
        projected = raw.cast(iid)
    except OSError:
        return False
    projected.release()
    return True
\n";

pub fn generate_runtime_support_module() -> String {
    format!(
        "{HEADER}{FUTURE_ANNOTATIONS}{RUNTIME_SUPPORT_BODY}{}{}",
        super::shared::NATIVE_OBJECT_PROTOCOL,
        super::implementation::HELPERS
    )
}

const ASYNC_IMPORT_LINE: &str = "\
from dynwinrt import WinRTCoroutine, WinRTCoroutineWithProgress
from dynwinrt.dynwinrt import _DynWinRTAsync, _DynWinRTAsyncWithProgress
";

const IREFERENCE_HELPER: &str = "\
def _dynwinrt_box_reference(value, value_type, wrap):
    raw = getattr(value, '_obj', value)
    if isinstance(raw, DynWinRTValue):
        return raw
    if raw is None:
        return DynWinRTValue.null_value()
    return DynWinRTValue.box_reference(wrap(raw), value_type)


def _dynwinrt_unbox_reference(value):
    raw = getattr(value, '_obj', None)
    if isinstance(raw, DynWinRTValue):
        return None if raw.is_null() else value.value
    return value


";

fn has_ireference_input<'a>(methods: impl IntoIterator<Item = &'a MethodMeta>) -> bool {
    fn contains(typ: &TypeMeta) -> bool {
        if ireference_inner_type(typ).is_some() {
            return true;
        }
        match typ {
            TypeMeta::Array(inner)
            | TypeMeta::AsyncOperation(inner)
            | TypeMeta::AsyncActionWithProgress(inner) => contains(inner),
            TypeMeta::AsyncOperationWithProgress(result, progress) => {
                contains(result) || contains(progress)
            }
            TypeMeta::Parameterized { args, .. } => args.iter().any(contains),
            // Struct inputs use their generated pack helpers; those modules
            // emit IREFERENCE_HELPER through has_ireference_struct_field.
            _ => false,
        }
    }

    methods.into_iter().any(|method| {
        method.params.iter().any(|param| {
            matches!(
                param.direction,
                ParamDirection::In | ParamDirection::OutFill
            ) && contains(&param.typ)
        })
    })
}

fn has_ireference_struct_field(structs: &[TypeMeta]) -> bool {
    fn contains(typ: &TypeMeta) -> bool {
        match typ {
            TypeMeta::Struct { fields, .. } => fields
                .iter()
                .any(|field| ireference_inner_type(&field.typ).is_some() || contains(&field.typ)),
            TypeMeta::Array(inner)
            | TypeMeta::AsyncOperation(inner)
            | TypeMeta::AsyncActionWithProgress(inner) => contains(inner),
            TypeMeta::AsyncOperationWithProgress(result, progress) => {
                contains(result) || contains(progress)
            }
            TypeMeta::Parameterized { args, .. } => args.iter().any(contains),
            _ => false,
        }
    }

    structs.iter().any(contains)
}

fn generate_compatibility_aliases<'a>(methods: impl IntoIterator<Item = &'a MethodMeta>) -> String {
    super::overloads::compatibility_aliases(methods)
        .into_iter()
        .map(|(legacy, canonical)| format!("    {legacy} = {canonical}\n"))
        .collect()
}

pub use class::generate_class;
pub use index::{
    append_to_index, generate_index, generate_public_index, generate_public_struct_index,
    generate_struct_index,
};
pub use structs::generate_struct;
pub use types::{generate_enum, generate_interface};

#[cfg(test)]
mod tests {
    use super::*;
    use crate::meta::{InterfaceMeta, ParamDirection, ParamMeta};

    fn reference() -> TypeMeta {
        TypeMeta::Parameterized {
            namespace: "Windows.Foundation".into(),
            name: "IReference`1".into(),
            piid: "61c17706-2d65-11e0-9ae8-d48564015472".into(),
            args: vec![TypeMeta::I32],
        }
    }

    fn parameterized(name: &str, piid: &str, args: Vec<TypeMeta>) -> TypeMeta {
        TypeMeta::Parameterized {
            namespace: "Windows.Foundation.Collections".into(),
            name: name.into(),
            piid: piid.into(),
            args,
        }
    }

    fn method(typ: TypeMeta) -> MethodMeta {
        MethodMeta {
            params: vec![ParamMeta {
                name: "value".into(),
                typ,
                direction: ParamDirection::In,
            }],
            ..Default::default()
        }
    }

    fn consumer(methods: Vec<MethodMeta>) -> InterfaceMeta {
        InterfaceMeta {
            namespace: "Contoso".into(),
            name: "IConsumer".into(),
            iid: "11111111-1111-1111-1111-111111111111".into(),
            methods,
            ..Default::default()
        }
    }

    #[test]
    fn generated_delegates_use_thread_affine_callback_contexts() {
        let runtime = generate_runtime_support_module();

        assert!(runtime.contains("_dynwinrt_wrap_delegate_callback,"));
        assert!(runtime.contains("_dynwinrt_wrap_delegate_callback(callback),"));
        assert!(!runtime.contains("copy_context"));
    }

    #[test]
    fn ireference_helper_detection_follows_nested_input_wrappers() {
        let iterable = parameterized(
            "IIterable`1",
            super::super::collections::IITERABLE_PIID,
            vec![reference()],
        );
        let mapping = parameterized(
            "IMap`2",
            super::super::collections::IMAP_PIID,
            vec![TypeMeta::String, reference()],
        );
        assert!(has_ireference_input([&method(iterable)]));
        assert!(has_ireference_input([&method(mapping)]));
        assert!(has_ireference_input([&method(TypeMeta::Array(Box::new(
            reference()
        )))]));
    }

    #[test]
    fn ireference_helper_detection_ignores_non_reference_nested_inputs() {
        let iterable = parameterized(
            "IIterable`1",
            super::super::collections::IITERABLE_PIID,
            vec![TypeMeta::I32],
        );
        let mapping = parameterized(
            "IMap`2",
            super::super::collections::IMAP_PIID,
            vec![TypeMeta::String, TypeMeta::I32],
        );
        assert!(!has_ireference_input([&method(iterable)]));
        assert!(!has_ireference_input([&method(mapping)]));
    }

    #[test]
    fn generated_nested_ireference_inputs_emit_the_boxing_helper() {
        let reference = reference();
        let iterable = parameterized(
            "IIterable`1",
            super::super::collections::IITERABLE_PIID,
            vec![reference.clone()],
        );
        let mapping = parameterized(
            "IMap`2",
            super::super::collections::IMAP_PIID,
            vec![TypeMeta::String, reference],
        );
        let interface = consumer(vec![method(iterable), method(mapping)]);
        let context = PythonProjectionContext::standalone([interface.type_identity()]).unwrap();
        let generated = generate_interface(&context, &interface);

        assert!(generated.contains("def _dynwinrt_box_reference(value, value_type, wrap):"));
        assert!(generated.contains(
            "_dynwinrt_vector(value, lambda item: _dynwinrt_collection_item(item, lambda item: _dynwinrt_box_reference("
        ));
        assert!(generated.contains(
            "_dynwinrt_map(value, lambda item: _dynwinrt_collection_item(item, lambda item: DynWinRTValue.from_hstring(item)"
        ));
        assert!(generated.contains(
            "lambda item: _dynwinrt_collection_item(item, lambda item: _dynwinrt_box_reference("
        ));

        let scalar = consumer(vec![method(parameterized(
            "IIterable`1",
            super::super::collections::IITERABLE_PIID,
            vec![TypeMeta::I32],
        ))]);
        let generated = generate_interface(&context, &scalar);
        assert!(!generated.contains("def _dynwinrt_box_reference(value, value_type, wrap):"));
        assert!(!generated.contains("_dynwinrt_box_reference("));
    }
}
