// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

mod class;
mod imports;
mod index;
mod structs;
mod types;

use std::collections::HashSet;

use crate::meta::{ClassMeta, InterfaceMeta, MethodMeta, ParamDirection};
use crate::types::{TypeKind, TypeMeta};

use crate::codegen::winrt::shared::imports::{
    collect_iface_type_imports, collect_struct_field_type_imports, collect_type_imports,
    collect_used_generics_from_class, collect_used_generics_from_methods,
    collect_used_generics_from_type, ireference_inner_type,
};
use crate::codegen::winrt::shared::structs::{
    collect_used_structs_from_class, collect_used_structs_from_iface,
    collect_used_structs_from_struct,
};

use super::method::{
    InstanceOverload, StaticOverload, StaticOverloadKind, generate_instance_method_group,
    generate_static_method_group, py_method_type_guard,
};
use super::naming::{
    is_py_reserved, python_module_layout_installed, python_module_name,
    python_public_qualified_module_name, to_snake_case, to_snake_case_filename,
};
use super::shared::reorder_getters_before_setters;
use super::signature::{
    py_collect_runtime_class_iid_consts, py_dynwinrt_type, py_generate_interface_registration,
    py_interface_iid_expr, py_runtime_symbol, py_wrap_native_value,
};
use super::structs::{
    py_struct_field_getter, py_struct_field_read_type, py_struct_field_setter, py_struct_field_type,
};
use super::type_helpers::methods_have_async_output;

const HEADER: &str = "# Generated by dynwinrt-codegen — do not edit\n";
const FUTURE_ANNOTATIONS: &str = "from __future__ import annotations\n";
const IMPORT_LINE: &str = "\
from ._runtime import (
    Callable, Iterable, Iterator, Mapping, MutableMapping, MutableSequence, Sequence,
    TYPE_CHECKING, UUID, WinGUID, datetime, timedelta,
    DynWinRTType, DynWinRTMethodSig, DynWinRTValue, DynWinRTArray,
    DynWinRTStruct, DynWinRtDelegate, DynWinRTOverrideInterface,
    _property, _weakref_ref,
    _dynwinrt_array, _dynwinrt_bind_overload, _dynwinrt_create_delegate,
    _dynwinrt_datetime_to_ticks, _dynwinrt_delegate, _dynwinrt_enum, _dynwinrt_guid,
    _dynwinrt_map, _dynwinrt_new_vector, _dynwinrt_ticks_to_datetime,
    _dynwinrt_ticks_to_timedelta, _dynwinrt_timedelta_to_ticks,
    _dynwinrt_cache_projected, _dynwinrt_projected_from_native,
    _dynwinrt_symbol, _dynwinrt_track_projected, _dynwinrt_uuid,
    _dynwinrt_vector, _dynwinrt_wrap_values,
)
";

const RUNTIME_SUPPORT_BODY: &str = "\
import asyncio as _asyncio
from builtins import property as _property
from contextvars import copy_context as _copy_context
from functools import lru_cache
from importlib import import_module
from collections.abc import (
    Callable, Iterable, Iterator, Mapping, MutableMapping, MutableSequence, Sequence,
)
from datetime import datetime, timedelta
from typing import TYPE_CHECKING
from uuid import UUID
from weakref import ref as _weakref_ref
from dynwinrt import (
    DynWinRTType, DynWinRTMethodSig, DynWinRTValue, DynWinRTArray,
    DynWinRTStruct, DynWinRtDelegate, DynWinRTOverrideInterface, WinGUID,
)
from dynwinrt.dynwinrt import (
    _dynwinrt_array, _dynwinrt_bind_overload, _dynwinrt_datetime_to_ticks, _dynwinrt_guid,
    _dynwinrt_map, _dynwinrt_new_vector, _dynwinrt_ticks_to_datetime, _dynwinrt_ticks_to_timedelta,
    _dynwinrt_timedelta_to_ticks, _dynwinrt_cache_projected, _dynwinrt_projected_from_native,
    _dynwinrt_track_projected, _dynwinrt_uuid, _dynwinrt_vector,
)


@lru_cache(maxsize=None)
def _dynwinrt_symbol(module, name):
    return getattr(import_module(f'.{module}', __package__), name)


def _dynwinrt_wrap_values(module, name, values):
    wrapper = _dynwinrt_symbol(module, name)
    wrap = getattr(wrapper, '_from_native', wrapper)
    return [None if value.is_null() else wrap(value) for value in values]


def _dynwinrt_enum(module, name, value):
    enum_type = _dynwinrt_symbol(module, name)
    try:
        return enum_type(value)
    except ValueError:
        return value


def _dynwinrt_create_delegate(iid, parameter_types, callback):
    context = _copy_context()
    def invoke(*args):
        return context.copy().run(callback, *args)
    return DynWinRtDelegate.create(iid, parameter_types, invoke)

def _dynwinrt_delegate(value, iid, parameter_types):
    raw = getattr(value, '_obj', value)
    if isinstance(raw, DynWinRTValue):
        return raw
    if not callable(value):
        raise TypeError('delegate value must be callable or a DynWinRTValue')
    return _dynwinrt_create_delegate(iid, parameter_types, value).to_value()
\n";

const EVENT_STREAM_SUPPORT: &str = r#"
_DYNWINRT_EVENT_STREAM_END = object()


class _DynWinRTEventStream:
    def __init__(self, subscribe, max_queue_size):
        if isinstance(max_queue_size, bool) or not isinstance(max_queue_size, int):
            raise TypeError('max_queue_size must be an int')
        if max_queue_size < 1:
            raise ValueError('max_queue_size must be at least 1')
        self._subscribe = subscribe
        self._max_queue_size = max_queue_size
        self._loop = None
        self._queue = None
        self._unsubscribe = None
        self._terminal_error = None
        self._entered = False
        self._closed = False
        self._waiting = False

    @property
    def closed(self):
        return self._closed

    @property
    def max_queue_size(self):
        return self._max_queue_size

    async def __aenter__(self):
        if self._entered:
            raise RuntimeError('WinRT event stream has already been entered')
        if self._closed:
            raise RuntimeError('WinRT event stream is closed')
        self._loop = _asyncio.get_running_loop()
        self._queue = _asyncio.Queue(maxsize=self._max_queue_size)
        self._entered = True
        try:
            self._unsubscribe = self._subscribe(self._on_event)
        except BaseException:
            self._entered = False
            self._loop = None
            self._queue = None
            raise
        return self

    async def __aexit__(self, exc_type, exc_value, traceback):
        await self.aclose()
        return False

    def __aiter__(self):
        if not self._entered:
            raise RuntimeError(
                "WinRT event streams must be entered with 'async with' before iteration"
            )
        return self

    async def __anext__(self):
        if not self._entered:
            raise RuntimeError(
                "WinRT event streams must be entered with 'async with' before iteration"
            )
        if self._closed:
            self._raise_terminal()
        if self._waiting:
            raise RuntimeError('WinRT event streams do not support concurrent iteration')
        self._waiting = True
        try:
            try:
                item = await self._queue.get()
            except _asyncio.CancelledError:
                await self.aclose()
                raise
        finally:
            self._waiting = False
        if item is _DYNWINRT_EVENT_STREAM_END:
            self._raise_terminal()
        return item

    async def aclose(self):
        if self._loop is not None and _asyncio.get_running_loop() is not self._loop:
            raise RuntimeError('WinRT event stream must be closed on its owning event loop')
        self._closed = True
        try:
            self._unsubscribe_now()
        finally:
            if self._unsubscribe is None:
                self._subscribe = None
            self._wake_terminal()

    def _on_event(self, *args):
        if self._closed:
            return None
        loop = self._loop
        if loop is None:
            return None
        loop.call_soon_threadsafe(self._enqueue, tuple(args))
        return None

    def _enqueue(self, item):
        if self._closed:
            return
        if self._queue.full():
            self._terminal_error = RuntimeError(
                f'WinRT event stream exceeded max_queue_size={self._max_queue_size}'
            )
            self._closed = True
            try:
                self._unsubscribe_now()
            except BaseException as error:
                self._loop.call_exception_handler({
                    'message': 'Failed to unsubscribe an overflowing WinRT event stream',
                    'exception': error,
                    'event_stream': self,
                })
            finally:
                self._wake_terminal()
            return
        self._queue.put_nowait(item)

    def _unsubscribe_now(self):
        unsubscribe = self._unsubscribe
        if unsubscribe is None:
            return
        unsubscribe()
        self._unsubscribe = None

    def _wake_terminal(self):
        queue = self._queue
        if queue is None:
            return
        while True:
            try:
                queue.get_nowait()
            except _asyncio.QueueEmpty:
                break
        queue.put_nowait(_DYNWINRT_EVENT_STREAM_END)

    def _raise_terminal(self):
        error = self._terminal_error
        self._terminal_error = None
        if error is not None:
            raise error
        raise StopAsyncIteration


def _dynwinrt_event_stream_method(subscribe_name, method_name):
    def events(self, *, max_queue_size=64):
        return _DynWinRTEventStream(getattr(self, subscribe_name), max_queue_size)
    events.__name__ = method_name
    return events
"#;

pub fn generate_runtime_support_module() -> String {
    format!("{HEADER}{FUTURE_ANNOTATIONS}{RUNTIME_SUPPORT_BODY}{EVENT_STREAM_SUPPORT}")
}

const ASYNC_IMPORT_LINE: &str = "\
from dynwinrt import WinRTAsync, WinRTAsyncWithProgress
from dynwinrt.dynwinrt import _DynWinRTAsync, _DynWinRTAsyncWithProgress
";

const IREFERENCE_HELPER: &str = "\
def _dynwinrt_box_reference(value, value_type, wrap):
    raw = getattr(value, '_obj', value)
    if isinstance(raw, DynWinRTValue):
        return raw
    if raw is None:
        return DynWinRTValue.null_value()
    return DynWinRTValue.box_reference(wrap(raw), value_type)


def _dynwinrt_unbox_reference(value):
    raw = getattr(value, '_obj', None)
    if isinstance(raw, DynWinRTValue):
        return None if raw.is_null() else value.value
    return value


";

fn has_ireference_input<'a>(methods: impl IntoIterator<Item = &'a MethodMeta>) -> bool {
    methods.into_iter().any(|method| {
        method.params.iter().any(|param| {
            param.direction == ParamDirection::In && ireference_inner_type(&param.typ).is_some()
        })
    })
}

fn has_ireference_struct_field(structs: &[TypeMeta]) -> bool {
    fn contains(typ: &TypeMeta) -> bool {
        match typ {
            TypeMeta::Struct { fields, .. } => fields
                .iter()
                .any(|field| ireference_inner_type(&field.typ).is_some() || contains(&field.typ)),
            TypeMeta::Array(inner)
            | TypeMeta::AsyncOperation(inner)
            | TypeMeta::AsyncActionWithProgress(inner) => contains(inner),
            TypeMeta::AsyncOperationWithProgress(result, progress) => {
                contains(result) || contains(progress)
            }
            TypeMeta::Parameterized { args, .. } => args.iter().any(contains),
            _ => false,
        }
    }

    structs.iter().any(contains)
}

fn generate_compatibility_aliases<'a>(methods: impl IntoIterator<Item = &'a MethodMeta>) -> String {
    super::overloads::compatibility_aliases(methods)
        .into_iter()
        .map(|(legacy, canonical)| format!("    {legacy} = {canonical}\n"))
        .collect()
}

pub use class::generate_class;
pub use index::{
    append_to_index, generate_index, generate_public_index, generate_public_struct_index,
    generate_struct_index,
};
pub use structs::generate_struct;
pub use types::{generate_enum, generate_interface};

#[cfg(test)]
mod tests {
    use super::generate_runtime_support_module;

    #[test]
    fn event_stream_runtime_is_bounded_thread_safe_and_closable() {
        let code = generate_runtime_support_module();
        assert!(code.contains("class _DynWinRTEventStream:"));
        assert!(code.contains("loop.call_soon_threadsafe(self._enqueue, tuple(args))"));
        assert!(code.contains("if self._queue.full():"));
        assert!(code.contains("await self.aclose()"));
        assert!(code.contains("self._unsubscribe_now()"));
        assert!(code.contains("WinRT event streams do not support concurrent iteration"));
        assert!(code.contains("def _dynwinrt_event_stream_method("));
    }
}
