// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

mod class;
mod imports;
mod index;
mod structs;
mod types;

use std::collections::HashSet;

use crate::meta::{ClassMeta, InterfaceMeta, MethodMeta, ParamDirection};
use crate::types::{TypeKind, TypeMeta};

use crate::codegen::winrt::shared::imports::{
    collect_iface_type_imports_by_identity, collect_struct_field_type_imports,
    collect_used_generic_identities_from_class, collect_used_generic_identities_from_methods,
    collect_used_generic_identities_from_type, get_in_params, ireference_inner_type,
};
use crate::codegen::winrt::shared::structs::{
    collect_used_structs_from_class_and_callbacks, collect_used_structs_from_iface,
    collect_used_structs_from_struct,
};

use super::member_plan::{Candidate, ScopePlan};
use super::method::{
    DispatchCandidate, InstanceOverload, StaticOverload, StaticOverloadKind, emit_dispatch,
    generate_instance_accessor, generate_instance_method_group, generate_static_accessor,
    generate_static_method_group,
};
use super::naming::{PythonProjectionContext, PythonSupportSymbol, is_py_reserved, to_snake_case};
use super::shared::reorder_getters_before_setters;
use super::signature::{
    py_collect_argument_iid_consts, py_dynwinrt_type, py_generate_interface_registration,
    py_interface_iid_expr, py_runtime_named_symbol, py_runtime_symbol, py_wrap_collection_item,
};
use super::structs::{
    py_struct_field_getter, py_struct_field_read_type, py_struct_field_setter, py_struct_field_type,
};
use super::type_helpers::methods_have_async_output;

const HEADER: &str = "# Generated by dynwinrt-codegen — do not edit\n";
const FUTURE_ANNOTATIONS: &str = "from __future__ import annotations\n";
fn import_line(
    context: &PythonProjectionContext,
    needs_legacy_helper: bool,
    needs_legacy_int_guard: bool,
) -> String {
    let object_input = context.support_symbol_import(PythonSupportSymbol::ObjectInput);
    let can_cast = context.support_symbol_import(PythonSupportSymbol::CanCast);
    let mut legacy_helpers = String::new();
    if needs_legacy_helper {
        legacy_helpers.push_str(&format!(
            "    {},\n",
            context.support_symbol_import(PythonSupportSymbol::LegacyCall)
        ));
    }
    if needs_legacy_int_guard {
        legacy_helpers.push_str(&format!(
            "    {},\n",
            context.support_symbol_import(PythonSupportSymbol::LegacyIntGuard)
        ));
    }
    let as_interface = context.support_symbol_import(PythonSupportSymbol::AsInterface);
    format!(
        "\
from ._runtime import (
    Callable, Iterable, Iterator, Mapping, MutableMapping, MutableSequence, Sequence,
    TYPE_CHECKING, UUID, WinGUID, datetime, timedelta,
    DynWinRTType, DynWinRTMethodSig, DynWinRTValue, DynWinRTArray,
    DynWinRTStruct, DynWinRtDelegate, DynWinRTOverrideInterface,
    {object_input}, _property, _weakref_ref,
    _dynwinrt_array, _dynwinrt_bind_overload, {can_cast}, _dynwinrt_create_delegate,
    _dynwinrt_datetime_to_ticks, _dynwinrt_delegate, _dynwinrt_enum, _dynwinrt_guid,
{legacy_helpers}    _dynwinrt_map, _dynwinrt_new_vector, _dynwinrt_ticks_to_datetime,
    _dynwinrt_ticks_to_timedelta, _dynwinrt_timedelta_to_ticks,
    {as_interface}, _dynwinrt_cache_projected, _dynwinrt_projected_from_native,
    _dynwinrt_symbol, _dynwinrt_track_projected, _dynwinrt_uuid,
    _dynwinrt_vector, _dynwinrt_wrap_values,
)
"
    )
}

fn collection_item_import<'a>(
    context: &PythonProjectionContext,
    methods: impl IntoIterator<Item = &'a MethodMeta>,
    collection_interface: bool,
) -> String {
    let method_uses_helper = methods.into_iter().any(|method| {
        !method.collection_inputs.is_empty()
            || method.params.iter().any(|parameter| {
                parameter.direction == ParamDirection::In
                    && super::collections::type_kind(&parameter.typ).is_some()
            })
    });
    if collection_interface || method_uses_helper {
        format!(
            "from ._runtime import {}\n",
            context.support_symbol_import(PythonSupportSymbol::CollectionItem)
        )
    } else {
        String::new()
    }
}

const RUNTIME_SUPPORT_BODY: &str = "\
from builtins import property as _property
from functools import lru_cache
from importlib import import_module
from collections.abc import (
    Callable, Iterable, Iterator, Mapping, MutableMapping, MutableSequence, Sequence,
)
from datetime import datetime, timedelta
from typing import TYPE_CHECKING, Protocol
from uuid import UUID
from weakref import ref as _weakref_ref
from dynwinrt import (
    DynWinRTType, DynWinRTMethodSig, DynWinRTValue, DynWinRTArray,
    DynWinRTStruct, DynWinRtDelegate, DynWinRTOverrideInterface, WinGUID,
)
from dynwinrt.dynwinrt import (
    _dynwinrt_array, _dynwinrt_bind_overload, _dynwinrt_datetime_to_ticks, _dynwinrt_guid,
    _dynwinrt_map, _dynwinrt_new_vector, _dynwinrt_ticks_to_datetime, _dynwinrt_ticks_to_timedelta,
    _dynwinrt_timedelta_to_ticks, _dynwinrt_cache_projected, _dynwinrt_projected_from_native,
    _dynwinrt_track_projected, _dynwinrt_uuid, _dynwinrt_vector,
    _dynwinrt_wrap_delegate_callback, _active_projected_lifetime_scope,
)


@lru_cache(maxsize=None)
def _dynwinrt_symbol(module, name):
    return getattr(import_module(f'.{module}', __package__), name)


def _dynwinrt_wrap_values(module, name, values):
    wrapper = _dynwinrt_symbol(module, name)
    wrap = getattr(wrapper, '_from_native', wrapper)
    return [None if value.is_null() else wrap(value) for value in values]


def _dynwinrt_collection_item(value, wrap, allow_none, role):
    if value is None:
        if allow_none:
            return DynWinRTValue.null_value()
        raise TypeError(f'{role} cannot be None')
    return wrap(value)


def _dynwinrt_enum(module, name, value):
    enum_type = _dynwinrt_symbol(module, name)
    try:
        return enum_type(value)
    except ValueError:
        return value


def _dynwinrt_create_delegate(iid, parameter_types, callback):
    return DynWinRtDelegate.create(
        iid,
        parameter_types,
        _dynwinrt_wrap_delegate_callback(callback),
    )

def _dynwinrt_delegate(value, iid, parameter_types, project=None):
    if isinstance(value, DynWinRtDelegate):
        return value.to_value()
    raw = getattr(value, '_obj', value)
    if isinstance(raw, DynWinRTValue):
        return raw
    if not callable(value):
        raise TypeError('delegate value must be callable or a DynWinRTValue')
    if project is not None:
        value = _dynwinrt_project_callback(value, project)
    return _dynwinrt_create_delegate(iid, parameter_types, value).to_value()


def _dynwinrt_project_callback(callback, project):
    # Projected arguments belong to the callback, not to a lifetime scope that
    # was active when it subscribed.
    def invoke(*args):
        token = _active_projected_lifetime_scope.set(None)
        try:
            arguments = project(*args)
        finally:
            _active_projected_lifetime_scope.reset(token)
        return callback(*arguments)
    return invoke


def _dynwinrt_can_cast(value, iid):
    raw = getattr(value, '_obj', value)
    if not isinstance(raw, DynWinRTValue):
        return False
    try_query = getattr(raw, '_try_query_interface', None)
    if not callable(try_query):
        raise RuntimeError(
            'Generated Python bindings require a matching dynwinrt runtime; '
            'install the matching runtime and regenerate all Python bindings.'
        )
    return try_query(iid)


def _dynwinrt_legacy_call(impl, parameter_names, args, kwargs, public_name):
    bound = _dynwinrt_bind_overload(parameter_names, args, kwargs)
    if bound is None:
        raise TypeError(f'No matching overload for {public_name}')
    return impl(*bound)


def _dynwinrt_legacy_int_guard(value, minimum=None, maximum=None):
    try:
        converted = int(value)
    except (TypeError, ValueError, OverflowError):
        return False
    return (
        (minimum is None or minimum <= converted)
        and (maximum is None or converted <= maximum)
    )


def _dynwinrt_as_interface(native, interface_class):
    if (
        isinstance(interface_class, type)
        and (
            getattr(interface_class, '_dynwinrt_runtime_class_type', False)
            or getattr(interface_class, '_dynwinrt_projectable_class_type', False)
        )
        and not hasattr(interface_class, 'from_value')
    ):
        name = interface_class.__name__
        raise TypeError(
            f'as_interface() requires a generated interface class, but {name} is a '
            f'runtime class. Use dynwinrt.project_as(obj, {name}) to cast to a runtime class.'
        )
    return interface_class.from_value(native)
\n";

/// `as_interface()`, emitted for every generated class and interface view.
/// It references the module's allocated name for the runtime-support helper.
fn as_interface_method(context: &PythonProjectionContext) -> String {
    format!(
        "    def as_interface(self, interface_class):\n        return {}(self._obj, interface_class)\n",
        context.support_symbol_reference(PythonSupportSymbol::AsInterface)
    )
}

pub fn generate_runtime_support_module() -> String {
    format!(
        "{HEADER}{FUTURE_ANNOTATIONS}{RUNTIME_SUPPORT_BODY}{}{}",
        super::shared::NATIVE_OBJECT_PROTOCOL,
        super::implementation::HELPERS
    )
}

const ASYNC_IMPORT_LINE: &str = "\
from dynwinrt import WinRTCoroutine, WinRTCoroutineWithProgress
from dynwinrt.dynwinrt import _DynWinRTAsync, _DynWinRTAsyncWithProgress
";

const IREFERENCE_HELPER: &str = "\
def _dynwinrt_box_reference(value, value_type, wrap):
    raw = getattr(value, '_obj', value)
    if isinstance(raw, DynWinRTValue):
        return raw
    if raw is None:
        return DynWinRTValue.null_value()
    return DynWinRTValue.box_reference(wrap(raw), value_type)


def _dynwinrt_unbox_reference(value):
    raw = getattr(value, '_obj', None)
    if isinstance(raw, DynWinRTValue):
        # A released wrapper is not a null reference: reading its value raises.
        # Runtimes without is_released() keep treating it as None.
        is_released = getattr(raw, 'is_released', None)
        if raw.is_null() and not (is_released is not None and is_released()):
            return None
        return value.value
    return value


";

fn has_ireference_input<'a>(methods: impl IntoIterator<Item = &'a MethodMeta>) -> bool {
    fn contains(typ: &TypeMeta) -> bool {
        if ireference_inner_type(typ).is_some() {
            return true;
        }
        match typ {
            TypeMeta::Array(inner)
            | TypeMeta::AsyncOperation(inner)
            | TypeMeta::AsyncActionWithProgress(inner) => contains(inner),
            TypeMeta::AsyncOperationWithProgress(result, progress) => {
                contains(result) || contains(progress)
            }
            TypeMeta::Parameterized { args, .. } => args.iter().any(contains),
            // Struct inputs use their generated pack helpers; those modules
            // emit IREFERENCE_HELPER through has_ireference_struct_field.
            _ => false,
        }
    }

    methods.into_iter().any(|method| {
        method.params.iter().any(|param| {
            matches!(
                param.direction,
                ParamDirection::In | ParamDirection::OutFill
            ) && contains(&param.typ)
        })
    })
}

fn has_ireference_struct_field(structs: &[TypeMeta]) -> bool {
    fn contains(typ: &TypeMeta) -> bool {
        match typ {
            TypeMeta::Struct { fields, .. } => fields
                .iter()
                .any(|field| ireference_inner_type(&field.typ).is_some() || contains(&field.typ)),
            TypeMeta::Array(inner)
            | TypeMeta::AsyncOperation(inner)
            | TypeMeta::AsyncActionWithProgress(inner) => contains(inner),
            TypeMeta::AsyncOperationWithProgress(result, progress) => {
                contains(result) || contains(progress)
            }
            TypeMeta::Parameterized { args, .. } => args.iter().any(contains),
            _ => false,
        }
    }

    structs.iter().any(contains)
}

fn generate_instance_compatibility_aliases<'a>(
    plan: &ScopePlan<'a>,
    overload: impl Fn(&Candidate<'a>) -> InstanceOverload<'a>,
    context: &PythonProjectionContext,
) -> String {
    plan.aliases()
        .iter()
        .map(|alias| {
            alias.dispatcher.as_ref().map_or_else(
                || format!("    {} = {}\n", alias.name, alias.target),
                |group| generate_instance_method_group(group, &overload, context),
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn generate_static_compatibility_aliases<'a>(
    plan: &ScopePlan<'a>,
    overload: impl Fn(&Candidate<'a>) -> StaticOverload<'a>,
    context: &PythonProjectionContext,
) -> String {
    plan.aliases()
        .iter()
        .map(|alias| {
            alias.dispatcher.as_ref().map_or_else(
                || format!("    {} = {}\n", alias.name, alias.target),
                |group| generate_static_method_group(group, &overload, context),
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

pub use class::generate_class;
pub use index::{
    append_to_index, generate_index, generate_public_index, generate_public_struct_index,
    generate_struct_index,
};
pub use structs::generate_struct;
pub use types::{generate_enum, generate_interface};

#[cfg(test)]
mod tests {
    use super::*;
    use crate::meta::{InterfaceMeta, ParamDirection, ParamMeta};

    fn reference() -> TypeMeta {
        TypeMeta::Parameterized {
            namespace: "Windows.Foundation".into(),
            name: "IReference`1".into(),
            piid: "61c17706-2d65-11e0-9ae8-d48564015472".into(),
            args: vec![TypeMeta::I32],
        }
    }

    fn parameterized(name: &str, piid: &str, args: Vec<TypeMeta>) -> TypeMeta {
        TypeMeta::Parameterized {
            namespace: "Windows.Foundation.Collections".into(),
            name: name.into(),
            piid: piid.into(),
            args,
        }
    }

    fn method(typ: TypeMeta) -> MethodMeta {
        MethodMeta {
            params: vec![ParamMeta {
                name: "value".into(),
                typ,
                direction: ParamDirection::In,
            }],
            ..Default::default()
        }
    }

    fn consumer(methods: Vec<MethodMeta>) -> InterfaceMeta {
        InterfaceMeta {
            namespace: "Contoso".into(),
            name: "IConsumer".into(),
            iid: "11111111-1111-1111-1111-111111111111".into(),
            methods,
            ..Default::default()
        }
    }

    #[test]
    fn generated_delegates_use_thread_affine_callback_contexts() {
        let runtime = generate_runtime_support_module();

        assert!(runtime.contains("_dynwinrt_wrap_delegate_callback,"));
        assert!(runtime.contains("_dynwinrt_wrap_delegate_callback(callback),"));
        assert!(!runtime.contains("copy_context"));
    }

    #[test]
    fn ireference_helper_detection_follows_nested_input_wrappers() {
        let iterable = parameterized(
            "IIterable`1",
            super::super::collections::IITERABLE_PIID,
            vec![reference()],
        );
        let mapping = parameterized(
            "IMap`2",
            super::super::collections::IMAP_PIID,
            vec![TypeMeta::String, reference()],
        );
        assert!(has_ireference_input([&method(iterable)]));
        assert!(has_ireference_input([&method(mapping)]));
        assert!(has_ireference_input([&method(TypeMeta::Array(Box::new(
            reference()
        )))]));
    }

    #[test]
    fn ireference_helper_detection_ignores_non_reference_nested_inputs() {
        let iterable = parameterized(
            "IIterable`1",
            super::super::collections::IITERABLE_PIID,
            vec![TypeMeta::I32],
        );
        let mapping = parameterized(
            "IMap`2",
            super::super::collections::IMAP_PIID,
            vec![TypeMeta::String, TypeMeta::I32],
        );
        assert!(!has_ireference_input([&method(iterable)]));
        assert!(!has_ireference_input([&method(mapping)]));
    }

    #[test]
    fn generated_nested_ireference_inputs_emit_the_boxing_helper() {
        let reference = reference();
        let iterable = parameterized(
            "IIterable`1",
            super::super::collections::IITERABLE_PIID,
            vec![reference.clone()],
        );
        let mapping = parameterized(
            "IMap`2",
            super::super::collections::IMAP_PIID,
            vec![TypeMeta::String, reference],
        );
        let interface = consumer(vec![method(iterable), method(mapping)]);
        let context = PythonProjectionContext::standalone([interface.type_identity()]).unwrap();
        let generated = generate_interface(&context, &interface);

        assert!(generated.contains("def _dynwinrt_box_reference(value, value_type, wrap):"));
        assert!(generated.contains(
            "_dynwinrt_vector(value, lambda item: _dynwinrt_collection_item(item, lambda item: _dynwinrt_box_reference("
        ));
        assert!(generated.contains(
            "_dynwinrt_map(value, lambda item: _dynwinrt_collection_item(item, lambda item: DynWinRTValue.from_hstring(item)"
        ));
        assert!(generated.contains(
            "lambda item: _dynwinrt_collection_item(item, lambda item: _dynwinrt_box_reference("
        ));

        let scalar = consumer(vec![method(parameterized(
            "IIterable`1",
            super::super::collections::IITERABLE_PIID,
            vec![TypeMeta::I32],
        ))]);
        let generated = generate_interface(&context, &scalar);
        assert!(!generated.contains("def _dynwinrt_box_reference(value, value_type, wrap):"));
        assert!(!generated.contains("_dynwinrt_box_reference("));
    }

    #[test]
    fn generated_cast_guard_rejects_null_and_non_object_values() {
        let runtime = generate_runtime_support_module();

        assert!(runtime.contains("try_query = getattr(raw, '_try_query_interface', None)"));
        assert!(runtime.contains("if not callable(try_query):\n        raise RuntimeError("));
        assert!(
            runtime.contains("install the matching runtime and regenerate all Python bindings.")
        );
        assert!(runtime.contains("return try_query(iid)"));
        assert!(!runtime.contains("raw.as_raw()"));
        assert!(!runtime.contains("except OSError:"));
        assert!(!runtime.contains("except RuntimeError:"));
        assert!(runtime.contains(
            "def _dynwinrt_legacy_call(impl, parameter_names, args, kwargs, public_name):"
        ));
        assert!(runtime.contains("raise TypeError(f'No matching overload for {public_name}')"));
        assert!(
            runtime.contains("def _dynwinrt_legacy_int_guard(value, minimum=None, maximum=None):")
        );
        assert!(
            runtime
                .contains("except (TypeError, ValueError, OverflowError):\n        return False")
        );
        assert!(!runtime.contains("except (TypeError, ValueError, OverflowError, RuntimeError)"));
    }

    #[test]
    fn delegate_inputs_pass_native_delegates_and_project_outside_lifetime_scopes() {
        let runtime = generate_runtime_support_module();

        assert!(runtime.contains(
            "    if isinstance(value, DynWinRtDelegate):\n        return value.to_value()\n"
        ));
        assert!(runtime.contains("        value = _dynwinrt_project_callback(value, project)\n"));
        assert!(runtime.contains(
            "        token = _active_projected_lifetime_scope.set(None)\n\
             \x20       try:\n\
             \x20           arguments = project(*args)\n\
             \x20       finally:\n\
             \x20           _active_projected_lifetime_scope.reset(token)\n\
             \x20       return callback(*arguments)\n"
        ));
    }
}
