// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import test from 'ava'
import { spawnSync } from 'node:child_process'
import { lstatSync, readFileSync, readlinkSync, rmSync, mkdirSync, symlinkSync, writeFileSync } from 'node:fs'
import { basename, dirname, join, resolve } from 'node:path'

test.serial('generated safe COM and unsafe WinML companions preserve exact contracts', (t) => {
  const winmd = process.env.DYNWINRT_WIN32_WINMD
  t.truthy(winmd, 'DYNWINRT_WIN32_WINMD is required')
  const packageRoot = resolve(process.cwd())
  const repositoryRoot = resolve(packageRoot, '..', '..')
  const output = join(packageRoot, 'target-generated-unsafe-companion')
  const externalLinkTarget = join(packageRoot, 'target-generated-unsafe-link-target')
  const lock = join(dirname(output), `.${basename(output)}.dynwinrt-generation.lock`)
  const transactionResidues = ['stage', 'backup', 'failed-output'].map((kind) =>
    join(dirname(output), `.${basename(output)}.dynwinrt-${kind}`),
  )
  rmSync(output, { recursive: true, force: true })
  rmSync(externalLinkTarget, { recursive: true, force: true })
  rmSync(lock, { force: true })
  for (const residue of transactionResidues) rmSync(residue, { recursive: true, force: true })

  try {
    const generationArgs = [
        'run',
        '--quiet',
        '-p',
        'dynwinrt-codegen',
        '--',
        'generate',
        '--winmd',
        winmd!,
        '--class-name',
        'Windows.Win32.System.Wmi.IWbemServices,Windows.Win32.Media.Audio.IAudioClient,Windows.Win32.UI.Shell.IThumbnailProvider,Windows.Win32.System.Com.IDataObject,Windows.Win32.AI.MachineLearning.WinML.IWinMLEvaluationContext',
        '--output',
        output,
      ]
    const runGeneration = (extraEnv: NodeJS.ProcessEnv = {}) =>
      spawnSync('cargo', generationArgs, {
        cwd: repositoryRoot,
        encoding: 'utf8',
        env: { ...process.env, DYNWINRT_CODEGEN_TEST_STRATEGY_RUNTIME: '1', ...extraEnv },
        windowsHide: true,
      })
    const generation = runGeneration()
    t.is(generation.status, 0, generation.stderr)

    const packageScope = join(output, 'node_modules', '@microsoft')
    mkdirSync(packageScope, { recursive: true })
    const packageJunction = join(packageScope, 'dynwinrt')
    symlinkSync(packageRoot, packageJunction, 'junction')
    mkdirSync(externalLinkTarget, { recursive: true })
    const sentinel = join(externalLinkTarget, 'sentinel.txt')
    writeFileSync(sentinel, 'outside-target-must-survive')
    const externalJunction = join(output, 'external-junction')
    symlinkSync(externalLinkTarget, externalJunction, 'junction')
    const packageJunctionTarget = resolve(dirname(packageJunction), readlinkSync(packageJunction))
    const externalJunctionTarget = resolve(dirname(externalJunction), readlinkSync(externalJunction))

    const incremental = runGeneration()
    t.is(incremental.status, 0, incremental.stderr)
    t.true(lstatSync(packageJunction).isSymbolicLink())
    t.true(lstatSync(externalJunction).isSymbolicLink())
    t.is(resolve(dirname(packageJunction), readlinkSync(packageJunction)), packageJunctionTarget)
    t.is(resolve(dirname(externalJunction), readlinkSync(externalJunction)), externalJunctionTarget)
    t.is(readFileSync(sentinel, 'utf8'), 'outside-target-must-survive')

    const rolledBack = runGeneration({ DYNWINRT_CODEGEN_TEST_FAIL_OUTPUT_COMMIT: 'after_link_move' })
    t.not(rolledBack.status, 0)
    t.regex(rolledBack.stderr, /after_link_move/)
    t.true(lstatSync(packageJunction).isSymbolicLink())
    t.true(lstatSync(externalJunction).isSymbolicLink())
    t.is(readFileSync(sentinel, 'utf8'), 'outside-target-must-survive')

    const publishedFailure = runGeneration({ DYNWINRT_CODEGEN_TEST_FAIL_OUTPUT_COMMIT: 'after_publish' })
    t.not(publishedFailure.status, 0)
    t.regex(publishedFailure.stderr, /after_publish/)
    t.true(lstatSync(packageJunction).isSymbolicLink())
    t.true(lstatSync(externalJunction).isSymbolicLink())
    t.is(readFileSync(sentinel, 'utf8'), 'outside-target-must-survive')

    const cleanupRun = runGeneration()
    t.is(cleanupRun.status, 0, cleanupRun.stderr)
    t.true(lstatSync(packageJunction).isSymbolicLink())
    t.true(lstatSync(externalJunction).isSymbolicLink())
    t.is(readFileSync(sentinel, 'utf8'), 'outside-target-must-survive')

    const wbemBase = join(output, 'com', 'windows', 'win32', 'system', 'wmi', 'IWbemServices')
    const dataObjectBase = join(output, 'com', 'windows', 'win32', 'system', 'com', 'IDataObject')
    const thumbnailBase = join(output, 'com', 'windows', 'win32', 'ui', 'shell', 'IThumbnailProvider')
    const audioBase = join(output, 'com', 'windows', 'win32', 'media', 'audio', 'IAudioClient')
    const evaluationBase = join(output, 'com', 'unsafe', 'windows', 'win32', 'ai', 'machine-learning', 'win-ml', 'IWinMLEvaluationContextUnsafe')
    const runner = join(output, 'generated-companion-runner.cjs')
    writeFileSync(
      runner,
      [
        "'use strict'",
        "const assert = require('node:assert/strict')",
        "const { pathToFileURL } = require('node:url')",
        `const runtime = require(${JSON.stringify(join(packageRoot, 'dist', 'index.js'))})`,
        "const { DynComAudioFormat, DynComFormatEtc, DynComStgMedium } = require('@microsoft/dynwinrt/com')",
        "const { DynComRaw, DynComRawMemory, DynComRawOwnedComPointer, DynComRawPointer, WinGuid } = require('@microsoft/dynwinrt/com/unsafe/raw')",
        `const strategyRuntime = require(${JSON.stringify(join(output, 'com', 'unsafe', 'runtime.js'))})`,
        'const { UnsafePointee, UnsafePointerOutput, UnsafeHandleOutput, UnsafeInterfaceReplacement, UnsafeCountedBuffer, UnsafeRawCall, __prepareStrategy, __prepareWritableStorage, __prepareExactWritableSpan, __strategyArgument, __assertRawContract, __validateStrategySpans, __activateStrategies, __markDispatchEntered, __finishStrategy, __failStrategy, __releaseExtracted, __attachUnsafeOutputs, __testRunOwnedFinalizer, __testCreateOwnedPointer } = strategyRuntime',
        `const wbem = require(${JSON.stringify(`${wbemBase}.js`)})`,
        `const dataObject = require(${JSON.stringify(`${dataObjectBase}.js`)})`,
        `const thumbnail = require(${JSON.stringify(`${thumbnailBase}.js`)})`,
        `const audio = require(${JSON.stringify(`${audioBase}.js`)})`,
        `const evaluation = require(${JSON.stringify(`${evaluationBase}.js`)})`,
        `const safeBarrel = require(${JSON.stringify(join(output, 'com', 'index.js'))})`,
        `const cjsBarrel = require(${JSON.stringify(join(output, 'com', 'unsafe', 'index.js'))})`,
        'function finishTransaction(records) {',
        '  const extracted = []',
        '  try {',
        '    for (const record of records) { const value = __finishStrategy(record); extracted.push(value) }',
        '    return extracted',
        '  } catch (error) {',
        '    const unsafeOutputs = []',
        '    for (let index = records.length - 1; index >= 0; index--) { const output = __failStrategy(records[index]); if (output) unsafeOutputs.push(output) }',
        '    for (let index = extracted.length - 1; index >= 0; index--) { const output = __releaseExtracted(extracted[index]); if (output) unsafeOutputs.push(output) }',
        '    throw __attachUnsafeOutputs(error, unsafeOutputs)',
        '  }',
        '}',
        'async function main() {',
        `  const esmWbem = await import(pathToFileURL(${JSON.stringify(`${wbemBase}.js`)}).href)`,
        `  const esmDataObject = await import(pathToFileURL(${JSON.stringify(`${dataObjectBase}.js`)}).href)`,
        `  const esmThumbnail = await import(pathToFileURL(${JSON.stringify(`${thumbnailBase}.js`)}).href)`,
        `  const esmAudio = await import(pathToFileURL(${JSON.stringify(`${audioBase}.js`)}).href)`,
        `  const esmEvaluation = await import(pathToFileURL(${JSON.stringify(`${evaluationBase}.js`)}).href)`,
        `  const esmSafeBarrel = await import(pathToFileURL(${JSON.stringify(join(output, 'com', 'index.mjs'))}).href)`,
        `  const esmBarrel = await import(pathToFileURL(${JSON.stringify(join(output, 'com', 'unsafe', 'index.mjs'))}).href)`,
        "  assert.equal(typeof wbem.IWbemServices, 'function')",
        "  assert.equal(typeof dataObject.IDataObject, 'function')",
        "  assert.equal(typeof thumbnail.IThumbnailProvider, 'function')",
        "  assert.equal(typeof audio.IAudioClient, 'function')",
        "  assert.equal(typeof evaluation.IWinMLEvaluationContextUnsafe, 'function')",
        '  assert.equal(esmAudio.IAudioClient, audio.IAudioClient)',
        '  assert.equal(esmEvaluation.IWinMLEvaluationContextUnsafe, evaluation.IWinMLEvaluationContextUnsafe)',
        '  assert.equal(safeBarrel.IAudioClient, audio.IAudioClient)',
        '  assert.equal(safeBarrel.IWbemServices, wbem.IWbemServices)',
        '  assert.equal(safeBarrel.IDataObject, dataObject.IDataObject)',
        '  assert.equal(safeBarrel.IThumbnailProvider, thumbnail.IThumbnailProvider)',
        '  assert.equal(cjsBarrel.UnsafePointerOutput, UnsafePointerOutput)',
        '  assert.equal(esmWbem.IWbemServices, wbem.IWbemServices)',
        '  assert.equal(esmDataObject.IDataObject, dataObject.IDataObject)',
        '  assert.equal(esmThumbnail.IThumbnailProvider, thumbnail.IThumbnailProvider)',
        '  assert.equal(esmSafeBarrel.IWbemServices, wbem.IWbemServices)',
        '  assert.equal(esmBarrel.UnsafePointerOutput, UnsafePointerOutput)',
        '  const createFake = runtime.createGeneratedIwbemServicesFake',
        '  const readStats = runtime.generatedUnsafeComStats',
        '  const setConditionalMode = runtime.setGeneratedIwbemServicesConditionalMode',
        "  assert.equal(typeof createFake, 'function')",
        "  assert.equal(typeof readStats, 'function')",
        '  runtime.initializeCom(1)',
        '  let fake = createFake()',
        '  let wrapper',
        '  try {',
        '    assert.equal(readStats().currentRefCount, 1)',
        '    wrapper = wbem.IWbemServices._fromNative(fake)',
        '    assert.equal(readStats().currentRefCount, 2)',
        "    for (const invalidOptions of [null, undefined, {}, { mode: 'other' }, { mode: 0 }]) {",
        "      assert.throws(() => wrapper.openNamespace('root', invalidOptions), /options|mode/)",
        '      assert.equal(readStats().openNamespaceCalls, 0)',
        '    }',
        '    setConditionalMode(0)',
        '    const syncBefore = readStats()',
        "    const workingNamespace = wrapper.openNamespace('root', { mode: 'sync' })",
        '    assert.ok(workingNamespace)',
        '    assert.equal(readStats().openNamespaceWorkingSlotNull, true)',
        '    assert.equal(readStats().openNamespaceWorkingArgumentNull, false)',
        '    assert.equal(readStats().openNamespaceResultArgumentNull, true)',
        '    assert.equal(readStats().openNamespaceContextArgumentNull, true)',
        '    assert.equal(readStats().openNamespaceLastFlags, 0)',
        '    assert.equal(readStats().currentRefCount, syncBefore.currentRefCount + 1)',
        '    workingNamespace.release()',
        '    assert.equal(readStats().currentRefCount, syncBefore.currentRefCount)',
        '    setConditionalMode(1)',
        '    const asyncBefore = readStats()',
        "    const callResult = wrapper.openNamespace('root', { mode: 'semisync' })",
        '    assert.ok(callResult)',
        '    assert.equal(readStats().openNamespaceWorkingSlotNull, true)',
        '    assert.equal(readStats().openNamespaceWorkingArgumentNull, true)',
        '    assert.equal(readStats().openNamespaceResultSlotNull, true)',
        '    assert.equal(readStats().openNamespaceResultArgumentNull, false)',
        '    assert.equal(readStats().openNamespaceContextArgumentNull, true)',
        '    assert.equal(readStats().openNamespaceLastFlags, 0x10)',
        '    assert.equal(readStats().currentRefCount, asyncBefore.currentRefCount + 1)',
        '    callResult.release()',
        '    assert.equal(readStats().currentRefCount, asyncBefore.currentRefCount)',
        '    setConditionalMode(-1)',
        '    const failureBefore = readStats()',
        "    assert.throws(() => wrapper.openNamespace('root', { mode: 'sync' }), /native call failed|HRESULT|0x80004005/i)",
        '    assert.equal(readStats().currentRefCount, failureBefore.currentRefCount)',
        '    const resultFailureBefore = readStats()',
        "    assert.throws(() => wrapper.openNamespace('root', { mode: 'semisync' }), /native call failed|HRESULT|0x80004005/i)",
        '    assert.equal(readStats().currentRefCount, resultFailureBefore.currentRefCount)',
        '    assert.equal(readStats().openNamespaceCalls, 4)',
        '    setConditionalMode(0)',
        "    const object = wrapper.getObject('root', { mode: 'sync' })",
        '    object.release()',
        "    wrapper.putClass(fake, { mode: 'sync' })",
        "    wrapper.deleteClass('Class', { mode: 'sync' })",
        "    wrapper.putInstance(fake, { mode: 'sync' })",
        "    wrapper.deleteInstance('root', { mode: 'sync' })",
        "    const methodOutput = wrapper.execMethod('root', 'Method', fake, { mode: 'sync' })",
        '    methodOutput.release()',
        '    setConditionalMode(1)',
        "    for (const result of [wrapper.getObject('root', { mode: 'semisync' }), wrapper.putClass(fake, { mode: 'semisync' }), wrapper.deleteClass('Class', { mode: 'semisync' }), wrapper.putInstance(fake, { mode: 'semisync' }), wrapper.deleteInstance('root', { mode: 'semisync' }), wrapper.execMethod('root', 'Method', fake, { mode: 'semisync' })]) result.release()",
        '    setConditionalMode(-1)',
        '    const conditionalFailureBefore = readStats().currentRefCount',
        "    assert.throws(() => wrapper.getObject('root', { mode: 'sync' }), /native call failed|HRESULT|0x80004005/i)",
        "    assert.throws(() => wrapper.putClass(fake, { mode: 'semisync' }), /native call failed|HRESULT|0x80004005/i)",
        "    assert.throws(() => wrapper.execMethod('root', 'Method', fake, { mode: 'sync' }), /native call failed|HRESULT|0x80004005/i)",
        '    assert.equal(readStats().currentRefCount, conditionalFailureBefore)',
        '    assert.equal(readStats().getObjectCalls, 3)',
        '    assert.equal(readStats().putClassCalls, 3)',
        '    assert.equal(readStats().deleteClassCalls, 2)',
        '    assert.equal(readStats().putInstanceCalls, 2)',
        '    assert.equal(readStats().deleteInstanceCalls, 2)',
        '    assert.equal(readStats().execMethodCalls, 3)',
        '    wrapper.release()',
        '    assert.equal(readStats().currentRefCount, 1)',
        '    wrapper.release()',
        "    assert.throws(() => wrapper.openNamespace('root', { mode: 'sync' }), /released|apartment-bound/)",
        '    fake.release()',
        '    assert.equal(readStats().currentRefCount, 0)',
        '    wrapper = undefined',
        '    fake = undefined',
        '  } finally {',
        '    wrapper?.release()',
        '    fake?.release()',
        '  }',
        '  const createThumbnail = runtime.createGeneratedThumbnailProviderFake',
        '  const thumbnailStats = runtime.generatedThumbnailProviderStats',
        '  let thumbnailFake = createThumbnail()',
        '  let thumbnailWrapper',
        '  try {',
        '    assert.equal(thumbnailStats().currentRefCount, 1)',
        '    thumbnailWrapper = thumbnail.IThumbnailProvider._fromNative(thumbnailFake)',
        '    assert.equal(thumbnailStats().currentRefCount, 2)',
        '    const [bitmap, alphaType] = thumbnailWrapper.getThumbnail(96)',
        "    assert.equal(typeof bitmap.value, 'bigint')",
        '    assert.ok(bitmap.value > 0n)',
        '    assert.equal(alphaType, 2)',
        '    assert.equal(thumbnailStats().calls, 1)',
        '    bitmap.release()',
        '    assert.equal(bitmap.isReleased, true)',
        '    assert.throws(() => bitmap.value, /released/)',
        '    bitmap.release()',
        '    thumbnailWrapper.release()',
        '    assert.equal(thumbnailStats().currentRefCount, 1)',
        '    thumbnailFake.release()',
        '    assert.equal(thumbnailStats().currentRefCount, 0)',
        '    thumbnailWrapper = undefined',
        '    thumbnailFake = undefined',
        '  } finally {',
        '    thumbnailWrapper?.release()',
        '    thumbnailFake?.release()',
        '  }',
        '  const createDataObject = runtime.createGeneratedDataObjectFake',
        '  const dataObjectStats = runtime.generatedDataObjectStats',
        '  let dataObjectFake = createDataObject()',
        '  let dataObjectWrapper',
        '  try {',
        '    dataObjectWrapper = dataObject.IDataObject._fromNative(dataObjectFake)',
        '    assert.equal(dataObjectStats().currentRefCount, 2)',
        '    const format = DynComFormatEtc.hglobal(13)',
        '    const medium = dataObjectWrapper.getData(format)',
        '    assert.deepEqual(medium.toBuffer(), Buffer.from([1, 2, 3, 4]))',
        '    assert.equal(dataObjectStats().outputReleased, true)',
        '    const filled = dataObjectWrapper.getDataHere(format, DynComStgMedium.hglobal(Buffer.alloc(4)))',
        '    assert.deepEqual(filled.toBuffer(), Buffer.from([9, 8, 7, 6]))',
        '    assert.equal(dataObjectWrapper.queryGetData(format), 0)',
        '    const [canonicalResult, canonical] = dataObjectWrapper.getCanonicalFormatEtc(format)',
        '    assert.equal(canonicalResult, 0)',
        '    assert.equal(canonical.clipboardFormat, 13)',
        '    dataObjectWrapper.setData(format, DynComStgMedium.hglobal(Buffer.from([5, 6, 7, 8])))',
        '    assert.deepEqual(dataObjectStats(), { getDataCalls: 1, getDataHereCalls: 1, queryGetDataCalls: 1, canonicalCalls: 1, setDataCalls: 1, lastSetRelease: 0, outputReleased: true, getDataHereInputReleased: true, setDataInputReleased: true, currentRefCount: 2 })',
        '    dataObjectWrapper.release()',
        '    dataObjectFake.release()',
        '    assert.equal(dataObjectStats().currentRefCount, 0)',
        '    dataObjectWrapper = undefined',
        '    dataObjectFake = undefined',
        '  } finally {',
        '    dataObjectWrapper?.release()',
        '    dataObjectFake?.release()',
        '  }',
        '  const createSafeAudio = runtime.createGeneratedAudioClientFake',
        '  const safeAudioStats = runtime.generatedAudioClientStats',
        '  const setFormatSupportMode = runtime.setGeneratedAudioClientFormatSupportMode',
        '  const setSafeAudioServiceMode = runtime.setGeneratedAudioClientGetServiceMode',
        '  let safeAudioFake = createSafeAudio()',
        '  let safeAudioWrapper',
        '  try {',
        '    safeAudioWrapper = audio.IAudioClient._fromNative(safeAudioFake)',
        '    const pcm = DynComAudioFormat.pcm(2, 48000, 16)',
        '    safeAudioWrapper.initialize(0, 0, 0n, 0n, pcm, null)',
        '    setFormatSupportMode(0)',
        '    assert.deepEqual(safeAudioWrapper.isFormatSupported(0, pcm), [0, null])',
        '    setFormatSupportMode(1)',
        '    const [closestStatus, closestFormat] = safeAudioWrapper.isFormatSupported(0, pcm)',
        '    assert.equal(closestStatus, 1)',
        '    assert.equal(closestFormat.channels, 1)',
        '    assert.equal(closestFormat.samplesPerSecond, 44100)',
        "    assert.throws(() => safeAudioWrapper.isFormatSupported(1, pcm), /native call failed|HRESULT|0x88890008/i)",
        '    setFormatSupportMode(-1)',
        "    assert.throws(() => safeAudioWrapper.isFormatSupported(0, pcm), /native call failed|HRESULT|0x80004005/i)",
        '    const mix = safeAudioWrapper.getMixFormat()',
        '    assert.equal(mix.channels, 2)',
        '    assert.equal(mix.samplesPerSecond, 48000)',
        '    setSafeAudioServiceMode(0)',
        "    const service = safeAudioWrapper.getService('1cb9ad4c-dbfa-4c32-b178-c2f568a703b2')",
        '    service.release()',
        '    assert.equal(safeAudioStats().initializeCalls, 1)',
        '    assert.equal(safeAudioStats().isFormatSupportedCalls, 4)',
        '    assert.equal(safeAudioStats().getMixFormatCalls, 1)',
        '    assert.equal(safeAudioStats().getServiceCalls, 1)',
        '    assert.equal(safeAudioStats().currentRefCount, 2)',
        '    safeAudioWrapper.release()',
        '    safeAudioFake.release()',
        '    assert.equal(safeAudioStats().currentRefCount, 0)',
        '    safeAudioWrapper = undefined',
        '    safeAudioFake = undefined',
        '  } finally {',
        '    safeAudioWrapper?.release()',
        '    safeAudioFake?.release()',
        '  }',
        '  const createAudio = runtime.createGeneratedEvaluationContextFake',
        '  const audioStats = runtime.generatedEvaluationContextStats',
        '  const setServiceMode = runtime.setGeneratedEvaluationContextOutputMode',
        '  const createCleanupResource = runtime.createGeneratedNativeCleanupResource',
        "  assert.equal(typeof createAudio, 'function')",
        "  assert.equal(typeof createCleanupResource, 'function')",
        '  assert.throws(() => new UnsafePointee(), /factory methods/)',
        '  assert.throws(() => new UnsafePointerOutput(), /factory methods/)',
        '  assert.throws(() => new UnsafeHandleOutput(), /factory methods/)',
        '  assert.throws(() => new UnsafeInterfaceReplacement(), /factory methods/)',
        '  assert.throws(() => { strategyRuntime.__prepareStrategy = () => null }, TypeError)',
        '  assert.throws(() => { delete strategyRuntime.__prepareStrategy }, TypeError)',
        "  assert.throws(() => Object.defineProperty(strategyRuntime, '__prepareStrategy', { value: () => null }), TypeError)",
        '  let audioFake = createAudio()',
        '  let audioWrapper',
        '  try {',
        '    audioWrapper = evaluation.IWinMLEvaluationContextUnsafe.from(audioFake)',
        '    const format = DynComRawMemory.allocate(22, 2)',
        '    format.writeU16(0, 1)',
        "    const inPointeeContract = Object.freeze({ direction: 'in', nullable: false, pointeeLayouts: Object.freeze({ x64: null, i686: null, arm64: null }) })",
        "    const nullableInPointeeContract = Object.freeze({ direction: 'in', nullable: true, pointeeLayouts: Object.freeze({ x64: null, i686: null, arm64: null }) })",
        "    const knownWritablePointeeContract = Object.freeze({ direction: 'out', nullable: false, pointeeLayouts: Object.freeze({ x64: Object.freeze({ size: 8, alignment: 8 }), i686: Object.freeze({ size: 4, alignment: 4 }), arm64: Object.freeze({ size: 8, alignment: 8 }) }) })",
        "    const unknownWritablePointeeContract = Object.freeze({ direction: 'inout', nullable: false, pointeeLayouts: Object.freeze({ x64: null, i686: null, arm64: null }) })",
        "    const nullableWritablePointeeContract = Object.freeze({ direction: 'out', nullable: true, pointeeLayouts: Object.freeze({ x64: null, i686: null, arm64: null }) })",
        "    assert.throws(() => UnsafePointerOutput.comOwned({}), /WinGUID|convert|class/i)",
        "    assert.throws(() => UnsafePointerOutput.comOwned(new Proxy(evaluation.IWinMLEvaluationContextUnsafe.iid, {})), /WinGUID|convert|class/i)",
        '    const invalidReplacementOwner = DynComRawOwnedComPointer.addRef(audioFake)',
        "    assert.throws(() => UnsafeInterfaceReplacement.unchanged(invalidReplacementOwner, {}), /WinGUID|convert|class/i)",
        '    invalidReplacementOwner.release()',
        '    assert.equal(audioStats().getValueCalls, 0)',
        '    const hardened = UnsafePointerOutput.coTaskMem()',
        "    const opaqueRecord = __prepareStrategy(UnsafePointee.required(format), 'UnsafePointee', 'opaque', inPointeeContract)",
        '    assert.equal(Object.isFrozen(opaqueRecord), true)',
        '    assert.deepEqual(Object.keys(opaqueRecord), [])',
        '    assert.equal(opaqueRecord.state, undefined)',
        '    assert.throws(() => { opaqueRecord.state = {} }, TypeError)',
        "    assert.throws(() => __strategyArgument(Object.freeze({})), /not authentic/)",
        "    assert.throws(() => __activateStrategies([Object.freeze({})]), /not authentic/)",
        "    assert.throws(() => __finishStrategy(Object.freeze({})), /not authentic/)",
        "    assert.throws(() => __markDispatchEntered([opaqueRecord], { entered: true }), /DispatchState|convert|class/i)",
        '    assert.equal(Object.isFrozen(hardened), true)',
        "    assert.throws(() => { hardened._state = 'prepared' }, TypeError)",
        '    assert.throws(() => Object.setPrototypeOf(hardened, {}), TypeError)',
        '    assert.throws(() => { UnsafePointerOutput.prototype.prepare = () => null }, TypeError)',
        '    class ForgedOutput extends UnsafePointerOutput {}',
        '    assert.equal(Object.getPrototypeOf(ForgedOutput.coTaskMem()), UnsafePointerOutput.prototype)',
        '    assert.throws(() => audioWrapper.getValueByName(format, new Proxy(hardened, {})), /exact generated UnsafePointerOutput/)',
        '    assert.throws(() => audioWrapper.getValueByName(format, {}), /exact generated UnsafePointerOutput/)',
        '    assert.equal(audioStats().getValueCalls, 0)',
        '    assert.throws(() => audioWrapper.bindValue(UnsafePointee.required(DynComRawPointer.null())), /non-null/)',
        '    assert.throws(() => audioWrapper.bindValue(UnsafePointee.required(null)), /non-null/)',
        '    const releasedFormat = DynComRawMemory.allocate(22, 2)',
        '    releasedFormat.release()',
        '    assert.throws(() => audioWrapper.bindValue(UnsafePointee.required(releasedFormat)), /released/)',
        '    const releasedSlot = DynComRawMemory.allocate(DynComRaw.pointerSize(), DynComRaw.pointerSize())',
        '    const releasedOutput = UnsafePointerOutput.coTaskMem(releasedSlot)',
        '    releasedSlot.release()',
        '    assert.throws(() => audioWrapper.getValueByName(format, releasedOutput), /released/)',
        '    assert.throws(() => DynComRawMemory.fromUnsafeAddress(0n, 8, 1), /non-null/)',
        '    assert.equal(audioStats().getValueCalls, 0)',
        '    const spanBase = DynComRawMemory.allocate(DynComRaw.pointerSize() * 2, DynComRaw.pointerSize())',
        '    const spanA = DynComRawMemory.fromUnsafePointer(spanBase.pointer(), DynComRaw.pointerSize(), DynComRaw.pointerSize())',
        '    const spanB = DynComRawMemory.fromUnsafePointer(spanBase.pointer(Math.floor(DynComRaw.pointerSize() / 2)), DynComRaw.pointerSize(), 1)',
        "    const exactSpan = __prepareExactWritableSpan(spanA, 'exactSpan', false)",
        "    const duplicateExactSpan = __prepareExactWritableSpan(spanA, 'duplicateExactSpan', false)",
        '    assert.throws(() => __validateStrategySpans([exactSpan, duplicateExactSpan]), /overlap/)',
        "    const exactOutputSpan = __prepareStrategy(UnsafePointerOutput.rawResponsibility(spanA), 'UnsafePointerOutput', 'exactOutputSpan')",
        '    assert.throws(() => __validateStrategySpans([exactSpan, exactOutputSpan]), /overlap/)',
        '    __failStrategy(exactOutputSpan)',
        "    const exactHandleSpan = __prepareStrategy(UnsafeHandleOutput.rawResponsibility(spanA), 'UnsafeHandleOutput', 'exactHandleSpan')",
        '    assert.throws(() => __validateStrategySpans([exactSpan, exactHandleSpan]), /overlap/)',
        '    __failStrategy(exactHandleSpan)',
        "    const partialExactSpan = __prepareStrategy(UnsafeCountedBuffer.required(spanB), 'UnsafeCountedBuffer', 'partialExactSpan')",
        '    assert.throws(() => __validateStrategySpans([exactSpan, partialExactSpan]), /overlap/)',
        '    for (const [kind, factory] of [',
        "      ['UnsafePointerOutput', slot => UnsafePointerOutput.comOwned(evaluation.IWinMLEvaluationContextUnsafe.iid, slot)],",
        "      ['UnsafePointerOutput', slot => UnsafePointerOutput.coTaskMem(slot)],",
        "      ['UnsafePointerOutput', slot => UnsafePointerOutput.bstr(slot)],",
        "      ['UnsafePointerOutput', slot => UnsafePointerOutput.localAlloc(slot)],",
        "      ['UnsafePointerOutput', slot => UnsafePointerOutput.globalAlloc(slot)],",
        "      ['UnsafeHandleOutput', slot => UnsafeHandleOutput.rawResponsibility(slot)],",
        '    ]) {',
        "      const first = __prepareStrategy(factory(spanA), kind, 'first')",
        "      const second = __prepareStrategy(UnsafePointerOutput.rawResponsibility(spanA), 'UnsafePointerOutput', 'second')",
        '      assert.throws(() => __validateStrategySpans([first, second]), /overlap/)',
        '      __failStrategy(second)',
        '      __failStrategy(first)',
        '    }',
        "    assert.throws(() => __prepareStrategy(UnsafePointerOutput.bstr(spanB), 'UnsafePointerOutput', 'misaligned'), /pointer-aligned/)",
        "    const partialFirst = __prepareStrategy(UnsafePointerOutput.coTaskMem(spanA), 'UnsafePointerOutput', 'partialFirst')",
        "    const partialSecond = __prepareStrategy(UnsafeCountedBuffer.required(spanB), 'UnsafeCountedBuffer', 'partialSecond')",
        '    assert.throws(() => __validateStrategySpans([partialFirst, partialSecond]), /overlap/)',
        "    const countedRecord = __prepareStrategy(UnsafeCountedBuffer.required(spanBase), 'UnsafeCountedBuffer', 'countedSpan')",
        "    const countedOutput = __prepareStrategy(UnsafePointerOutput.rawResponsibility(spanA), 'UnsafePointerOutput', 'countedOutput')",
        '    assert.throws(() => __validateStrategySpans([countedRecord, countedOutput]), /overlap/)',
        '    __failStrategy(countedOutput)',
        "    const writablePointee = __prepareStrategy(UnsafePointee.required(spanA), 'UnsafePointee', 'writablePointee', knownWritablePointeeContract)",
        '    assert.throws(() => __validateStrategySpans([exactSpan, writablePointee]), /overlap/)',
        "    const writableOutput = __prepareStrategy(UnsafePointerOutput.rawResponsibility(spanA), 'UnsafePointerOutput', 'writableOutput')",
        '    assert.throws(() => __validateStrategySpans([writablePointee, writableOutput]), /overlap/)',
        '    __failStrategy(writableOutput)',
        "    const partialWritable = __prepareStrategy(UnsafePointee.required(spanB), 'UnsafePointee', 'partialWritable', unknownWritablePointeeContract)",
        "    const partialWritableOutput = __prepareStrategy(UnsafePointerOutput.rawResponsibility(spanA), 'UnsafePointerOutput', 'partialWritableOutput')",
        '    assert.throws(() => __validateStrategySpans([partialWritable, partialWritableOutput]), /overlap/)',
        '    __failStrategy(partialWritableOutput)',
        "    const otherWritable = __prepareStrategy(UnsafePointee.required(spanBase), 'UnsafePointee', 'otherWritable', unknownWritablePointeeContract)",
        '    assert.throws(() => __validateStrategySpans([partialWritable, otherWritable]), /overlap/)',
        "    const countSlot = __prepareWritableStorage(spanA, 'countSlot', Object.freeze({ direction: 'out', nullable: false, pointeeLayouts: Object.freeze({ x64: Object.freeze({ size: 4, alignment: 4 }), i686: Object.freeze({ size: 4, alignment: 4 }), arm64: Object.freeze({ size: 4, alignment: 4 }) }) }))",
        '    assert.throws(() => __validateStrategySpans([exactSpan, countSlot]), /overlap/)',
        '    assert.throws(() => __validateStrategySpans([otherWritable, countSlot]), /overlap/)',
        '    const undersizedPointee = DynComRawMemory.allocate(4, 4)',
        "    assert.throws(() => __prepareStrategy(UnsafePointee.required(undersizedPointee), 'UnsafePointee', 'undersizedPointee', knownWritablePointeeContract), /smaller/)",
        '    undersizedPointee.release()',
        "    assert.throws(() => __prepareStrategy(UnsafePointee.required(spanB), 'UnsafePointee', 'misalignedPointee', knownWritablePointeeContract), /alignment/)",
        '    const releasedPointee = DynComRawMemory.allocate(8, 8)',
        '    releasedPointee.release()',
        "    assert.throws(() => __prepareStrategy(UnsafePointee.required(releasedPointee), 'UnsafePointee', 'releasedPointee', knownWritablePointeeContract), /released/)",
        "    assert.throws(() => __prepareStrategy(UnsafePointee.required(spanA.pointer()), 'UnsafePointee', 'unboundedPointee', knownWritablePointeeContract), /bounded/)",
        "    assert.throws(() => __prepareStrategy(UnsafePointee.required(DynComRawPointer.null()), 'UnsafePointee', 'rawNullPointee', knownWritablePointeeContract), /non-null/)",
        "    assert.throws(() => __prepareStrategy(UnsafePointee.required(null), 'UnsafePointee', 'nullPointee', knownWritablePointeeContract), /non-null/)",
        "    assert.throws(() => __prepareStrategy(UnsafePointee.nullable(), 'UnsafePointee', 'requiredContractPointee', knownWritablePointeeContract), /non-null/)",
        "    assert.ok(__strategyArgument(__prepareStrategy(UnsafePointee.nullable(), 'UnsafePointee', 'nullableWritablePointee', nullableWritablePointeeContract)))",
        "    assert.ok(__strategyArgument(__prepareStrategy(UnsafePointee.nullable(DynComRawPointer.null()), 'UnsafePointee', 'nullableRawWritablePointee', nullableWritablePointeeContract)))",
        '    const replacementOwner = DynComRawOwnedComPointer.addRef(audioFake)',
        '    const replacementSlot = DynComRawMemory.fromUnsafePointer(spanBase.pointer(), DynComRaw.pointerSize(), 1)',
        "    const replacementRecord = __prepareStrategy(UnsafeInterfaceReplacement.unchanged(replacementOwner, evaluation.IWinMLEvaluationContextUnsafe.iid, replacementSlot), 'UnsafeInterfaceReplacement', 'replacementSpan')",
        '    assert.throws(() => __validateStrategySpans([exactSpan, replacementRecord]), /overlap/)',
        "    const replacementOutput = __prepareStrategy(UnsafePointerOutput.rawResponsibility(replacementSlot), 'UnsafePointerOutput', 'replacementOutput')",
        '    assert.throws(() => __validateStrategySpans([replacementRecord, replacementOutput]), /overlap/)',
        '    __failStrategy(replacementOutput)',
        '    __failStrategy(replacementRecord)',
        '    replacementOwner.release()',
        '    replacementSlot.release()',
        '    spanB.release()',
        '    spanA.release()',
        '    spanBase.release()',
        '    for (let failAt = 0; failAt < 3; failAt++) {',
        '      const finishSlots = [0, 1, 2].map(() => DynComRawMemory.allocate(DynComRaw.pointerSize(), DynComRaw.pointerSize()))',
        '      const finishStrategies = finishSlots.map(slot => UnsafePointerOutput.rawResponsibility(slot))',
        "      const finishRecords = finishStrategies.map((strategy, index) => __prepareStrategy(strategy, 'UnsafePointerOutput', `finish${index}`))",
        '      __validateStrategySpans(finishRecords)',
        '      __activateStrategies(finishRecords)',
        '      for (let index = 0; index < 3; index++) { if (index !== failAt) finishSlots[index].writePointer(0, DynComRawPointer.fromAddress(BigInt(0x100 + index))) }',
        '      let finishError',
        '      try { finishTransaction(finishRecords) } catch (error) { finishError = error }',
        '      assert.equal(finishError.unsafeOutputs.length, 3)',
        '      for (const slot of finishSlots) slot.release()',
        '    }',
        '    assert.equal(audioStats().getValueCalls, 0)',
        '    const closest = UnsafePointerOutput.coTaskMem()',
        '    setServiceMode(6)',
        '    const closestOwner = audioWrapper.getValueByName(format, closest)',
        '    assert.equal(audioStats().getValueCalls, 1)',
        '    const closestView = closestOwner.view(16, 4)',
        '    assert.equal(closestView.readU32(0), 0xaabbccdd)',
        '    closestView.release()',
        '    assert.equal(__testRunOwnedFinalizer(closestOwner), true)',
        '    assert.equal(__testRunOwnedFinalizer(closestOwner), true)',
        '    assert.throws(() => closestOwner.view(16, 4), /released/)',
        '    setServiceMode(-6)',
        '    assert.throws(() => audioWrapper.getValueByName(format, UnsafePointerOutput.coTaskMem()), /native call failed|HRESULT|0x80004005/i)',
        '    assert.equal(audioStats().getValueCalls, 2)',
        '    assert.throws(() => audioWrapper.getValueByName(format, closest), /finished/)',
        '    assert.equal(audioStats().getValueCalls, 2)',
        '    assert.throws(() => audioWrapper.getValueByName(format, UnsafePointee.required(format)), /UnsafePointerOutput/)',
        '    assert.equal(audioStats().getValueCalls, 2)',
        '    const iidStorage = DynComRawMemory.allocate(16, 4)',
        '    setServiceMode(1)',
        '    const beforeFailureRefs = audioStats().currentRefCount',
        '    assert.throws(() => audioWrapper.getValueByName(iidStorage, UnsafePointerOutput.comOwned(evaluation.IWinMLEvaluationContextUnsafe.iid)), /native call failed|HRESULT|0x80004005/i)',
        '    assert.equal(audioStats().getValueCalls, 3)',
        '    assert.equal(audioStats().currentRefCount, beforeFailureRefs)',
        '    const rawFailure = UnsafePointerOutput.rawResponsibility()',
        '    let rawFailureError',
        '    try { audioWrapper.getValueByName(iidStorage, rawFailure) } catch (error) { rawFailureError = error }',
        '    assert.equal(rawFailureError.unsafeOutputs.length, 1)',
        '    const dirtyPointer = rawFailure.takeFailurePointer()',
        '    assert.equal(dirtyPointer.address, rawFailureError.unsafeOutputs[0].pointer.address)',
        '    assert.throws(() => rawFailure.takeFailurePointer(), /No raw failure pointer/)',
        '    DynComRawOwnedComPointer.assumeTransferred(dirtyPointer, evaluation.IWinMLEvaluationContextUnsafe.iid).release()',
        '    assert.equal(audioStats().currentRefCount, beforeFailureRefs)',
        '    setServiceMode(-2)',
        '    const nullFailure = UnsafePointerOutput.rawResponsibility()',
        '    let nullFailureError',
        '    try { audioWrapper.getValueByName(iidStorage, nullFailure) } catch (error) { nullFailureError = error }',
        '    assert.equal(nullFailureError.unsafeOutputs[0].pointer.isNull, true)',
        '    assert.equal(nullFailure.takeFailurePointer().isNull, true)',
        '    assert.throws(() => nullFailure.takeFailurePointer(), /No raw failure pointer/)',
        '    setServiceMode(0)',
        '    const managedService = audioWrapper.getValueByName(iidStorage, UnsafePointerOutput.comOwned(evaluation.IWinMLEvaluationContextUnsafe.iid))',
        '    assert.equal(audioStats().currentRefCount, beforeFailureRefs + 1)',
        '    managedService.release()',
        '    assert.equal(audioStats().currentRefCount, beforeFailureRefs)',
        "    const wrongIid = WinGuid.parse('aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee')",
        '    assert.throws(() => audioWrapper.getValueByName(iidStorage, UnsafePointerOutput.comOwned(wrongIid)), /interface|0x80004002/i)',
        '    assert.equal(audioStats().currentRefCount, beforeFailureRefs)',
        '    setServiceMode(2)',
        '    assert.throws(() => audioWrapper.getValueByName(iidStorage, UnsafePointerOutput.comOwned(evaluation.IWinMLEvaluationContextUnsafe.iid)), /Required pointer output was null/)',
        '    const nullable = audioWrapper.getValueByName(iidStorage, UnsafePointerOutput.comOwned(evaluation.IWinMLEvaluationContextUnsafe.iid, null, true))',
        '    assert.equal(nullable, null)',
        '    setServiceMode(3)',
        '    assert.equal(__testRunOwnedFinalizer(audioWrapper.getValueByName(iidStorage, UnsafePointerOutput.bstr())), true)',
        '    setServiceMode(-3)',
        '    assert.throws(() => audioWrapper.getValueByName(iidStorage, UnsafePointerOutput.bstr()), /native call failed|HRESULT|0x80004005/i)',
        '    setServiceMode(4)',
        '    assert.equal(__testRunOwnedFinalizer(audioWrapper.getValueByName(iidStorage, UnsafePointerOutput.localAlloc())), true)',
        '    setServiceMode(-4)',
        '    assert.throws(() => audioWrapper.getValueByName(iidStorage, UnsafePointerOutput.localAlloc()), /native call failed|HRESULT|0x80004005/i)',
        '    setServiceMode(5)',
        '    assert.equal(__testRunOwnedFinalizer(audioWrapper.getValueByName(iidStorage, UnsafePointerOutput.globalAlloc())), true)',
        '    setServiceMode(-5)',
        '    assert.throws(() => audioWrapper.getValueByName(iidStorage, UnsafePointerOutput.globalAlloc()), /native call failed|HRESULT|0x80004005/i)',
        '    setServiceMode(2)',
        '    assert.equal(audioWrapper.getValueByName(iidStorage, UnsafePointerOutput.borrowed(null, true)), null)',
        '    assert.equal(audioWrapper.getValueByName(iidStorage, UnsafePointerOutput.unclassified(null, true)), null)',
        '    assert.equal(audioWrapper.getValueByName(iidStorage, UnsafePointerOutput.rawResponsibility(null, true)), null)',
        '    const rawSlot = DynComRawMemory.allocate(DynComRaw.pointerSize(), DynComRaw.pointerSize())',
        '    const handle = UnsafeHandleOutput.rawResponsibility(rawSlot)',
        "    const handleRecord = __prepareStrategy(handle, 'UnsafeHandleOutput', 'handle')",
        '    __activateStrategies([handleRecord])',
        '    rawSlot.writePointer(0, DynComRawPointer.fromAddress(0x55n))',
        '    assert.equal(__finishStrategy(handleRecord).address, 0x55n)',
        "    assert.throws(() => __prepareStrategy(handle, 'UnsafeHandleOutput', 'handle'), /finished/)",
        '    rawSlot.release()',
        '    for (const factory of [UnsafeHandleOutput.borrowed, UnsafeHandleOutput.closeHandle, UnsafeHandleOutput.destroyIcon, UnsafeHandleOutput.deleteObject]) {',
        '      const nullableHandle = factory.call(UnsafeHandleOutput, null, true)',
        "      const nullableRecord = __prepareStrategy(nullableHandle, 'UnsafeHandleOutput', 'nullableHandle')",
        '      __activateStrategies([nullableRecord])',
        '      assert.equal(__finishStrategy(nullableRecord), null)',
        '    }',
        '    for (const [kind, factory] of [[1, UnsafeHandleOutput.closeHandle], [2, UnsafeHandleOutput.destroyIcon], [3, UnsafeHandleOutput.deleteObject]]) {',
        '      const nativeSlot = DynComRawMemory.allocate(DynComRaw.pointerSize(), DynComRaw.pointerSize())',
        '      const nativeStrategy = factory.call(UnsafeHandleOutput, nativeSlot)',
        "      const nativeRecord = __prepareStrategy(nativeStrategy, 'UnsafeHandleOutput', 'nativeHandle')",
        '      __activateStrategies([nativeRecord])',
        '      nativeSlot.writePointer(0, DynComRawPointer.fromAddress(createCleanupResource(kind)))',
        '      const nativeOwner = __finishStrategy(nativeRecord)',
        '      assert.equal(__testRunOwnedFinalizer(nativeOwner), true)',
        '      assert.equal(__testRunOwnedFinalizer(nativeOwner), true)',
        '      nativeSlot.release()',
        '    }',
        '    const owner = DynComRawOwnedComPointer.addRef(audioFake)',
        '    const unchanged = UnsafeInterfaceReplacement.unchanged(owner, evaluation.IWinMLEvaluationContextUnsafe.iid)',
        "    const unchangedRecord = __prepareStrategy(unchanged, 'UnsafeInterfaceReplacement', 'unchanged')",
        '    __activateStrategies([unchangedRecord])',
        '    const unchangedResult = __finishStrategy(unchangedRecord)',
        '    assert.equal(unchangedResult.previous, owner)',
        '    assert.equal(unchangedResult.current, owner)',
        '    unchangedResult.release()',
        "    assert.throws(() => __prepareStrategy(unchanged, 'UnsafeInterfaceReplacement', 'unchanged'), /finished/)",
        '    const preservesOwner = DynComRawOwnedComPointer.addRef(audioFake)',
        '    const preserves = UnsafeInterfaceReplacement.preservesOld(preservesOwner, evaluation.IWinMLEvaluationContextUnsafe.iid)',
        "    const preservesRecord = __prepareStrategy(preserves, 'UnsafeInterfaceReplacement', 'preserves')",
        '    __activateStrategies([preservesRecord])',
        '    const preservesResult = __finishStrategy(preservesRecord)',
        '    assert.equal(preservesResult.previous, preservesOwner)',
        '    assert.equal(preservesResult.current, preservesOwner)',
        '    preservesResult.release()',
        '    const reentrantOwner = DynComRawOwnedComPointer.addRef(audioFake)',
        '    const reentrant = UnsafeInterfaceReplacement.preservesOld(reentrantOwner, evaluation.IWinMLEvaluationContextUnsafe.iid)',
        "    const reentrantRecord = __prepareStrategy(reentrant, 'UnsafeInterfaceReplacement', 'reentrant')",
        '    __activateStrategies([reentrantRecord])',
        '    reentrantOwner.release()',
        '    const reentrantResult = __finishStrategy(reentrantRecord)',
        '    assert.notEqual(reentrantResult.previous, reentrantOwner)',
        '    assert.equal(reentrantResult.previous.released, false)',
        '    assert.equal(reentrantResult.current, reentrantResult.previous)',
        '    reentrantResult.release()',
        '    const consumesOwner = DynComRawOwnedComPointer.addRef(audioFake)',
        '    const consumes = UnsafeInterfaceReplacement.consumesOld(consumesOwner, evaluation.IWinMLEvaluationContextUnsafe.iid)',
        "    const consumesRecord = __prepareStrategy(consumes, 'UnsafeInterfaceReplacement', 'consumes')",
        '    __activateStrategies([consumesRecord])',
        '    const consumesResult = __finishStrategy(consumesRecord)',
        '    assert.equal(consumesResult.previous, null)',
        '    assert.ok(consumesResult.current)',
        '    consumesResult.release()',
        '    const preDispatchOwner = DynComRawOwnedComPointer.addRef(audioFake)',
        '    const preDispatchReplacement = UnsafeInterfaceReplacement.consumesOld(preDispatchOwner, evaluation.IWinMLEvaluationContextUnsafe.iid)',
        "    const preDispatchRecord = __prepareStrategy(preDispatchReplacement, 'UnsafeInterfaceReplacement', 'preDispatch')",
        '    __activateStrategies([preDispatchRecord])',
        '    __markDispatchEntered([preDispatchRecord], DynComRaw.__createDispatchState())',
        '    __failStrategy(preDispatchRecord)',
        "    const preDispatchRetry = __prepareStrategy(preDispatchReplacement, 'UnsafeInterfaceReplacement', 'preDispatchRetry')",
        '    __activateStrategies([preDispatchRetry])',
        '    const preDispatchResult = __finishStrategy(preDispatchRetry)',
        '    preDispatchResult.release()',
        "    const replacementFactories = [UnsafeInterfaceReplacement.consumesOld, UnsafeInterfaceReplacement.preservesOld, UnsafeInterfaceReplacement.unchanged]",
        '    const aliasCallCount = audioStats().getValueCalls',
        '    for (let first = 0; first < replacementFactories.length; first++) {',
        '      for (let second = first; second < replacementFactories.length; second++) {',
        '        const sharedOwner = DynComRawOwnedComPointer.addRef(audioFake)',
        '        const slots = [0, 1].map(() => DynComRawMemory.allocate(DynComRaw.pointerSize(), DynComRaw.pointerSize()))',
        "        const records = [first, second].map((mode, index) => __prepareStrategy(replacementFactories[mode](sharedOwner, evaluation.IWinMLEvaluationContextUnsafe.iid, slots[index]), 'UnsafeInterfaceReplacement', `pair${first}${second}${index}`))",
        '        assert.throws(() => __validateStrategySpans(records), /owner is used by multiple/)',
        '        assert.ok(sharedOwner.address > 0n)',
        '        sharedOwner.release()',
        '        for (const slot of slots) slot.release()',
        '      }',
        '    }',
        '    for (let first = 0; first < replacementFactories.length; first++) {',
        '      for (let second = first; second < replacementFactories.length; second++) {',
        '        for (let third = second; third < replacementFactories.length; third++) {',
        '          const sharedOwner = DynComRawOwnedComPointer.addRef(audioFake)',
        '          const slots = [0, 1, 2].map(() => DynComRawMemory.allocate(DynComRaw.pointerSize(), DynComRaw.pointerSize()))',
        "          const records = [first, second, third].map((mode, index) => __prepareStrategy(replacementFactories[mode](sharedOwner, evaluation.IWinMLEvaluationContextUnsafe.iid, slots[index]), 'UnsafeInterfaceReplacement', `triple${first}${second}${third}${index}`))",
        '          assert.throws(() => __validateStrategySpans(records), /owner is used by multiple/)',
        '          assert.ok(sharedOwner.address > 0n)',
        '          sharedOwner.release()',
        '          for (const slot of slots) slot.release()',
        '        }',
        '      }',
        '    }',
        '    const independentOwners = [0, 1, 2].map(() => DynComRawOwnedComPointer.addRef(audioFake))',
        '    const independentSlots = [0, 1, 2].map(() => DynComRawMemory.allocate(DynComRaw.pointerSize(), DynComRaw.pointerSize()))',
        "    const independentRecords = replacementFactories.map((factory, index) => __prepareStrategy(factory(independentOwners[index], evaluation.IWinMLEvaluationContextUnsafe.iid, independentSlots[index]), 'UnsafeInterfaceReplacement', `independent${index}`))",
        '    __validateStrategySpans(independentRecords)',
        '    __activateStrategies(independentRecords)',
        '    const independentResults = independentRecords.map(record => __finishStrategy(record))',
        '    for (const result of independentResults) result.release()',
        '    for (const slot of independentSlots) slot.release()',
        '    assert.equal(audioStats().getValueCalls, aliasCallCount)',
        '    const rollbackOwnerA = DynComRawOwnedComPointer.addRef(audioFake)',
        '    const rollbackOwnerB = DynComRawOwnedComPointer.addRef(audioFake)',
        '    const rollbackSlotA = DynComRawMemory.allocate(DynComRaw.pointerSize(), DynComRaw.pointerSize())',
        '    const rollbackSlotB = DynComRawMemory.allocate(DynComRaw.pointerSize(), DynComRaw.pointerSize())',
        '    const rollbackA = UnsafeInterfaceReplacement.consumesOld(rollbackOwnerA, evaluation.IWinMLEvaluationContextUnsafe.iid, rollbackSlotA)',
        '    const rollbackB = UnsafeInterfaceReplacement.consumesOld(rollbackOwnerB, evaluation.IWinMLEvaluationContextUnsafe.iid, rollbackSlotB)',
        "    const rollbackRecordA = __prepareStrategy(rollbackA, 'UnsafeInterfaceReplacement', 'rollbackA')",
        "    const rollbackRecordB = __prepareStrategy(rollbackB, 'UnsafeInterfaceReplacement', 'rollbackB')",
        '    __validateStrategySpans([rollbackRecordA, rollbackRecordB])',
        '    rollbackSlotB.release()',
        '    assert.throws(() => __activateStrategies([rollbackRecordA, rollbackRecordB]), /released/)',
        "    const rollbackRetry = __prepareStrategy(rollbackA, 'UnsafeInterfaceReplacement', 'rollbackRetry')",
        '    __activateStrategies([rollbackRetry])',
        '    const rollbackResult = __finishStrategy(rollbackRetry)',
        '    rollbackResult.release()',
        '    rollbackOwnerB.release()',
        '    rollbackSlotA.release()',
        "    assert.ok(__strategyArgument(__prepareStrategy(UnsafeCountedBuffer.required(format), 'UnsafeCountedBuffer', 'counted')))",
        "    assert.ok(__strategyArgument(__prepareStrategy(UnsafeCountedBuffer.nullable(), 'UnsafeCountedBuffer', 'nullableCounted')))",
        "    assert.ok(__strategyArgument(__prepareStrategy(UnsafePointee.nullable(), 'UnsafePointee', 'nullablePointee', nullableInPointeeContract)))",
        "    assert.throws(() => __prepareStrategy(UnsafePointee.required(null), 'UnsafePointee', 'requiredPointee', inPointeeContract), /non-null/)",
        "    assert.ok(__strategyArgument(__prepareStrategy(UnsafeRawCall.value(format), 'UnsafeRawCall', 'raw')))",
        '    __assertRawContract(UnsafeRawCall.acknowledge())',
        '    assert.throws(() => __assertRawContract(UnsafeRawCall.value(format)), /acknowledge/)',
        '    let retryCleanupCalls = 0',
        "    const retryOwner = __testCreateOwnedPointer(() => { retryCleanupCalls++; if (retryCleanupCalls === 1) throw new Error('retry cleanup') })",
        '    assert.throws(() => retryOwner.release(), /retry cleanup/)',
        '    assert.equal(retryOwner.released, false)',
        '    retryOwner.release()',
        '    assert.equal(retryCleanupCalls, 2)',
        '    __testRunOwnedFinalizer(retryOwner)',
        '    assert.equal(retryCleanupCalls, 2)',
        '    let abandonedCleanupCalls = 0',
        '    const abandonedOwner = __testCreateOwnedPointer(() => { abandonedCleanupCalls++ })',
        '    __testRunOwnedFinalizer(abandonedOwner)',
        '    __testRunOwnedFinalizer(abandonedOwner)',
        '    assert.equal(abandonedCleanupCalls, 1)',
        '    let failedFinalizerCalls = 0',
        "    const failedFinalizerOwner = __testCreateOwnedPointer(() => { failedFinalizerCalls++; throw new Error('finalizer cleanup') })",
        '    assert.equal(__testRunOwnedFinalizer(failedFinalizerOwner), false)',
        '    assert.equal(__testRunOwnedFinalizer(failedFinalizerOwner), false)',
        '    assert.equal(failedFinalizerCalls, 1)',
        '    assert.equal(failedFinalizerOwner.released, false)',
        '    iidStorage.release()',
        '    format.release()',
        '    audioWrapper.release()',
        '    audioFake.release()',
        '    audioWrapper = undefined',
        '    audioFake = undefined',
        '    assert.equal(audioStats().currentRefCount, 0)',
        '  } finally {',
        '    audioWrapper?.release()',
        '    audioFake?.release()',
        '  }',
        "  console.log('generated-unsafe-companion-ok')",
        '}',
        'main().catch(error => { console.error(error); process.exitCode = 1 })',
        '',
      ].join('\n'),
    )
    const execution = spawnSync(process.execPath, [runner], {
      cwd: output,
      encoding: 'utf8',
      windowsHide: true,
    })
    t.is(execution.status, 0, `${execution.stderr}\n${execution.stdout}`)
    t.regex(execution.stdout, /generated-unsafe-companion-ok/)

    const consumer = join(output, 'generated-consumer.ts')
    writeFileSync(
      consumer,
      [
        "import { IWbemServices } from './com/windows/win32/system/wmi/IWbemServices.js'",
        "import { IDataObject } from './com/windows/win32/system/com/IDataObject.js'",
        "import { IThumbnailProvider } from './com/windows/win32/ui/shell/IThumbnailProvider.js'",
        "import { IAudioClient } from './com/windows/win32/media/audio/IAudioClient.js'",
        "import { IWinMLEvaluationContextUnsafe } from './com/unsafe/windows/win32/ai/machine-learning/win-ml/IWinMLEvaluationContextUnsafe.js'",
        "import { IWbemServices as FromBarrel } from './com/index.js'",
        "import { UnsafePointee, UnsafePointerOutput } from './com/unsafe/runtime.js'",
        "import type { UnsafeOwnedPointer } from './com/unsafe/runtime.js'",
        "import type { DynComRawMemory, DynWinRtValue } from '@microsoft/dynwinrt/com/unsafe/raw'",
        "import { DynComAudioFormat, DynComFormatEtc, DynComStgMedium } from '@microsoft/dynwinrt/com'",
        'declare const native: DynWinRtValue',
        'declare const storage: DynComRawMemory',
        'declare const thumbnails: IThumbnailProvider',
        'declare const dataObjects: IDataObject',
        'const direct: IWbemServices = IWbemServices._fromNative(native)',
        'const barrel: FromBarrel = FromBarrel._fromNative(native)',
        "const namespaceOutput = direct.openNamespace('root', { mode: 'sync' })",
        'namespaceOutput.release()',
        "const resultOutput = direct.openNamespace('root', { mode: 'semisync' })",
        'resultOutput.release()',
        '// @ts-expect-error only exact registered modes are accepted',
        "direct.openNamespace('root', { mode: 'other' })",
        'thumbnails.getThumbnail(96)[0].release()',
        'const format = DynComFormatEtc.hglobal(13)',
        'dataObjects.getData(format).toBuffer()',
        'dataObjects.getDataHere(format, DynComStgMedium.hglobal(Buffer.alloc(4))).toBuffer()',
        'dataObjects.setData(format, DynComStgMedium.hglobal(Buffer.from([1])))',
        '// @ts-expect-error SetData ownership transfer is intentionally hidden',
        'dataObjects.setData(format, DynComStgMedium.hglobal(Buffer.from([1])), true)',
        'const audio = IAudioClient._fromNative(native)',
        'audio.isFormatSupported(0, DynComAudioFormat.pcm(2, 48_000, 16))',
        'const unsafeEvaluation = IWinMLEvaluationContextUnsafe.from(native)',
        '// @ts-expect-error strategy result types are invariant',
        'const wrongOutput: UnsafePointerOutput<string> = UnsafePointerOutput.coTaskMem()',
        'const ownedOutput: UnsafePointerOutput<UnsafeOwnedPointer | null> = UnsafePointerOutput.coTaskMem()',
        'void wrongOutput',
        'void ownedOutput',
        'unsafeEvaluation.bindValue(UnsafePointee.required(storage))',
        'unsafeEvaluation.getValueByName(storage, UnsafePointerOutput.coTaskMem())',
        'unsafeEvaluation.release()',
        'audio.release()',
        'barrel.release()',
        'direct.release()',
        '',
      ].join('\n'),
    )
    const tsc = spawnSync(
      process.execPath,
      [
        join(packageRoot, 'node_modules', 'typescript', 'bin', 'tsc'),
        '--noEmit',
        '--strict',
        '--module',
        'Node16',
        '--moduleResolution',
        'Node16',
        '--target',
        'ES2022',
        consumer,
      ],
      { cwd: packageRoot, encoding: 'utf8', windowsHide: true },
    )
    t.is(tsc.status, 0, `${tsc.stdout}\n${tsc.stderr}`)
  } finally {
    rmSync(output, { recursive: true, force: true })
    rmSync(externalLinkTarget, { recursive: true, force: true })
    rmSync(lock, { force: true })
    for (const residue of transactionResidues) rmSync(residue, { recursive: true, force: true })
  }
})
