[package]
name = "dynwinrt-py"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Python bindings for dynwinrt via PyO3"
repository = "https://github.com/microsoft/dynwinrt"
authors = ["Microsoft"]
[lib]
name = "dynwinrt_py"
crate-type = ["cdylib"]

[dependencies]
dynwinrt = { path = "../../crates/dynwinrt" }
pyo3 = "0.29.0"
pollster = "0.4.0"

[dependencies.windows]
version = ">=0.59, <=0.62"
features = [
    "ApplicationModel",
    "Foundation",
    "Win32_System_WindowsProgramming",
    "Win32_System_WinRT",
]
