// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

use dynwinrt_codegen::codegen::{com, win32};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

const MANIFEST: &str = ".dynwinrt-win32-manifest.json";
const VERSION: u32 = 2;
const HEADER: &str = "// Generated by dynwinrt-codegen (flat Win32)\n";

#[derive(Default, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct Manifest {
    version: u32,
    namespaces: BTreeMap<String, Namespace>,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct Namespace {
    exports: BTreeSet<String>,
    javascript_sha256: String,
    declarations_sha256: String,
    #[serde(default)]
    extra_files: BTreeMap<String, ExtraFile>,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct ExtraFile {
    sha256: String,
    exports: BTreeSet<String>,
}

fn extra_file_name(name: &str) -> bool {
    let stem = name
        .strip_suffix(".d.ts")
        .or_else(|| name.strip_suffix(".js"));
    stem.is_some_and(|stem| identifier(stem) && !matches!(stem, "Apis" | "index"))
}

fn valid_hash(hash: &str) -> bool {
    hash.len() == 64 && hash.bytes().all(|byte| byte.is_ascii_hexdigit())
}

fn namespace_directory(namespace: &str) -> Result<String, String> {
    if !namespace.starts_with("Windows.Win32.")
        || namespace.split('.').any(|part| !identifier(part))
    {
        return Err(format!("Invalid flat Win32 namespace `{namespace}`"));
    }
    // Use the existing namespace naming and Windows filename validation.
    let module = com::canonical_module_path(namespace, "Apis")?;
    module
        .strip_suffix("/Apis")
        .map(str::to_string)
        .ok_or_else(|| format!("Invalid flat Win32 module path `{module}`"))
}

fn identifier(value: &str) -> bool {
    let mut chars = value.chars();
    chars
        .next()
        .is_some_and(|first| first.is_ascii_alphabetic() || first == '_')
        && chars.all(|character| character.is_ascii_alphanumeric() || character == '_')
}

fn digest(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}

fn validate(manifest: &Manifest) -> Result<(), String> {
    if !matches!(manifest.version, 1 | VERSION) {
        return Err(format!(
            "Unsupported Win32 generation manifest version {}",
            manifest.version
        ));
    }
    let mut paths = BTreeSet::new();
    let mut aliases = BTreeSet::new();
    for (namespace, record) in &manifest.namespaces {
        let path = namespace_directory(namespace)?;
        if !paths.insert(com::windows_relative_path_key(&path)?)
            || !aliases.insert(namespace.replace('.', "_"))
        {
            return Err(format!("Conflicting flat Win32 namespace `{namespace}`"));
        }
        if record.exports.is_empty()
            || record.exports.iter().any(|name| !identifier(name))
            || [&record.javascript_sha256, &record.declarations_sha256]
                .iter()
                .any(|hash| !valid_hash(hash))
        {
            return Err(format!("Invalid Win32 generation record for `{namespace}`"));
        }
        let mut files = BTreeSet::new();
        let mut names = record.exports.clone();
        for (file, extra) in &record.extra_files {
            if manifest.version == 1
                || !extra_file_name(file)
                || !files.insert(com::windows_relative_path_key(file)?)
                || !valid_hash(&extra.sha256)
                || extra.exports.iter().any(|name| !identifier(name))
            {
                return Err(format!("Invalid Win32 extra file `{namespace}/{file}`"));
            }
            let companion = if let Some(stem) = file.strip_suffix(".d.ts") {
                if !extra.exports.is_empty() {
                    return Err(format!(
                        "Declaration file `{file}` cannot carry runtime exports"
                    ));
                }
                format!("{stem}.js")
            } else {
                format!(
                    "{}.d.ts",
                    file.strip_suffix(".js").expect("validated JavaScript file")
                )
            };
            if !record.extra_files.contains_key(&companion) {
                return Err(format!(
                    "Win32 extra file `{file}` has no paired module/declaration"
                ));
            }
            for name in &extra.exports {
                if !names.insert(name.clone()) {
                    return Err(format!(
                        "Conflicting Win32 namespace export `{namespace}.{name}`"
                    ));
                }
            }
        }
    }
    Ok(())
}

fn read_file(root: &Path, relative: &Path) -> Result<Option<Vec<u8>>, String> {
    let mut path = root.to_path_buf();
    for component in relative.components() {
        let std::path::Component::Normal(segment) = component else {
            return Err(format!("Unsafe Win32 output path {}", relative.display()));
        };
        path.push(segment);
        match fs::symlink_metadata(&path) {
            Ok(metadata) if super::is_link_or_reparse_point(&metadata) => {
                return Err(format!("Refusing linked Win32 output {}", path.display()));
            }
            Ok(_) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
            Err(error) => return Err(format!("Failed to inspect {}: {error}", path.display())),
        }
    }
    fs::read(&path)
        .map(Some)
        .map_err(|error| format!("Failed to read {}: {error}", path.display()))
}

fn read_manifest(output: &Path) -> Result<Option<Manifest>, String> {
    let Some(bytes) = read_file(output, &Path::new("win32").join(MANIFEST))? else {
        return Ok(None);
    };
    let manifest: Manifest = serde_json::from_slice(&bytes)
        .map_err(|error| format!("Invalid Win32 generation manifest: {error}"))?;
    validate(&manifest)?;
    for (namespace, record) in &manifest.namespaces {
        let directory = Path::new("win32").join(namespace_directory(namespace)?);
        for (file, expected) in [
            ("Apis.js", &record.javascript_sha256),
            ("Apis.d.ts", &record.declarations_sha256),
        ]
        .into_iter()
        .chain(
            record
                .extra_files
                .iter()
                .map(|(file, extra)| (file.as_str(), &extra.sha256)),
        ) {
            let path = directory.join(file);
            let bytes = read_file(output, &path)?
                .ok_or_else(|| format!("Win32 manifest references missing {}", path.display()))?;
            if digest(&bytes) != *expected {
                return Err(format!(
                    "Win32 generated file {} does not match its manifest",
                    path.display()
                ));
            }
        }
    }
    Ok(Some(manifest))
}

pub(super) fn namespace_paths(output: &Path) -> Result<BTreeSet<String>, String> {
    let Some(manifest) = read_manifest(output)? else {
        return Ok(BTreeSet::new());
    };
    manifest
        .namespaces
        .keys()
        .map(|namespace| namespace_directory(namespace))
        .collect()
}

fn runtime_import(import_name: &str, directory: &str) -> String {
    if import_name == "@microsoft/dynwinrt" {
        "@microsoft/dynwinrt/win32".into()
    } else if import_name.starts_with("./") || import_name.starts_with("../") {
        format!(
            "{}{}",
            "../".repeat(directory.split('/').count() + 1),
            import_name
        )
    } else {
        import_name.to_string()
    }
}

fn write_javascript(output: &Path, relative: &Path, content: &str) -> Result<(), String> {
    super::write_generated_javascript_file(output, &output.join(relative), content)
}

pub(super) fn generate(
    output: &Path,
    winmd: &str,
    namespaces: &BTreeSet<String>,
    import_name: &str,
    dry_run: bool,
) -> Result<(), String> {
    let existing = read_manifest(output)?;
    let root = output.join("win32");
    if existing.is_none()
        && root.exists()
        && fs::read_dir(&root)
            .map_err(|error| format!("Failed to inspect {}: {error}", root.display()))?
            .next()
            .transpose()
            .map_err(|error| format!("Failed to inspect {}: {error}", root.display()))?
            .is_some()
    {
        return Err(
            "Existing win32 output has no generation manifest; use a fresh output directory".into(),
        );
    }
    let mut manifest = existing.unwrap_or_else(|| Manifest {
        version: VERSION,
        namespaces: BTreeMap::new(),
    });
    manifest.version = VERSION;
    let mut generated = Vec::new();
    let mut stale_files = Vec::new();
    for namespace in namespaces {
        let directory = namespace_directory(namespace)?;
        let generated_namespace =
            win32::generate_namespace(winmd, namespace, &runtime_import(import_name, &directory))?;
        if generated_namespace.namespace != *namespace {
            return Err(format!("Win32 projection changed namespace `{namespace}`"));
        }
        let exports = generated_namespace
            .exports
            .iter()
            .cloned()
            .collect::<BTreeSet<_>>();
        if exports.len() != generated_namespace.exports.len() {
            return Err(format!("Duplicate Win32 exports in `{namespace}`"));
        }
        for omitted in &generated_namespace.omissions {
            eprintln!(
                "warning: omitting flat Win32 export `{namespace}::{}`: {}",
                omitted.name, omitted.reason
            );
        }
        let mut extra_files = BTreeMap::new();
        for (name, content) in &generated_namespace.extra_files {
            if !extra_file_name(name) {
                return Err(format!("Invalid projected Win32 file `{namespace}/{name}`"));
            }
            let exports = if name.ends_with(".js") {
                super::collect_com_cjs_exports(content)
            } else {
                BTreeSet::new()
            };
            if extra_files
                .insert(
                    name.clone(),
                    ExtraFile {
                        sha256: digest(content.as_bytes()),
                        exports,
                    },
                )
                .is_some()
            {
                return Err(format!(
                    "Duplicate projected Win32 file `{namespace}/{name}`"
                ));
            }
        }
        if let Some(previous) = manifest.namespaces.get(namespace) {
            for file in previous
                .extra_files
                .keys()
                .filter(|file| !extra_files.contains_key(*file))
            {
                stale_files.push(Path::new("win32").join(&directory).join(file));
            }
        }
        manifest.namespaces.insert(
            namespace.clone(),
            Namespace {
                exports,
                javascript_sha256: digest(generated_namespace.js.as_bytes()),
                declarations_sha256: digest(generated_namespace.dts.as_bytes()),
                extra_files,
            },
        );
        generated.push((directory, generated_namespace));
    }
    validate(&manifest)?;
    if dry_run {
        for (_, generated) in generated {
            println!(
                "Would generate flat Win32 {}.Apis ({} exports, {} omitted)",
                generated.namespace,
                generated.exports.len(),
                generated.omissions.len()
            );
        }
        return Ok(());
    }
    for (directory, generated) in generated {
        let relative = Path::new("win32").join(&directory);
        write_javascript(output, &relative.join("Apis.js"), &generated.js)?;
        write_javascript(output, &relative.join("Apis.d.ts"), &generated.dts)?;
        for (file, content) in generated.extra_files {
            write_javascript(output, &relative.join(file), &content)?;
        }
        println!(
            "Generated flat Win32 {}.Apis ({} exports, {} omitted)",
            generated.namespace,
            generated.exports.len(),
            generated.omissions.len()
        );
    }
    for relative in stale_files {
        let path = output.join(relative);
        super::ensure_safe_generated_destination(output, &path)?;
        fs::remove_file(&path).map_err(|error| {
            format!(
                "Failed to remove stale Win32 output {}: {error}",
                path.display()
            )
        })?;
    }
    write_indexes(output, &manifest)?;
    let path = root.join(MANIFEST);
    super::ensure_safe_generated_destination(output, &path)?;
    let content = serde_json::to_string_pretty(&manifest)
        .map_err(|error| format!("Failed to serialize Win32 generation manifest: {error}"))?;
    fs::write(&path, format!("{content}\n"))
        .map_err(|error| format!("Failed to write {}: {error}", path.display()))?;
    super::write_bindings_manifest(output)
}

fn write_indexes(output: &Path, manifest: &Manifest) -> Result<(), String> {
    let mut root_js = HEADER.to_string();
    let mut root_mjs = HEADER.to_string();
    let mut root_dts = HEADER.to_string();
    for (namespace, record) in &manifest.namespaces {
        let directory = namespace_directory(namespace)?;
        let relative = Path::new("win32").join(&directory);
        let mut js = HEADER.to_string();
        let mut mjs = HEADER.to_string();
        let mut dts = HEADER.to_string();
        let modules = std::iter::once(("Apis.js", &record.exports)).chain(
            record
                .extra_files
                .iter()
                .filter(|(name, _)| name.ends_with(".js"))
                .map(|(name, extra)| (name.as_str(), &extra.exports)),
        );
        for (index, (module, exports)) in modules.enumerate() {
            js.push_str(&format!("const _module{index} = require('./{module}');\n"));
            for name in exports {
                js.push_str(&format!(
                    "Object.defineProperty(exports, '{name}', {{ enumerable: true, get: () => _module{index}.{name} }});\n"
                ));
            }
            if !exports.is_empty() {
                mjs.push_str(&format!(
                    "export {{ {} }} from './{module}';\n",
                    exports.iter().cloned().collect::<Vec<_>>().join(", ")
                ));
            }
            dts.push_str(&format!("export * from './{module}';\n"));
        }
        for (file, content) in [("index.js", js), ("index.mjs", mjs), ("index.d.ts", dts)] {
            write_javascript(output, &relative.join(file), &content)?;
        }
        let alias = namespace.replace('.', "_");
        root_js.push_str(&format!(
            "Object.defineProperty(exports, '{alias}', {{ enumerable: true, get: () => require('./{directory}/index.js') }});\n"
        ));
        root_mjs.push_str(&format!(
            "export * as {alias} from './{directory}/index.mjs';\n"
        ));
        root_dts.push_str(&format!(
            "export * as {alias} from './{directory}/index.js';\n"
        ));
    }
    for (file, content) in [
        ("index.js", root_js),
        ("index.mjs", root_mjs),
        ("index.d.ts", root_dts),
    ] {
        write_javascript(output, &Path::new("win32").join(file), &content)?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn record() -> Namespace {
        Namespace {
            exports: BTreeSet::from(["regCloseKey".into()]),
            javascript_sha256: digest(b"js"),
            declarations_sha256: digest(b"dts"),
            extra_files: BTreeMap::new(),
        }
    }

    #[test]
    fn win32_paths_use_main_namespace_layout() {
        assert_eq!(
            namespace_directory("Windows.Win32.System.SystemInformation").unwrap(),
            "windows/win32/system/system-information"
        );
        assert!(namespace_directory("Windows.Win32...escape").is_err());
        assert!(namespace_directory("Windows.Win32.System/escape").is_err());
        assert_eq!(
            runtime_import("./runtime.js", "windows/win32/system/registry"),
            "../../../../.././runtime.js"
        );
    }

    #[test]
    fn win32_output_manifest_rejects_invalid_and_colliding_records() {
        let mut manifest = Manifest {
            version: VERSION,
            namespaces: BTreeMap::from([("Windows.Win32.System.Registry".into(), record())]),
        };
        validate(&manifest).unwrap();
        manifest
            .namespaces
            .insert("Windows.Win32.System.REGISTRY".into(), record());
        assert!(validate(&manifest).is_err());
        manifest.namespaces.remove("Windows.Win32.System.REGISTRY");
        manifest.namespaces.values_mut().next().unwrap().exports = BTreeSet::from(["bad);".into()]);
        assert!(validate(&manifest).is_err());
        assert!(
            serde_json::from_str::<Manifest>(r#"{"version":1,"namespaces":{},"unexpected":true}"#)
                .is_err()
        );
    }
}
