// Generated by dynwinrt-codegen — do not edit
import { DynCom, DynComMethodSig, DynWinRtValue, WinGuid } from '@microsoft/dynwinrt';

function _handleArg(h) {
    if (typeof h === 'bigint' || typeof h === 'number') return h;
    if (h instanceof Uint8Array) {
        const _dv = new DataView(h.buffer, h.byteOffset, h.byteLength);
        if (h.byteLength >= 8) return _dv.getBigUint64(0, true);
        if (h.byteLength >= 4) return BigInt(_dv.getUint32(0, true));
        throw new TypeError('handle Buffer must be at least 4 bytes');
    }
    throw new TypeError(`handle must be a bigint, number, or Buffer, got ${typeof h}`);
}

export const IID_IDataTransferManagerInterop = WinGuid.parse('3a3dcd6c-3eab-43dc-bcde-45671ce800c8');
const IID_DataTransferManager_default = WinGuid.parse('a5caee9b-8708-49d1-8d36-67d25a8da00c');

let _IDataTransferManagerInteropCache;
const _IDataTransferManagerInterop = new Proxy({}, {
    get(_target, prop) {
        _IDataTransferManagerInteropCache ??= DynCom.registerIUnknownInterface('Windows.Win32.UI.Shell.IDataTransferManagerInterop', IID_IDataTransferManagerInterop)
            .addMethod('GetForWindow', new DynComMethodSig().addIn(DynCom.pointerType()).addIn(DynCom.pointerType()).addOut(DynCom.pointerType()))
            .addMethod('ShowShareUIForWindow', new DynComMethodSig().addIn(DynCom.pointerType()));
        const value = _IDataTransferManagerInteropCache[prop];
        return typeof value === 'function' ? value.bind(_IDataTransferManagerInteropCache) : value;
    },
});

export class IDataTransferManagerInterop {
    _obj;
    constructor(obj) { this._obj = obj; }
    static _fromNative(obj) { return new IDataTransferManagerInterop(obj); }
    /** Create a new `IDataTransferManagerInterop` by activating the `Windows.ApplicationModel.DataTransfer.DataTransferManager` factory and QI'ing to the interop. */
    static create() {
        const factory = DynWinRtValue.activationFactory('Windows.ApplicationModel.DataTransfer.DataTransferManager');
        const _obj = factory.cast(IID_IDataTransferManagerInterop);
        return new IDataTransferManagerInterop(_obj);
    }
    getForWindow(appWindow) {
        const _raw = _IDataTransferManagerInterop.method(3).invoke(this._obj, [DynCom.pointer(_handleArg(appWindow)), DynCom.iidPointer(IID_DataTransferManager_default)]);
        const _out = DynCom.adoptComPointer(_raw, IID_DataTransferManager_default);
        return _out;
    }
    showShareUIForWindow(appWindow) {
        _IDataTransferManagerInterop.method(4).invoke(this._obj, [DynCom.pointer(_handleArg(appWindow))]);
    }
}
