// Generated by dynwinrt-codegen — do not edit
import type { DynWinRtValue } from '@microsoft/dynwinrt';

/** Opaque Win32 handle. Pass a raw pointer value as a `bigint` (full 64-bit) or `number` (safe integer), or an Electron/Node `Buffer`/`Uint8Array` of the handle's pointer bits — e.g. `BrowserWindow.getNativeWindowHandle()` — which is read as the handle VALUE. */
export type HWND = bigint | number | Buffer | Uint8Array;

export declare const IID_IDataTransferManagerInterop: unknown;

export declare class IDataTransferManagerInterop {
    /** Activate the projected WinRT class and QI to the interop. */
    static create(): IDataTransferManagerInterop;
    /** Wrap an existing native COM pointer (for QueryInterface bridging). */
    static _fromNative(obj: unknown): IDataTransferManagerInterop;
    getForWindow(appWindow: HWND): DynWinRtValue;
    showShareUIForWindow(appWindow: HWND): void;
}
