// Generated by dynwinrt-codegen — do not edit
import type { DynWinRtValue } from '@microsoft/dynwinrt';

/** Opaque Win32 handle or pointer newtype (e.g. HWND, PWSTR). Accepts either a raw pointer as `bigint` or a `Buffer`. */
export type HWND = bigint | Buffer;

export declare const IID_IDataTransferManagerInterop: unknown;

export declare class IDataTransferManagerInterop {
    /** Activate the projected WinRT class and QI to the interop. */
    static create(): IDataTransferManagerInterop;
    /** Wrap an existing native COM pointer (for QueryInterface bridging). */
    static _fromNative(obj: unknown): IDataTransferManagerInterop;
    getForWindow(appWindow: HWND): DynWinRtValue;
    showShareUIForWindow(appWindow: HWND): void;
}
