// Generated by dynwinrt-codegen — do not edit
const { DynCom, DynComMethodSig, WinGuid } = require('@microsoft/dynwinrt/com/unsafe');
const { TBPFLAG } = require('./TBPFLAG.js');
const { STPFLAG } = require('./STPFLAG.js');

const _nativeLayout_RECT = '{"name":"Windows.Win32.Foundation.RECT","x86":{"size":16,"alignment":4,"fields":[{"name":"left","offset":0,"count":1,"type":{"kind":"i32"}},{"name":"top","offset":4,"count":1,"type":{"kind":"i32"}},{"name":"right","offset":8,"count":1,"type":{"kind":"i32"}},{"name":"bottom","offset":12,"count":1,"type":{"kind":"i32"}}]},"x64":{"size":16,"alignment":4,"fields":[{"name":"left","offset":0,"count":1,"type":{"kind":"i32"}},{"name":"top","offset":4,"count":1,"type":{"kind":"i32"}},{"name":"right","offset":8,"count":1,"type":{"kind":"i32"}},{"name":"bottom","offset":12,"count":1,"type":{"kind":"i32"}}]},"arm64":{"size":16,"alignment":4,"fields":[{"name":"left","offset":0,"count":1,"type":{"kind":"i32"}},{"name":"top","offset":4,"count":1,"type":{"kind":"i32"}},{"name":"right","offset":8,"count":1,"type":{"kind":"i32"}},{"name":"bottom","offset":12,"count":1,"type":{"kind":"i32"}}]}}';
function createRECT(bytes) { return DynCom.createNativeStruct(_nativeLayout_RECT, bytes); }
const _nativeLayout_THUMBBUTTON = '{"name":"Windows.Win32.UI.Shell.THUMBBUTTON","x86":{"size":540,"alignment":4,"fields":[{"name":"dwMask","offset":0,"count":1,"type":{"kind":"i32"}},{"name":"iId","offset":4,"count":1,"type":{"kind":"u32"}},{"name":"iBitmap","offset":8,"count":1,"type":{"kind":"u32"}},{"name":"hIcon","offset":12,"count":1,"type":{"kind":"pointer"}},{"name":"szTip","offset":16,"count":260,"type":{"kind":"u16"}},{"name":"dwFlags","offset":536,"count":1,"type":{"kind":"i32"}}]},"x64":{"size":552,"alignment":8,"fields":[{"name":"dwMask","offset":0,"count":1,"type":{"kind":"i32"}},{"name":"iId","offset":4,"count":1,"type":{"kind":"u32"}},{"name":"iBitmap","offset":8,"count":1,"type":{"kind":"u32"}},{"name":"hIcon","offset":16,"count":1,"type":{"kind":"pointer"}},{"name":"szTip","offset":24,"count":260,"type":{"kind":"u16"}},{"name":"dwFlags","offset":544,"count":1,"type":{"kind":"i32"}}]},"arm64":{"size":552,"alignment":8,"fields":[{"name":"dwMask","offset":0,"count":1,"type":{"kind":"i32"}},{"name":"iId","offset":4,"count":1,"type":{"kind":"u32"}},{"name":"iBitmap","offset":8,"count":1,"type":{"kind":"u32"}},{"name":"hIcon","offset":16,"count":1,"type":{"kind":"pointer"}},{"name":"szTip","offset":24,"count":260,"type":{"kind":"u16"}},{"name":"dwFlags","offset":544,"count":1,"type":{"kind":"i32"}}]}}';
function createTHUMBBUTTON(bytes) { return DynCom.createNativeStruct(_nativeLayout_THUMBBUTTON, bytes); }
function createTHUMBBUTTONArray(bytes) { return DynCom.createNativeStructArray(_nativeLayout_THUMBBUTTON, bytes); }

const IID_ITaskbarList4 = WinGuid.parse('c43dc798-95d1-4bea-9030-bb99e2983a1a');

let _ITaskbarList4Cache;
const _ITaskbarList4 = new Proxy({}, {
    get(_target, prop) {
        _ITaskbarList4Cache ??= DynCom.registerIUnknownInterface('Windows.Win32.UI.Shell.ITaskbarList4', IID_ITaskbarList4)
            .addMethodAt(3, 'HrInit', new DynComMethodSig())
            .addMethodAt(4, 'AddTab', new DynComMethodSig().addIn(DynCom.pointerType()))
            .addMethodAt(5, 'DeleteTab', new DynComMethodSig().addIn(DynCom.pointerType()))
            .addMethodAt(6, 'ActivateTab', new DynComMethodSig().addIn(DynCom.pointerType()))
            .addMethodAt(7, 'SetActiveAlt', new DynComMethodSig().addIn(DynCom.pointerType()))
            .addMethodAt(8, 'MarkFullscreenWindow', new DynComMethodSig().addIn(DynCom.pointerType()).addIn(DynCom.i32Type()))
            .addMethodAt(9, 'SetProgressValue', new DynComMethodSig().addIn(DynCom.pointerType()).addIn(DynCom.u64Type()).addIn(DynCom.u64Type()))
            .addMethodAt(10, 'SetProgressState', new DynComMethodSig().addIn(DynCom.pointerType()).addIn(DynCom.i32Type()))
            .addMethodAt(11, 'RegisterTab', new DynComMethodSig().addIn(DynCom.pointerType()).addIn(DynCom.pointerType()))
            .addMethodAt(12, 'UnregisterTab', new DynComMethodSig().addIn(DynCom.pointerType()))
            .addMethodAt(13, 'SetTabOrder', new DynComMethodSig().addIn(DynCom.pointerType()).addIn(DynCom.pointerType()))
            .addMethodAt(14, 'SetTabActive', new DynComMethodSig().addIn(DynCom.pointerType()).addIn(DynCom.pointerType()).addIn(DynCom.u32Type()))
            .addMethodAt(15, 'ThumbBarAddButtons', new DynComMethodSig().addIn(DynCom.pointerType()).addIn(DynCom.u32Type()).addInputBuffer(DynCom.nativeStructType(_nativeLayout_THUMBBUTTON), 1, undefined, false))
            .addMethodAt(16, 'ThumbBarUpdateButtons', new DynComMethodSig().addIn(DynCom.pointerType()).addIn(DynCom.u32Type()).addInputBuffer(DynCom.nativeStructType(_nativeLayout_THUMBBUTTON), 1, undefined, false))
            .addMethodAt(17, 'ThumbBarSetImageList', new DynComMethodSig().addIn(DynCom.pointerType()).addIn(DynCom.pointerType()))
            .addMethodAt(18, 'SetOverlayIcon', new DynComMethodSig().addIn(DynCom.pointerType()).addIn(DynCom.pointerType()).addIn(DynCom.pointerType()))
            .addMethodAt(19, 'SetThumbnailTooltip', new DynComMethodSig().addIn(DynCom.pointerType()).addIn(DynCom.pointerType()))
            .addMethodAt(20, 'SetThumbnailClip', new DynComMethodSig().addIn(DynCom.pointerType()).addIn(DynCom.nativeStructPointerType(_nativeLayout_RECT, true)))
            .addMethodAt(21, 'SetTabProperties', new DynComMethodSig().addIn(DynCom.pointerType()).addIn(DynCom.i32Type()));
        const value = _ITaskbarList4Cache[prop];
        return typeof value === 'function' ? value.bind(_ITaskbarList4Cache) : value;
    },
});

class ITaskbarList4 {
    static IID = IID_ITaskbarList4;
    _obj;
    constructor(obj) { this._obj = obj; }
    static _fromNative(obj) { return Object.assign(Object.create(ITaskbarList4.prototype), { _obj: obj }); }
    /** Release the underlying native COM reference. Safe to call more than once. */
    release() {
        this._obj.release();
    }
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist-hrinit} */
    hrInit() {
        _ITaskbarList4.method(3).invoke(this._obj, []);
    }
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist-addtab} */
    addTab(hwnd) {
        _ITaskbarList4.method(4).invoke(this._obj, [DynCom.pointer(DynCom.handleValue(hwnd))]);
    }
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist-deletetab} */
    deleteTab(hwnd) {
        _ITaskbarList4.method(5).invoke(this._obj, [DynCom.pointer(DynCom.handleValue(hwnd))]);
    }
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist-activatetab} */
    activateTab(hwnd) {
        _ITaskbarList4.method(6).invoke(this._obj, [DynCom.pointer(DynCom.handleValue(hwnd))]);
    }
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist-setactivealt} */
    setActiveAlt(hwnd) {
        _ITaskbarList4.method(7).invoke(this._obj, [DynCom.pointer(DynCom.handleValue(hwnd))]);
    }
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist2-markfullscreenwindow} */
    markFullscreenWindow(hwnd, fFullscreen) {
        _ITaskbarList4.method(8).invoke(this._obj, [DynCom.pointer(DynCom.handleValue(hwnd)), DynCom.i32(fFullscreen ? 1 : 0)]);
    }
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist3-setprogressvalue} */
    setProgressValue(hwnd, ullCompleted, ullTotal) {
        _ITaskbarList4.method(9).invoke(this._obj, [DynCom.pointer(DynCom.handleValue(hwnd)), DynCom.u64(BigInt(ullCompleted)), DynCom.u64(BigInt(ullTotal))]);
    }
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist3-setprogressstate} */
    setProgressState(hwnd, tbpFlags) {
        _ITaskbarList4.method(10).invoke(this._obj, [DynCom.pointer(DynCom.handleValue(hwnd)), DynCom.i32(tbpFlags)]);
    }
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist3-registertab} */
    registerTab(tab, mdi) {
        _ITaskbarList4.method(11).invoke(this._obj, [DynCom.pointer(DynCom.handleValue(tab)), DynCom.pointer(DynCom.handleValue(mdi))]);
    }
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist3-unregistertab} */
    unregisterTab(tab) {
        _ITaskbarList4.method(12).invoke(this._obj, [DynCom.pointer(DynCom.handleValue(tab))]);
    }
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist3-settaborder} */
    setTabOrder(tab, insertBefore) {
        _ITaskbarList4.method(13).invoke(this._obj, [DynCom.pointer(DynCom.handleValue(tab)), DynCom.pointer(DynCom.handleValue(insertBefore))]);
    }
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist3-settabactive} */
    setTabActive(tab, mdi, reserved) {
        _ITaskbarList4.method(14).invoke(this._obj, [DynCom.pointer(DynCom.handleValue(tab)), DynCom.pointer(DynCom.handleValue(mdi)), DynCom.u32(reserved)]);
    }
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist3-thumbbaraddbuttons} */
    thumbBarAddButtons(hwnd, pButton) {
        _ITaskbarList4.method(15).invoke(this._obj, [DynCom.pointer(DynCom.handleValue(hwnd)), DynCom.nativeStructBuffer(_nativeLayout_THUMBBUTTON, pButton)]);
    }
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist3-thumbbarupdatebuttons} */
    thumbBarUpdateButtons(hwnd, pButton) {
        _ITaskbarList4.method(16).invoke(this._obj, [DynCom.pointer(DynCom.handleValue(hwnd)), DynCom.nativeStructBuffer(_nativeLayout_THUMBBUTTON, pButton)]);
    }
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist3-thumbbarsetimagelist} */
    thumbBarSetImageList(hwnd, himl) {
        _ITaskbarList4.method(17).invoke(this._obj, [DynCom.pointer(DynCom.handleValue(hwnd)), DynCom.pointer(himl)]);
    }
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist3-setoverlayicon} */
    setOverlayIcon(hwnd, hIcon, description) {
        _ITaskbarList4.method(18).invoke(this._obj, [DynCom.pointer(DynCom.handleValue(hwnd)), DynCom.pointer(hIcon), DynCom.wideStringPointer(description)]);
    }
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist3-setthumbnailtooltip} */
    setThumbnailTooltip(hwnd, tip) {
        _ITaskbarList4.method(19).invoke(this._obj, [DynCom.pointer(DynCom.handleValue(hwnd)), DynCom.wideStringPointer(tip)]);
    }
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist3-setthumbnailclip} */
    setThumbnailClip(hwnd, prcClip) {
        _ITaskbarList4.method(20).invoke(this._obj, [DynCom.pointer(DynCom.handleValue(hwnd)), prcClip === null ? DynCom.nullNativeStructPointer() : DynCom.nativeStruct(_nativeLayout_RECT, prcClip)]);
    }
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist4-settabproperties} */
    setTabProperties(tab, stpFlags) {
        _ITaskbarList4.method(21).invoke(this._obj, [DynCom.pointer(DynCom.handleValue(tab)), DynCom.i32(stpFlags)]);
    }
}
exports.createRECT = createRECT;
exports.createTHUMBBUTTON = createTHUMBBUTTON;
exports.createTHUMBBUTTONArray = createTHUMBBUTTONArray;
exports.IID_ITaskbarList4 = IID_ITaskbarList4;
exports.ITaskbarList4 = ITaskbarList4;
