// Generated by dynwinrt-codegen — do not edit

/** Opaque Win32 handle value. Pass a raw pointer value as a `bigint` (full pointer width) or `number` (safe integer). */
export type HWND = bigint | number;

export declare const IID_ITaskbarList2: unknown;

export declare class ITaskbarList2 {
    static readonly IID: typeof IID_ITaskbarList2;
    protected constructor(obj: unknown);
    /** Wrap an existing native COM pointer (for QueryInterface bridging). */
    static _fromNative(obj: unknown): ITaskbarList2;
    /** Release the underlying native COM reference. Safe to call more than once. */
    release(): void;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist-hrinit} */
    hrInit(): void;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist-addtab} */
    addTab(hwnd: HWND | Buffer | Uint8Array): void;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist-deletetab} */
    deleteTab(hwnd: HWND | Buffer | Uint8Array): void;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist-activatetab} */
    activateTab(hwnd: HWND | Buffer | Uint8Array): void;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist-setactivealt} */
    setActiveAlt(hwnd: HWND | Buffer | Uint8Array): void;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist2-markfullscreenwindow} */
    markFullscreenWindow(hwnd: HWND | Buffer | Uint8Array, fFullscreen: boolean): void;
}
