# Generated by dynwinrt-codegen — do not edit
from __future__ import annotations
from functools import lru_cache
from importlib import import_module
from typing import TYPE_CHECKING
from dynwinrt_py import (
    DynWinRTType, DynWinRTMethodSig, DynWinRTValue, DynWinRTArray,
    DynWinRTStruct, DynWinRtDelegate, WinGUID,
)


@lru_cache(maxsize=None)
def _dynwinrt_symbol(module, name):
    return getattr(import_module(f'.{module}', __package__), name)


def _dynwinrt_wrap_values(module, name, values):
    wrapper = _dynwinrt_symbol(module, name)
    return [wrapper(value) for value in values]


def _dynwinrt_enum(module, name, value):
    enum_type = _dynwinrt_symbol(module, name)
    try:
        return enum_type(value)
    except ValueError:
        return value


def _dynwinrt_wait_action(value):
    value.wait()
    return None


if TYPE_CHECKING:
    from .i_www_form_url_decoder_entry import IID_IWwwFormUrlDecoderEntry, IWwwFormUrlDecoderEntry  # noqa: F401

IID_IIterator_IWwwFormUrlDecoderEntry = DynWinRTType.parameterized(WinGUID.parse('6a79e863-4300-459a-9966-cbb660963ee1'), [DynWinRTType.interface(WinGUID.parse('125e7431-f678-4e8e-b670-20a9b06c512d'))]).iid()

_IIterator_IWwwFormUrlDecoderEntry = DynWinRTType.register_interface(
    "IIterator_IWwwFormUrlDecoderEntry", IID_IIterator_IWwwFormUrlDecoderEntry) \
    .add_method("get_Current", DynWinRTMethodSig().add_out(DynWinRTType.interface(WinGUID.parse('125e7431-f678-4e8e-b670-20a9b06c512d')))) \
    .add_method("get_HasCurrent", DynWinRTMethodSig().add_out(DynWinRTType.bool_type())) \
    .add_method("MoveNext", DynWinRTMethodSig().add_out(DynWinRTType.bool_type())) \
    .add_method("GetMany", DynWinRTMethodSig().add_out_fill(DynWinRTType.array_type(DynWinRTType.interface(WinGUID.parse('125e7431-f678-4e8e-b670-20a9b06c512d')))).add_out(DynWinRTType.u32_type()))


class IIterator_IWwwFormUrlDecoderEntry:
    def __init__(self, obj: DynWinRTValue):
        self._obj = obj.cast(IID_IIterator_IWwwFormUrlDecoderEntry)

    @staticmethod
    def from_value(obj: DynWinRTValue) -> 'IIterator_IWwwFormUrlDecoderEntry':
        return IIterator_IWwwFormUrlDecoderEntry(obj.cast(IID_IIterator_IWwwFormUrlDecoderEntry))


    @property
    def current(self) -> 'IWwwFormUrlDecoderEntry':
        return _dynwinrt_symbol('i_www_form_url_decoder_entry', 'IWwwFormUrlDecoderEntry')(_IIterator_IWwwFormUrlDecoderEntry.method(6).invoke(self._obj, []))

    @property
    def has_current(self) -> bool:
        return _IIterator_IWwwFormUrlDecoderEntry.method(7).invoke(self._obj, []).to_bool()

    def move_next(self) -> bool:
        return _IIterator_IWwwFormUrlDecoderEntry.method(8).invoke(self._obj, []).to_bool()

    def get_many(self, items: 'DynWinRTArray') -> list['IWwwFormUrlDecoderEntry']:
        _results = _IIterator_IWwwFormUrlDecoderEntry.method(9).invoke_all(self._obj, [items.to_value()])
        return _dynwinrt_wrap_values('i_www_form_url_decoder_entry', 'IWwwFormUrlDecoderEntry', _results[0].as_array().to_values())[:_results[1].to_number()]
