# Generated by dynwinrt-codegen — do not edit
from __future__ import annotations
from functools import lru_cache
from importlib import import_module
from typing import TYPE_CHECKING
from dynwinrt_py import (
    DynWinRTType, DynWinRTMethodSig, DynWinRTValue, DynWinRTArray,
    DynWinRTStruct, DynWinRtDelegate, WinGUID,
)


@lru_cache(maxsize=None)
def _dynwinrt_symbol(module, name):
    return getattr(import_module(f'.{module}', __package__), name)


def _dynwinrt_wrap_values(module, name, values):
    wrapper = _dynwinrt_symbol(module, name)
    return [wrapper(value) for value in values]


def _dynwinrt_enum(module, name, value):
    enum_type = _dynwinrt_symbol(module, name)
    try:
        return enum_type(value)
    except ValueError:
        return value


IID_IStringable = WinGUID.parse('96369f54-8eb6-48f0-abce-c1b211e627c3')

_IStringable = DynWinRTType.register_interface(
    "IStringable", IID_IStringable) \
    .add_method("ToString", DynWinRTMethodSig().add_out(DynWinRTType.hstring()))


class IStringable:
    def __init__(self, obj: DynWinRTValue):
        self._obj = obj

    @staticmethod
    def from_value(obj: DynWinRTValue) -> 'IStringable':
        return IStringable(obj.cast(IID_IStringable))


    def to_string(self) -> str:
        return _IStringable.method(6).invoke(self._obj, []).to_string()
