# Generated by dynwinrt-codegen — do not edit
from __future__ import annotations
from functools import lru_cache
from importlib import import_module
from typing import TYPE_CHECKING
from dynwinrt_py import (
    DynWinRTType, DynWinRTMethodSig, DynWinRTValue, DynWinRTArray,
    DynWinRTStruct, DynWinRtDelegate, WinGUID,
)


@lru_cache(maxsize=None)
def _dynwinrt_symbol(module, name):
    return getattr(import_module(f'.{module}', __package__), name)


def _dynwinrt_wrap_values(module, name, values):
    wrapper = _dynwinrt_symbol(module, name)
    return [wrapper(value) for value in values]


def _dynwinrt_enum(module, name, value):
    enum_type = _dynwinrt_symbol(module, name)
    try:
        return enum_type(value)
    except ValueError:
        return value


def _dynwinrt_wait_action(value):
    value.wait()
    return None


IID_IUriRuntimeClassWithAbsoluteCanonicalUri = WinGUID.parse('758d9661-221c-480f-a339-50656673f46f')

_IUriRuntimeClassWithAbsoluteCanonicalUri = DynWinRTType.register_interface(
    "IUriRuntimeClassWithAbsoluteCanonicalUri", IID_IUriRuntimeClassWithAbsoluteCanonicalUri) \
    .add_method("get_AbsoluteCanonicalUri", DynWinRTMethodSig().add_out(DynWinRTType.hstring())) \
    .add_method("get_DisplayIri", DynWinRTMethodSig().add_out(DynWinRTType.hstring()))


class IUriRuntimeClassWithAbsoluteCanonicalUri:
    def __init__(self, obj: DynWinRTValue):
        self._obj = obj

    @staticmethod
    def from_value(obj: DynWinRTValue) -> 'IUriRuntimeClassWithAbsoluteCanonicalUri':
        return IUriRuntimeClassWithAbsoluteCanonicalUri(obj.cast(IID_IUriRuntimeClassWithAbsoluteCanonicalUri))


    @property
    def absolute_canonical_uri(self) -> str:
        return _IUriRuntimeClassWithAbsoluteCanonicalUri.method(6).invoke(self._obj, []).to_string()

    @property
    def display_iri(self) -> str:
        return _IUriRuntimeClassWithAbsoluteCanonicalUri.method(7).invoke(self._obj, []).to_string()
