# Generated by dynwinrt-codegen — do not edit
from __future__ import annotations
from builtins import property as _property
from contextvars import copy_context as _copy_context
from functools import lru_cache
from importlib import import_module
from collections.abc import (
    Callable, Iterable, Iterator, Mapping, MutableMapping, MutableSequence, Sequence,
)
from datetime import datetime, timedelta
from typing import TYPE_CHECKING
from uuid import UUID
from weakref import ref as _weakref_ref
from dynwinrt_py import (
    DynWinRTType, DynWinRTMethodSig, DynWinRTValue, DynWinRTArray,
    DynWinRTStruct, DynWinRtDelegate, DynWinRTOverrideInterface, WinGUID,
)
from dynwinrt_py.dynwinrt_py import (
    _dynwinrt_array, _dynwinrt_bind_overload, _dynwinrt_datetime_to_ticks, _dynwinrt_guid,
    _dynwinrt_map, _dynwinrt_new_vector, _dynwinrt_ticks_to_datetime, _dynwinrt_ticks_to_timedelta,
    _dynwinrt_timedelta_to_ticks, _dynwinrt_track_projected, _dynwinrt_uuid, _dynwinrt_vector,
)


@lru_cache(maxsize=None)
def _dynwinrt_symbol(module, name):
    return getattr(import_module(f'.{module}', __package__), name)


def _dynwinrt_wrap_values(module, name, values):
    wrapper = _dynwinrt_symbol(module, name)
    wrap = getattr(wrapper, '_from_native', wrapper)
    return [None if value.is_null() else wrap(value) for value in values]


def _dynwinrt_enum(module, name, value):
    enum_type = _dynwinrt_symbol(module, name)
    try:
        return enum_type(value)
    except ValueError:
        return value


def _dynwinrt_create_delegate(iid, parameter_types, callback):
    context = _copy_context()
    def invoke(*args):
        return context.copy().run(callback, *args)
    return DynWinRtDelegate.create(iid, parameter_types, invoke)

def _dynwinrt_delegate(value, iid, parameter_types):
    raw = getattr(value, '_obj', value)
    if isinstance(raw, DynWinRTValue):
        return raw
    if not callable(value):
        raise TypeError('delegate value must be callable or a DynWinRTValue')
    return _dynwinrt_create_delegate(iid, parameter_types, value).to_value()


IID_IWwwFormUrlDecoderEntry = WinGUID.parse('125e7431-f678-4e8e-b670-20a9b06c512d')

_IWwwFormUrlDecoderEntry = DynWinRTType.register_interface(
    "IWwwFormUrlDecoderEntry", IID_IWwwFormUrlDecoderEntry) \
    .add_method("get_Name", DynWinRTMethodSig().add_out(DynWinRTType.hstring())) \
    .add_method("get_Value", DynWinRTMethodSig().add_out(DynWinRTType.hstring()))


class IWwwFormUrlDecoderEntry:
    def __init__(self, obj: DynWinRTValue):
        self._obj = obj
        _dynwinrt_track_projected(self, 'Windows.Foundation.IWwwFormUrlDecoderEntry')

    @staticmethod
    def from_value(obj: DynWinRTValue) -> 'IWwwFormUrlDecoderEntry':
        return IWwwFormUrlDecoderEntry(obj.cast(IID_IWwwFormUrlDecoderEntry))


    @_property
    def name(self) -> str:
        return _IWwwFormUrlDecoderEntry.method(6).invoke(self._obj, []).to_string()

    @_property
    def value(self) -> str:
        return _IWwwFormUrlDecoderEntry.method(7).invoke(self._obj, []).to_string()
