# Generated by dynwinrt-codegen — do not edit
from __future__ import annotations
from ._runtime import (
    Callable, Iterable, Iterator, Mapping, MutableMapping, MutableSequence, Sequence,
    TYPE_CHECKING, UUID, WinGUID, datetime, timedelta,
    DynWinRTType, DynWinRTMethodSig, DynWinRTValue, DynWinRTArray,
    DynWinRTStruct, DynWinRtDelegate, DynWinRTOverrideInterface,
    _property, _weakref_ref,
    _dynwinrt_array, _dynwinrt_bind_overload, _dynwinrt_can_cast, _dynwinrt_create_delegate,
    _dynwinrt_datetime_to_ticks, _dynwinrt_delegate, _dynwinrt_enum, _dynwinrt_guid,
    _dynwinrt_map, _dynwinrt_new_vector, _dynwinrt_ticks_to_datetime,
    _dynwinrt_ticks_to_timedelta, _dynwinrt_timedelta_to_ticks,
    _dynwinrt_cache_projected, _dynwinrt_projected_from_native,
    _dynwinrt_symbol, _dynwinrt_track_projected, _dynwinrt_uuid,
    _dynwinrt_vector, _dynwinrt_wrap_values,
)
from typing import Protocol, TypedDict
from dynwinrt import (
    DynWinRTInterfacePlan, DynWinRTImplementationMethod,
    DynWinRTImplementation, DynWinRTImplementationDescriptor,
    DynWinRTImplementationHandle,
)

IID_IWwwFormUrlDecoderEntry = WinGUID.parse('125e7431-f678-4e8e-b670-20a9b06c512d')

_IWwwFormUrlDecoderEntry = DynWinRTType.register_interface(
    "IWwwFormUrlDecoderEntry", IID_IWwwFormUrlDecoderEntry) \
    .add_method("get_Name", DynWinRTMethodSig().add_out(DynWinRTType.hstring())) \
    .add_method("get_Value", DynWinRTMethodSig().add_out(DynWinRTType.hstring()))


class IWwwFormUrlDecoderEntryHandlers(Protocol):
    """Synchronous handlers; multi-output results are named dicts and FillArray inputs are capacities."""
    def get_name(self) -> str: ...
    def get_value(self) -> str: ...
from ._runtime import (
    _implementation_check, _implementation_field, _implementation_array,
    _implementation_reference, _implementation_sync, _implementation_handler,
)

_implementation_plan = None

def _get_implementation_plan():
    global _implementation_plan
    if _implementation_plan is None:
        _implementation_plan = DynWinRTInterfacePlan.create("Windows.Foundation.IWwwFormUrlDecoderEntry", DynWinRTType.interface(WinGUID.parse("125e7431-f678-4e8e-b670-20a9b06c512d")), [
            DynWinRTImplementationMethod("get_Name", 6, DynWinRTMethodSig().add_out(DynWinRTType.hstring())),
            DynWinRTImplementationMethod("get_Value", 7, DynWinRTMethodSig().add_out(DynWinRTType.hstring()))
        ], [])
    return _implementation_plan


class IWwwFormUrlDecoderEntry:
    _dynwinrt_interface_type = True
    @staticmethod
    def implementation(handlers: IWwwFormUrlDecoderEntryHandlers) -> DynWinRTImplementationDescriptor:
        h6 = _implementation_handler(handlers, "get_name", 0, "Windows.Foundation.IWwwFormUrlDecoderEntry")
        h7 = _implementation_handler(handlers, "get_value", 0, "Windows.Foundation.IWwwFormUrlDecoderEntry")
        plan = _get_implementation_plan()
        def dispatch(vtable_index, args):
            if not isinstance(args, list):
                raise TypeError('implementation arguments must be a list')
            if vtable_index == 6:
                if len(args) != 0:
                    raise TypeError('implementation argument count mismatch')
                result = _implementation_sync(h6(), "Windows.Foundation.IWwwFormUrlDecoderEntry.get_name")
                return [DynWinRTValue.from_hstring((lambda v: _implementation_check(v, isinstance(v, str), "Windows.Foundation.IWwwFormUrlDecoderEntry.get_name.result"))(result))]
            if vtable_index == 7:
                if len(args) != 0:
                    raise TypeError('implementation argument count mismatch')
                result = _implementation_sync(h7(), "Windows.Foundation.IWwwFormUrlDecoderEntry.get_value")
                return [DynWinRTValue.from_hstring((lambda v: _implementation_check(v, isinstance(v, str), "Windows.Foundation.IWwwFormUrlDecoderEntry.get_value.result"))(result))]
            raise ValueError('unknown implementation vtable slot')
        return DynWinRTImplementationDescriptor(plan, dispatch)

    @classmethod
    def implement(cls, handlers: IWwwFormUrlDecoderEntryHandlers, *additional: DynWinRTImplementationDescriptor, interfaces=()) -> DynWinRTImplementationHandle:
        return DynWinRTImplementationHandle._create(cls, handlers, additional, interfaces)

    @classmethod
    def from_implementation(cls, owner: DynWinRTImplementation | DynWinRTImplementationHandle) -> 'IWwwFormUrlDecoderEntry':
        """Query an independently owned view, tracked by the current lifetime scope."""
        if not isinstance(owner, (DynWinRTImplementation, DynWinRTImplementationHandle)):
            raise TypeError('from_implementation requires a DynWinRTImplementation controller or handle')
        value = owner.to_value()
        try:
            native = value.cast(IID_IWwwFormUrlDecoderEntry)
            try:
                view = object.__new__(cls)
                cls._set_native(view, native, cache=False)
                return view
            except BaseException:
                native.release()
                raise
        finally:
            value.release()

    _dynwinrt_interface_iid = IID_IWwwFormUrlDecoderEntry
    def __new__(cls, *args, **kwargs):
        if len(args) == 1 and not kwargs and isinstance(args[0], DynWinRTValue):
            return _dynwinrt_projected_from_native(cls, args[0], '_set_native')
        return super().__new__(cls)

    def _set_native(self, obj: DynWinRTValue, *, cache=True):
        self._obj = obj
        self._dynwinrt_native_ready = True
        _dynwinrt_track_projected(self, 'Windows.Foundation.IWwwFormUrlDecoderEntry')
        if cache:
            _dynwinrt_cache_projected(self)

    def __init__(self, obj: DynWinRTValue):
        if getattr(self, '_dynwinrt_native_ready', False):
            return
        IWwwFormUrlDecoderEntry._set_native(self, obj)

    @classmethod
    def _from_native(cls, obj: DynWinRTValue) -> 'IWwwFormUrlDecoderEntry':
        return cls(obj)

    @classmethod
    def from_value(cls, obj: DynWinRTValue) -> 'IWwwFormUrlDecoderEntry':
        return cls._from_native(obj.cast(IID_IWwwFormUrlDecoderEntry))

    def as_interface(self, interface_class):
        return interface_class.from_value(self._obj)


    @_property
    def name(self) -> str:
        return _IWwwFormUrlDecoderEntry.method(6).invoke(self._obj, []).to_string()

    @_property
    def value(self) -> str:
        return _IWwwFormUrlDecoderEntry.method(7).invoke(self._obj, []).to_string()
