// Generated by dynwinrt-codegen — do not edit
import type { DynWinRtValue } from '../dist/index.js';

/** Opaque Win32 handle. Pass either a raw pointer value as a `bigint` (safe for full 64-bit handle values) or a `number` (only for handles that fit in a JS safe integer, e.g. HWND with small window IDs). Do NOT pass a `Buffer` — `DynCom.pointer(Buffer)` uses the buffer's own address, not the bytes it contains; for an Electron `getNativeWindowHandle()` Buffer, read the handle value first (for example, `buf.readBigUInt64LE(0)`). */
export type HWND = bigint | number;

export declare const IID_IDataTransferManagerInterop: unknown;

export declare class IDataTransferManagerInterop {
    /** Activate the projected WinRT class and QI to the interop. */
    static create(): IDataTransferManagerInterop;
    /** Wrap an existing native COM pointer (for QueryInterface bridging). */
    static _fromNative(obj: unknown): IDataTransferManagerInterop;
    getForWindow(appWindow: HWND): DynWinRtValue;
    showShareUIForWindow(appWindow: HWND): void;
}
