// Generated by dynwinrt-codegen — do not edit
import type { DynWinRtValue } from '../dist/index.js';

/** Opaque Win32 handle or pointer newtype (e.g. HWND, PWSTR). Accepts either a raw pointer as `bigint` or a `Buffer`. */
export type HWND = bigint | Buffer;

export declare const IID_ISystemMediaTransportControlsInterop: unknown;

export declare class ISystemMediaTransportControlsInterop {
    /** Activate the projected WinRT class and QI to the interop. */
    static create(): ISystemMediaTransportControlsInterop;
    /** Wrap an existing native COM pointer (for QueryInterface bridging). */
    static _fromNative(obj: unknown): ISystemMediaTransportControlsInterop;
    getForWindow(appWindow: HWND): DynWinRtValue;
}
