// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// E2E: real Node.js proof that the generated natural SystemMediaTransportControls
// wrapper drives live WinRT via the IInspectable-rooted (+6) *Interop* HWND
// pattern:
//   ISystemMediaTransportControlsInterop::GetForWindow(HWND, REFIID, void**)
// The test uses ONLY high-level generated wrappers — no low-level
// `registerInterface` / `coCreateInstance` / QI plumbing in the test.
//
// This is the companion of dtm.mjs. DTM proves the IUnknown-rooted (+3)
// interop; this proves the IInspectable-rooted (+6) interop AND exercises a
// real SMTC member (isPlayEnabled) to prove the returned object is a live,
// usable SystemMediaTransportControls, not just a valid IInspectable pointer.
//
// Run: node bindings/js/e2e/smtc.mjs

import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { DynWinRtValue } from '../dist/index.js';
// Classic-COM interop wrapper: gets the SMTC pointer from an HWND.
import { ISystemMediaTransportControlsInterop } from './ISystemMediaTransportControlsInterop.js';
import { acquireHwndBigInt } from './hwnd.mjs';

// The SMTC full-WinRT projection under ./smtc-projected/ is a bulky generated
// fixture and is intentionally gitignored. On a clean checkout it must be
// regenerated before this test can run — otherwise a static import below would
// fail with an opaque module-not-found error. Fail early with a helpful
// message that spells out the exact regeneration command.
const __dirname_smtc = dirname(fileURLToPath(import.meta.url));
const SMTC_FIXTURE = resolve(
    __dirname_smtc,
    'smtc-projected/SystemMediaTransportControls.js'
);
if (!existsSync(SMTC_FIXTURE)) {
    console.error(`[e2e] FAIL: SMTC projection fixture not found: ${SMTC_FIXTURE}`);
    console.error(`[e2e] This fixture is gitignored — regenerate it with:`);
    console.error(`  cargo run -p dynwinrt-codegen -- generate \\`);
    console.error(`    --namespace Windows.Media \\`);
    console.error(`    --class-name SystemMediaTransportControls \\`);
    console.error(`    --output bindings/js/e2e/smtc-projected \\`);
    console.error(`    --import-name ../../dist/index.js`);
    process.exit(1);
}
// Full WinRT natural projection: exercises real SMTC members via the same
// underlying COM pointer. Both wrappers are generated by dynwinrt-codegen.
const { SystemMediaTransportControls: SmtcProjected } =
    await import('./smtc-projected/SystemMediaTransportControls.js');
const { MediaPlaybackStatus } =
    await import('./smtc-projected/MediaPlaybackStatus.js');

function fail(msg) {
    console.error(`[e2e] FAIL: ${msg}`);
    process.exit(1);
}

// SMTC (unlike DTM) is documented as requiring a real top-level window that
// owns a media session. The classic-vertical `createTestHwnd()` helper
// creates a hidden `WS_POPUP` window owned by this process; that has been
// sufficient for interop dispatch on tested Windows builds.

console.log('[e2e] step 1: acquiring a process-owned HWND via napi createTestHwnd()');
const hwndBig = acquireHwndBigInt();
console.log(`[e2e]   HWND → 0x${hwndBig.toString(16)}`);
if (hwndBig === 0n) fail('acquireHwndBigInt returned NULL');

console.log('[e2e] step 2: ISystemMediaTransportControlsInterop.getForWindow(hwnd)  [HIGH-LEVEL WRAPPER, IInspectable-rooted +6]');
let smtcStub;
try {
    const interop = ISystemMediaTransportControlsInterop.create();
    smtcStub = interop.getForWindow(hwndBig);
} catch (e) {
    fail(`ISystemMediaTransportControlsInterop.getForWindow threw: ${e && e.message ? e.message : e}`);
}
if (smtcStub == null) fail('getForWindow returned null');
console.log(`[e2e]   got SystemMediaTransportControls (companion stub) = ${smtcStub}`);
if (!smtcStub._obj) fail('companion stub is missing native _obj');

console.log('[e2e] step 3: prove liveness via IInspectable::GetRuntimeClassName (companion stub property)');
let name;
try {
    name = smtcStub.runtimeClassName;
} catch (e) {
    fail(`smtcStub.runtimeClassName threw: ${e && e.message ? e.message : e}`);
}
console.log(`[e2e]   runtimeClassName = ${JSON.stringify(name)}`);
const expected = 'Windows.Media.SystemMediaTransportControls';
if (name !== expected) fail(`expected runtimeClassName='${expected}', got '${name}'`);

console.log('[e2e] step 4: MEANINGFUL — exercise real SMTC members through the natural WinRT wrapper');
// Re-wrap the SAME native pointer with the full WinRT projection.
// This is still 100% "generated wrapper" code — no manual registerInterface.
const smtc = SmtcProjected._fromNative(smtcStub._obj);

// (a) round-trip a boolean property.
console.log('[e2e]   set isPlayEnabled = true');
try {
    smtc.isPlayEnabled = true;
} catch (e) {
    fail(`smtc.isPlayEnabled = true threw: ${e && e.message ? e.message : e}`);
}
let readBack;
try {
    readBack = smtc.isPlayEnabled;
} catch (e) {
    fail(`get smtc.isPlayEnabled threw: ${e && e.message ? e.message : e}`);
}
console.log(`[e2e]   get isPlayEnabled → ${readBack}`);
if (readBack !== true) fail(`isPlayEnabled round-trip: expected true, got ${readBack}`);

// Flip it back to prove get/set really goes to the COM object.
console.log('[e2e]   set isPlayEnabled = false');
smtc.isPlayEnabled = false;
const readBack2 = smtc.isPlayEnabled;
console.log(`[e2e]   get isPlayEnabled → ${readBack2}`);
if (readBack2 !== false) fail(`isPlayEnabled round-trip #2: expected false, got ${readBack2}`);

// (b) round-trip an enum property.
console.log('[e2e]   set playbackStatus = MediaPlaybackStatus.Playing (3)');
try {
    smtc.playbackStatus = MediaPlaybackStatus.Playing;
} catch (e) {
    fail(`set playbackStatus threw: ${e && e.message ? e.message : e}`);
}
let status;
try {
    status = smtc.playbackStatus;
} catch (e) {
    fail(`get playbackStatus threw: ${e && e.message ? e.message : e}`);
}
console.log(`[e2e]   get playbackStatus → ${status} (${status === MediaPlaybackStatus.Playing ? 'Playing' : 'other'})`);
if (status !== MediaPlaybackStatus.Playing) fail(`playbackStatus round-trip: expected ${MediaPlaybackStatus.Playing} (Playing), got ${status}`);

// (c) reach a nested COM object.
console.log('[e2e]   get displayUpdater (IInspectable child object)');
let updater;
try {
    updater = smtc.displayUpdater;
} catch (e) {
    fail(`get displayUpdater threw: ${e && e.message ? e.message : e}`);
}
if (updater == null || !updater._obj) fail('displayUpdater returned null / no _obj');
console.log(`[e2e]   displayUpdater is a live SystemMediaTransportControlsDisplayUpdater`);

console.log('PASS');
process.exit(0);
