// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

use std::collections::{BTreeMap, BTreeSet};

use super::ir::{
    AbiType, AsyncIoKind, Cleanup, Conversion, Direction, EnumDefinition, InputExpression,
    NativeArchitectureLayout, NativeBuilderFieldKind, NativeFieldType, NativeLayout,
    NativeOutputFieldKind, NativeScalar, ProjectedApis, ProjectedAsyncFunction, ProjectedFunction,
    ProjectedNativeBuilder, ReturnShape, StringEncoding, Subsystem, SurfaceType,
};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedOutput {
    pub js: String,
    pub dts: String,
    pub extra_files: Vec<(String, String)>,
}

pub(super) fn render(apis: &ProjectedApis, runtime_import: &str) -> GeneratedOutput {
    let js = render_js(apis, runtime_import, &unsafe_runtime_import(runtime_import));
    let dts = render_dts(apis, runtime_import);
    let mut extra_files = Vec::new();
    for definition in &apis.enums {
        let (js, dts) = render_enum(definition);
        extra_files.push((format!("{}.js", definition.name), js));
        extra_files.push((format!("{}.d.ts", definition.name), dts));
    }
    extra_files.sort_by(|left, right| left.0.cmp(&right.0));
    GeneratedOutput {
        js,
        dts,
        extra_files,
    }
}

fn render_js(apis: &ProjectedApis, runtime_import: &str, unsafe_runtime_import: &str) -> String {
    let mut output = String::new();
    output.push_str("// Generated by dynwinrt-codegen - do not edit\n");
    output.push_str("'use strict'\n");
    output.push_str(&format!(
        "const {{ DynWin32 }} = require({runtime_import:?})\n\
         const {{ DynWin32Function }} = require({unsafe_runtime_import:?})\n\n"
    ));
    let subsystems = collect_subsystems(apis);
    for subsystem in &subsystems {
        let initializer = subsystem_initializer(*subsystem);
        output.push_str(&format!(
            "function {initializer}() {{ return DynWin32.{initializer}() }}\nexports.{initializer} = {initializer}\n"
        ));
    }
    if !subsystems.is_empty() {
        output.push('\n');
    }
    let native_layouts = collect_native_layouts(apis);
    for layout in native_layouts.values() {
        let builder = apis
            .native_builders
            .iter()
            .find(|builder| builder.layout_name == layout.name);
        output.push_str(&format!(
            "const _nativeLayout_{} = {}\n",
            layout.name,
            native_layout_descriptor_js(layout)
        ));
        if let Some(builder) = builder {
            render_native_builder_js(&mut output, layout, builder);
        } else {
            output.push_str(&format!(
                "function create{}(bytes) {{ return DynWin32.createNativeStruct(_nativeLayout_{}, bytes) }}\nexports.create{} = create{}\n\n",
                layout.name, layout.name, layout.name, layout.name
            ));
        }
    }

    fn render_native_builder_js(
        output: &mut String,
        layout: &NativeLayout,
        builder: &ProjectedNativeBuilder,
    ) {
        output.push_str(&format!(
            "function create{}(init) {{\n  const value = DynWin32.createNativeStruct(_nativeLayout_{})\n  init ??= {{}}\n",
            builder.js_name, layout.name
        ));
        if let Some(size_field) = &builder.size_field {
            output.push_str(&format!(
                "  DynWin32.setNativeStructU32(value, _nativeLayout_{}, {:?}, value.length)\n",
                layout.name, size_field
            ));
        }
        for field in &builder.fields {
            match field.kind {
                NativeBuilderFieldKind::Boolean => output.push_str(&format!(
                    "  DynWin32.setNativeStructBool32(value, _nativeLayout_{}, {:?}, Boolean(init.{}))\n",
                    layout.name, field.native_name, field.surface_name
                )),
                NativeBuilderFieldKind::DataPointer { nullable } => output.push_str(&format!(
                    "  DynWin32.setNativeStructPointer(value, _nativeLayout_{}, {:?}, DynWin32.dataPointer(init.{} ?? null, {}))\n",
                    layout.name, field.native_name, field.surface_name, nullable
                )),
            }
        }
        output.push_str(&format!(
            "  return value\n}}\nexports.create{0} = create{0}\n\n",
            builder.js_name
        ));
        for field in &builder.outputs {
            let function = match field.kind {
                NativeOutputFieldKind::U32 => {
                    format!("get{}{}", builder.js_name, upper_first(&field.surface_name))
                }
                NativeOutputFieldKind::Resource { .. } => {
                    format!(
                        "take{}{}",
                        builder.js_name,
                        upper_first(&field.surface_name)
                    )
                }
            };
            let expression = match field.kind {
                NativeOutputFieldKind::U32 => format!(
                    "DynWin32.getNativeStructU32(value, _nativeLayout_{}, {:?})",
                    layout.name, field.native_name
                ),
                NativeOutputFieldKind::Resource { cleanup } => format!(
                    "DynWin32.takeNativeStructResource(value, _nativeLayout_{}, {:?}, {:?})",
                    layout.name,
                    field.native_name,
                    cleanup_name(cleanup)
                ),
            };
            output.push_str(&format!(
                "function {function}(value) {{ return {expression} }}\nexports.{function} = {function}\n"
            ));
        }
        if !builder.outputs.is_empty() {
            output.push('\n');
        }
    }

    if apis.functions.iter().any(|function| {
        function
            .inputs
            .iter()
            .any(|input| matches!(input, InputExpression::BufferLength { .. }))
    }) {
        output.push_str(
            "function _bufferCount(value, divisor) {\n\
             \x20 if (value == null) return 0\n\
             \x20 if (!ArrayBuffer.isView(value)) throw new TypeError('expected Buffer or TypedArray')\n\
             \x20 if (value.byteLength % divisor !== 0) throw new RangeError('buffer byte length is not divisible by its native element size')\n\
             \x20 const count = value.byteLength / divisor\n\
             \x20 if (!Number.isSafeInteger(count)) throw new RangeError('native buffer count is not a safe integer')\n\
             \x20 return count\n\
             }\n\n",
        );
    }
    if apis.functions.iter().any(|function| {
        function
            .inputs
            .iter()
            .any(|input| matches!(input, InputExpression::ScalarPointer { .. }))
    }) {
        output.push_str(
            "function _scalarPointer(kind, value) {\n\
             \x20 switch (kind) {\n\
             \x20   case 'bool8': { const b = Buffer.alloc(1); b.writeUInt8(value ? 1 : 0); return b }\n\
             \x20   case 'bool32': { const b = Buffer.alloc(4); b.writeInt32LE(value ? 1 : 0); return b }\n\
             \x20   case 'i8': { const b = Buffer.alloc(1); b.writeInt8(value); return b }\n\
             \x20   case 'u8': { const b = Buffer.alloc(1); b.writeUInt8(value); return b }\n\
             \x20   case 'i16': { const b = Buffer.alloc(2); b.writeInt16LE(value); return b }\n\
             \x20   case 'u16': { const b = Buffer.alloc(2); b.writeUInt16LE(value); return b }\n\
             \x20   case 'i32': { const b = Buffer.alloc(4); b.writeInt32LE(value); return b }\n\
             \x20   case 'u32': { const b = Buffer.alloc(4); b.writeUInt32LE(value); return b }\n\
             \x20   case 'i64': { const b = Buffer.alloc(8); b.writeBigInt64LE(BigInt(value)); return b }\n\
             \x20   case 'u64': { const b = Buffer.alloc(8); b.writeBigUInt64LE(BigInt(value)); return b }\n\
             \x20   case 'f32': { const b = Buffer.alloc(4); b.writeFloatLE(value); return b }\n\
             \x20   case 'f64': { const b = Buffer.alloc(8); b.writeDoubleLE(value); return b }\n\
             \x20   default: throw new TypeError(`unsupported scalar pointer kind ${kind}`)\n\
             \x20 }\n\
             }\n\n",
        );
    }

    for function in &apis.functions {
        render_function_js(&mut output, function, apis);
        output.push('\n');
    }
    for function in &apis.async_functions {
        render_async_function_js(&mut output, function);
        output.push('\n');
    }
    output.push_str("const Apis = Object.freeze({\n");
    for subsystem in &subsystems {
        let initializer = subsystem_initializer(*subsystem);
        output.push_str(&format!("  {initializer}: {initializer},\n"));
    }
    for function in &apis.functions {
        output.push_str(&format!("  {}: {},\n", function.js_name, function.js_name));
        if let Some(alias) = &function.unicode_alias {
            output.push_str(&format!("  {alias}: {alias},\n"));
        }
    }
    for function in &apis.async_functions {
        output.push_str(&format!("  {}: {},\n", function.js_name, function.js_name));
    }

    output.push_str("})\nexports.Apis = Apis\n");
    output
}

fn upper_first(value: &str) -> String {
    let mut chars = value.chars();
    chars
        .next()
        .map(|first| first.to_ascii_uppercase().to_string() + chars.as_str())
        .unwrap_or_default()
}

fn render_async_function_js(output: &mut String, function: &ProjectedAsyncFunction) {
    let runtime_method = match function.kind {
        AsyncIoKind::Read => "beginReadFile",
        AsyncIoKind::Write => "beginWriteFile",
    };
    output.push_str(&format!(
        "function {}(file, buffer, offset, signal) {{\n  try {{\n    if (signal != null && (typeof signal.addEventListener !== 'function' || typeof signal.removeEventListener !== 'function' || typeof signal.aborted !== 'boolean')) return Promise.reject(new TypeError('signal must be an AbortSignal'))\n    if (signal?.aborted) {{ const error = new Error('The operation was aborted'); error.name = 'AbortError'; return Promise.reject(error) }}\n  }} catch (error) {{ return Promise.reject(error) }}\n  let operation\n  let aborted = false\n  const abort = () => {{ aborted = true; operation?.cancel() }}\n  try {{ signal?.addEventListener('abort', abort, {{ once: true }}) }} catch (error) {{ return Promise.reject(error) }}\n  try {{ operation = DynWin32.{}(file, buffer, offset ?? 0n) }} catch (error) {{ signal?.removeEventListener('abort', abort); return Promise.reject(error) }}\n  if (aborted) operation.cancel()\n  const promise = new Promise((resolve, reject) => {{\n    try {{ operation.start((error, bytesTransferred) => error ? reject(error) : resolve(bytesTransferred)) }} catch (error) {{ reject(error) }}\n  }})\n  return promise.catch((cause) => {{\n    const message = String(cause?.message ?? '')\n    const cancelled = message.includes('Win32 error 995') || message.includes('OVERLAPPED operation was aborted')\n    if (!aborted || !cancelled) throw cause\n    const error = new Error('The operation was aborted')\n    error.name = 'AbortError'\n    error.cause = cause\n    throw error\n  }}).finally(() => signal?.removeEventListener('abort', abort))\n}}\nexports.{0} = {0}\n",
        function.js_name, runtime_method
    ));
}

fn unsafe_runtime_import(runtime_import: &str) -> String {
    if runtime_import.ends_with("/win32") {
        format!("{runtime_import}/unsafe")
    } else if let Some(prefix) = runtime_import.strip_suffix("win32.js") {
        format!("{prefix}win32-unsafe.js")
    } else {
        format!("{runtime_import}/unsafe")
    }
}

fn render_function_js(output: &mut String, function: &ProjectedFunction, apis: &ProjectedApis) {
    let plan_name = format!("_{}Plan", function.js_name);
    let bind_name = format!("_bind{}Plan", function.metadata_name);
    output.push_str(&format!(
        "let {plan_name}\nfunction {bind_name}() {{\n  return {plan_name} ??= DynWin32Function.bind({{\n    dll: {:?},\n    entryPoint: {:?},\n    parameters: [\n",
        function.runtime.dll, function.runtime.entry_point
    ));
    for parameter in &function.runtime.parameters {
        output.push_str(&format!(
            "      {{ type: {:?}, direction: {:?}, nullable: {}, cleanup: {:?}, consumesResource: {}, resourceCleanup: {:?}, aggregateDescriptor: {} }},\n",
            abi_name(parameter.abi),
            direction_name(parameter.direction),
            parameter.nullable,
            cleanup_name(parameter.cleanup),
            parameter.consumes_resource,
            cleanup_name(parameter.resource_cleanup),
            parameter
                .aggregate
                .as_ref()
                .map(native_layout_descriptor_js)
                .unwrap_or_else(|| "undefined".into()),
        ));
    }
    output.push_str(&format!(
        "    ],\n    returnType: {:?},\n    returnCleanup: {:?},\n    successRule: {:?},\n    captureLastError: {},\n    callingConvention: {:?},\n    returnAggregateDescriptor: {},\n  }})\n}}\n",
        function
            .runtime
            .return_abi
            .map(abi_name)
            .unwrap_or("void"),
        cleanup_name(function.runtime.return_cleanup),
        success_name(function.runtime.success_rule),
        function.runtime.capture_last_error,
        calling_convention_name(function.runtime.calling_convention),
        function
            .runtime
            .return_aggregate
            .as_ref()
            .map(native_layout_descriptor_js)
            .unwrap_or_else(|| "undefined".into()),
    ));
    let mut surface_parameters = function
        .parameters
        .iter()
        .map(|parameter| parameter.name.as_str())
        .collect::<Vec<_>>();
    if function.subsystem.is_some() {
        surface_parameters.insert(0, "_subsystem");
    }
    output.push_str(&format!(
        "function {}({}) {{\n",
        function.js_name,
        surface_parameters.join(", ")
    ));
    for parameter in &function.parameters {
        if let Some(minimum) = parameter.minimum_bytes {
            output.push_str(&format!(
                "  if ({} != null && {}.byteLength < {}) throw new RangeError({:?})\n",
                parameter.name,
                parameter.name,
                minimum,
                format!(
                    "{} must contain at least {minimum} bytes for its native fixed-size contract",
                    parameter.name
                ),
            ));
        }
    }
    let arguments = function
        .inputs
        .iter()
        .map(|input| render_input(input, function))
        .collect::<Vec<_>>()
        .join(", ");
    let output_aggregates = function
        .inputs
        .iter()
        .filter_map(|input| {
            let InputExpression::NativeAggregate {
                parameter_index,
                layout,
                by_value: false,
                ..
            } = input
            else {
                return None;
            };
            apis.native_builders
                .iter()
                .find(|builder| builder.layout_name == layout.name && !builder.outputs.is_empty())
                .map(|_| (&function.parameters[*parameter_index].name, &layout.name))
        })
        .collect::<Vec<_>>();
    for (parameter, layout) in &output_aggregates {
        output.push_str(&format!(
            "  DynWin32.prepareNativeStructCall({parameter}, _nativeLayout_{layout})\n"
        ));
    }
    let invocation = function.subsystem.map_or_else(
        || format!("{bind_name}().invoke([{arguments}])"),
        |subsystem| {
            format!(
                "{bind_name}().invokeWithSubsystem(_subsystem, {:?}, [{arguments}])",
                subsystem_name(subsystem)
            )
        },
    );
    output.push_str(&format!(
        "  const _call = {invocation}\n  const _return = _call.returnValue\n  const _outputs = _call.outputs\n"
    ));
    for (parameter, layout) in &output_aggregates {
        output.push_str(&format!(
            "  DynWin32.markNativeStructCallResult({parameter}, _nativeLayout_{layout}, _call.succeeded)\n"
        ));
    }
    match &function.return_shape {
        ReturnShape::Void => output.push_str("  return undefined\n"),
        ReturnShape::Direct { typ, conversion } => {
            if let SurfaceType::NativeStruct(name) = typ {
                output.push_str(&format!(
                    "  return DynWin32.toNativeStruct(_return, _nativeLayout_{name})\n"
                ));
            } else {
                output.push_str(&format!(
                    "  return {}\n",
                    render_output_conversion(*conversion, "_return")
                ));
            }
        }
        ReturnShape::Object {
            status,
            return_value,
            outputs,
            last_error,
        } => {
            output.push_str("  return {\n");
            if *status {
                output.push_str("    status: DynWin32.toNumber(_return),\n");
            } else if let Some((typ, conversion)) = return_value {
                if let SurfaceType::NativeStruct(name) = typ {
                    output.push_str(&format!(
                        "    result: DynWin32.toNativeStruct(_return, _nativeLayout_{name}),\n"
                    ));
                } else {
                    output.push_str(&format!(
                        "    result: {},\n",
                        render_output_conversion(*conversion, "_return")
                    ));
                }
            }
            for result in outputs {
                output.push_str(&format!(
                    "    {}: {},\n",
                    result.name,
                    render_output_conversion(
                        result.conversion,
                        &format!("_outputs[{}]", result.output_index)
                    )
                ));
            }
            if *last_error {
                output.push_str("    lastError: _call.lastError,\n");
            }
            output.push_str("  }\n");
        }
    }
    output.push_str("}\n");
    output.push_str(&format!("exports.{0} = {0}\n", function.js_name));
    if let Some(alias) = &function.unicode_alias {
        output.push_str(&format!(
            "const {alias} = {}\nexports.{alias} = {alias}\n",
            function.js_name
        ));
    }
}

fn render_input(input: &InputExpression, function: &ProjectedFunction) -> String {
    match input {
        InputExpression::Surface {
            parameter_index,
            conversion,
        } => {
            let parameter = &function.parameters[*parameter_index];
            let value = &parameter.name;
            match conversion {
                Conversion::Boolean => format!("DynWin32.bool32({value})"),
                Conversion::Boolean8 => format!("DynWin32.bool8({value})"),
                Conversion::I8 => format!("DynWin32.i8({value})"),
                Conversion::U8 => format!("DynWin32.u8({value})"),
                Conversion::I16 => format!("DynWin32.i16({value})"),
                Conversion::U16 => format!("DynWin32.u16({value})"),
                Conversion::I32 => format!("DynWin32.i32({value})"),
                Conversion::U32 => format!("DynWin32.u32({value})"),
                Conversion::I64 => format!("DynWin32.i64({value})"),
                Conversion::U64 => format!("DynWin32.u64({value})"),
                Conversion::F32 => format!("DynWin32.f32({value})"),
                Conversion::F64 => format!("DynWin32.f64({value})"),
                Conversion::Handle => {
                    format!("DynWin32.handle({value}, {})", parameter.nullable)
                }
                Conversion::DataPointer => {
                    if parameter.alignment.unwrap_or(1) > 1 {
                        format!(
                            "DynWin32.alignedDataPointer({value}, {}, {})",
                            parameter.alignment.unwrap(),
                            parameter.nullable
                        )
                    } else {
                        format!("DynWin32.dataPointer({value}, {})", parameter.nullable)
                    }
                }
                Conversion::WideString => {
                    format!("DynWin32.wideString({value}, {})", parameter.nullable)
                }
                Conversion::AnsiString => {
                    format!("DynWin32.ansiString({value}, {})", parameter.nullable)
                }
                Conversion::WideMultiString => {
                    format!("DynWin32.wideMultiString({value}, {})", parameter.nullable)
                }
                Conversion::AnsiMultiString => {
                    format!("DynWin32.ansiMultiString({value}, {})", parameter.nullable)
                }
                Conversion::ResourceInput(cleanup) => {
                    format!("DynWin32.resource({value}, {:?})", cleanup_name(*cleanup))
                }
                Conversion::BigInt => format!("DynWin32.handle({value})"),
                Conversion::Number | Conversion::Resource | Conversion::NativeAggregate => {
                    unreachable!("result conversion cannot be an input")
                }
            }
        }
        InputExpression::BufferLength {
            parameter_index,
            divisor,
            abi,
        } => {
            let value = &function.parameters[*parameter_index].name;
            format!(
                "DynWin32.{}(_bufferCount({}, {}))",
                abi_name(*abi),
                value,
                divisor
            )
        }
        InputExpression::NullPointer => "DynWin32.nullPointer()".into(),
        InputExpression::Zero(abi) => render_zero(*abi),
        InputExpression::NativeAggregate {
            parameter_index,
            layout,
            nullable,
            by_value,
        } => {
            let value = &function.parameters[*parameter_index].name;
            if *by_value {
                format!(
                    "DynWin32.nativeStructValue({value}, _nativeLayout_{})",
                    layout.name
                )
            } else {
                format!(
                    "DynWin32.nativeStruct({value}, _nativeLayout_{}, {nullable})",
                    layout.name
                )
            }
        }
        InputExpression::ScalarPointer {
            parameter_index,
            scalar,
            nullable,
        } => {
            let value = &function.parameters[*parameter_index].name;
            let kind = scalar_pointer_kind(*scalar);
            let alignment = scalar_pointer_alignment(*scalar);
            let converted = format!(
                "DynWin32.alignedDataPointer(_scalarPointer({kind:?}, {value}), {alignment}, false)"
            );
            if *nullable {
                format!("({value} == null ? DynWin32.nullPointer() : {converted})")
            } else {
                converted
            }
        }
        InputExpression::ComInterface {
            parameter_index,
            iid,
        } => {
            let value = &function.parameters[*parameter_index].name;
            format!(
                "DynWin32.comObject({value}, {iid:?}, {})",
                function.parameters[*parameter_index].nullable
            )
        }
        InputExpression::StringPointerPointer {
            parameter_index,
            encoding,
            nullable,
        } => {
            let value = &function.parameters[*parameter_index].name;
            match encoding {
                StringEncoding::Wide => {
                    format!("DynWin32.wideStringPointerPointer({value}, {nullable})")
                }
                StringEncoding::Ansi => {
                    format!("DynWin32.ansiStringPointerPointer({value}, {nullable})")
                }
            }
        }
    }
}

fn render_output_conversion(conversion: Conversion, value: &str) -> String {
    match conversion {
        Conversion::Boolean => format!("DynWin32.toBoolean({value})"),
        Conversion::Number => format!("DynWin32.toNumber({value})"),
        Conversion::BigInt => format!("DynWin32.toBigint({value})"),
        Conversion::Resource => format!("DynWin32.toResource({value})"),
        Conversion::NativeAggregate => {
            unreachable!("native aggregate output requires its descriptor")
        }
        Conversion::I8
        | Conversion::Boolean8
        | Conversion::U8
        | Conversion::I16
        | Conversion::U16
        | Conversion::I32
        | Conversion::U32
        | Conversion::I64
        | Conversion::U64
        | Conversion::F32
        | Conversion::F64
        | Conversion::Handle
        | Conversion::DataPointer
        | Conversion::WideString
        | Conversion::AnsiString
        | Conversion::WideMultiString
        | Conversion::AnsiMultiString
        | Conversion::ResourceInput(_) => unreachable!("input conversion cannot be a result"),
    }
}

fn render_dts(apis: &ProjectedApis, runtime_import: &str) -> String {
    let mut output = String::new();
    output.push_str("// Generated by dynwinrt-codegen - do not edit\n");
    output.push_str(&format!(
        "import type {{ DynWin32NativeStruct, DynWin32Resource, DynWin32SubsystemContext, DynWinRtValue }} from {runtime_import:?}\n"
    ));
    for definition in &apis.enums {
        output.push_str(&format!(
            "import type {{ {} }} from './{}.js'\n",
            definition.name, definition.name
        ));
    }
    output.push('\n');

    let mut handles = BTreeSet::new();
    if !apis.async_functions.is_empty() {
        handles.insert("HANDLE".to_string());
    }
    for function in &apis.functions {
        for parameter in &function.parameters {
            collect_handle_alias(&parameter.typ, &mut handles);
        }
        match &function.return_shape {
            ReturnShape::Direct { typ, .. } => collect_handle_alias(typ, &mut handles),
            ReturnShape::Object {
                return_value,
                outputs,
                ..
            } => {
                if let Some((typ, _)) = return_value {
                    collect_handle_alias(typ, &mut handles);
                }
                for output in outputs {
                    collect_handle_alias(&output.typ, &mut handles);
                }
            }
            ReturnShape::Void => {}
        }
    }
    for handle in handles {
        output.push_str(&format!(
            "export type {handle} = bigint | number | DynWin32Resource\n"
        ));
    }
    for layout in collect_native_layouts(apis).values() {
        if let Some(builder) = apis
            .native_builders
            .iter()
            .find(|builder| builder.layout_name == layout.name)
        {
            output.push_str(&format!("export interface {}Init {{\n", builder.js_name));
            for field in &builder.fields {
                let typ = match field.kind {
                    NativeBuilderFieldKind::Boolean => "boolean",
                    NativeBuilderFieldKind::DataPointer { nullable: true } => {
                        "Buffer | Uint8Array | null"
                    }
                    NativeBuilderFieldKind::DataPointer { nullable: false } => {
                        "Buffer | Uint8Array"
                    }
                };
                output.push_str(&format!(
                    "  {}{}: {}\n",
                    field.surface_name,
                    if field.optional { "?" } else { "" },
                    typ
                ));
            }
            output.push_str(&format!(
                "}}\nexport type {0} = DynWin32NativeStruct\nexport declare function create{1}(init?: {1}Init): {0}\n",
                layout.name, builder.js_name
            ));
            for field in &builder.outputs {
                let (prefix, typ) = match field.kind {
                    NativeOutputFieldKind::U32 => ("get", "number"),
                    NativeOutputFieldKind::Resource { .. } => ("take", "DynWin32Resource | null"),
                };
                output.push_str(&format!(
                    "export declare function {prefix}{}{}(value: {}): {typ}\n",
                    builder.js_name,
                    upper_first(&field.surface_name),
                    layout.name
                ));
            }
        } else {
            output.push_str(&format!(
                "export type {} = DynWin32NativeStruct\nexport declare function create{}(bytes?: Buffer | Uint8Array): {}\n",
                layout.name, layout.name, layout.name
            ));
        }
    }
    if !apis.functions.is_empty() {
        output.push('\n');
    }
    let subsystems = collect_subsystems(apis);
    for subsystem in &subsystems {
        let initializer = subsystem_initializer(*subsystem);
        output.push_str(&format!(
            "export declare function {initializer}(): DynWin32SubsystemContext\n"
        ));
    }
    for function in &apis.functions {
        let mut parameters = function
            .parameters
            .iter()
            .map(|parameter| {
                let mut typ = dts_type(&parameter.typ);
                if parameter.nullable {
                    typ.push_str(" | null");
                }
                format!("{}: {typ}", parameter.name)
            })
            .collect::<Vec<_>>();
        if function.subsystem.is_some() {
            parameters.insert(0, "_subsystem: DynWin32SubsystemContext".into());
        }
        let parameters = parameters.join(", ");
        output.push_str(&format!(
            "export declare function {}({parameters}): {}\n",
            function.js_name,
            dts_return_shape(&function.return_shape)
        ));
        if let Some(alias) = &function.unicode_alias {
            output.push_str(&format!(
                "export declare const {alias}: typeof {}\n",
                function.js_name
            ));
        }
    }
    for function in &apis.async_functions {
        output.push_str(&format!(
            "export declare function {}(file: DynWin32Resource, buffer: Buffer, offset?: bigint, signal?: AbortSignal): Promise<number>\n",
            function.js_name
        ));
    }
    output.push_str("\nexport declare const Apis: Readonly<{\n");
    for subsystem in &subsystems {
        let initializer = subsystem_initializer(*subsystem);
        output.push_str(&format!("  {initializer}: typeof {initializer}\n"));
    }
    for function in &apis.functions {
        output.push_str(&format!(
            "  {}: typeof {}\n",
            function.js_name, function.js_name
        ));
        if let Some(alias) = &function.unicode_alias {
            output.push_str(&format!("  {alias}: typeof {alias}\n"));
        }
    }
    for function in &apis.async_functions {
        output.push_str(&format!(
            "  {}: typeof {}\n",
            function.js_name, function.js_name
        ));
    }
    output.push_str("}>\n");
    output
}

fn collect_handle_alias(typ: &SurfaceType, handles: &mut BTreeSet<String>) {
    if let SurfaceType::Handle(name) = typ {
        handles.insert(name.clone());
    }
}

fn dts_return_shape(shape: &ReturnShape) -> String {
    match shape {
        ReturnShape::Void => "void".into(),
        ReturnShape::Direct { typ, .. } => dts_type(typ),
        ReturnShape::Object {
            status,
            return_value,
            outputs,
            last_error,
        } => {
            let mut fields = Vec::new();
            if *status {
                fields.push("readonly status: number".into());
            } else if let Some((typ, _)) = return_value {
                fields.push(format!("readonly result: {}", dts_type(typ)));
            }
            fields.extend(
                outputs
                    .iter()
                    .map(|output| format!("readonly {}: {}", output.name, dts_type(&output.typ))),
            );
            if *last_error {
                fields.push("readonly lastError: number".into());
            }
            format!("{{ {} }}", fields.join("; "))
        }
    }
}

fn dts_type(typ: &SurfaceType) -> String {
    match typ {
        SurfaceType::Boolean => "boolean".into(),
        SurfaceType::Number => "number".into(),
        SurfaceType::BigInt => "bigint".into(),
        SurfaceType::Enum(name) | SurfaceType::Handle(name) => name.clone(),
        SurfaceType::Buffer => "Buffer | Uint8Array".into(),
        SurfaceType::String(StringEncoding::Wide | StringEncoding::Ansi) => {
            "string | Buffer | Uint8Array".into()
        }
        SurfaceType::MultiString(StringEncoding::Wide | StringEncoding::Ansi) => {
            "string | readonly string[] | Buffer | Uint8Array".into()
        }
        SurfaceType::ManagedResource => "DynWin32Resource".into(),
        SurfaceType::Resource => "DynWin32Resource | null".into(),
        SurfaceType::NativeStruct(name) | SurfaceType::NativeUnion(name) => name.clone(),
        SurfaceType::ComInterface(_) => "DynWinRtValue".into(),
    }
}

fn render_zero(abi: AbiType) -> String {
    match abi {
        AbiType::Bool32 => "DynWin32.bool32(false)".into(),
        AbiType::I8 => "DynWin32.i8(0)".into(),
        AbiType::U8 => "DynWin32.u8(0)".into(),
        AbiType::I16 => "DynWin32.i16(0)".into(),
        AbiType::U16 => "DynWin32.u16(0)".into(),
        AbiType::I32 => "DynWin32.i32(0)".into(),
        AbiType::U32 => "DynWin32.u32(0)".into(),
        AbiType::I64 => "DynWin32.i64(0n)".into(),
        AbiType::U64 => "DynWin32.u64(0n)".into(),
        AbiType::F32 => "DynWin32.f32(0)".into(),
        AbiType::F64 => "DynWin32.f64(0)".into(),
        AbiType::Pointer => "DynWin32.nullPointer()".into(),
        AbiType::FunctionPointer | AbiType::Handle => "DynWin32.handle(0n, true)".into(),
    }
}

fn collect_native_layouts(apis: &ProjectedApis) -> BTreeMap<String, NativeLayout> {
    let mut layouts = BTreeMap::new();
    for function in &apis.functions {
        for input in &function.inputs {
            if let InputExpression::NativeAggregate { layout, .. } = input {
                layouts
                    .entry(layout.name.clone())
                    .or_insert_with(|| layout.clone());
            }
        }
        if let Some(layout) = &function.runtime.return_aggregate {
            layouts
                .entry(layout.name.clone())
                .or_insert_with(|| layout.clone());
        }
    }
    layouts
}

fn native_layout_descriptor_js(layout: &NativeLayout) -> String {
    let descriptor = format!(
        "{{\"name\":\"{}.{}\",\"kind\":\"{}\",\"x86\":{},\"x64\":{},\"arm64\":{}}}",
        layout.namespace,
        layout.name,
        match layout.kind {
            super::ir::NativeAggregateKind::Struct => "struct",
            super::ir::NativeAggregateKind::Union => "union",
        },
        native_architecture_json(&layout.x86),
        native_architecture_json(&layout.x64),
        native_architecture_json(&layout.arm64),
    );
    format!(
        "'{}'",
        descriptor.replace('\\', "\\\\").replace('\'', "\\'")
    )
}

fn native_architecture_json(layout: &NativeArchitectureLayout) -> String {
    let fields = layout
        .fields
        .iter()
        .map(|field| {
            format!(
                "{{\"name\":\"{}\",\"offset\":{},\"count\":{},\"type\":{}}}",
                field.name,
                field.offset,
                field.count,
                native_field_type_json(&field.typ)
            )
        })
        .collect::<Vec<_>>()
        .join(",");
    format!(
        "{{\"size\":{},\"alignment\":{},\"fields\":[{}]}}",
        layout.size, layout.alignment, fields
    )
}

fn native_field_type_json(typ: &NativeFieldType) -> String {
    match typ {
        NativeFieldType::Scalar(scalar) => {
            format!("{{\"kind\":\"{}\"}}", native_scalar_name(*scalar))
        }
        NativeFieldType::Guid => "{\"kind\":\"guid\"}".into(),
        NativeFieldType::Pointer => "{\"kind\":\"pointer\"}".into(),
        NativeFieldType::Handle { cleanup } => format!(
            "{{\"kind\":\"handle\",\"cleanup\":\"{}\"}}",
            cleanup_name(*cleanup)
        ),
        NativeFieldType::Struct { name, layout, .. } => format!(
            "{{\"kind\":\"struct\",\"name\":\"{name}\",\"layout\":{}}}",
            native_architecture_json(layout)
        ),
        NativeFieldType::Union { name, layout, .. } => format!(
            "{{\"kind\":\"union\",\"name\":\"{name}\",\"layout\":{}}}",
            native_architecture_json(layout)
        ),
    }
}

fn native_scalar_name(scalar: NativeScalar) -> &'static str {
    match scalar {
        NativeScalar::I8 => "i8",
        NativeScalar::U8 => "u8",
        NativeScalar::I16 => "i16",
        NativeScalar::U16 => "u16",
        NativeScalar::I32 => "i32",
        NativeScalar::U32 => "u32",
        NativeScalar::I64 => "i64",
        NativeScalar::U64 => "u64",
        NativeScalar::F32 => "f32",
        NativeScalar::F64 => "f64",
        NativeScalar::NativeIsize => "isize",
        NativeScalar::NativeUsize => "usize",
    }
}

fn scalar_pointer_kind(scalar: super::ir::Scalar) -> &'static str {
    match scalar {
        super::ir::Scalar::Bool8 => "bool8",
        super::ir::Scalar::Bool32 => "bool32",
        super::ir::Scalar::I8 => "i8",
        super::ir::Scalar::U8 => "u8",
        super::ir::Scalar::I16 => "i16",
        super::ir::Scalar::U16 => "u16",
        super::ir::Scalar::I32 => "i32",
        super::ir::Scalar::U32 => "u32",
        super::ir::Scalar::I64 | super::ir::Scalar::NativeIsize => "i64",
        super::ir::Scalar::U64 | super::ir::Scalar::NativeUsize => "u64",
        super::ir::Scalar::F32 => "f32",
        super::ir::Scalar::F64 => "f64",
    }
}

fn scalar_pointer_alignment(scalar: super::ir::Scalar) -> usize {
    match scalar {
        super::ir::Scalar::Bool32
        | super::ir::Scalar::I32
        | super::ir::Scalar::U32
        | super::ir::Scalar::F32 => 4,
        super::ir::Scalar::Bool8 | super::ir::Scalar::I8 | super::ir::Scalar::U8 => 1,
        super::ir::Scalar::I16 | super::ir::Scalar::U16 => 2,
        super::ir::Scalar::I64
        | super::ir::Scalar::U64
        | super::ir::Scalar::F64
        | super::ir::Scalar::NativeIsize
        | super::ir::Scalar::NativeUsize => 8,
    }
}

fn render_enum(definition: &EnumDefinition) -> (String, String) {
    let mut js = String::from("// Generated by dynwinrt-codegen - do not edit\n'use strict'\n");
    js.push_str(&format!("const {} = Object.freeze({{\n", definition.name));
    for member in &definition.members {
        js.push_str(&format!("  {}: {},\n", member.name, member.value));
    }
    js.push_str(&format!("}})\nexports.{0} = {0}\n", definition.name));

    let mut dts = String::from("// Generated by dynwinrt-codegen - do not edit\n");
    dts.push_str(&format!(
        "export type {0} = (typeof {0})[keyof typeof {0}]\nexport declare const {0}: {{\n",
        definition.name
    ));
    for member in &definition.members {
        dts.push_str(&format!("  readonly {}: {}\n", member.name, member.value));
    }
    dts.push_str("}\n");
    (js, dts)
}

fn collect_subsystems(apis: &ProjectedApis) -> BTreeSet<Subsystem> {
    apis.functions
        .iter()
        .filter_map(|function| function.subsystem)
        .collect()
}

fn subsystem_name(subsystem: Subsystem) -> &'static str {
    match subsystem {
        Subsystem::Winsock => "winsock",
        Subsystem::GdiPlus => "gdiplus",
        Subsystem::MediaFoundation => "mediaFoundation",
    }
}

fn subsystem_initializer(subsystem: Subsystem) -> &'static str {
    match subsystem {
        Subsystem::Winsock => "initializeWinsock",
        Subsystem::GdiPlus => "initializeGdiPlus",
        Subsystem::MediaFoundation => "initializeMediaFoundation",
    }
}

fn abi_name(typ: AbiType) -> &'static str {
    match typ {
        AbiType::Bool32 => "bool32",
        AbiType::I8 => "i8",
        AbiType::U8 => "u8",
        AbiType::I16 => "i16",
        AbiType::U16 => "u16",
        AbiType::I32 => "i32",
        AbiType::U32 => "u32",
        AbiType::I64 => "i64",
        AbiType::U64 => "u64",
        AbiType::F32 => "f32",
        AbiType::F64 => "f64",
        AbiType::Pointer => "pointer",
        AbiType::FunctionPointer => "functionPointer",
        AbiType::Handle => "handle",
    }
}

fn direction_name(direction: Direction) -> &'static str {
    match direction {
        Direction::In => "in",
        Direction::Out => "out",
        Direction::InOut => "inout",
    }
}

fn cleanup_name(cleanup: Cleanup) -> &'static str {
    match cleanup {
        Cleanup::None => "none",
        Cleanup::CloseHandle => "closeHandle",
        Cleanup::RegCloseKey => "regCloseKey",
        Cleanup::LocalFree => "localFree",
        Cleanup::GlobalFree => "globalFree",
        Cleanup::FreeLibrary => "freeLibrary",
        Cleanup::CloseServiceHandle => "closeServiceHandle",
        Cleanup::CoTaskMemFree => "coTaskMemFree",
        Cleanup::CredFree => "credFree",
    }
}

fn success_name(success: super::ir::SuccessRule) -> &'static str {
    match success {
        super::ir::SuccessRule::Always => "always",
        super::ir::SuccessRule::ReturnZero => "zero",
        super::ir::SuccessRule::ReturnNonZero => "nonzero",
        super::ir::SuccessRule::ReturnNonNull => "nonnull",
        super::ir::SuccessRule::HResultSucceeded => "hresult",
        super::ir::SuccessRule::SignedNonNegative => "nonnegative",
        super::ir::SuccessRule::ReturnValidHandle => "validHandle",
    }
}

fn calling_convention_name(convention: super::ir::CallingConvention) -> &'static str {
    match convention {
        super::ir::CallingConvention::System => "system",
        super::ir::CallingConvention::Cdecl => "cdecl",
    }
}
