// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';

export const IID_IStringable = WinGuid.parse('96369f54-8eb6-48f0-abce-c1b211e627c3');

const _IStringable = DynWinRtType.registerInterface(
    "IStringable", IID_IStringable)
    .addMethod("ToString", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()));

export class IStringable {
    readonly _obj: DynWinRtValue;

    constructor(obj: DynWinRtValue) {
        this._obj = obj;
    }

    static from(obj: DynWinRtValue): IStringable {
        return new IStringable(obj.cast(IID_IStringable));
    }

    toString(): string {
        return _IStringable.method(6).invoke(this._obj, []).toString();
    }
}
