// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';

export const IID_IUriRuntimeClassWithAbsoluteCanonicalUri = WinGuid.parse('758d9661-221c-480f-a339-50656673f46f');

const _IUriRuntimeClassWithAbsoluteCanonicalUri = DynWinRtType.registerInterface(
    "IUriRuntimeClassWithAbsoluteCanonicalUri", IID_IUriRuntimeClassWithAbsoluteCanonicalUri)
    .addMethod("get_AbsoluteCanonicalUri", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_DisplayIri", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()));

export class IUriRuntimeClassWithAbsoluteCanonicalUri {
    readonly _obj: DynWinRtValue;

    constructor(obj: DynWinRtValue) {
        this._obj = obj;
    }

    static from(obj: DynWinRtValue): IUriRuntimeClassWithAbsoluteCanonicalUri {
        return new IUriRuntimeClassWithAbsoluteCanonicalUri(obj.cast(IID_IUriRuntimeClassWithAbsoluteCanonicalUri));
    }

    get absoluteCanonicalUri(): string {
        return _IUriRuntimeClassWithAbsoluteCanonicalUri.method(6).invoke(this._obj, []).toString();
    }

    get displayIri(): string {
        return _IUriRuntimeClassWithAbsoluteCanonicalUri.method(7).invoke(this._obj, []).toString();
    }
}
