// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { WwwFormUrlDecoder } from './WwwFormUrlDecoder';

const IID_IUriRuntimeClass = WinGuid.parse('9e365e57-48b2-4160-956f-c7385120bbfc');
const IID_IUriRuntimeClassFactory = WinGuid.parse('44a9796f-723e-4fdf-a218-033e75b0c084');
const IID_IUriEscapeStatics = WinGuid.parse('c1d432ba-c824-4452-a7fd-512bc3bbe9a1');
const IID_IUriRuntimeClassWithAbsoluteCanonicalUri = WinGuid.parse('758d9661-221c-480f-a339-50656673f46f');
const IID_IStringable = WinGuid.parse('96369f54-8eb6-48f0-abce-c1b211e627c3');

const _IUriRuntimeClass = DynWinRtType.registerInterface(
    "IUriRuntimeClass", IID_IUriRuntimeClass)
    .addMethod("get_AbsoluteUri", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_DisplayUri", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Domain", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Extension", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Fragment", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Host", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Password", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Path", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Query", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_QueryParsed", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Foundation.WwwFormUrlDecoder', WinGuid.parse('d45a0451-f225-4542-9296-0e1df5d254df'))))
    .addMethod("get_RawUri", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_SchemeName", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_UserName", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Port", new DynWinRtMethodSig().addOut(DynWinRtType.i32()))
    .addMethod("get_Suspicious", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("Equals", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Foundation.Uri', WinGuid.parse('9e365e57-48b2-4160-956f-c7385120bbfc'))).addOut(DynWinRtType.boolType()))
    .addMethod("CombineUri", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.runtimeClass('Windows.Foundation.Uri', WinGuid.parse('9e365e57-48b2-4160-956f-c7385120bbfc'))));

const _IUriRuntimeClassFactory = DynWinRtType.registerInterface(
    "IUriRuntimeClassFactory", IID_IUriRuntimeClassFactory)
    .addMethod("CreateUri", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.runtimeClass('Windows.Foundation.Uri', WinGuid.parse('9e365e57-48b2-4160-956f-c7385120bbfc'))))
    .addMethod("CreateWithRelativeUri", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.hstring()).addOut(DynWinRtType.runtimeClass('Windows.Foundation.Uri', WinGuid.parse('9e365e57-48b2-4160-956f-c7385120bbfc'))));

const _IUriEscapeStatics = DynWinRtType.registerInterface(
    "IUriEscapeStatics", IID_IUriEscapeStatics)
    .addMethod("UnescapeComponent", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.hstring()))
    .addMethod("EscapeComponent", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.hstring()));

const _IUriRuntimeClassWithAbsoluteCanonicalUri = DynWinRtType.registerInterface(
    "IUriRuntimeClassWithAbsoluteCanonicalUri", IID_IUriRuntimeClassWithAbsoluteCanonicalUri)
    .addMethod("get_AbsoluteCanonicalUri", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_DisplayIri", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()));

const _IStringable = DynWinRtType.registerInterface(
    "IStringable", IID_IStringable)
    .addMethod("ToString", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()));

export class Uri {
    readonly _obj: DynWinRtValue;
    private static _f_IUriRuntimeClassFactory: DynWinRtValue;
    private static f_IUriRuntimeClassFactory() { return Uri._f_IUriRuntimeClassFactory ??= DynWinRtValue.activationFactory('Windows.Foundation.Uri').cast(IID_IUriRuntimeClassFactory); }
    private static _s_IUriEscapeStatics: DynWinRtValue;
    private static s_IUriEscapeStatics() { return Uri._s_IUriEscapeStatics ??= DynWinRtValue.activationFactory('Windows.Foundation.Uri').cast(IID_IUriEscapeStatics); }

    constructor(obj: DynWinRtValue) {
        this._obj = obj.cast(IID_IUriRuntimeClass);
    }

    static createUri(uri: string): Uri {
        return new Uri(_IUriRuntimeClassFactory.method(6).invoke(Uri.f_IUriRuntimeClassFactory(), [DynWinRtValue.hstring(uri)]));
    }

    static createWithRelativeUri(baseUri: string, relativeUri: string): Uri {
        return new Uri(_IUriRuntimeClassFactory.method(7).invoke(Uri.f_IUriRuntimeClassFactory(), [DynWinRtValue.hstring(baseUri), DynWinRtValue.hstring(relativeUri)]));
    }

    static unescapeComponent(toUnescape: string): string {
        return _IUriEscapeStatics.method(6).invoke(Uri.s_IUriEscapeStatics(), [DynWinRtValue.hstring(toUnescape)]).toString();
    }

    static escapeComponent(toEscape: string): string {
        return _IUriEscapeStatics.method(7).invoke(Uri.s_IUriEscapeStatics(), [DynWinRtValue.hstring(toEscape)]).toString();
    }

    get absoluteUri(): string {
        return _IUriRuntimeClass.method(6).invoke(this._obj, []).toString();
    }

    get displayUri(): string {
        return _IUriRuntimeClass.method(7).invoke(this._obj, []).toString();
    }

    get domain(): string {
        return _IUriRuntimeClass.method(8).invoke(this._obj, []).toString();
    }

    get extension(): string {
        return _IUriRuntimeClass.method(9).invoke(this._obj, []).toString();
    }

    get fragment(): string {
        return _IUriRuntimeClass.method(10).invoke(this._obj, []).toString();
    }

    get host(): string {
        return _IUriRuntimeClass.method(11).invoke(this._obj, []).toString();
    }

    get password(): string {
        return _IUriRuntimeClass.method(12).invoke(this._obj, []).toString();
    }

    get path(): string {
        return _IUriRuntimeClass.method(13).invoke(this._obj, []).toString();
    }

    get query(): string {
        return _IUriRuntimeClass.method(14).invoke(this._obj, []).toString();
    }

    get queryParsed(): WwwFormUrlDecoder {
        return new WwwFormUrlDecoder(_IUriRuntimeClass.method(15).invoke(this._obj, []));
    }

    get rawUri(): string {
        return _IUriRuntimeClass.method(16).invoke(this._obj, []).toString();
    }

    get schemeName(): string {
        return _IUriRuntimeClass.method(17).invoke(this._obj, []).toString();
    }

    get userName(): string {
        return _IUriRuntimeClass.method(18).invoke(this._obj, []).toString();
    }

    get port(): number {
        return _IUriRuntimeClass.method(19).invoke(this._obj, []).toNumber();
    }

    get suspicious(): boolean {
        return _IUriRuntimeClass.method(20).invoke(this._obj, []).toBool();
    }

    equals(pUri: Uri): boolean {
        return _IUriRuntimeClass.method(21).invoke(this._obj, [(pUri as any)._obj ?? pUri]).toBool();
    }

    combineUri(relativeUri: string): Uri {
        return new Uri(_IUriRuntimeClass.method(22).invoke(this._obj, [DynWinRtValue.hstring(relativeUri)]));
    }

    as<T>(InterfaceClass: { from(obj: DynWinRtValue): T }): T {
        return InterfaceClass.from(this._obj);
    }
}

export class IUriRuntimeClassWithAbsoluteCanonicalUri {
    readonly _obj: DynWinRtValue;

    constructor(obj: DynWinRtValue) {
        this._obj = obj;
    }

    static from(obj: DynWinRtValue): IUriRuntimeClassWithAbsoluteCanonicalUri {
        return new IUriRuntimeClassWithAbsoluteCanonicalUri(obj.cast(IID_IUriRuntimeClassWithAbsoluteCanonicalUri));
    }

    get absoluteCanonicalUri(): string {
        return _IUriRuntimeClassWithAbsoluteCanonicalUri.method(6).invoke(this._obj, []).toString();
    }

    get displayIri(): string {
        return _IUriRuntimeClassWithAbsoluteCanonicalUri.method(7).invoke(this._obj, []).toString();
    }
}

export class IStringable {
    readonly _obj: DynWinRtValue;

    constructor(obj: DynWinRtValue) {
        this._obj = obj;
    }

    static from(obj: DynWinRtValue): IStringable {
        return new IStringable(obj.cast(IID_IStringable));
    }

    toString(): string {
        return _IStringable.method(6).invoke(this._obj, []).toString();
    }
}
