// Generated by dynwinrt-codegen — do not edit
export declare class WwwFormUrlDecoder {
    private constructor();
    static createWwwFormUrlDecoder(query: string): WwwFormUrlDecoder;
    getFirstValueByName(name: string): string;
}
