// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';

const IID_IWwwFormUrlDecoderRuntimeClass = WinGuid.parse('d45a0451-f225-4542-9296-0e1df5d254df');
const IID_IWwwFormUrlDecoderRuntimeClassFactory = WinGuid.parse('5b8c6b3d-24ae-41b5-a1bf-f0c3d544845b');

const _IWwwFormUrlDecoderRuntimeClass = DynWinRtType.registerInterface(
    "IWwwFormUrlDecoderRuntimeClass", IID_IWwwFormUrlDecoderRuntimeClass)
    .addMethod("GetFirstValueByName", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.hstring()));

const _IWwwFormUrlDecoderRuntimeClassFactory = DynWinRtType.registerInterface(
    "IWwwFormUrlDecoderRuntimeClassFactory", IID_IWwwFormUrlDecoderRuntimeClassFactory)
    .addMethod("CreateWwwFormUrlDecoder", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.runtimeClass('Windows.Foundation.WwwFormUrlDecoder', WinGuid.parse('d45a0451-f225-4542-9296-0e1df5d254df'))));

export class WwwFormUrlDecoder {
    _obj;
    static _f_IWwwFormUrlDecoderRuntimeClassFactory;
    static f_IWwwFormUrlDecoderRuntimeClassFactory() { return WwwFormUrlDecoder._f_IWwwFormUrlDecoderRuntimeClassFactory ??= DynWinRtValue.activationFactory('Windows.Foundation.WwwFormUrlDecoder').cast(IID_IWwwFormUrlDecoderRuntimeClassFactory); }

    constructor(obj) {
        this._obj = obj.cast(IID_IWwwFormUrlDecoderRuntimeClass);
    }
    static createWwwFormUrlDecoder(query) {
        return new WwwFormUrlDecoder(_IWwwFormUrlDecoderRuntimeClassFactory.method(6).invoke(WwwFormUrlDecoder.f_IWwwFormUrlDecoderRuntimeClassFactory(), [DynWinRtValue.hstring(query)]));
    }
    getFirstValueByName(name) {
        return _IWwwFormUrlDecoderRuntimeClass.method(6).invoke(this._obj, [DynWinRtValue.hstring(name)]).toString();
    }
}
