// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('@microsoft/dynwinrt');

const IID_IWwwFormUrlDecoderRuntimeClass = WinGuid.parse('d45a0451-f225-4542-9296-0e1df5d254df');
const IID_IWwwFormUrlDecoderRuntimeClassFactory = WinGuid.parse('5b8c6b3d-24ae-41b5-a1bf-f0c3d544845b');
const IID_WwwFormUrlDecoder = WinGuid.parse('d45a0451-f225-4542-9296-0e1df5d254df');

let _IWwwFormUrlDecoderRuntimeClassCache;
const _IWwwFormUrlDecoderRuntimeClass = new Proxy({}, {
    get(_target, prop) {
        _IWwwFormUrlDecoderRuntimeClassCache ??= DynWinRtType.registerInterface(
        "IWwwFormUrlDecoderRuntimeClass", IID_IWwwFormUrlDecoderRuntimeClass)
        .addMethod("GetFirstValueByName", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.hstring()));
        const value = _IWwwFormUrlDecoderRuntimeClassCache[prop];
        return typeof value === 'function' ? value.bind(_IWwwFormUrlDecoderRuntimeClassCache) : value;
    }
});

let _IWwwFormUrlDecoderRuntimeClassFactoryCache;
const _IWwwFormUrlDecoderRuntimeClassFactory = new Proxy({}, {
    get(_target, prop) {
        _IWwwFormUrlDecoderRuntimeClassFactoryCache ??= DynWinRtType.registerInterface(
        "IWwwFormUrlDecoderRuntimeClassFactory", IID_IWwwFormUrlDecoderRuntimeClassFactory)
        .addMethod("CreateWwwFormUrlDecoder", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.runtimeClass('Windows.Foundation.WwwFormUrlDecoder', WinGuid.parse('d45a0451-f225-4542-9296-0e1df5d254df'))));
        const value = _IWwwFormUrlDecoderRuntimeClassFactoryCache[prop];
        return typeof value === 'function' ? value.bind(_IWwwFormUrlDecoderRuntimeClassFactoryCache) : value;
    }
});

class WwwFormUrlDecoder {
    _obj;
    static _f_IWwwFormUrlDecoderRuntimeClassFactory;
    static f_IWwwFormUrlDecoderRuntimeClassFactory() { return WwwFormUrlDecoder._f_IWwwFormUrlDecoderRuntimeClassFactory ??= DynWinRtValue.activationFactory('Windows.Foundation.WwwFormUrlDecoder').cast(IID_IWwwFormUrlDecoderRuntimeClassFactory); }

    constructor(...args) {
        if (args.length === 1) {
            this._obj = WwwFormUrlDecoder.createWwwFormUrlDecoder(args[0])._obj;
            return;
        }
        throw new TypeError('No matching constructor for WwwFormUrlDecoder.');
    }
    static _fromNative(obj) {
        return Object.assign(Object.create(WwwFormUrlDecoder.prototype), { _obj: obj.cast(IID_IWwwFormUrlDecoderRuntimeClass) });
    }
    static createWwwFormUrlDecoder(query) {
        return WwwFormUrlDecoder._fromNative(_IWwwFormUrlDecoderRuntimeClassFactory.method(6).invoke(WwwFormUrlDecoder.f_IWwwFormUrlDecoderRuntimeClassFactory(), [DynWinRtValue.hstring(query)]));
    }
    getFirstValueByName(name) {
        return _IWwwFormUrlDecoderRuntimeClass.method(6).invoke(this._obj, [DynWinRtValue.hstring(name)]).toString();
    }
}
exports.IID_WwwFormUrlDecoder = IID_WwwFormUrlDecoder;
exports.WwwFormUrlDecoder = WwwFormUrlDecoder;
