// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
    process::Command,
};

use dynwinrt_codegen::{
    codegen::{com, win32},
    win32_metadata,
};

struct Scratch(PathBuf);

impl Drop for Scratch {
    fn drop(&mut self) {
        fs::remove_dir_all(&self.0).expect("remove this test's generated module directory");
    }
}

#[test]
fn all_supported_win32_modules_load_and_have_valid_declarations() {
    let required = std::env::var("DYNWINRT_REQUIRE_WIN32_METADATA").as_deref() == Ok("1");
    let metadata = std::env::var("DYNWINRT_WIN32_WINMD").ok();
    let Some(metadata) = metadata else {
        assert!(
            !required,
            "DYNWINRT_REQUIRE_WIN32_METADATA=1 requires a metadata path"
        );
        eprintln!("Skipping generated Win32 module test: metadata is not configured");
        return;
    };
    assert!(
        Path::new(&metadata).is_file(),
        "configured Win32 metadata does not exist"
    );
    let tsc = std::env::var_os("DYNWINRT_TSC")
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            Path::new(env!("CARGO_MANIFEST_DIR"))
                .join(r"..\..\bindings\js\node_modules\typescript\bin\tsc")
        });
    let require_tsc = std::env::var("DYNWINRT_REQUIRE_TSC").as_deref() == Ok("1");
    assert!(
        !require_tsc || tsc.is_file(),
        "DYNWINRT_REQUIRE_TSC=1 requires a TypeScript compiler"
    );
    let directory =
        std::env::temp_dir().join(format!("dynwinrt-win32-modules-{}", std::process::id()));
    fs::create_dir(&directory).unwrap();
    let scratch = Scratch(directory);
    let functions = win32_metadata::parse_all_functions(&metadata).expect("parse native exports");
    let mut containers = BTreeMap::new();
    for function in functions {
        containers
            .entry((function.namespace.clone(), function.container.clone()))
            .or_insert_with(Vec::new)
            .push(function);
    }
    let mut modules = Vec::new();
    let mut namespace_count = 0;
    for ((namespace, class_name), functions) in containers {
        let raw = win32_metadata::RawApis {
            namespace,
            class_name,
            functions,
        };
        let projection = win32::project_apis(&raw);
        if projection.complete_count() == 0 {
            continue;
        }
        namespace_count += 1;
        let (generated, _) = win32::generate_apis_files(&raw, "@microsoft/dynwinrt/win32");
        let module = com::canonical_module_path(&raw.namespace, &raw.class_name).unwrap();
        let target = scratch.0.join(&module);
        let parent = target.parent().unwrap();
        fs::create_dir_all(parent).unwrap();
        let mut outputs = BTreeMap::from([
            (format!("{}.js", raw.class_name), generated.js),
            (format!("{}.d.ts", raw.class_name), generated.dts),
        ]);
        let mut names = BTreeSet::new();
        for (file, content) in generated.extra_files {
            assert!(
                names.insert(com::windows_relative_path_key(&file).unwrap()),
                "{namespace}",
                namespace = raw.namespace
            );
            assert!(
                outputs.insert(file, content).is_none(),
                "duplicate generated file"
            );
        }
        for (file, content) in &outputs {
            assert!(
                content.starts_with("// Generated by dynwinrt-codegen"),
                "{file}"
            );
            let pair = if let Some(stem) = file.strip_suffix(".d.ts") {
                format!("{stem}.js")
            } else {
                format!(
                    "{}.d.ts",
                    file.strip_suffix(".js").expect("known output extension")
                )
            };
            assert!(
                outputs.contains_key(&pair),
                "{file} has no implementation/declaration pair"
            );
            let path = parent.join(file);
            fs::write(&path, content).unwrap();
            if file.ends_with(".js") {
                modules.push(path);
            }
        }
    }
    assert!(
        namespace_count > 0,
        "metadata must exercise actual generated modules"
    );
    let runtime = scratch.0.join(r"node_modules\@microsoft\dynwinrt");
    fs::create_dir_all(&runtime).unwrap();
    fs::write(
        runtime.join("package.json"),
        r#"{
      "name":"@microsoft/dynwinrt",
      "exports":{
        "./win32":{"types":"./win32.d.ts","default":"./win32.js"},
        "./win32/unsafe":{"types":"./win32.d.ts","default":"./win32.js"}
      }
    }"#,
    )
    .unwrap();
    fs::write(
        runtime.join("win32.js"),
        r#"
const forbidCall = new Proxy({}, {
  get(_, name) { throw new Error(`Native operation ${String(name)} ran during import`); }
});
module.exports = { DynWin32: forbidCall, DynWin32Function: forbidCall };
"#,
    )
    .unwrap();
    fs::write(
        runtime.join("win32.d.ts"),
        r#"
export declare class DynWin32NativeStruct { private constructor(); }
export declare class DynWin32Resource { private constructor(); }
export declare class DynWin32SubsystemContext { private constructor(); }
export declare class DynWinRtValue { private constructor(); }
"#,
    )
    .unwrap();
    fs::write(
        scratch.0.join("globals.d.ts"),
        "declare class Buffer extends Uint8Array {}\n",
    )
    .unwrap();
    fs::write(scratch.0.join("package.json"), r#"{"type":"commonjs"}"#).unwrap();
    let modules_file = scratch.0.join("modules.json");
    fs::write(&modules_file, serde_json::to_vec(&modules).unwrap()).unwrap();
    let node_script = r#"
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { pathToFileURL } = require('node:url');
(async () => {
  const modules = JSON.parse(fs.readFileSync(process.argv[1], 'utf8'));
  const failures = [];
  for (const file of modules) {
    try {
      const cjs = require(file);
      const esm = await import(pathToFileURL(file).href);
      for (const name of Object.keys(cjs)) {
        assert.notEqual(cjs[name], undefined, `${file}: undefined export ${name}`);
        assert.equal(esm[name], cjs[name], `${file}: missing ESM named export ${name}`);
      }
    } catch (error) {
      failures.push(`${file}: ${error.stack}`);
    }
  }
  assert.equal(failures.length, 0, failures.join('\n'));
  console.log(`Loaded ${modules.length} generated modules without native calls`);
})().catch(error => { console.error(error); process.exitCode = 1; });
"#;
    let node = Command::new("node")
        .args(["--eval", node_script])
        .arg(&modules_file)
        .output()
        .expect("Node is required for module loading tests");
    if !tsc.is_file() {
        assert!(
            node.status.success(),
            "{}\n{}",
            String::from_utf8_lossy(&node.stdout),
            String::from_utf8_lossy(&node.stderr)
        );
        eprintln!("Skipping declaration compilation only: TypeScript is not installed");
        return;
    }
    fs::write(
        scratch.0.join("tsconfig.json"),
        r#"{
      "compilerOptions":{
        "noEmit":true,"strict":true,"skipLibCheck":false,
        "target":"ES2022","module":"NodeNext","moduleResolution":"NodeNext","types":[]
      },
      "include":["**/*.d.ts"]
    }"#,
    )
    .unwrap();
    let result = Command::new("node")
        .arg(tsc)
        .args(["--project"])
        .arg(scratch.0.join("tsconfig.json"))
        .output()
        .expect("run TypeScript declaration compiler");
    assert!(
        node.status.success() && result.status.success(),
        "Module loading:\n{}\n{}\nDeclaration compilation:\n{}\n{}",
        String::from_utf8_lossy(&node.stdout),
        String::from_utf8_lossy(&node.stderr),
        String::from_utf8_lossy(&result.stdout),
        String::from_utf8_lossy(&result.stderr)
    );
}
