// Generated by dynwinrt-codegen — do not edit
import { WinGuid, DynWinRtImplementation, DynWinRtImplementationHandle } from '@microsoft/dynwinrt';
import { DynWinRtImplementationDescriptor, DynWinRtImplementationOptions, DynWinRtImplementationType } from '@microsoft/dynwinrt';


/** Synchronous owner-thread handlers. Out parameters precede the logical result; FillArray inputs are capacities. */
export interface IStringableHandlers {
    toString(): string;
}

export declare const IID_IStringable: WinGuid;

export declare class IStringable {
    private constructor();
    /** Validate synchronous handlers and create an independent interface descriptor. */
    static implementation(handlers: IStringableHandlers): DynWinRtImplementationDescriptor;
    /** Create an instance with a stable typed value and explicit lifetime management. */
    static implement<const T extends readonly DynWinRtImplementationType[]>(handlers: IStringableHandlers, options: DynWinRtImplementationOptions<T>): DynWinRtImplementationHandle<IStringable>;
    static implement(handlers: IStringableHandlers, ...additional: DynWinRtImplementationDescriptor[]): DynWinRtImplementationHandle<IStringable>;
    /** Query an independent view, without consuming the handle's primary value. */
    static fromImplementation(owner: DynWinRtImplementation | DynWinRtImplementationHandle<unknown>): IStringable;

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IStringable;

    toString(): string;
}
