// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid, DynWinRtInterfacePlan, DynWinRtImplementation, DynWinRtImplementationHandle } = require('@microsoft/dynwinrt');

const IID_IStringable = WinGuid.parse('96369f54-8eb6-48f0-abce-c1b211e627c3');

let _IStringableCache;
const _IStringable = new Proxy({}, {
    get(_target, prop) {
        _IStringableCache ??= DynWinRtType.registerInterface(
        "IStringable", IID_IStringable)
        .addMethod("ToString", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()));
        const value = _IStringableCache[prop];
        return typeof value === 'function' ? value.bind(_IStringableCache) : value;
    }
});


function __implementationCheck(value, valid, label) {
    if (!valid) throw new TypeError(`${label}: invalid implementation result`);
    return value;
}
function __implementationField(value, name, label) {
    if (value === null || typeof value !== 'object') throw new TypeError(`${label}: expected a named result object`);
    const field = Object.getOwnPropertyDescriptor(value, name);
    if (!field || !Object.hasOwn(field, 'value')) throw new TypeError(`${label}: missing data field ${name}`);
    return field.value;
}
function __implementationArray(value, label, bytes = false, capacity = undefined) {
    if (!Array.isArray(value) && !(bytes && value instanceof Uint8Array)) throw new TypeError(`${label}: expected an array`);
    if (capacity !== undefined && value.length !== capacity) throw new RangeError(`${label}: FillArray result must match capacity ${capacity}`);
    return Array.from(value);
}
function __implementationReference(value, iid, label) {
    if (value === null) return DynWinRtValue.nullValue();
    const raw = value instanceof DynWinRtValue ? value : value?._obj;
    if (!(raw instanceof DynWinRtValue)) throw new TypeError(`${label}: expected a managed WinRT value or null`);
    return raw.isNull() ? DynWinRtValue.nullValue() : raw.cast(iid);
}
function __implementationSync(value, label) {
    if (value !== null && (typeof value === 'object' || typeof value === 'function') && typeof value.then === 'function') {
        throw new TypeError(`${label}: implementation callbacks must return synchronously, not a Promise or thenable`);
    }
    return value;
}
function __implementationHandler(handlers, name, label) {
    if (handlers === null || (typeof handlers !== 'object' && typeof handlers !== 'function')) throw new TypeError(`${label}: expected a handler object`);
    let owner = handlers;
    while (owner && owner !== Object.prototype && owner !== Function.prototype) {
        const property = Object.getOwnPropertyDescriptor(owner, name);
        if (property) {
            const callback = property.value;
            if (typeof callback !== 'function') throw new TypeError(`${label}: missing synchronous handler ${name} (accessors are not handlers)`);
            if (Object.prototype.toString.call(callback) === '[object AsyncFunction]' || Object.prototype.toString.call(callback) === '[object AsyncGeneratorFunction]') {
                throw new TypeError(`${label}.${name}: async handlers are not supported`);
            }
            return callback.bind(handlers);
        }
        owner = Object.getPrototypeOf(owner);
    }
    throw new TypeError(`${label}: missing synchronous handler ${name}`);
}

let __implementationPlan;
function __getImplementationPlan() {
    return (__implementationPlan ??= DynWinRtInterfacePlan.create("Windows.Foundation.IStringable", DynWinRtType.interface(WinGuid.parse("96369f54-8eb6-48f0-abce-c1b211e627c3")), [
        { name: "ToString", vtableIndex: 6, signature: new DynWinRtMethodSig().addOut(DynWinRtType.hstring()) }
    ], []));
}

class IStringable {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStringable(obj.cast(IID_IStringable));
    }

    static implementation(handlers) {
        const h6 = __implementationHandler(handlers, "toString", "Windows.Foundation.IStringable");
        const plan = __getImplementationPlan();
        return Object.freeze({ plan, dispatch(vtableIndex, args) {
            if (!Array.isArray(args)) throw new TypeError('implementation arguments must be an array');
            switch (vtableIndex) {
                case 6: {
                    if (args.length !== 0) throw new TypeError('implementation argument count mismatch');
                    const result = __implementationSync(h6(), "Windows.Foundation.IStringable.toString");
                    return [DynWinRtValue.hstring(((v) => __implementationCheck(v, typeof v === 'string', "Windows.Foundation.IStringable.toString.result"))(result))];
                }
                default: throw new RangeError('unknown implementation vtable slot');
            }
        } });
    }

    static implement(handlers, ...additional) {
        return DynWinRtImplementationHandle.create(this, handlers, additional, view => view._obj.release());
    }

    static fromImplementation(owner) {
        if (!(owner instanceof DynWinRtImplementation) && !(owner instanceof DynWinRtImplementationHandle)) throw new TypeError('fromImplementation requires a DynWinRtImplementation controller or handle');
        const value = owner.toValue();
        try {
            return this.from(value);
        } finally {
            value.release();
        }
    }

    toString() {
        return _IStringable.method(6).invoke(this._obj, []).toString();
    }
}
exports.IID_IStringable = IID_IStringable;
exports.IStringable = IStringable;
