// Generated by dynwinrt-codegen — do not edit
import { WinGuid, DynWinRtImplementation } from '@microsoft/dynwinrt';
import { DynWinRtImplementationDescriptor } from '@microsoft/dynwinrt';


/** Synchronous owner-thread handlers. Out parameters precede the logical result; FillArray inputs are capacities. */
export interface IStringableHandlers {
    toString(): string;
}

export declare const IID_IStringable: WinGuid;

export declare class IStringable {
    private constructor();
    /** Validate synchronous handlers and create an independent interface descriptor. */
    static implementation(handlers: IStringableHandlers): DynWinRtImplementationDescriptor;
    /** Create a non-agile owner-thread implementation. The controller is separate from this wrapper. */
    static implement(handlers: IStringableHandlers, ...additional: DynWinRtImplementationDescriptor[]): DynWinRtImplementation;
    /** Query a controller for this interface and return an owned, typed view. */
    static fromImplementation(owner: DynWinRtImplementation): IStringable;

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IStringable;

    toString(): string;
}
