// Generated by dynwinrt-codegen — do not edit
import { WinGuid, DynWinRtImplementation } from '@microsoft/dynwinrt';
import { DynWinRtImplementationDescriptor } from '@microsoft/dynwinrt';


/** Synchronous owner-thread handlers. Out parameters precede the logical result; FillArray inputs are capacities. */
export interface IUriRuntimeClassWithAbsoluteCanonicalUriHandlers {
    getAbsoluteCanonicalUri(): string;
    getDisplayIri(): string;
}

export declare const IID_IUriRuntimeClassWithAbsoluteCanonicalUri: WinGuid;

export declare class IUriRuntimeClassWithAbsoluteCanonicalUri {
    private constructor();
    /** Validate synchronous handlers and create an independent interface descriptor. */
    static implementation(handlers: IUriRuntimeClassWithAbsoluteCanonicalUriHandlers): DynWinRtImplementationDescriptor;
    /** Create a non-agile owner-thread implementation. The controller is separate from this wrapper. */
    static implement(handlers: IUriRuntimeClassWithAbsoluteCanonicalUriHandlers, ...additional: DynWinRtImplementationDescriptor[]): DynWinRtImplementation;
    /** Query a controller for this interface and return an owned, typed view. */
    static fromImplementation(owner: DynWinRtImplementation): IUriRuntimeClassWithAbsoluteCanonicalUri;

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IUriRuntimeClassWithAbsoluteCanonicalUri;

    get absoluteCanonicalUri(): string;

    get displayIri(): string;
}
