// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid, DynWinRtInterfacePlan, DynWinRtImplementation, DynWinRtImplementationHandle } = require('@microsoft/dynwinrt');

const IID_IWwwFormUrlDecoderEntry = WinGuid.parse('125e7431-f678-4e8e-b670-20a9b06c512d');

let _IWwwFormUrlDecoderEntryCache;
const _IWwwFormUrlDecoderEntry = new Proxy({}, {
    get(_target, prop) {
        _IWwwFormUrlDecoderEntryCache ??= DynWinRtType.registerInterface(
        "IWwwFormUrlDecoderEntry", IID_IWwwFormUrlDecoderEntry)
        .addMethod("get_Name", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("get_Value", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()));
        const value = _IWwwFormUrlDecoderEntryCache[prop];
        return typeof value === 'function' ? value.bind(_IWwwFormUrlDecoderEntryCache) : value;
    }
});


function __implementationCheck(value, valid, label) {
    if (!valid) throw new TypeError(`${label}: invalid implementation result`);
    return value;
}
function __implementationField(value, name, label) {
    if (value === null || typeof value !== 'object') throw new TypeError(`${label}: expected a named result object`);
    const field = Object.getOwnPropertyDescriptor(value, name);
    if (!field || !Object.hasOwn(field, 'value')) throw new TypeError(`${label}: missing data field ${name}`);
    return field.value;
}
function __implementationArray(value, label, bytes = false, capacity = undefined) {
    if (!Array.isArray(value) && !(bytes && value instanceof Uint8Array)) throw new TypeError(`${label}: expected an array`);
    if (capacity !== undefined && value.length !== capacity) throw new RangeError(`${label}: FillArray result must match capacity ${capacity}`);
    return Array.from(value);
}
function __implementationReference(value, iid, label) {
    if (value === null) return DynWinRtValue.nullValue();
    const raw = value instanceof DynWinRtValue ? value : value?._obj;
    if (!(raw instanceof DynWinRtValue)) throw new TypeError(`${label}: expected a managed WinRT value or null`);
    return raw.isNull() ? DynWinRtValue.nullValue() : raw.cast(iid);
}
function __implementationSync(value, label) {
    if (value !== null && (typeof value === 'object' || typeof value === 'function') && typeof value.then === 'function') {
        throw new TypeError(`${label}: implementation callbacks must return synchronously, not a Promise or thenable`);
    }
    return value;
}
function __implementationHandler(handlers, name, label) {
    if (handlers === null || (typeof handlers !== 'object' && typeof handlers !== 'function')) throw new TypeError(`${label}: expected a handler object`);
    let owner = handlers;
    while (owner && owner !== Object.prototype && owner !== Function.prototype) {
        const property = Object.getOwnPropertyDescriptor(owner, name);
        if (property) {
            const callback = property.value;
            if (typeof callback !== 'function') throw new TypeError(`${label}: missing synchronous handler ${name} (accessors are not handlers)`);
            if (Object.prototype.toString.call(callback) === '[object AsyncFunction]' || Object.prototype.toString.call(callback) === '[object AsyncGeneratorFunction]') {
                throw new TypeError(`${label}.${name}: async handlers are not supported`);
            }
            return callback.bind(handlers);
        }
        owner = Object.getPrototypeOf(owner);
    }
    throw new TypeError(`${label}: missing synchronous handler ${name}`);
}

let __implementationPlan;
function __getImplementationPlan() {
    return (__implementationPlan ??= DynWinRtInterfacePlan.create("Windows.Foundation.IWwwFormUrlDecoderEntry", DynWinRtType.interface(WinGuid.parse("125e7431-f678-4e8e-b670-20a9b06c512d")), [
        { name: "get_Name", vtableIndex: 6, signature: new DynWinRtMethodSig().addOut(DynWinRtType.hstring()) },
        { name: "get_Value", vtableIndex: 7, signature: new DynWinRtMethodSig().addOut(DynWinRtType.hstring()) }
    ], []));
}

class IWwwFormUrlDecoderEntry {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IWwwFormUrlDecoderEntry(obj.cast(IID_IWwwFormUrlDecoderEntry));
    }

    static implementation(handlers) {
        const h6 = __implementationHandler(handlers, "getName", "Windows.Foundation.IWwwFormUrlDecoderEntry");
        const h7 = __implementationHandler(handlers, "getValue", "Windows.Foundation.IWwwFormUrlDecoderEntry");
        const plan = __getImplementationPlan();
        return Object.freeze({ plan, dispatch(vtableIndex, args) {
            if (!Array.isArray(args)) throw new TypeError('implementation arguments must be an array');
            switch (vtableIndex) {
                case 6: {
                    if (args.length !== 0) throw new TypeError('implementation argument count mismatch');
                    const result = __implementationSync(h6(), "Windows.Foundation.IWwwFormUrlDecoderEntry.getName");
                    return [DynWinRtValue.hstring(((v) => __implementationCheck(v, typeof v === 'string', "Windows.Foundation.IWwwFormUrlDecoderEntry.getName.result"))(result))];
                }
                case 7: {
                    if (args.length !== 0) throw new TypeError('implementation argument count mismatch');
                    const result = __implementationSync(h7(), "Windows.Foundation.IWwwFormUrlDecoderEntry.getValue");
                    return [DynWinRtValue.hstring(((v) => __implementationCheck(v, typeof v === 'string', "Windows.Foundation.IWwwFormUrlDecoderEntry.getValue.result"))(result))];
                }
                default: throw new RangeError('unknown implementation vtable slot');
            }
        } });
    }

    static implement(handlers, ...additional) {
        return DynWinRtImplementationHandle.create(this, handlers, additional, view => view._obj.release());
    }

    static fromImplementation(owner) {
        if (!(owner instanceof DynWinRtImplementation) && !(owner instanceof DynWinRtImplementationHandle)) throw new TypeError('fromImplementation requires a DynWinRtImplementation controller or handle');
        const value = owner.toValue();
        try {
            return this.from(value);
        } finally {
            value.release();
        }
    }

    get name() {
        return (() => { const _m = _IWwwFormUrlDecoderEntry.method(6); return typeof _m.getString === 'function' ? _m.getString(this._obj) : _IWwwFormUrlDecoderEntry.method(6).invoke(this._obj, []).toString(); })();
    }

    get value() {
        return (() => { const _m = _IWwwFormUrlDecoderEntry.method(7); return typeof _m.getString === 'function' ? _m.getString(this._obj) : _IWwwFormUrlDecoderEntry.method(7).invoke(this._obj, []).toString(); })();
    }
}
exports.IID_IWwwFormUrlDecoderEntry = IID_IWwwFormUrlDecoderEntry;
exports.IWwwFormUrlDecoderEntry = IWwwFormUrlDecoderEntry;
